### ISSUE TITLE
Different max_number_of_devices based on devise model

### ISSUE THREAD

**Issue by kinto-d** [lynndylanhurley/devise_token_auth#1003]
Is there any practical way to limiting max_number_of_devices based on devise model, for an example, I want to have a User model has only 1 single concurrent devices, but has 3 on Admin model.

Thank you.

**Comment by zachfeldman** [comment]
Hey @kinto-d , heres where that's governed:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L213

You could probably override the `build_header` method to achieve this?
