### ISSUE TITLE
Where should I store token?

### ISSUE THREAD

**Issue by JarLowrey** [lynndylanhurley/devise_token_auth#1005]
I've got my react/redux front-end SPA successfully sending requests, and my backend API successfully sending back authentication info. In the response header I am receiving `access-token`, `token-type`, `client`, `expiry`, and `uid`. Now, how should I store this data to be visible in the next request? 

[This is the best post I've found summarizing the differences between localStorage and cookies.](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage). Basically, localStorage is vulnerable to XSS attacks, and cookies might be vulnerable to CSRF but utilizing HttpOnly option fixes that vulnerability. This is backed up by [this](https://stackoverflow.com/a/37396572) and [this](https://security.stackexchange.com/questions/80727/best-place-to-store-authentication-tokens-client-side) SO posts. 

I haven't been able to find any info on using HttpOnly cookies, and some resources say this should be done server side. Anyone have any guidance to offer?

**Comment by zachfeldman** [comment]
Store it in a cookie. See https://github.com/lynndylanhurley/j-toker for an example

**Comment by MaicolBen** [comment]
You should use local storage for persisting more than a sesions-basis (that's sessionStorage)
