### ISSUE TITLE
Omniauth with devise token auth

### ISSUE THREAD

**Issue by sushant12** [lynndylanhurley/devise_token_auth#1007]
I am using google_oauth2. Everything is working fine except that after I log in via the google , the authenticate_api_employee! is nil.

### omniauth_callbacks_controller.rb

```
module Overrides
  class OmniauthCallbacksController < DeviseTokenAuth::OmniauthCallbacksController

  	def omniauth_success
      super do |resource|
        if omniauth_window_type.present? # auth requested from angular
           sign_in resource
       else  # if backend standalone auth
       		# redirect_to '/test' and return
       		sign_in_and_redirect resource and return
        end
      end
    end

    # break out provider attribute assignment for easy method extension
    def assign_provider_attrs(user, auth_hash)
      user.assign_attributes({
         email: auth_hash['info']['email'],
         name: auth_hash['info']['name'],
         admin: true,
         first_name: CustomRegex.japanese?(auth_hash['info']["first_name"]) ? '' : auth_hash['info']["first_name"],
         first_name: CustomRegex.japanese?(auth_hash['info']["last_name"]) ? '' : auth_hash['info']["last_name"],
         uqid: SecureRandom.uuid,
         company_id: 1,
         timeline: 0
     	})
    end
  end
end
```
My controllers have this before_action

`before_action :authenticate_api_employee!`

Versions

```
ruby '2.3.0'

gem 'rails', '4.2.6'

gem 'rails-api', '~> 0.4.0'

gem 'devise_token_auth'

gem 'omniauth'

gem 'omniauth-google-oauth2'
```

So ya, the problem is that I am not being authenticated

**Comment by zachfeldman** [comment]
Hey @sushant12 , sorry to hear that. What is the authenticate_api_employee! ? All I know from your post is that it's a before action and that it's nil.

**Comment by sushant12** [comment]
@zachfeldman `authenticate_api_employee!` is the same as `authenticate_user!` .

**Comment by zachfeldman** [comment]
Ok, and you're saying that it's nil....if it's a before_action I'm not sure what you mean? Do you mean that it's not running? Can you be more descriptive?

**Comment by sushant12** [comment]
@zachfeldman yes it is before_action :) . sorry for the confusion. I am trying to find the solution myself and it is so frustrating

**Comment by sushant12** [comment]
@zachfeldman https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/controllers/helpers.rb#L33

what would happen if the `#{group_name}_signed_in?` is true from the start?

**Comment by sushant12** [comment]
@zachfeldman why is that the omniauth_callbacks_controller.rb do not have this line of code
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/confirmations_controller.rb#L28
