### ISSUE TITLE
Reset Password Tokens No Longer Expire

### ISSUE THREAD

**Issue by stratigos** [lynndylanhurley/devise_token_auth#1008]
The Devise configuration for: 

```ruby
Devise.setup do |config|
  # ...
  config.reset_password_within = 30.seconds
  #...
end
```
no longer has any effect in DeviseTokenAuth. I believe it has been bypassed by #957. As pointed out in #672, the `DeviseTokenAuth::PasswordsController#edit` was previously not returning an error properly when an expired token was found, which I think is noteworthy given this recently merged PR.

Essentially, the call to `Devise::Models::Recoverable#reset_password_period_valid?` is never made. I will manually add this to an override in my application for now, and will get to work on a PR.

----

Devise handles this in [Devise::PasswordsController#update](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L32). The resource is sent [#reset_password_by_token](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/recoverable.rb#L143), which in turn calls [#reset_password_period_valid?](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/recoverable.rb#L75). So to me, it looks like the call to `#reset_password_by_token` was removed with #957, thus skipping over some expected functionality, including checking if the token has expired yet or not. 

Im no crypto expert, but I feel that the callback to `resource_class.with_reset_password_token` appears less secure than `resource_class.reset_password_by_token`.

----
**Version**:   `devise_token_auth (0.1.42)`
**Environmental Info**: 
  * **Routes**: scoped to "v1"
  * **Config**: I am testing this by setting the `devise` config for `reset_password_within` to be 30 seconds. Other than that, all that is customized is my mailer account/host info.
  * **Custom Overrides**: nothing in terms of passwords, but have overridden the Sessions controller to use the yield block to accept custom parameters on login.

**Comment by zachfeldman** [comment]
@stratigos good catch if this is really happening. We'd welcome your PR!

**Comment by stratigos** [comment]
Yeah Im going to work on it today/tonight hopefully, if not tomorrow, and am pretty sure it should be easy to restore to the `#update` action.

**Comment by stratigos** [comment]
So, I worked on this for a while, and came to the following: 

* If this functionality is to be restored in `DeviseTokenAuth::PasswordsController#update`, then adopters will all have to start submitting a reset password token with this request. I dont think its a healthy approach to force such a change.

* The best place for this to happen, for `devise_token_auth`, is in the `DeviseTokenAuth::PasswordsController#edit` action. In fact, I believe the best course of action is to restore the original functionality, and roll back #957.

After examining this in detail, I am unsure as to why the change was necessary in the first place. I have been using the latest releases of `devise_token_auth` in my application since Dec 2016, and have never experienced any problems pertaining to "password cant be blank" errors occurring from the reset link in the email. Additionally, I am not sure why such an error would not have been reported until [Sept 14, 2017](https://github.com/lynndylanhurley/devise_token_auth/pull/957#issue-257731625).  So I am wondering if this was an issue with the reporter's application, or any customizations, as this is not a problem for a basic use case.

I cant find a way to re-implement the missing functionality without arriving at the above conclusion - it should just be put back where it was.

If anyone else could take a look and either enlighten me to the need for the change, Id be most grateful. That, or help me find a way to re-implement without requiring the reset pw token be made available in `#update` :). 

What I can certainly do is add some tests that verify password reset expiry works. 

@zachfeldman what do you think about the above? Is my perspective wrong? Should this be rolled back, or would you like me to submit a PR with the old functionality restored + pw reset expiry tests added?

@dks17 Could you please shed some light on your implementation, and perhaps we can find out why you were experiencing the problem that led to this change (#957), and why I havent ever experienced the same issue? I currently am forced to downgrade the gem in my host application (or override and add my own fix), as using a short password reset expiry is a requirement for me.

Thanks, and heres hoping we get to the bottom of this soon :)

**Comment by stratigos** [comment]
- nevermind this comment - i mistook some `devise` code using a user attr as a request param... this message will self destruct, sorry for the distraction all :)

**Comment by dks17** [comment]
@stratigos, hello.

1. I try to use devise_token_auth with Mongoid gem. To be exact, I don't want to use ODM and ORM simultaneously but only one Mongoid ODM.
2. Look at this, when you create new object:

with Mongoid
```
[1] pry(main)> User.new
=> #<User _id: BSON::ObjectId('5a04140ebb23be0efe965802'), c_at: nil, email: "", locked_until: nil, provider: "email", u_at: nil, uid: "">
```
and with MySQL
```
irb(main):002:0> User.new
=> #<User id: nil, email: "", created_at: nil, updated_at: nil>
```

Mongoid every time return new object with existed id property, not nil.

3. To achieve this #15 devise_token_auth should escape all checking conditions like:
if @resource.id

but check object existence and having errors of this object.

That is why I got stuck there.


Further about origin devise_token_auth gem and #957 PR.

> Could you please shed some light on your implementation, and perhaps we can find out why you were experiencing the problem that led to this change (#957)?

As I wrote there I caught the error when I followed the same link in email with recovery password information.
If you would like downgrade the gem and write some tests you are welcome, but please check my error case too.

> why I havent ever experienced the same issue?

I don't know.

**Comment by dks17** [comment]
I have already answered.

2017-11-09 4:51 GMT+03:00 Todd <notifications@github.com>:

**Comment by stratigos** [comment]
@dks17 Thanks for adding some info. I can see how you reached this problem, and what actions you chose to take to alleviate it. I can see how you arrived at your solution as well.

The problem, as I see it, is that this breaks functionality for anyone that does not have your use case. Additionally, even for your use case, it also breaks the ability to expire a reset password token. Its unfortunate that there are no tests which express this, and thats how I believe this side effect went unnoticed. 

I think if you take a look at the  `devise` source for [#reset_password_by_token](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/recoverable.rb#L143), you can see the additional functionality it is providing, and why its necessary to check for the presence of a persisted record afterwards.

Perhaps checking for presence of the `#id` itself was inadequate, and that something like `#persisted?` would have made more sense.

I believe a better approach would have been for you to override the functionality for `DeviseTokenAuth::PasswordsController#edit` in your application. I think the best approach overall would be to conditionally check for the type of data adapter being used, and proceed somewhat differently if using Mongoid. 

Further, I am thinking there may have been the assumption that errors appearing on your object should not be there, when in fact, it could be something within your host application that causes that. When I am asking about your implementation, I am referring to any custom overrides, scopes, mappings, logic, etc - anything youve done to make it "not vanilla." For a default (or "vanilla") use of `devise_token_auth`, this was working perfectly fine, and the functionality that was removed is needed. 

I am also curious to know the maintainers' position on this. @zachfeldman is this gem to now be so focused on Mongoid, that we can expect breaking changes for non Mongoid use cases? Should I accept that this is the expected behavior moving forward, and simply create my own local component for handling secure password reset token checks and expiry?

Thanks to the both of you for helping me understand this more.

**Comment by zachfeldman** [comment]
@stratigos we definitely aren't trying to support Mongo as our primary DB...we had an open pull request for Mongo support but it died a while ago. I tried to contact someone who had a fork that supported Mongo. Maybe it was @dks17 ?

I'm down to revert changes if you want to submit a PR, some additional test coverage would be helpful too...

**Comment by dks17** [comment]
@zachfeldman, I have [fork for Mongoid](https://github.com/dks17/devise_token_auth/tree/mongoid-v0.1.42), but now it's only experiment.

@stratigos rights
#957 PR changed behavior and it occurs like side effect. It is my bad.

Devise method reset_password_by_token(attributes={}) [accepts also](https://github.com/plataformatec/devise/blob/88e9a85d6a796a41f4dcf2528ed6d5f48916b5fd/lib/devise/models/recoverable.rb#L142) password and password_confirmation attributes. Every time even token is valid and not expired this method returns object with error. It tries reset password [here ](https://github.com/plataformatec/devise/blob/88e9a85d6a796a41f4dcf2528ed6d5f48916b5fd/lib/devise/models/recoverable.rb#L151)
`recoverable.reset_password(attributes[:password], attributes[:password_confirmation]) `

I wrote some tests and added a method to store predictable behavior. It also considers case then token is expired and returns error. I hope it helps to escape password: 'can't be blank' error and restore previous behavior before #957 PR. I have no the confidence that I did all right.

@stratigos please check  #1017 PR

**Comment by stratigos** [comment]
@dks17 that is certainly a better change, and those tests are needed. It looks like that change does restore the password reset expiry feature. 

However, I still think the best approach overall would have been for you to make a local override, and changed the `#edit` action to suit your application's needs. The original `#edit`, before #957, has much simpler code, and also allows error messages to appear as expected for the default use case.

I need those error messages in  my client application . A 404 page is not suitable for my consumers, so I would then need to make a local override to correctly attribute and return the expected error messages (i.e., "Your password reset token is expired, please reset your password again..."), even though that was the original functionality in this controller before #957. 

So for me, and I expect most everyone else, this is still broken. Its better than having no password reset token expiry at all, but we are still forced to make local overrides to restore functionality pertaining to handling and returning errors.

**Comment by stratigos** [comment]
@dks17 I looked over your change, and it suffices to restore the expected functionality. Thanks for adding those tests.

Handling the errors is more complex than I thought it would be, when `#edit` is restored to the point prior to #957, but the flow for handling a reset token error makes more sense with your change. Ill submit a PR for that once #1017 gets merged, which should then take care of #672.

**Comment by stratigos** [comment]
Now that #1017 is merged, Im going to bundle my app locally, and will close this thread once I see the pw reset expire working in action. Thx to both of you for your contributions in working this out.

**Comment by stratigos** [comment]
This appears to be working as of f8a8b6381130c657ae6983925bef6423743fe31a. 

I needed to update to `0.1.43beta1` to keep up with the update to #1017, which also requires that `users.allow_password_change` be added to your application schema as well (replace `users` with whatever your scope name is). 

After I migrated my application's database to have that table column, password reset expiry works as expected.

**Comment by typhoon2099** [comment]
This change has caused issues with our application. Users have requested password reset emails which then don't have valid links because their anti-spam filters have followed the link. Removing the token update in with_reset_password_token fixes this.

**Comment by akegan** [comment]
@typhoon2099 after pulling in the latest changes with your #1206  I'm finding that this issue of configuring the expiration time of a token still persists. It fixes the problem of anti-spam filters invalidating the link, but it seems like the link still never expires if the user doesn't actually reset their password.

Is there some other way to configure the expiration time of reset password tokens?
