### ISSUE TITLE
Cant login after signing in via oauth

### ISSUE THREAD

**Issue by sushant12** [lynndylanhurley/devise_token_auth#1010]
I have a rails-api app and I added the `gem 'omniauth-google-oauth2'` .  Everything is working fine up to showing an oauth screen and then clicking next to signup and the user is also saved into the db as well. But after that, I get an err saying 'Either signup or log in'. This is happening because I have a `before_action :authenticate_api_employee!` on my controllers.

I did some research and found out that the `current_api_employee` is nil as well. Any idea how this can be fixed?

I have overridden the omniauth_callbacks_controller and added a debugger there and current_api_employee have a value but it s value is set to nil after I am signed in and redirected.

Do i need to add `?origin=http:/.....` to the oauth url ? It looks like the omniauth_success needs that url to redirect properly but I am overriding the omniauth_success method.

Would really appreciate your help

My `ApplicationController` is extending from `ActionController::API` .

My Omniauth controller 

```
module Overrides
  class OmniauthCallbacksController < DeviseTokenAuth::OmniauthCallbacksController

  	def omniauth_success
      super do |resource|
        if omniauth_window_type.present? # auth requested from angular
           sign_in resource
       else  # if backend standalone auth
       		redirect_to '/test' and return
       		# sign_in_and_redirect test_path and return
        end
      end
    end


    # break out provider attribute assignment for easy method extension
    def assign_provider_attrs(user, auth_hash)
      user.assign_attributes({
         email: auth_hash['info']['email'],
         name: auth_hash['info']['name'],
         admin: true,
         first_name: CustomRegex.japanese?(auth_hash['info']["first_name"]) ? '' : auth_hash['info']["first_name"],
         last_name: CustomRegex.japanese?(auth_hash['info']["last_name"]) ? '' : auth_hash['info']["last_name"],
         uqid: SecureRandom.uuid,
         company_id: 1,
         timeline: 0
     	})
    end
  end
end
```

My Gemfile

```
gem 'devise_token_auth'
gem 'omniauth'
gem 'omniauth-google-oauth2'
ruby '2.3.0'
ENV['NOKOGIRI_USE_SYSTEM_LIBRARIES'] = 'YES'
gem 'rails', '4.2.6'
gem 'rails-api', '~> 0.4.0'
```

**Comment by zachfeldman** [comment]
@sushant12 are you going to explain how you fixed your problem in case anyone else has it? That would be helpful!

**Comment by sushant12** [comment]
@zachfeldman  i made a very rookie mistake. After I was redirected to auth_origin_url with tokens I used that token and sent it in the header to make a call to my apis.

**Comment by zachfeldman** [comment]
Ok!

**Comment by el-rotny** [comment]
Just in case someone needed to see how this is done on the client side. Posted a work around on redux-token-auth https://github.com/kylecorbelli/redux-token-auth/issues/28#issuecomment-412233112
