### ISSUE TITLE
API is not using defined ApiController but rather ApplicationController

### ISSUE THREAD

**Issue by karlingen** [lynndylanhurley/devise_token_auth#1014]
Doing a POST to `/api/v1/auth/sign_in` with email and password causes status 401.
Removing the line `before_action :authenticate_user!` from ApplicationController resolves the issue but breaks rest of the app. 

Using version `v0.1.42` of the gem.

Why is this happening when the auth is not even mounted to ApplicationController?
Also, the `sign_in` method should always ignore `:authenticate_user!` just like Devise. 

Controllers:
```
class Api::ApiController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
end

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end
```

Routes: 
```
devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
# API
namespace :api, defaults: { format: 'json' } do
  scope :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: { sessions: "users/sessions" }
    get :test
  end
end
```

Curl: 
```bash
$ curl -XPOST 'http://localhost:3000/api/v1/auth/sign_in' -d '{ "email":"foo@bar.com", "password":"123456" }' -H "Content-Type: application/json" -H 'Content-Type: application/json'
```

**Comment by zachfeldman** [comment]
@karlingen what happens if you turn off the option to refresh the token on every request?

**Comment by karlingen** [comment]
@zachfeldman no change unfortunately.. Seems like it's the same issue here: https://github.com/lynndylanhurley/devise_token_auth/issues/887
