### ISSUE TITLE
[WORKING] Instructions for Rails 5 API and Google OAuth2

### ISSUE THREAD

**Issue by sarink** [lynndylanhurley/devise_token_auth#1020]
## What is this?
This isn't really an issue, but more of a guide for how I made this gem work with a brand new Rails 5 API-only project and [Google OAuth2](https://github.com/zquestz/omniauth-google-oauth2). 

Hopefully it will serve to help others trying to use this today, as well as the authors to fix some of these problems in the library, and/or just update documentation.

*Please note that each time you make a change to an `initializer` file you need to restart your server for it to take effect!*

## Start with a new Rails 5 project
```
rails new . --api
```

## Initial gem install/configuration (copying [these instructions](https://github.com/lynndylanhurley/devise_token_auth#installation))

Add to `Gemfile`:
```
gem 'devise_token_auth', '0.1.43.beta1'
gem 'omniauth-google-oauth2'
```

Execute:
```
bundle install
rails g devise_token_auth:install User auth
rake db:migrate
```

## Create your google credentials
* Go to [the dashboard](https://console.cloud.google.com/projectselector/apis/credentials?supportedpurview=project), and walk through the process
* Your callback url is going to be: `<HOST>/omniauth/google_oauth2/callback` (assuming you used the default "omniauth" prefix)
* Copy your client_id and client_secret for the next step (I suggest storing them in `secrets.yml` and `gitignoring` that file), *DON'T COMMIT YOUR KEYS TO SOURCE CONTROL!*

## Configure OmniAuth (cherry-picking from [these instructions](https://github.com/omniauth/omniauth))

Add to `config/application.rb`
```
    # https://github.com/omniauth/omniauth#integrating-omniauth-into-your-rails-api
    config.session_store :cookie_store, key: '_interslice_session'
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore, config.session_options
```

Add to `config/initializers/omniauth.rb`
```
# https://github.com/omniauth/omniauth#getting-started
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, GOOGLE_KEY, GOOGLE_SECRET
end
```

## Error: undefined method `mount_devise_token_auth_for' for #<ActionDispatch::Routing::Mapper>

Add to top of `routes.rb`:
```
# https://github.com/lynndylanhurley/devise_token_auth/issues/777
require "devise_token_auth"
```

## Error: undefined method `flash' for #<Devise::OmniauthCallbacksController>

Add to `config/initializers/devise_token_auth.rb`
```
Rails.application.config.to_prepare do
 Devise::OmniauthCallbacksController.class_eval do
   # https://stackoverflow.com/questions/39879995/undefined-local-variable-or-method-flash-for-deviseomniauthcallbackscontro
   def failure
     set_flash_message! :alert, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.name), reason: failure_message
     redirect_to after_omniauth_failure_path_for(resource_name)
   end
```

Add to `config/initializers/devise.rb`
```
Devise.setup do |config|
  # https://stackoverflow.com/questions/39879995/undefined-local-variable-or-method-flash-for-
  config.navigational_formats = [:json]
end
````

## Error: ActiveModel::ForbiddenAttributesError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success
At this point, you _should_ have your omniauth flow succeeding (check your server output), but it dies in the `success` trying to save the attributes for the user.

Let's add another monkey-patch to `config/initializers/devise.rb`
```
Rails.application.config.to_prepare do
 Devise::OmniauthCallbacksController.class_eval do
   # https://github.com/lynndylanhurley/devise_token_auth/issues/82#issuecomment-344461078
   def assign_provider_attrs(user, auth_hash)
     all_attrs = auth_hash['info'].slice(*user.attributes.keys)
     orig_val = ActionController::Parameters.permit_all_parameters
     ActionController::Parameters.permit_all_parameters = true
     permitted_attrs = ActionController::Parameters.new(all_attrs)
     permitted_attrs.permit({})
     return_val = user.assign_attributes(permitted_attrs)
     ActionController::Parameters.permit_all_parameters = orig_val
     return return_val
   end
```

## The test
You should be able to successfully login with google-oauth2, and you should see a new `User` in your database with values in the `name, email, image` columns

Enjoy!

**Comment by sarink** [comment]
Update: I may have spoken too soon, although this _does_ achieve a successful auth, and the user is inserted into the database, `omniauth_callbacks_controller#omniauth_success` triggers `render_data_or_redirect

**Comment by H-L** [comment]
Hello @sarink,
I cannot pass through the last fix, I can't figure why.
Is there anything to set up on the User model (other than the `rails g devise_token_auth:install User auth`) ?

**Comment by Thananjaya** [comment]
Thanks for making things work in proper manner

**Comment by akshitahluwalia** [comment]
I am unable to monkey patch. `devise_token_auth.rb` file is as follows.
```
DeviseTokenAuth.setup do |config|
end
Rails.application.config.to_prepare do
   Devise::OmniauthCallbacksController.class_eval do
      def assign_provider_attrs(user, auth_hash)
        all_attrs = auth_hash['info'].slice(*user.attributes.keys)
        orig_val = ActionController::Parameters.permit_all_parameters
        ActionController::Parameters.permit_all_parameters = true
        permitted_attrs = ActionController::Parameters.new(all_attrs)
        permitted_attrs.permit({})
        return_val = user.assign_attributes(permitted_attrs)
        ActionController::Parameters.permit_all_parameters = orig_val
        return return_val
    end
  end
end
```

**Comment by sarink** [comment]
@akshitahluwalia that's exactly what mine looks like. Have you restarted your server? What error are you getting?

**Comment by akshitahluwalia** [comment]
@sarink It started working now. But after the login, i just don't have client_id and access_token rendered in header or response body and I am unable to figure that out. Please help.

**Comment by sarink** [comment]
@akshitahluwalia after the redirect? It should take you to your `auth_origin_url` and then you should see it in the url as query parameters. From there you parse it out and store it wherever (probably a cookie)

**Comment by akshitahluwalia** [comment]
Thanks, it worked !...

**Comment by sarink** [comment]
@mikeeus there's a better way than that monkey-patch that's a little clearer, I've updated the original instructions.

**Comment by MohamedTaha123** [comment]
pleaaaaaaaaaaaase i get this error : NoMethodError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success 
undefined method `[]' for nil:NilClass
uid: auth_hash['uid'],

**Comment by NOOBFREEAKER** [comment]
Error:- `ActionController::RoutingError: uninitialized constant OmniauthCallbacksController`
routes.rb :- `require "devise_token_auth"
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    sessions: 'overrides/sessions',
    registrations: 'overrides/registrations',
    omniauth_callbacks: 'overrides/omniauth_callbacks'
  }
  end`

**Comment by NOOBFREEAKER** [comment]
This is what I am getting as an error.
```
Started POST "/omniauth/facebook/callback" for 127.0.0.1 at 2019-03-12 13:26:08 +0530
Processing by DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks as */*
  Parameters: {"provider"=>"facebook"}
Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)


  
RuntimeError (No resource_class found):
  
app/controllers/application_controller.rb:6:in `configure_permitted_parameters'
```

My application controller has permitted parameters , i need it during `/auth` . What should be my approach of going round this and solve my issue to check if this is working? Help Appreciated!

**Comment by NOOBFREEAKER** [comment]
I get This Error :- 
`undefined method `new_session_path' for #<Devise::OmniauthCallbacksController:`
and the trace sends it to this code piece 
```
def failure
     set_flash_message! :alert, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.name), reason: failure_message
>  redirect_to after_omniauth_failure_path_for(resource_name)
end
```
What can be done to resolve this?

**Comment by yara11** [comment]
> @akshitahluwalia after the redirect? It should take you to your `auth_origin_url` and then you should see it in the url as query parameters. From there you parse it out and store it wherever (probably a cookie)

Hello I have the same problem, using omniauth-facebook. I can't find the client and access-token. I go to localhost:3000/auth/facebook?auth_origin_url=localhost:3000 in my browser. Once I sign in I'm redirected to https://www.facebook.com/v3.2/dialog/oauth/read/, there are no query parameters in the url. Can you please help?

**Comment by conflictor** [comment]
this specific instruction that i haven't seen on antothers answers, helps me to pass to production with devise and google auth, excellent, thanks you so much

config.session_store :cookie_store, key: '_interslice_session'
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore, config.session_options

**Comment by mquispe1185** [comment]
> this specific instruction that i haven't seen on antothers answers, helps me to pass to production with devise and google auth, excellent, thanks you so much
> 
> config.session_store :cookie_store, key: '_interslice_session'
> config.middleware.use ActionDispatch::Cookies
> config.middleware.use ActionDispatch::Session::CookieStore, config.session_options

in which file you add this?
