### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by Dimkarodinz** [lynndylanhurley/devise_token_auth#1022]
Added ukrainian localization to config/locales. Need access to push branch for pull request

* **Version**: 0.1.43.beta1

**Comment by zachfeldman** [comment]
@Dimkarodinz thanks! Please open a pull request from a fork of this repository.

**Comment by zachfeldman** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by Dimkarodinz** [comment]
Thanks! Just a moment

2017-11-16 23:00 GMT+02:00 Zach Feldman <notifications@github.com>:
