### ISSUE TITLE
BCrypt::Errors::InvalidSalt errors

### ISSUE THREAD

**Issue by furkanayhan** [lynndylanhurley/devise_token_auth#103]
- When I try to create a user by sending a POST request to `http://localhost:3000/auth` url.
  with `email`, `password` and `password_confirmation` parameters.
  - I get this: `BCrypt::Errors::InvalidSalt in DeviseTokenAuth::RegistrationsController#create`
  - However user is created.

- When I try to sign in by sending a POST request to `http://localhost:3000/auth/sign_in` url.
  with  `email` and `password` parameters.
  - Again, I get this: `BCrypt::Errors::InvalidSalt in DeviseTokenAuth::SessionsController#create`

Ruby version: 2.2.0
Rails version: 4.2.0
devise_token_auth version: master branch of this git repo

**Comment by lynndylanhurley** [comment]
Master is in the middle of a big update, and I'm sure there are several issues.

You can try using version `0.1.30`, but there may be issues there with Rails 4.2. I'm in the middle of upgrading, should be ready in the next day or so.

**Comment by furkanayhan** [comment]
Yes there are some issues with Rails 4.2 and `0.1.30`, so I decided to use master repo.

I have tried to fix this issue, but I could not.
Thank you, I will wait for new upgrades.

**Comment by lynndylanhurley** [comment]
Please check out version `0.1.31.beta6` and let me know if this has been resolved.

**Comment by furkanayhan** [comment]
It has been resolved. Thank you.
I guess I can close this issue now.

**Comment by lynndylanhurley** [comment]
Awesome, thanks @furkanayhan :smiley:
