### ISSUE TITLE
Error with mailer_sender

### ISSUE THREAD

**Issue by jdevng** [lynndylanhurley/devise_token_auth#1037]
config/initializers/devise_token_auth.rb:3:in `block in <top (required)>': undefined method `mailer_sender=' for DeviseTokenAuth:Module (NoMethodError)

In my initializer:

    DeviseTokenAuth.setup do |config|
      config.mailer_sender = "my@email.com"

if I change DeviseTokenAuth to Devise, it works. I'm not well versed enough to contribute with a change - I would assume this is an issue with DeviseTokenAuth not inheriting.

**Comment by zachfeldman** [comment]
Hey @jdevng does this actually affect the outcome of your app? If you change the line to Devise.setup, does your mail send correctly?

**Comment by jdevng** [comment]
Yes - I'll run some broader tests.

**Comment by MaicolBen** [comment]
You have to use `Devise`, check at the end of the section of https://github.com/lynndylanhurley/devise_token_auth#configuration-cont

**Comment by jdevng** [comment]
Thanks @MaicolBen - am I losing anything by not using the default value?

**Comment by MaicolBen** [comment]
No, you should change it unless you want "myapp.com" mail
