### ISSUE TITLE
Unpermitted parameters: user, registration

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#104]
I get an unpermitted parameters issues for "user, registration" when I try the curl command below:

    curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST http://0.0.0.0:3000/auth -d "{\"user\":{\"email\":\"user@example.com\",\"password\":\"secret\"}}"

Error:

    Processing by DeviseTokenAuth::RegistrationsController#create as JSON
      Parameters: {"user"=>{"email"=>"user@example.com", "password"=>"[FILTERED]"}, "registration"=>{"user"=>{"email"=>"user@example.com", "password"=>"[FILTERED]"}}}
    Can't verify CSRF token authenticity

    ActionController::UnpermittedParameters (found unpermitted parameters: user, registration):
      actionpack (4.1.8) lib/action_controller/metal/strong_parameters.rb:382:in `unpermitted_parameters!'
      actionpack (4.1.8) lib/action_controller/metal/strong_parameters.rb:275:in `permit'
      devise_token_auth (0.1.30) app/controllers/devise_token_auth/registrations_controller.rb:116:in `sign_up_params'
      devise_token_auth (0.1.30) app/controllers/devise_token_auth/registrations_controller.rb:9:in `create'

**Comment by ACPK** [comment]
All set!

**Comment by reydi** [comment]
What did you do?

**Comment by nicolas-besnard** [comment]
I think he just remove the key "user" from his JSON

**Comment by nicolas-besnard** [comment]
```http
curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST http://0.0.0.0:3000/auth -d "{\"email\":\"user@example.com\",\"password\":\"secret\"}"
````

**Comment by nicolas-besnard** [comment]
@ACPK FYI: you don't need to espace JSON on your CURL command :)

**Comment by ACPK** [comment]
@nicolas-besnard Here's the working line.

    Curl http://test.com auth --data "email=test@test.com&password=123456789&password_confirmation=123456789&first_name=John&last_name=Smith"
