### ISSUE TITLE
Easily saving access_token in User model for later 3rd party API access

### ISSUE THREAD

**Issue by danielcnorris** [lynndylanhurley/devise_token_auth#1041]
I've completed the basic setup following the readme after initiating a new rails 5 app, API only. I am using GitHub as my authentication provider. I want to save the GitHub access token in my User model, so that I can periodically fetch data from GitHub's API (via Octokit). Is there a way for me to easily extend the devise token auth controller, so that it does it's automatic magic and additionally saves the token in the `access_token` attribute of my User class? Thanks.

EDIT: Is it as simple as just subclassing `OmniauthCallbacksController`? I am new to Rails.

**Comment by danielcnorris** [comment]
Would something like this work?

https://stackoverflow.com/questions/39425850/what-does-yield-resource-in-the-devise-controllers-do

**Comment by zachfeldman** [comment]
@danielcnorris have you tried overriding the controller, calling super on the correct action to call the default code for it at the right time, then putting code before that to intercept the request and log that token? I'd start by trying to do a controller override.

**Comment by danielcnorris** [comment]
@zachfeldman Thanks for your suggestion. I also realized that I can create an Oktokit client with my application credentials that will automatically give me access to data for users that have authorized my app. So I don't actually need to store the token in the User model. I may still try it to confirm it works.

**Comment by zachfeldman** [comment]
Nice
