### ISSUE TITLE
Confirmation flow

### ISSUE THREAD

**Issue by kjakub** [lynndylanhurley/devise_token_auth#1045]
After clicking on confirmation link in email, backend redirecting to url with params for example

`/?account_confirmation_success=true&account_confirmation_success=true&client_id=GkgWm0LKhoVlgT353ztRlQ&client_id=z-egqMAP32r5VJGBciAJEg&config=default&config=default&expiry=1514259134&expiry=1514262981&token=uSJvkZAmJW66yFqCdh6lpg&token=fGY-7HMMy3EftinljvYeSQ&uid=joby@gmail.com&uid=mygucakune@hotmail.com`

What i suppose to do with that ? Is this mean to be tokens/data to authenticate with ? Something like auto-login after clicking confirmation link in email ? 

1. If YES how do integrate that with https://github.com/neroniaky/angular2-token ?
2. OR how do i get rid off sensitive data from URL params ?  i just wanna display "confirm ok please login to user" -> how do i override controllers in here? - is it same as devise gem ?

**Comment by zachfeldman** [comment]
How are you sending the confirmation email?

**Comment by kjakub** [comment]
@zachfeldman I did not change anything on rails side just enabled

```
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         # :rememberable, 
         :trackable,  
         :validatable,
         # :omniauthable,
         :confirmable
end
```

and controllers are not overridden

register post request

```
Request Headers

Accept:application/json
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:229
Content-Type:application/json
Host:localhost:3000
Origin:http://localhost:4200
Referer:http://localhost:4200/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Request Payload

{email: "zokob@hotmail.com", password: "Pa$$w0rd!", first_name: "Daquan", last_name: "Wooten",…}
confirm_success_url:"http://localhost:4200/account_confirmed"
email:"zokob@hotmail.com"
first_name:"Daquan"
...
```

link in email

`http://localhost:3000/auth/confirmation?config=default&confirmation_token=ZmyCtRezoXtxRVjxCBzk&redirect_url=http%3A%2F%2Flocalhost%3A4200%2Faccount_confirmed`

redirected from rails 
```

Processing by DeviseTokenAuth::ConfirmationsController#show as HTML
  Parameters: {"config"=>"default", "confirmation_token"=>"ZmyCtRezoXtxRVjxCBzk", "redirect_url"=>"http://localhost:4200/account_confirmed"}
  User Load (1.9ms)  SELECT  "users".* FROM "users" WHERE "users"."confirmation_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["confirmation_token", "ZmyCtRezoXtxRVjxCBzk"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  SQL (0.6ms)  UPDATE "users" SET "confirmed_at" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["confirmed_at", "2017-12-12 15:27:42.968966"], ["updated_at", "2017-12-12 15:27:42.970433"], ["id", 35]]
   (2.8ms)  COMMIT
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["tokens", "{\"76_YsspL7hP6_z-oZmqnEw\":{\"token\":\"$2a$10$rGpuTmF56WyyThEItNLXa.imOJs9CQwtCw61vKxGC0jTAjI3Fgy3a\",\"expiry\":1514302063}}"], ["updated_at", "2017-12-12 15:27:43.036559"], ["id", 35]]
   (2.8ms)  COMMIT
Redirected to http://localhost:4200/account_confirmed?account_confirmation_success=true&client_id=76_YsspL7hP6_z-oZmqnEw&config=default&expiry=1514302063&token=pbLBKNQiEkGfE_QW3MSWWw&uid=zokob%40hotmail.com
```

**Comment by zachfeldman** [comment]
Ok, this makes sense to me. So the link in the email contains a confirmation token and a redirect url - then your'e redirected to that redirect URL with all the params you need to sign in the user. What's wrong exactly?

**Comment by kjakub** [comment]
in this case nothing wrong, and i was guessing right then "Is this mean to be tokens/data to authenticate with ?" and same case for reset password flow. 

hmm, i am not sure if i want to perform auto-login on frontend after clicking link in emails, so i better override those controllers and remove those url params, for my case are not necessary there. I might find some time and do PR and have it as a switch in config. What do you think ?

**Comment by zachfeldman** [comment]
Cool, sure. Yeah a PR might be nice I'm not sure how many others would find this useful but I'd be down to review it!
