### ISSUE TITLE
NoMethodError: undefined method 'allow_password_change='

### ISSUE THREAD

**Issue by hansy** [lynndylanhurley/devise_token_auth#1046]
Trying to hit the password reset endpoint, but Rails spits this error: `NoMethodError: undefined method 'allow_password_change='`. It's breaking in the passwords controller.

Do I have to add this method to the model manually? Here's my current `User` model:

```
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :confirmable

  include DeviseTokenAuth::Concerns::User
end
```

Using Version 0.1.43.beta1 (from master branch).

**Comment by hansy** [comment]
Oh I see. It's not a method; it's an attribute that must not have made it into my schema. Apologies for the confusion.

**Comment by arnaudcosson** [comment]
@hansy can you please show the code you edit to fix this error?

**Comment by hansy** [comment]
@arnaudcosson Add `allow_password_change` as a boolean attribute to your Devise model in your migration.
