### ISSUE TITLE
I can not insert name when registering user

### ISSUE THREAD

**Issue by RuanHerculano** [lynndylanhurley/devise_token_auth#1048]
**My request**:
[![Screenshot_from_2017-12-21_16.45.39.png](https://s10.postimg.org/3xhhka6xl/Screenshot_from_2017-12-21_16.45.39.png)](https://postimg.org/image/ekbappf2t/)

**My response**:
[![Screenshot_from_2017-12-21_16.46.08.png](https://s10.postimg.org/o4uxcrzbt/Screenshot_from_2017-12-21_16.46.08.png)](https://postimg.org/image/h1n1x5tw5/)

**My migration**:
[![Screenshot_from_2017-12-21_16.50.26.png](https://s10.postimg.org/ex2ow4xfd/Screenshot_from_2017-12-21_16.50.26.png)](https://postimg.org/image/e7jwjrwvp/)

**My model**:
[![Screenshot_from_2017-12-21_16.52.42.png](https://s10.postimg.org/u5sm9zr4p/Screenshot_from_2017-12-21_16.52.42.png)](https://postimg.org/image/8jdlsysk5/)

**Comment by zachfeldman** [comment]
What does your controller look like? Name isn't inserted by default as far as I know, I think you'd have to override the controller.

**Comment by RuanHerculano** [comment]
I did not create a controller for this. It is necessary to create?

**Comment by zachfeldman** [comment]
Yes, you'll probably have to create an overrides controller to override default behavior because I don't think the API assumes/creates/updates a name out of the box. See the docs

**Comment by RuanHerculano** [comment]
Do you have any examples to show me of someone who did something similar?

**Comment by RuanHerculano** [comment]
**This resolve my problem!**
tanks @zachfeldman
```ruby
class ApplicationController < ActionController::API
[...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    Rails.logger.info "in ApplicationController.rb configure_permitted_parameters!"
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :nickname])
  end

end```
