### ISSUE TITLE
Manual Authentication and Registration

### ISSUE THREAD

**Issue by NicholasLYang** [lynndylanhurley/devise_token_auth#1051]
Hi, so I'm attempting to integrate devise_token_auth and graphql_ruby. Namely, I want authentication for some of my mutations. However, I'm struggling with finding a way to manually create users and authenticate them without going through the usual request routes. Is there a helper function or something for creating users? Thanks!

**Comment by zachfeldman** [comment]
Hey @NicholasLYang how about User.create(user_params)? Not sure why you need to use a special DTA method to create a user. There is a special DTA method for auth though! See `valid_token` in the docs:
https://github.com/lynndylanhurley/devise_token_auth

**Comment by NicholasLYang** [comment]
Main issue with just creating the user is it doesn't trigger the confirmable email. Though actually...I can just do that manually. Alright, that works. Thanks!

**Comment by zachfeldman** [comment]
@NicholasLYang you're welcome! We're always welcoming new contributors....if you have time, check out the issue queue.

**Comment by j-jackson** [comment]
@zachfeldman sorry if this is a dumb question, but how would you handle login?

I have a controller which which successfully creates and stores the tokens when hitting "

**/api/v1/auth/sign_in**

```ruby
module Api
  module V1
    class ApplicationController < ApplicationController
      skip_before_action :authenticate_user!
      include DeviseTokenAuth::Concerns::SetUserByToken
    end
  end
end
```

Is there a method I can call from my GraphQL mutation to do this?
