### ISSUE TITLE
Support Devise 4.4.0 & Ruby 2.5.0

### ISSUE THREAD

**Issue by nitsujri** [lynndylanhurley/devise_token_auth#1057]
Hi lynndylanhurley, thanks for this amazing gem that helps keep our API's secure.

A few days ago devise upgraded to `4.4.0` to support Ruby `2.5.0`.

We would love to start testing Ruby 2.5 and need this version bump to help us along.

Thanks!
Justin

**Comment by lynndylanhurley** [comment]
Thanks for the heads up @nitsujri! We'll take care of this ASAP. Feel free to submit a PR if you have time!

**Comment by MaicolBen** [comment]
Closed via #1056
