### ISSUE TITLE
Circular dependency detected while autoloading constant Api

### ISSUE THREAD

**Issue by rajaaa92** [lynndylanhurley/devise_token_auth#106]
I'm using this gem together with the module `ng-token-auth` in my Ionic mobile app (which bases on angular). 
After logging in, if I reload the page, a request `auth/validate_token` will be sent. I get a `'Circular dependency detected while autoloading constant Api'` on that.
I'm also using the gem `grape` for building the API, which could also be the source of the problem.

This is my `routes.rb` file (`devise` is also included because I'm using it in my Rails app which contains the API):
```ruby
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  namespace :api do
    mount_devise_token_auth_for 'User', at: '/v1/auth'
    mount API => '/'
    mount GrapeSwaggerRails::Engine => '/doc'
  end
  (...)
end
```

There is no useful info in the server logs. How can I solve this problem?
Thank you!

**Comment by lynndylanhurley** [comment]
Can you try upgrading to version `0.1.31.beta8`? This looks like it may be related to an issue with `namespace` that was just fixed in that version.

**Comment by rajaaa92** [comment]
that worked! thank you so much!
