### ISSUE TITLE
NoMethodError: undefined method `provider' for #<User

### ISSUE THREAD

**Issue by shivabhusal** [lynndylanhurley/devise_token_auth#1063]
I am facing this error
```ruby
 > a=User.create
   (3.0ms)  BEGIN
   (0.1ms)  ROLLBACK
NoMethodError: undefined method `provider' for #<User:0x0000000008433390>
```
I don't have `uid` and `provider` fields in `users` table. However, I have moved these fields to `auth_identities` table. 

can I make `devise_token_auth` not to search for the fields `uid`, `provider`?

**Comment by zachfeldman** [comment]
You could but you'd have to modify the library extensively. This is default behavior.

**Comment by omarosama89** [comment]
@shivabhusal Yeah you can.
1. in `config/initializers/devise_token_auth.rb` uncomment this line and make it `false` 
```
  config.change_headers_on_each_request = false
```
2. search for `config.other_uid` and set it to whatever field you want.
3. Create `app/controllers/devise_token_auth/concerns/resource_finder.rb` file with
```
module DeviseTokenAuth::Concerns::ResourceFinder
  extend ActiveSupport::Concern
  include DeviseTokenAuth::Controllers::Helpers

  def provider
    "${new_attribute_name}"
  end
end
```
