### ISSUE TITLE
Simplify the Readme.

### ISSUE THREAD

**Issue by zoopyserg** [lynndylanhurley/devise_token_auth#1069]
The first sentence should be a 25-word description of WHAT THIS GEM DOES.

The second sentence may be a 25-word description of HOW IT DOES IT. The big picture.

And only then the rest of Readme (what it integrates with, the options, the settings etc.).

Ideally, it should be a website with a new page for each section.

Request for contributions goes to the bottom.

**Comment by zachfeldman** [comment]
Hey @zoopyserg , that sounds great! I look forward to your pull request :)

**Comment by zoopyserg** [comment]
I already helped you by posting this suggestion.

**Comment by lynndylanhurley** [comment]
![screen shot 2018-01-17 at 11 44 47 am](https://user-images.githubusercontent.com/468037/35057922-fc867bd2-fb7b-11e7-8bd5-90b56df9e175.png)

**Comment by zoopyserg** [comment]
Yeah, and?
This doesn't answer my question.
As a visitor, I want to know in first 10 seconds, what data gets moved to where, and what for.

**Comment by zachfeldman** [comment]
Hey @zoopyserg this is a completely volunteer run, not for profit project, so your demanding tone is not helpful. 

We appreciate your suggestion but if you want it to get done fast, we'd appreciate your help doing it even more than just opening an issue.

**Comment by zoopyserg** [comment]
I think if it's not clear in first few seconds what this project does, the author also doesn't fully understand why he's running this project.

Your task, as a project owner, is to come up with a line that you can tell to a person, absolutely unfamiliar with the jargon, and they would understand it.

The fact that it's non-profit doesn't mean it has to be not understandable.

**Comment by zoopyserg** [comment]
Don't expect your users to read everything about everything to understand your project.
Say "The only way to bind front-end frameworks with Devise" as your first line, if that's the case.

**Comment by KelseyDH** [comment]
I appreciate the tenor of what's being put forward, and I do strongly encourage a few of us make mindful contributions to improving documentation in this project.

For narrowing focus of how exactly to do this I would everyone's attention to this constructive blog post on the matter that I think distills how to write good documentation well:  https://www.divio.com/en/blog/documentation/

**Comment by waiting-for-dev** [comment]
@zoopyserg , maybe you feel you have the right to have people out there working for free for you, but open source development is not easy (usually no revenue at all, investing of your free time...). If you don't like something, just don't take it.

> The fact that it's non-profit doesn't mean it has to be not understandable.

The fact that is non-profit means that you as a user can't demand anything. They are the maintainers themselves who accept to take a responsibility that technically doesn't exist. Next time you encounter an issue, instead of investing your time to criticize people's work it would more profitable if you solve it. You are wrong if you think that the job of maintaining a project falls backs only in the project owner. Without going any further, this gem has [128 contributors](https://github.com/lynndylanhurley/devise_token_auth/graphs/contributors). It would be nice if you became one of them.

**Comment by zoopyserg** [comment]
I mean exactly what KelseyDH just said.

There are many great plugins out there.
Too many.
So you have to choose.
The normal way of research looks like "open each one in a new tab, close the ones that don't have demos, are outdated, or are hard to understand from the first sight, and try out the rest".

I came to this gem from several places, so it sounds like if you want tokens for SPA on Rails, this is the way to go. 

And when I come here, I don't expect the Readme to start with "Contributors wanted".
I expect the first line to tell me why this gem is the best option.

I'm saying don't be on the way of people trying to learn it.
I don't demand anything.

**Comment by zachfeldman** [comment]
Hey @waiting-for-dev , we really appreciate your encouraging comments in this situation. Have a great day!

**Comment by zoopyserg** [comment]
Say:

> _Summary_
> If you're building SPA on Rails, and you want authentication, you [need tokens, not cookies](https://auth0.com/blog/cookies-vs-tokens-definitive-guide/).
> Tokens need to be refreshed on each claim to keep the app secure and convenient.
> You need to expire tokens if the user signs out.
> If the user has many devices, there may be many tokens per account, and each one needs to be analyzed separately.
> This gem handles all the server-side aspects of this.
> On the client-side you may have any framework you like.
>
> _DEMOS_
> - Angular
> - Reakt
> - jToker
> - Vue
> ...
> 
> _Installation_
> ...
> 
> _Usage_
> ...
>
> _Settings_
> ...

I'm not qualified yet to commit that.
I may be wrong about some of these things.
But that's in a nutshell what I would put on top of my Readme.
Readme should be the place after which I have to look no further.

I find @waiting-for-dev 's docs on [devise-jwt](https://github.com/waiting-for-dev/devise-jwt) much more comprehensive. 
Which is the main reason why I tried that gem first, before trying this one.

**Comment by lynndylanhurley** [comment]
@zoopyserg thank you, that summary is an improvement over mine. 

@waiting-for-dev thank you for your kind words.

@KelseyDH thanks for your input. I'll read through that link ASAP.

Re-opening this for further discussion.

**Comment by RigoTheDev** [comment]
@zoopyserg Wow, you must be a very lovely person to deal with.
