### ISSUE TITLE
Error with RailsAdmin. "The action 'new' could not be found for DeviseTokenAuth::SessionsController"

### ISSUE THREAD

**Issue by furkanayhan** [lynndylanhurley/devise_token_auth#107]
I want to use RailsAdmin gem for my API application.

when I visit "localhost:3000/admin"
I get: `The action 'new' could not be found for DeviseTokenAuth::SessionsController`

my `routes.rb`
```ruby
mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
mount_devise_token_auth_for 'User', at: '/api/v1/auth', skip: [:omniauth_callbacks]
namespace :api, defaults: { format: 'json' } do
  namespace :v1 do
    # resources...
  end
end
```

Ruby 2.2
Rails 4.2

**Comment by lynndylanhurley** [comment]
1. Which version of this gem are you using?

2. Does the discussion in #47 help you out at all?

**Comment by furkanayhan** [comment]
- I am using `0.1.31.beta8`
- I have tried, but it did not help.

Can't I use Devise for web while using this gem?
How do I login in a browser, not via an API.

**Comment by lynndylanhurley** [comment]
You can use devise alongside this gem, but you will need to mount the routes to a different path.

For example:

~~~ruby
Rails.application.routes.draw do

  # token auth routes available at /api/v1/auth
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  # standard devise routes available at /users
  devise_for :users

end
~~~

**Comment by furkanayhan** [comment]
Your routes.rb config fixes the route issue.

But there is a new problem now.

In Rails Admin panel, when I try to Log Out, it goes to `/api/v1/auth/sign_out` instead of `/users/sign_out`.
They are both defined in routes:
```
destroy_api_v1_user_session DELETE /api/v1/auth/sign_out(.:format)        devise_token_auth/sessions#destroy {:format=>"json"}
destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
```

Reason:
- Rails Admin try to find `logout_path` (https://github.com/sferik/rails_admin/blob/master/app/helpers/rails_admin/application_helper.rb#L43)
- It asks `Devise::Mapping.find_scope!` (https://github.com/plataformatec/devise/blob/master/lib/devise/mapping.rb#L38)
- It matches the first one, then returns `:api_v1_user` instead of `:user`.

**Comment by lynndylanhurley** [comment]
Can this be solved by moving the `devise_for` method before the `devise_token_auth_for` method? For example:

~~~ruby
Rails.application.routes.draw do

  # standard devise routes available at /users
  devise_for :users

  # token auth routes available at /api/v1/auth
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

end
~~~

**Comment by furkanayhan** [comment]
And this works. Than you! :+1:

**Comment by lynndylanhurley** [comment]
:metal:
