### ISSUE TITLE
Session Overflow Error

### ISSUE THREAD

**Issue by jgoodall628** [lynndylanhurley/devise_token_auth#1077]
I am using sessions for omniauth only and to the best of my knowledge they are not really used for anything. But I am receiving a session overflow error. When I look at my session, the entire serialized user is stored in the session. I have done some research and I think the issue may be related to this line `sign_in(:user, user, store: false, event: :fetch, bypass: DeviseTokenAuth.bypass_sign_in) `. Reference this issue here https://github.com/plataformatec/devise/issues/3981. Please let me know if there is a way to limit the session size or fix this problem.

When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**: 0.1.39
* **Rails Stacktrace**: /gems/activerecord-session_store-1.0.0/lib/active_record/session_store/session.rb:94 in raise_on_session_data_overflow!
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:382 in block in make_lambda
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:169 in block (2 levels) in halting
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:770 in block (2 levels) in deprecated_false_terminator
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:769 in catch
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:769 in block in deprecated_false_terminator
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:170 in block in halting
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454 in block in call
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454 in each
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454 in call
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101 in __run_callbacks__
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750 in _run_save_callbacks
/gems/activerecord-5.0.2/lib/active_record/callbacks.rb:298 in create_or_update
/gems/activerecord-5.0.2/lib/active_record/persistence.rb:125 in save
/gems/activerecord-5.0.2/lib/active_record/validations.rb:44 in save
/gems/activerecord-5.0.2/lib/active_record/attribute_methods/dirty.rb:22 in save
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:319 in block (2 levels) in save
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:395 in block in with_transaction_returning_status
/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232 in block in transaction
/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189 in within_new_transaction
/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232 in transaction
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211 in transaction
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:392 in with_transaction_returning_status
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:319 in block in save
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:334 in rollback_active_record_state!
/gems/activerecord-5.0.2/lib/active_record/transactions.rb:318 in save
/gems/activerecord-5.0.2/lib/active_record/suppressor.rb:41 in save
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/active_record_5.rb:15 in block in save
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/transaction.rb:858 in with_database_metric_name
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent.rb:584 in with_database_metric_name
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/active_record_5.rb:14 in save
/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/active_record_store.rb:85 in block in write_session
/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:47 in silence_logger
/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/active_record_store.rb:82 in write_session
/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:354 in commit_session
/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:234 in context
/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/cookies.rb:613 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38 in block in call
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97 in __run_callbacks__
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750 in _run_call_callbacks
/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90 in run_callbacks
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:36 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/remote_ip.rb:79 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/airbrake-6.0.0/lib/airbrake/rack/middleware.rb:52 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:49 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/railties-5.0.2/lib/rails/rack/logger.rb:36 in call_app
/gems/railties-5.0.2/lib/rails/rack/logger.rb:24 in block in call
/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69 in block in tagged
/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26 in tagged
/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69 in tagged
/gems/railties-5.0.2/lib/rails/rack/logger.rb:24 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-2.0.3/lib/rack/method_override.rb:22 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-2.0.3/lib/rack/runtime.rb:22 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-2.0.3/lib/rack/sendfile.rb:111 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-cors-0.4.1/lib/rack/cors.rb:81 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/railties-5.0.2/lib/rails/engine.rb:522 in call
/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/puma-3.6.2/lib/puma/configuration.rb:225 in call
/gems/puma-3.6.2/lib/puma/server.rb:578 in handle_request
/gems/puma-3.6.2/lib/puma/server.rb:415 in process_client
/gems/puma-3.6.2/lib/puma/server.rb:275 in block in run
/gems/puma-3.6.2/lib/puma/thread_pool.rb:116 in block in spawn_thread

**Comment by MaicolBen** [comment]
Did you try upgrading with the latest version of this gem?

**Comment by jgoodall628** [comment]
I determined that the issue was caused by the serializer i was using.
