### ISSUE TITLE
codeclimate-test-reporter soon be deprecated

### ISSUE THREAD

**Issue by dks17** [lynndylanhurley/devise_token_auth#1080]
Just for information. [codeclimate-test-reporter - [SOON TO BE DEPRECATED]](https://github.com/codeclimate/ruby-test-reporter)
They suggest using [new test reporter](https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage).

I am not sure but Gemfile should be corrected from:
```ruby
# code coverage, metrics
group :test do
  gem 'codeclimate-test-reporter', require: nil
  gem 'rails-controller-testing'
end
```
to
```ruby
# code coverage, metrics
group :test do
  gem 'simplecov', require: false
  gem 'rails-controller-testing'
end
```

**Comment by zachfeldman** [comment]
@dks17 makes sense. Want to make a PR for this?

**Comment by dks17** [comment]
@zachfeldman Ok. I'll try.

**Comment by dks17** [comment]
@zachfeldman, @MaicolBen 
I hope example 2 will be helpfully.
https://github.com/codeclimate/test-reporter/blob/master/examples/ruby_examples.md
