### ISSUE TITLE
Can't add field for unique validation

### ISSUE THREAD

**Issue by MaratovichDan** [lynndylanhurley/devise_token_auth#1089]
In model `User`, I added field `phone_number`. Phone number should be validatable field.
```

class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
  include DeviseTokenAuth::Concerns::User

  validates :phone_number, uniqueness: true

end
```

When I create user, I get error: `ActiveRecord::RecordInvalid (Validation failed: Phone number has already been taken)
`
`Parameters: {"email"=>"dan.s91@mail.ru", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "phone_number"=>"0133456789", "registration"=>{"email"=>"dan.s9122312121112234@mail.ru", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "phone_number"=>"0133456789"}}`

**Comment by zachfeldman** [comment]
Seems like your validation is working just fine? Not sure how this question relates to this gem either.

**Comment by MaratovichDan** [comment]
@zachfeldman yes, you are right. Thank's!
