### ISSUE TITLE
"an error ocurred" when receiving the callback from google

### ISSUE THREAD

**Issue by mgs96** [lynndylanhurley/devise_token_auth#1090]
Hello, I'm trying to implement omniauth with google, I was able to redirect to google, select account and then redirect to the callback route, but I'm getting `an error ocurred` error when rendering omniauthsuccess, the users are being created, I can see them in the rails console, I have already looked some tutorials like [this one](https://richonrails.com/articles/google-authentication-in-ruby-on-rails/) but no success

![screenshot_1](https://user-images.githubusercontent.com/11526488/36155479-7a659c46-10a2-11e8-8647-4d9e139f419a.png)

the versions of the gems are the following:
- devise (4.3.0)
- devise_token_auth (0.1.42)
- oauth2 (1.4.0)
- omniauth (1.8.1)
- oauth2 (1.4.0)
- omniauth (1.8.1)
- omniauth-google-oauth2 (0.5.3)
- omniauth-oauth2 (1.5.0)
- rails (5.1.4)

The project was created using the --api flag, I have already configured the devise initializer.
```ruby
Devise.setup do |config|
    config.navigational_formats = [ :json ]
    config.mailer_sender = "mail@gmail.com"
    config.omniauth :google_oauth2, ENV["GOOGLE_KEY"], ENV["GOOGLE_SECRET"], {}
end
```
the routes are the following:
```ruby
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, defaults: { format: :json }

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :products
    end
  end
end
```

currently I'm not using any front end, just testing in my browser.

Thanks in advance.. and If I'm able to pull this off, I will gladly contribute with a tutorial, or a README, or something, thanks again

**Comment by 13LD** [comment]
Try to make like this - it works for me 
```
provider :google_oauth2, ENV["GOOGLE_KEY"], ENV["GOOGLE_SECRET"],
{
    display: 'popup',
    prompt: 'select_account consent',
    access_type: 'offline',
    scope: 'userinfo.email',
    redirect_uri: 'http://vimapp.herokuapp.com/omniauth/google_oauth2/callback'
}
```
