### ISSUE TITLE
Does it works with Sequel?

### ISSUE THREAD

**Issue by unrooty** [lynndylanhurley/devise_token_auth#1092]
I use Squel-rails and sequel-devise  gems. When I run `rails g devise_token_auth:install User auth`, I have an exception: `'retrieve_connection': No connection pool with 'primary' found. (ActiveRecord::ConnectionNotEstablished) `. Is there any way to use `devise_token_auth` with Sequel?

**Comment by zachfeldman** [comment]
@unrooty you'll need to be more specific.

**Comment by unrooty** [comment]
Nobody can help with this question?

**Comment by zachfeldman** [comment]
@unrooty not without more detail. You've refused to elaborate so I'm closing for now.

If I had to guess, you're asking if this gem works with Sequel instead of ActiveRecord, which I don't think it does. Feel free to write a pull request though if you can figure it out!
