### ISSUE TITLE
No create in confirmations controller?

### ISSUE THREAD

**Issue by davidwparker** [lynndylanhurley/devise_token_auth#1093]
I noticed in the confirmations controller that there is no create action.

I'm using rails-api, and the plan is to have a 100% React frontend. As Rails won't be handling any views, I don't expect devise_token_auth to handle confirmations w/a handler, but instead I would handle it via React.

Is the best way to handle this to override the default confirmations controller? Or is there a plan to make a create action so the gem can handle it?

Thanks!

**Comment by zachfeldman** [comment]
Hey @davidwparker , can you be more specific? My understanding is that a confirmation just sends a token back to the server, we confirm the user, then send back an auth token for you to user for to keep them logged in after that. The `show` action handles this, so why do you need a `create`? If you need to send the user an email, you could just generate a token for them using Devise's built in methods and then send them an email yourself (that's what we do).

I suppose it might be nice to integrate this directly into the lib as a controller action though! Feel free to write a PR.

**Comment by davidwparker** [comment]
@zachfeldman - when the user hits the application from the email, it will never hit the `show` method, as for my app it's all an SPA and each request doesn't hit the backend unless I manually send that extra request. For this instance, I figured it would just `create` the confirmation manually (similar to how the show works) but just render the resource as json. Thanks!

**Comment by zachfeldman** [comment]
Ok!
