### ISSUE TITLE
Basic Example with Postman?

### ISSUE THREAD

**Issue by davidwparker** [lynndylanhurley/devise_token_auth#1094]
Hello again,

Sorry, but I've been banging my head against this and figured I'd finally just ask.

I have setup my rails-api app to be completely JSON based. I'm using Postman to test each API.

I now have users, confirmations, sessions.

I've created my first resource, and I've added `before_action :authenticate_user!` figuring that would Just Work. 

For postman, the authorization methods they recommend don't align, so I've tried to do three different ways via headers or params, all to no avail.

1. Set header = `Authorization` and then multiple fields in there (similar to this: https://github.com/lynndylanhurley/ng-token-auth#using-alternate-header-formats)
2. Set headers for each thing individually (access-token, client, uid)
3. Set each thing as a param (access-token, client, uid)

Based on this, I would expect 2 or 3 to work:
https://github.com/lynndylanhurley/devise_token_auth/blob/v0.1.42/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L19

Note I'm using v0.1.42.

Unfortunately, none of these seem to work. It seems to look up the user, then fails the rest of the chain.

For the data, I'm using the uid from the DB table, then within the JSON field for tokens, I take the client and token: `"SOME_CLIENT": { "token": "SOME_TOKEN" }`

I'm sure I'm missing something small. 

Thanks for the help!

**Comment by davidwparker** [comment]
Digging in a little more, I just realized that the access-token should be sent back from a previous request because it's the token-hash stored in the DB (so I was using the hash not the token). 

I'm not certain how to get the initial token value... My guess it it would be returned when running the create session and returned there? (I'm not seeing it in Postman though).

**Comment by zachfeldman** [comment]
Hey @davidwparker, how about looking at one of the client libraries like jtoker, ng-token-auth, or redux-auth for an example? They're not 100% reliable and up to date but might give you some ideas.

I'm pretty sure the token should be returned when creating a session as you've mentioned....

**Comment by davidwparker** [comment]
@zachfeldman - yes, I looked at the example on ng-auth-token. As it turned out, I answered my own question (using the token-hash instead of the token). I'm not sure why Postman wasn't returning it ❓ but manually creating the token in console, grabbing the bcrypt password token-hash, and saving that (after turning off updates on requests) and I'm able to use that manually / easily. 

Thanks!

**Comment by zachfeldman** [comment]
Nice!
