### ISSUE TITLE
Token is not generated when login  through facebook

### ISSUE THREAD

**Issue by lateshkudnekar** [lynndylanhurley/devise_token_auth#1099]
Hi,
I'm developing a user registration and login feature for my ember app, rails api as backend. After getting user info and token from facebook, i am creating a new user and after calling sign_in tokens are not generated, plz provide suggestion (No errors on log)
```.....
  def redirect_callbacks
    find_for_oauth(request.env["omniauth.auth"])
  end

  private
  def find_for_oauth(auth)
    email = auth.info.email
    user = User.where(:email => email).first if email
    # Create the user if it's a new registration
    if user.nil?
      user = User.new(
        name: auth.extra.raw_info.name,
        email: email,
        password: Devise.friendly_token[0,20],
        uid: auth.uid,
        provider: auth.provider,
      )
      user.save!
      sign_in user
    else
      sign_in user
    end
  end
end
```

Rail Api
* Rails v5.0.
* devise_token_auth (0.1.43.beta1)
* devise 4.0.0.rc2
* omniauth 1.6.1
* omniauth-facebook 4.0.0
* omniauth-oauth2 1.4.0

Ember
* torii 0.10.1
* ember-simple-auth 1.1.0

**Comment by zachfeldman** [comment]
Hey @lateshkudnekar, have you looked at the jtoker, redux-token-auth, or similar repositories for guidance?

**Comment by mikeover** [comment]
@zachfeldman I'm in a similar spot. I'm using redux-token-auth for my frontend which is a separate app and repo from my Rails 5 backend API. From the frontend, I'm redirecting the user to `/omniauth/twitter`, getting sent to Twitter for auth, getting back to the callback on the backend at `/auth/twitter/callback` but then it just stops there. 

It creates a user, creates an auth token but I never back to the frontend app. Where am I going wrong here?

**Comment by zachfeldman** [comment]
@mikeover except you're using Rails 5 API and this user probably wasn't.

**Comment by mikeover** [comment]
He is, it says explicitly in the OP that he's using Rails 5 API.

**Comment by zachfeldman** [comment]
Oh ok, I kind of interpreted that as, "A Rails API" vs. "Rails 5 in API-only mode". My bad!
