### ISSUE TITLE
Unrequired route

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#110]
I figured it out that there is some route that aren't required for this project such as '/resource/sign_up' on 'devise_token_auth/registrations#new'. Is it possible to delete them on Devise ?

**Comment by lynndylanhurley** [comment]
This will require several of the devise mapping methods to be overridden ([starting here](https://github.com/plataformatec/devise/blob/5eb9f187438b1c55337e40dbaea3b5cde0e55e05/lib/devise/rails/routes.rb#L358)).

`devise_for` is a really tricky method, and I try to avoid modifying it whenever I can. But I've been getting several issues a week related to the `new` routes not being used, so I'll probably end up fixing this when I get a chance.

**Comment by nicolas-besnard** [comment]
I tried to play with Devise's route yesterday : I didn't end well :(. I got some issues with the prefix of my routes. Didn't get why.

**Comment by booleanbetrayal** [comment]
@nicolas-besnard - going to close this unless you feel it's still a pressing issue / have a PR for me to look at. can re-open as needed.
