### ISSUE TITLE
Paranoid mode is non existent

### ISSUE THREAD

**Issue by riggy** [lynndylanhurley/devise_token_auth#1100]
While in default configuration here: https://github.com/lynndylanhurley/devise_token_auth/blob/master/config/initializers/devise.rb#L73 it seems that paranoid mode is supported, in fact it isn't at all. I stumbled upon this by accident when I was trying out the password reset api endpoint. It yields different messages depending on whether the email exists in the database or not. With `config.paranoid = true` this behavior isn't changed. I thought it's isolated case, but when I tried to search the repository for `paranoid`, one and only entry was... in that initializer file I mentioned above. Ergo - it's not implemented.

Is this on a roadmap maybe?

 * **Version:** 0.1.42

**Comment by zachfeldman** [comment]
Hey @riggy ! We don't really have a roadmap. But we do accept PRs! Thanks for your help.
