### ISSUE TITLE
Problems with devise version

### ISSUE THREAD

**Issue by luzho** [lynndylanhurley/devise_token_auth#1102]
I'm trying to create an api of my web application, I want to use devise token auth, for managing sessions in the api but I have problems installing it, since there is a dependency problem with the gem devise.

Try to make a downgrade to the gem devise to version 4.3.0 but in this it presents a bug with ruby 2.5.0 that solved in version 4.4.0.

I do not know what to do, I have as a last option to make a separate application with the necessary version of devise, but I would like to exhaust some other alternative first.

* **Version**:  devise_token_auth 0.1.42, Devise version 4.4.1

**Comment by MaicolBen** [comment]
Sorry, we don't have a release yet. You can point to master: `gem 'devise_token_auth', git: 'https://github.com/lynndylanhurley/devise_token_auth'`
