### ISSUE TITLE
LoadError: cannot load such file -- omniauth

### ISSUE THREAD

**Issue by joeczucha** [lynndylanhurley/devise_token_auth#1105]
Clean install:

    devise_token_auth 0.1.42 (also occurs with master branch from Github)
    rails 5.1.5

When running `rails s`:

    Could not load 'omniauth'. Please ensure you have the omniauth gem >= 1.0.0 installed and listed in your Gemfile.
    rake aborted!
    LoadError: cannot load such file -- omniauth
    /Users/joe/Labs/authentication-test/app/models/user.rb:3:in `<class:User>'
    /Users/joe/Labs/authentication-test/app/models/user.rb:1:in `<top (required)>'
    /Users/joe/Labs/authentication-test/config/routes.rb:2:in `block in <top (required)>'
    /Users/joe/Labs/authentication-test/config/routes.rb:1:in `<top (required)>'
    /Users/joe/Labs/authentication-test/config/environment.rb:5:in `<top (required)>'
    /Users/joe/.rbenv/versions/2.4.3/bin/bundle:23:in `load'
    /Users/joe/.rbenv/versions/2.4.3/bin/bundle:23:in `<main>'

Seems that the generated user model includes the following modules: 

    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable

Whereas the default devise generated user model includes the following modules:

    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,

Sure enough, removing `:omniauthable` from this list fixes this for me.

Thanks for your efforts with this gem.

**Comment by zachfeldman** [comment]
@joeczucha glad it was fixed! You're welcome

**Comment by drwhirst** [comment]
ibm_watson-0.20.1

**Comment by PierceF** [comment]
So how do you fix it without removing :omniauthable ?
