### ISSUE TITLE
Omniauthable deleted on UsersConcern : Why ?

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#111]
[see](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L11)

**Comment by lynndylanhurley** [comment]
This gem supports multi user authentication with omniauth, standard devise does not. 

It was easier to exclude the devise module and write a custom version from scratch than it was to monkey-patch the existing module.
