### ISSUE TITLE
uid is blank upon basic rails 5 api setup, user registration 

### ISSUE THREAD

**Issue by colorwheeloflife** [lynndylanhurley/devise_token_auth#1111]
Latest devise_token_auth

Setting up a fresh rails 5 in api-mode

Following along this guide and have hit a snag: https://github.com/dnasseri/rails5-api-guide  (the part where the first curl command is shown)

Trying to perform a very basic user registration under test conditions.  Sending post request from my client and is hitting the correct route. 

Each record is not having a 'uid' field generated.  The first record saves fine because it falls to default as "".  It is required to be unique so two ""'s are a no go. 

Why is this field even needed since it is a user record and the id field is there?  Why clue as to why uid is not being generated? 

Thanks!

**Comment by zachfeldman** [comment]
Kind of inconclusive whether Rails 5 or API are compatible:
https://github.com/lynndylanhurley/devise_token_auth/issues/458

Could you try running the test suite against your setup?

**Comment by colorwheeloflife** [comment]
Wasn't including DeviseTokenAuth::Concerns::User
