### ISSUE TITLE
Tests on token expiry fail when they're run on the WET time zone

### ISSUE THREAD

**Issue by nesteves** [lynndylanhurley/devise_token_auth#1112]
While working on a different issue, I found one of the tests on token expiry (`test/models/user_test.rb`, on the test `'works per user'`) failed for no apparent reason.

What I found was that, although `DeviseTokenAuth.token_lifespan` is set to 2.weeks, the expression `(Time.now + DeviseTokenAuth.token_lifespan).to_i - Time.now.to_i` returns 13 days, 23 hours and 59 minutes. When changing the system's time zone to e.g. EST (the local one is WET), this no longer happens.

The fix is rather simple, one just needs to replace all instances of `Time.now` to `Time.zone.now` or `Time.current`. I'll open the pull request shortly.

**Comment by zachfeldman** [comment]
Good catch! Fix looks good to me.
