### ISSUE TITLE
Automatic Login after successful email confirmation

### ISSUE THREAD

**Issue by rafinkarki** [lynndylanhurley/devise_token_auth#1122]
How to auto login when an email gets confirmed successfully?
It redirects me to login page and i will have to login manually when email is confirmed successfully

**Comment by zachfeldman** [comment]
The library doesn't currently have a built in way to do it. See this issue:
https://github.com/lynndylanhurley/devise_token_auth/issues/1045

**Comment by rafinkarki** [comment]
Thanks but is there any way to do that custom?

**Comment by zachfeldman** [comment]
Sure, there's a way. This is a volunteer-run project though, I don't have time right now to help you with an example but perhaps someone else will.
