### ISSUE TITLE
Add Rubocop

### ISSUE THREAD

**Issue by MaicolBen** [lynndylanhurley/devise_token_auth#1124]
This will improve remarkably the quality of the repo, but currently, there are 2563 issues on rubocop, so it will take a while, this can be done by parts (folders or whatever group of files).

**Comment by zachfeldman** [comment]
That would be a great enhancement

**Comment by lynndylanhurley** [comment]
Agreed - this will be a huge help.

**Comment by Evan-M** [comment]
While it seems daunting, the top offenses are:
```
1487  Style/StringLiterals
329   Metrics/LineLength
130   Style/FrozenStringLiteralComment
127   Style/HashSyntax
94    Metrics/BlockLength
```

and the worst offenders are:
```
1038  test/dummy/app/helpers/application_helper.rb
325   test/dummy/db/schema.rb
85    app/models/devise_token_auth/concerns/user.rb
73    lib/devise_token_auth/rails/routes.rb
69    lib/generators/devise_token_auth/install_generator.rb
```

So simply ignoring the code in the `test/dummy` Rails app cuts the offenses down to under 1000!

**Comment by MaicolBen** [comment]
There is a plugin in atom that fixes automatically by file, I don't know if it can be done in the command line. The only downside of this is that all the PRs will have conflicts, but this should be done sometime.

**Comment by Evan-M** [comment]
There is definitely a builtin `--autocorrect` option, that can even be enabled for specific cops only
https://rubocop.readthedocs.io/en/latest/configuration/#autocorrect

**Comment by dks17** [comment]
Consider also `guard-rubocop` [gem](https://github.com/yujinakayama/guard-rubocop).
```ruby
gem 'rubocop', require: false
gem 'guard-rubocop'
```

**Comment by dks17** [comment]
@MaicolBen Hello. We added many changes to realize this enhancement. We didn't cover it totally, but most. I think future work should be carried on as usual for pull requests.
Should the issue be closed?

**Comment by MaicolBen** [comment]
agreed
