### ISSUE TITLE
Password/Edit route not working

### ISSUE THREAD

**Issue by amillette** [lynndylanhurley/devise_token_auth#1127]
I have recently setup the mailer to send email on forgot password. But when I click on the link received in the email, I always get the Not Found error.

Completed 404 Not Found in 3ms (ActiveRecord: 0.5ms)
ActionController::RoutingError (Not Found):
devise_token_auth (0.1.42) app/controllers/devise_token_auth/passwords_controller.rb:183:in `render_edit_error'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/passwords_controller.rb:106:in `edit'

**Comment by NOOBFREEAKER** [comment]
What was the issue?

**Comment by amillette** [comment]
I don't remember the exact issue, but it was something that I did wrong in the config/initializers/devise.rb
