### ISSUE TITLE
ensure_pristine_resource error

### ISSUE THREAD

**Issue by hansy** [lynndylanhurley/devise_token_auth#1135]
v0.1.43

I'm having issues with the `ensure_pristine_resource` method in the lib's `app > controllers > devise_token_auth > concerns > set_user_by_token.rb`. Namely line 33:

```
@resource.assign_attributes(changes) if changes
```

I think I see what you're doing here, but `assign_attributes` is creating erroneous behavior when applying the hashed changes. For example:

```
irb(main)> u = User.first
=> #<User id: 1, name: "">
irb(main)> u.name = "John"
=> "John"
irb(main)> changes = u.changes
=> {"name"=>["", "John"]}
irb(main)> u.assign_attributes(changes)
=> nil
irb(main)> u
=> #<User id: 1, name: "[\"\", \"John\"]">
```

When using certain libraries, like Carrierwave, the application breaks at that line because I guess the parsing is off. I haven't done extensive testing, but doing something like this seems to at least parse the `changes` hash correctly:

```
changes.each { |attr, val| @resource[attr] = val[1] } if changes
```

Thoughts?

**Comment by Evan-M** [comment]
This looks like a bug...

https://github.com/lynndylanhurley/devise_token_auth/blob/7df89606ef127961c1957aaccf714ff322ebf431/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L24-L34

The hash returned by `#changes` on line 27 includes _both_ the old _and_ new values, i.e. 
`attr => [original value, new value]`.  (See: [API Docs for `ActiveModel::Dirty#changes`])

Of course the `ActiveModel::AttributeAssignment#assign_attributes` method expects a hash with just the _new_ values, i.e. `attr => new_value`.

No need to re-invent the wheel here though... Use the [`Hash#transform_values`] method (from [`ActiveSupport::CoreExt`][`Active Support Core Extensions - Working with Values`]) to transform the hash with both the existing and pending values into a hash with just the pending values:
~~~ruby
# Stash pending changes in the resource before reloading. 
pending_changes = @resource.changes.transform_values(&:last)
~~~

[API Docs for `ActiveModel::Dirty#changes`]: http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changes
[`Hash#transform_values`]: http://api.rubyonrails.org/classes/Hash.html#method-i-transform_values
[`Active Support Core Extensions - Working with Values`]: http://guides.rubyonrails.org/active_support_core_extensions.html#working-with-values

**Comment by hansy** [comment]
@Evan-M's suggestion is clean and seems to work. Can this issue officially be filed as a bug?
