### ISSUE TITLE
How solve undefined method `allow_password_change' while changing user password ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [lynndylanhurley/devise_token_auth#1136]
devise_token_auth version (0.1.43)

I used PUT with /user/auth/password

Then I sent this in the body 

    {
	    "password": "password11",
	    "password_confirmation": "password11"
    }

and in the header I sent:

    [
            {"key":"Content-Type","value":"application/json"},
            {"key":"token-type","value":"Beare"},
            {"key":"expiry","value":"33079916336"},
            {"key":"client","value":"slfjseeowifomewflqwed"},
            {"key":"access-token","value":"sdflkgnmowjfwem"},
            {"key":"uid","value":"my-email123@gmail.com"}
    ]

Then I got this in the stack:

     NoMethodError (undefined method `allow_password_change' for #<User:0x00007fda8d440880>):

What should I do ?

**Comment by Evan-M** [comment]
@Mohammed-Eliass: this may be related to [This comment](lynndylanhurley/devise_token_auth/pull/863#issuecomment-354855068) regarding PR #863.

Could you please check your `schema.rb` and confirm that your `users` table has a column called `:allow_password_change`?  The column _should_ be a `:boolean` and default to `false`:
~~~ruby
# ...

create_table 'users' do |t|
  # ...
  t.boolean  :allow_password_change, default: false, null: false
  # ...
end

# ...
~~~

If not, then try generating a new migration to add the column.

**Comment by Mohammed-Eliass** [comment]
Worked like magic, Thank mate!

**Comment by jaypitti** [comment]
So im getting the same issue but even when i remigrate it doesnt appear.. help lol

**Comment by Mohammed-Eliass** [comment]
@jaypitti it didn't appear when I used it with api mode, so I generated a migration and it's working!

        class AddAllowPasswordChangeToUsers < ActiveRecord::Migration[5.1]
          def change
              add_column :users, : allow_password_change, :boolean, default: false, null: false
          end
        end

**Comment by AteqEjaz** [comment]
Giving me  following error after adding Above column 

**ArgumentError at /api/v1/auth/password/edit
bad argument (expected URI object or URI string)**

**Comment by giapnhdev** [comment]
Override `resource_update_method` is a solution

    def resource_update_method
      allow_password_change = recoverable_enabled? && @resource.allow_password_change == true || require_client_password_reset_token?
      if params[:current_password].nil? && (DeviseTokenAuth.check_current_password_before_update == false || allow_password_change)
        'update'
      else
        'update_with_password'
      end
    end
