### ISSUE TITLE
devise_token_auth for public API, but devise for rest of app?

### ISSUE THREAD

**Issue by jdgblinq** [lynndylanhurley/devise_token_auth#114]
Hello,

We have a rails application with a public JSON API. The same application also has an administrative interface that does not rely on the public JSON API; it's just vanilla Rails. Our AngularJS frontend is a separate application on a separate host. We don't use AngularJS in our Rails app.

In your examples, it seems like everything uses ng-token-auth. Is it possible to use devise_token_auth without ng-token-auth? In other words, can we use devise_token_auth with vanilla Rails forms?

Alternatively, is it possible to limit devise_token_auth to certain routes and use regular devise for the remaining routes?

Thanks,

-- 
Jesse

**Comment by nicolas-besnard** [comment]
Hello :)

If you want to use this gem without `ng-token-token`, you just have to add the required headers to your request.

I think you can use `devise_token_auth` for some route and `Devise` for the other part, I havent't test it yet. You should look at the documentation [here](mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks])

**Comment by lynndylanhurley** [comment]
> Is it possible to use devise_token_auth without ng-token-auth? In other words, can we use devise_token_auth with vanilla Rails forms?

Yes it is possible, but the client application will need to implement the functionality of ng-token-auth.

This includes:

* Token management (validation, expiration, persistence, etc.)
* OAuth success/failure handling
* Registration success/failure handling
* Password reset submission / confirmation
* Multiple user type support introduces additional problems

> Alternatively, is it possible to limit devise_token_auth to certain routes and use regular devise for the remaining routes?

The best way to accomplish this will be to mount the standard devise routes to one path, and to route the devise_token_auth routes to a separate path. Something like this:

~~~ruby
Rails.application.routes.draw do

  # standard devise routes available at /users
  devise_for :users

  # token auth routes available at /api/v1/auth
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

end
~~~

**Comment by jdgblinq** [comment]
This works quite well. Thank you.

**Comment by lynndylanhurley** [comment]
:metal:

**Comment by dyaa** [comment]
:metal: :v:

**Comment by Jefferson210** [comment]
Hi @jdgblinq, What is the configuration of the controllers?

I perform the configuration as indicated @lynndylanhurley in the routes but it still does not work.

thanks for your help.
