### ISSUE TITLE
Password Reset Links Invalidated After Being Clicked

### ISSUE THREAD

**Issue by typhoon2099** [lynndylanhurley/devise_token_auth#1141]
When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**: 0.1.43 with [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth)?

We seem to have a situation where users are following the password reset link that is emailed to them multiple times, or an add on is scanning the URL to resolve it (anti-virus or something), the end result of which is a link that cannot be sued to reset their passwords, they are instead met with a 404.

As best as I can figure out, once the link is clicked then the reset token is removed from the database. My expectation would be that the token is left in place until the password has been successfully reset, allowing the user to open (accidentally or otherwise) the link multiple times without the link expiring.

I haven't looked into this yet either but it would also be useful if, once a link had expired, a user could be shown a message explaining this, instead of an empty 404 page. We get quite a few support requests due to user not understanding what is going on with the password reset flow.

**Comment by newfylox** [comment]
Agreed with adding a new exception that we can catch or other error then 404.

**Comment by MaicolBen** [comment]
Agreed, what do you suggest? A simple view that could be overridden? Because the gem doesn't have any styles

**Comment by typhoon2099** [comment]
I think having a way to set a URL to redirect the user to would be useful. That way we could redirect them to the login page and then display an error message explaining what has happened.

**Comment by jamsi** [comment]
@colmben thanks for sharing. However it still doesn't solve the issue of anti-virus or other addons that are checking links, therefore invalidating the request (one of our clients experienced this recently). Does anyone know if we're able to ensure a reset password link can be clicked multiple times - and is then only invalidated ONCE successful completion of the reset password process. 

Of course, having a short "window" for the "config.reset_password_within" option is going to help with security.

**Comment by typhoon2099** [comment]
Pull request #1206 should have resolved this issue.

**Comment by jamsi** [comment]
After a little more digging (for some reason I had to re-run rails generate devise:install as my devise.rb was a little clunky) - it appears to work now. Thanks for your help.

**Comment by typhoon2099** [comment]
No worries, I hadn't actually realised that my pull request had made it into 1.0.0.

@MaicolBen Can this issue be closed now?

**Comment by jamsi** [comment]
I really need more coffee. No it didn't make it to 1.0.0, apologies. Missed out by 1 day it seems :D

**Comment by mcelicalderon** [comment]
I added a comment in https://github.com/lynndylanhurley/devise_token_auth/pull/1206

Looks like behavior is is a bit different from what it should.
