### ISSUE TITLE
How to override concern

### ISSUE THREAD

**Issue by MaratovichDan** [lynndylanhurley/devise_token_auth#1145]
I want override concern `resource_finder.rb` which include method ```provider```

**Comment by Marinlemaignan** [comment]
yep just override `provider` method from your application_controller, or any child controllers if you need more granularity..
something like:
```
def provider
    if request_for_cool_stuff?
      'cool_stuff_bro'
    else
      super
    end
  end
```

**Comment by MaicolBen** [comment]
thanks @Marinlemaignan
