### ISSUE TITLE
How could send the access-token and other credentials ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [lynndylanhurley/devise_token_auth#1146]
version 0.1.43

I overrode the registrations class of devise_token_auth gem, then I changed the create method (sign_up) to do different logic like (send sms verification code with Twilio gem after the sign_up)!

How could I send the same user header that being sent with devise_toke_auth default header after sign_up or sign_in ?

**Comment by MaicolBen** [comment]
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/devise-token-auth) for questions, the headers are sent in [update_auth_header](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L7)

**Comment by MaicolBen** [comment]
Sorry for the delay, you have to set `@resource` with the customer

**Comment by Mohammed-Eliass** [comment]
Could you please, put some example ?

**Comment by MaicolBen** [comment]
you do in the create method: `@resource = customer`, `update_auth_header` looks up for that variable

**Comment by Mohammed-Eliass** [comment]
@MaicolBen Thank you so much, but bear with me and please try to help me here!

My problem is how to return the default headers with this line: 
   `render json: {message: 'A verification code has been sent to your mobile.'}, status: :created`

     def create
       if Customer.where(mobile_phone_number: params[:mobile_phone_number]).exists?
          render json: {message: 'Mobile phone number already existed!'}, status: :unprocessable_entity
       elsif Customer.where(email: params[:email]).exists?
          render json: {message: 'Email already existed!'}, status: :unprocessable_entity
       else
          customer = Customer.new() #some_logic
          if customer.save
            customer.generate_verification_code
            render json: {message: 'A verification code has been sent to your mobile. Please fill it in below.'}, status: :created ######### I should return the headers here
          else
            render json: customer.errors
          end
        end
      end


So could you please tell me how to do it!

**Comment by MaicolBen** [comment]
As I said, assign `@resource = customer` just before that `render json: {message: 'A verifica ....`. And of course keep `after_action :update_auth_header, only: [:create]`

**Comment by Mohammed-Eliass** [comment]
I swear to God, I tried this nothing happened, same result!

    after_action :update_auth_header, only: [:create]

    def create
       if Customer.where(mobile_phone_number: params[:mobile_phone_number]).exists?
          render json: {message: 'Mobile phone number already existed!'}, status: :unprocessable_entity
       elsif Customer.where(email: params[:email]).exists?
          render json: {message: 'Email already existed!'}, status: :unprocessable_entity
       else
          customer = Customer.new() #some_logic
          if customer.save
            customer.generate_verification_code
            @resource = customer
            render json: {message: 'A verification code has been sent to your mobile. Please fill it in below.'}, status: :created
          else
            render json: customer.errors
          end
        end
      end

**Comment by MaicolBen** [comment]
No need to swear haha, we have to dig why `update_auth_header` isn't returning the headers, do you have `change_headers_on_each_request` enabled? is `customer.valid?` true?

**Comment by Mohammed-Eliass** [comment]
:), I'm losing my mind with this issue!

     config.change_headers_on_each_request = false
and the customer is saved to the DB, and I get from postman the message: "A verification code has  ..."!

**Comment by MaicolBen** [comment]
you are kind of emulating what the registrations controller is doing, you need to call `@client_id, @token = @resource.create_token` as well, I know it's kind of weird but `update_auth_header` needs `@client_id`.

**Comment by Mohammed-Eliass** [comment]
I wrote as the following:
      @resource = user
      @client_id, @token = @resource.create_token
      render json: {message: 'A verification code ... '}, status: :created

got the json message: "A verification code ....", but nothing happened with the headers! ;(

**Comment by Mohammed-Eliass** [comment]
The headers:

    Cache-Control →max-age=0, private, must-revalidate
    Content-Type →application/json; charset=utf-8
    ETag →W/"f2dfd6a8a5dd9b173cf92d27a31b83cd"
    Set-Cookie →_app_session=a/long string/5403ff1; path=/; HttpOnly Transfer-Encoding →chunked
    X-Content-Type-Options →nosniff
    X-Frame-Options →SAMEORIGIN
    X-Request-Id →32875e44-e393-4dd2-9f68-5aa2e6e8856e
    X-Runtime →0.765757
    X-XSS-Protection →1; mode=block

**Comment by MaicolBen** [comment]
You will have to debug `update_auth_header`, you can do it with:
```ruby
def update_auth_header
  binding.pry # or any debugger you have
  super
end
```
Reading the code seems you need to have `@used_auth_by_token ` set but I don't what is the purpose.

You are registrating a customer, so follow the [registrations controller](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/registrations_controller.rb) code

**Comment by Mohammed-Eliass** [comment]
Thanks man, I'll do my best to solve this!
And I'm so sorry if I wasted your valuable time!

**Comment by Mohammed-Eliass** [comment]
@MaicolBen 
I quit this stupid way I'm so tired from this bullsh*t, so do you know any way to get custom behavior after the resource saves!
Any examples or code snippets ? I appreciate it man!

**Comment by MaicolBen** [comment]
As I said take a look at the registrations controller, you are registrating a new user, so you have to follow that logic

**Comment by MaicolBen** [comment]
To send manually the headers, you can do:
```ruby
@client_id, @token = customer.create_token
auth_header = customer.build_auth_header(@token, @client_id)
response.headers.merge!(auth_header)
```
