### ISSUE TITLE
cant sigh_in on my custom controller

### ISSUE THREAD

**Issue by chubbyzz** [lynndylanhurley/devise_token_auth#1150]
i would sigh_in after my custom register method
i'm trying somethink like this
> sigh_in(@user, scope: :user)
but there is no authenticated user after this

Rails 4.2.5.1
devise_token_auth 0.1.42

**Comment by MaicolBen** [comment]
Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/devise-token-auth) for questions, you might have a problem with one of the devise modules, e.g.: the user isn't confirmed
