### ISSUE TITLE
Getting undefined method `make_response!` for overridden Devise controller class

### ISSUE THREAD

**Issue by terenceponce** [lynndylanhurley/devise_token_auth#1158]
When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**: 0.1.43
* **Rails Stacktrace**:

```
Error:
Api::Devise::RegistrationsController#test_user_creation_with_valid_input_succeeds:
NoMethodError: undefined method `make_response!' for Api::Devise::RegistrationsController:Class
    test/controllers/api/devise/registrations_controller_test.rb:12:in `block in <class:RegistrationsController>'
```

* **Environmental Info**:
  * **Routes**:

  ```
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/devise/registrations'
  }
  ```

  * **Gems**: Just a fresh Rails app in API mode (`--api`)
  * **Custom Overrides**: I tried overriding the Registrations controller but haven't really done anything different yet:

  ```
  module Api
    module Devise
      class RegistrationsController < DeviseTokenAuth::RegistrationsController
        include DeviseTokenAuth::Concerns::SetUserByToken

        def create
          super
        end
      end
    end
  end
  ```

  * **Custom Frontend**: No frontend yet.

I made a fresh Rails app and tried using this gem. I was hoping to override the controllers so I can use this gem with [Versionist](https://github.com/bploetz/versionist) and [apipie-rails](https://github.com/Apipie/apipie-rails). Here's a test that I made just to make sure that the gem works as expected out of the box:

```ruby
require 'test_helper'

class Api::Devise::RegistrationsController < ActionDispatch::IntegrationTest
  test "user creation with valid input succeeds" do
    user_params = {
      email: 'test@example.com',
      password: 'securepassword',
      password_confirmation: 'securepassword',
      confirm_success_url: 'http://localhost:3000'
    }

    post user_registration_url, params: user_params
    body = JSON.parse(response.body)
    assert_response :success
  end
end
```

This test works if I just use the default route that devise_token_auth comes with. However, if I try to use my override controller instead, it produces this error:

```
Error:
Api::Devise::RegistrationsController#test_user_creation_with_valid_input_succeeds:
NoMethodError: undefined method `make_response!' for Api::Devise::RegistrationsController:Class
    test/controllers/api/devise/registrations_controller_test.rb:12:in `block in <class:RegistrationsController>'
```

I tried searching everywhere for the solution, but I found nothing so I'm hoping someone can help me out on this.

**Comment by MaicolBen** [comment]
is that your code? we don't have any `make_response` in the code

**Comment by terenceponce** [comment]
No. It's just a fresh Rails 5.2 app. I certainly haven't written any code aside from the things needed to integrate devise_token_auth and override one of the controllers.

**Comment by MaicolBen** [comment]
The registrations controller could be inheriting from the wrong controller, also, `Api::Devise::RegistrationsController` in the test should be `Api::Devise::RegistrationsControllerTest` or something like that. Otherwise you are putting a test in the real class.

**Comment by dlt** [comment]
@terenceponce this happened because you're trying to open the `Devise::RegistrationsController` class to override it, but instead is creating a new class `Api::Devise::RegistrationsController`.

One way to solve your problem would be to create an initializer and put the following in it:

```ruby
Devise::RegistrationsController.class_eval do
  include DeviseTokenAuth::Concerns::SetUserByToken
  def create
    super
  end
end
```

**Comment by iarobinson** [comment]
I had this error and when my code was like this:

```
class Organizations::PaymentMethodsController
  # include HandlesOrganizationUrls
  def index
  end
end
```
... then I made it like this and it worked:
```
class Organizations::PaymentMethodsController < ApplicationController
  # include HandlesOrganizationUrls
  def index
  end
end
```

**Comment by juliofalbo** [comment]
I know that it is old, but you can just make a little workaround to trigger the autoloading.

`stub_const("#{Model}::CONST", 2)` as suggested here: https://github.com/rspec/rspec-mocks/issues/1079#issuecomment-215620243
