### ISSUE TITLE
bad argument (expected URI object or URI string)

### ISSUE THREAD

**Issue by raviada** [lynndylanhurley/devise_token_auth#116]
When the user is registered, I got an email about account confirmation. When I click on the link, I am getting this error. what am I doing wrong?

```bad argument (expected URI object or URI string)```

see the attached pic.

![2015-01-15_0623](https://cloud.githubusercontent.com/assets/819292/5757344/a6a28106-9c7f-11e4-9413-e491519a9d04.png)

**Comment by raviada** [comment]
even though I set this in ```application_controller.rb```
```protect_from_forgery with: :null_session```
I am still getting the following warnings when I register an account.
```
Can't verify CSRF token authenticity
Unpermitted parameters: confirm_success_url, config_name, registration
Unpermitted parameters: confirm_success_url, config_name, registration
```

is that the reason why I see the above error because ```Unpermitted parameters: confirm_success_url, config_name, registration```?

**Comment by lynndylanhurley** [comment]
@raviada - you can ignore the `Unpermitted parameters` messages. They are not harmful, and they are expected.

Which versions of this gem and the angular module are you using?

**Comment by raviada** [comment]
ok, thanks. I am using the following versions
```
"ng-token-auth": "~0.0.24"
gem 'devise_token_auth', :git => 'https://github.com/lynndylanhurley/devise_token_auth.git'
```

**Comment by sdornan** [comment]
I think it's because it's trying to build a url using ```params[:redirect_url]``` and it doesn't exist.

**Comment by kalabiyau** [comment]
@raviada if you had custom email template - look at the right one from DTA

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/views/devise/mailer/confirmation_instructions.html.erb

it includes proper parameters

**Comment by ACPK** [comment]
@sdornan I'm trying to use the "reset password" functionality and am having problems with the redirect_url. Do you know why the allow this param?

**Comment by aksswami** [comment]
+1

**Comment by booleanbetrayal** [comment]
Closing this since it appears to be due to misconfiguration of a custom mailer. Can re-open as needed.
