### ISSUE TITLE
If the user is invalid, it doesn't return the tokens in sign in

### ISSUE THREAD

**Issue by AmitJoki** [lynndylanhurley/devise_token_auth#1160]
**Version**: 0.1.43 and redux-token-auth.

I am trying out this gem and while trying out sign_in, I am getting 200 OK result with the user model being responded with in JSON too, but the access-token and client and other such headers are being left out.

What this does in my [Redux-Token-Auth](https://github.com/kylecorbelli/redux-token-auth) is that, they're being saved as `undefined` and therefore there's no persistence at all. Because the verfying token url is thus:
```
http://localhost:3001/auth/validate_token?access-token=undefined&client=undefined&uid=undefined
```

This is a bummer considering this is what the gem is all about.

**Comment by MaicolBen** [comment]
Are you sure? I just checked 0.1.43, and it returns the headers, can you post the entire request here? You can use the network tab in the Chrome developer tools

**Comment by AmitJoki** [comment]
Yes. Wait a second.

**Comment by AmitJoki** [comment]
**Url:** /auth/sign_in

**Request Headers:**
```
POST /auth/sign_in HTTP/1.1
Host: localhost:3001
Connection: keep-alive
Content-Length: 54
Accept: application/json, text/plain, */*
Origin: http://localhost:5000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Content-Type: application/json;charset=UTF-8
DNT: 1
Referer: http://localhost:5000/login?msg=true
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ta;q=0.8
```
**Response Headers**
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://localhost:5000
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS, HEAD
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 1728000
Content-Type: application/json; charset=utf-8
ETag: W/"003642d98f15350444bc4cc82616f380"
Cache-Control: max-age=0, private, must-revalidate
X-Meta-Request-Version: 0.6.0
X-Request-Id: 046a4077-ac04-41bc-8c91-522ce362350a
X-Runtime: 3.117000
Vary: Origin
Transfer-Encoding: chunked
```

Response is the correct user data which I am getting back, no problem there.

**Comment by MaicolBen** [comment]
You aren't posting the request and response bodies, but you have `Content-Type: application/json` which its absence makes the gem not replying with the token headers

**Comment by AmitJoki** [comment]
@MaicolBen request payload is `{email, password}` and I am getting response as the correct user data in the format `{data: {...user_object} }`

**Comment by MaicolBen** [comment]
If you don't send "Content-Type: application/json", the gem won't return the auth headers, but that isn't your case. Also, asking for the body was silly, sorry, because we can't post sensitive information.

Can you check if the user is valid? Do `user.valid?`

**Comment by AmitJoki** [comment]
I don't think that's the problem. If the user is invalid, he wouldn't even be saved in the database. I am getting back the user fine and I am getting the user whose credentials I've given. So, the initial request is fine. I send the email and password and I get the corresponding user's data without a hitch. Just that since the access token isn't being returned, there's no way to verify the token.

I have a feeling my issue and #1159 are similar.

**Comment by MaicolBen** [comment]
It isn't the same because #1159 is a batch request, and if the user is invalid, it will still return 200 and the user. I'm asking that because I realized about it just now.

**Comment by AmitJoki** [comment]
Let me check in the rails console and get back to you.

**Comment by AmitJoki** [comment]
@MaicolBen strangely it IS returning `false` though `user.errors.full_messages` is empty. Any idea why?

**Comment by MaicolBen** [comment]
Yes, but the gem shouldn't return the user if it's invalid, so keep it open

**Comment by shailjasingh** [comment]
Yes , I was also stuck in the same issue, If user is invalid then it should not be allow to signin, instead of missing access token cllent id.
