### ISSUE TITLE
How to add another parameter to validate a user?

### ISSUE THREAD

**Issue by newfylox** [lynndylanhurley/devise_token_auth#1162]
Hi guys,

I'm looking for a simple solution to add another parameter with `email` to register a user or find a user. Right now `find_resource` is only using `email` but I would like to do something like this
```ruby
where(email: my_email, my_param: my_other_param)
```
so it would be a `where` clause on `email` AND `my_param` for every calls (register, login, logout, etc.)

Or a better solution would be to override that line
```ruby
validates :email, uniqueness: { scope: :provider }, on: :create, if: :email_provider?
```
to make sure it's uniqueness with **provider** AND **my_other_param**.

I was thinking about relying on another column instead of `email` like `username` (so I would concatenate `email` and `my_other_param` as a `username` but it seems it does that validation before using my `username`. Am I wrong?

I don't want to override all the controllers or copy a whole file from your gem because I want to be sure that every time I update your gem, I stay up to date.

Thanks!

**Comment by MaicolBen** [comment]
Well, you can return false in `email_provider?`, and do your own validation. This isn't a login with [multiple fields](https://github.com/lynndylanhurley/devise_token_auth/pull/1128), it's more a special case, and this gem is already overloaded with special cases. 

Let me know if I can help you in another way.

**Comment by MaicolBen** [comment]
@newfylox Sorry for the delay, you can override `find_resource` entirely. I don't see another easy way to do it
