### ISSUE TITLE
Multiples Profiles Relationship 

### ISSUE THREAD

**Issue by betosalvador** [lynndylanhurley/devise_token_auth#1168]
Hello everyone

I'm working on a system where the user can be a Employer, Employee or a Operator.

Each theese roles must have a model class, where I will implement specific behaviors.

All theese classes must have a login user.

So, I think that this solution could work:

```
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable
  include DeviseTokenAuth::Concerns::User

  belongs_to :profile, polymorphic: true
end


class Employer < ApplicationRecord
  has_one :user, as: :profile, dependent: :destroy
end


class Employee < ApplicationRecord
  has_one :user, as: :profile, dependent: :destroy
end


class Operator < ApplicationRecord
  has_one :user, as: :profile, dependent: :destroy
end
```

I want to create specifics registrations controllers, for each profile (EmployerController, EmployeeController, OperatorController), because each registration may have different behaviors.

And I want to use the default SigiIn controller for all profiles.

How to configure the routes for this?

Thanks in advance

**Comment by MaicolBen** [comment]
@betosalvador Check https://github.com/lynndylanhurley/devise_token_auth/blob/master/docs/usage/routes.md. You have to add the next code for each model:
```ruby
 mount_devise_token_auth_for 'Employee', at: '/api/v1/employees', controllers: {
    registrations:  'api/v1/employees/registrations',
    sessions:  'api/v1/sessions',
}
```
As you can see in the example, it's for `Employee`, I suggest to use a folder for each resource, and the sessions controller isn't in any specific resource folder.

**Comment by betosalvador** [comment]
Hello @MaicolBen, thanks for response.

My model Employee don't is a Devise model.

I have just one Devise model: "User".

Do you think that solve my case?

hugs

**Comment by betosalvador** [comment]
@MaicolBen , just more one question:

I have namespaces configured in my routes, like:

```
  namespace :api, path: '/' do
    namespace :v1, path: '/', constraints: ApiVersionConstraint.new(version: 1, default: true) do
    end
  end
```
Do you think better call mount_devise_token_auth_for method inside or outside namespaces?

thanks in advance

**Comment by betosalvador** [comment]
I made the suggested test, but the only route generated was 

**/api/v1/employees/validate_token**

could you please open my issue again?

thanks again

**Comment by betosalvador** [comment]
@MaicolBen 

please, reopen my issue
thanks

**Comment by MaicolBen** [comment]
Reopening, but it seems more a question than an issue. I need time to setup your problem locally and try a different solution.

**Comment by MaicolBen** [comment]
Yes, that's what I said, a controller for each model like `Employees::RegistrationsControler`, `Operators::RegistrationsControler` and so on
