### ISSUE TITLE
Skip email confirmation

### ISSUE THREAD

**Issue by daniele-cappuccio** [lynndylanhurley/devise_token_auth#1170]
This is a question, not an issue. Is there an easy way to skip email confirmation when new users sign up?

**Comment by dks17** [comment]
Hi. I think there are two ways:
1. Don't use `confirmable` module in your user model
```ruby
devise :registerable #,:confirmable
```
2. Or use `skip_confirmation!` on your user object:
```ruby
user = User.new(email: my@mail.com)
user.skip_confirmation!
user.save
```

**Comment by daniele-cappuccio** [comment]
The first solution worked fine! Thanks!
