### ISSUE TITLE
How to implement 2FA?

### ISSUE THREAD

**Issue by fameoflight** [lynndylanhurley/devise_token_auth#1171]
Any ideas how can I implement 2FA with devise token auth?

**Comment by MaicolBen** [comment]
@fameoflight Have you checked [devise-two-factor](https://github.com/tinfoil/devise-two-factor) ?

**Comment by fameoflight** [comment]
@MaicolBen do you have any examples?

**Comment by fameoflight** [comment]
I feel like 2fa and this are incompatible.

**Comment by fameoflight** [comment]
For someone else looking for a solution. I modified is_valid_password? on User, model to parse the string as JSON and then getting password and OTP token separately.

**Comment by MaicolBen** [comment]
@fameoflight Sorry I don't have experience with 2fa, thank you for posting your findings!

**Comment by bettysteger** [comment]
@fameoflight can you share an example, how you did it? were you using https://github.com/tinfoil/devise-two-factor ?

**Comment by bettysteger** [comment]
If anyone needs this, i created a [gist](https://gist.github.com/bettysteger/670a9a3ef0814ff52059dc2e6757e580) if you want to use [devise-two-factor](https://github.com/tinfoil/devise-two-factor)
