### ISSUE TITLE
Devise Token Auth Postman configuration

### ISSUE THREAD

**Issue by Jefferson210** [lynndylanhurley/devise_token_auth#1173]
Hi, I'm starting with the use of this gem. I have followed the steps to install it from the official documentation but I can not make it work.

I make requests through POSTMAN but it always returns the message. "What I try is to log in with the user that I manually insert with the rails console.
{"errors": ["You need to sign in or sign up before continuing."]} ".
![captura de pantalla de 2018-05-20 22-53-11](https://user-images.githubusercontent.com/12091256/40289898-46e954e2-5cbb-11e8-8931-1ffe84868461.png)
![captura de pantalla de 2018-05-20 22-53-38](https://user-images.githubusercontent.com/12091256/40289913-583e8604-5cbb-11e8-9058-ceea2820a551.png)
this is my controller aplication:
![captura de pantalla de 2018-05-20 22-55-22](https://user-images.githubusercontent.com/12091256/40289952-9c0c14d2-5cbb-11e8-90d5-0841f2b7b08c.png)
I'm missing some configuration?

thanks for your help

**Comment by gegianno** [comment]
Try sending the JSON as this:
```
{  
  "email": "admin@example.com",  
  "password": "password123"  
}
```
