### ISSUE TITLE
401s after response with new headers fail

### ISSUE THREAD

**Issue by gegianno** [lynndylanhurley/devise_token_auth#1174]
I'm using this gem for authentication with `change_headers_on_each_request = true`, so whenever the frontend receives a response it updates the tokens from the headers. This is working fine with `batch_request_buffer_throttle = 30.seconds`.

My question is: when the 30 seconds have passed, what should the frontend do if the first request (the one which should respond with the header carrying the new auth tokens) fails?

I'm currently experiencing log outs when the frontend rejects a response, because of timeout on slow networks or server delays. I have tested several versions of this gem but I'm am having this issue on all of them.

I think this should be managed server-side. What would be the correct approach here?
  
  
* **Version**: 0.1.43
* **Custom frontend**

**Comment by iur-kaia** [comment]
@gegianno I have the same issue caused by a slow network. Did you find a solution?

**Comment by gegianno** [comment]
I finally set `change_headers_on_each_request  = false` and went with a frontend approach. I still think this should be managed server-side, but for my particular situation handling it on the frontend was good enough.

**Comment by MaicolBen** [comment]
you can use [token validation](https://devise-token-auth.gitbook.io/devise-token-auth/usage/overrides) to refresh it
