### ISSUE TITLE
Remove Password Validation

### ISSUE THREAD

**Issue by xishoon** [lynndylanhurley/devise_token_auth#1177]
How to remove password validations using devise auth token?

**Comment by dks17** [comment]
Try to disable `:validatable` module or [change password length](https://github.com/plataformatec/devise/wiki/Customize-minimum-password-length).
```ruby
  devise :rememberable, #:validatable
```

**Comment by dks17** [comment]
@xishoon Hello. Please close the issue if you solved it.
