### ISSUE TITLE
Could not load 'omniauth'

### ISSUE THREAD

**Issue by ricardodovalle** [lynndylanhurley/devise_token_auth#118]
I am using the basic gem installation, but I am getting this error in `rake db:migrate`

    Could not load 'omniauth'. Please ensure you have the omniauth gem >= 1.0.0 installed and listed in your Gemfile. rake aborted!`

I am not using omniauth.

Versions:
`gem 'rails', 4.2.0'`
`gem 'devise_token_auth', '~> 0.1.30'`

Thanks

**Comment by AntonFilipko** [comment]
Also have this issue, even with applying this changes https://github.com/lynndylanhurley/devise_token_auth#example-disable-oauth-authentication

**Comment by lorenjohnson** [comment]
Same issue, recommend config doesn't fix this but adding omniauth to my Gemfile does make things go again. Looking at the code I don't see a way to override this currently due to the devise call in DeviseTokenAuth::Concerns::User including omniauth...

**Comment by AntonFilipko** [comment]
yep, also finally I've decied to stay with omniauth in Gemfile

**Comment by lynndylanhurley** [comment]
Thanks @ricardodovalle - I'll look into this ASAP.

**Comment by ricardodovalle** [comment]
Thanks to you @lynndylanhurley, It is a great gem! :+1:

**Comment by lynndylanhurley** [comment]
:metal:

**Comment by lepek** [comment]
Same issue here, I don't want to add the omniauth dependency to my app....

**Comment by robypez** [comment]
Same for me. 

I load 
```
include DeviseTokenAuth::Concerns::User 
```
after 

```
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, :validatable
```

and I add

```
namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
      resources :contents, only: [:index, :show] do
        get :hottest, on: :collection
      end
    end
  end
```

But on rake routes

```
oadError: cannot load such file -- omniauth
```

**Comment by booleanbetrayal** [comment]
This should no longer be happening as of 0.0.32. Can re-open as needed.

**Comment by ryankc33** [comment]
@booleanbetrayal Using 0.1.34, still getting this error

**Comment by audreyschwarz** [comment]
Still happening on 0.1.36. If this isn't going to be fixed, can omniauth at least be added as an explicit dependency?

**Comment by lynndylanhurley** [comment]
Thx, I'll take a look ASAP.

**Comment by alienspaces** [comment]
@lynndylanhurley just wondering if there is any movement on this? Thanks for all your hard work!

**Comment by montdidier** [comment]
Still happening devise_token_auth 0.1.39

**Comment by hakunin** [comment]
Just installed it, same issue.

**Comment by johnsaltarelli** [comment]
Same issue here. using 0.1.40.

**Comment by calebearruda** [comment]
Still happening in devise_token_auth 0.1.42,  shouldn't this issue be reopened since it is happening in the latest release?

**Comment by lsarni** [comment]
Same issue with devise_token_auth (0.1.42), but it only happened when I created a second model using `rails g devise_token_auth:install`. For the first model it worked fine.

**Comment by tomoyuki28jp** [comment]
Same issue here :(

**Comment by JarLowrey** [comment]
Just installed and it occurred after running `rails g devise_token_auth:install User auth`

**Comment by zachfeldman** [comment]
@JarLowrey what if you try it from the master branch?

**Comment by JarLowrey** [comment]
I just added the `gem 'omniauth'` to my gemfile and it started working.

**Comment by oregontrail256** [comment]
Same here, I had to add `gem 'omniauth` for this to work.

**Comment by zachfeldman** [comment]
Please don't comment here just to say, "same here", this issue is closed - open a new one if you're still having an issue. Thanks

**Comment by josephecombs** [comment]
If you want this error to go away, remove the ```:omniauthable``` decoration from your User Class.
