### ISSUE TITLE
The email_required? method is not working

### ISSUE THREAD

**Issue by betosalvador** [lynndylanhurley/devise_token_auth#1186]
Hello, guys

I have the follow code for my user.rb

```
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable
  include DeviseTokenAuth::Concerns::User

  def password_required?
    false
  end
  
  def email_required?
    false
  end
end
```

But when I try to create e user from console, I have the follow:
```
u = User.new

u.valid?
=> false

 u.errors.keys
=> [:email]
```

The password_required? works, but email_required? don't work.

Can anyone help me?

THanks in advance

**Comment by betosalvador** [comment]
When I remove "validatable" module, this works.

But I dont feel good with this solution :(

**Comment by betosalvador** [comment]
Hello

Anyone could help me.

Please :)

**Comment by MaicolBen** [comment]
Sorry, we are looking for [contributors](https://github.com/lynndylanhurley/devise_token_auth/issues/969), I don't know why it was done that way, in #662 was complained about it too. I will close this one so we don't have duplicates
