### ISSUE TITLE
Remove uniqueness for email

### ISSUE THREAD

**Issue by chaitanya-nyros** [lynndylanhurley/devise_token_auth#1213]
Please let me know how to remove duplicate email validation from this gem

Thanks.

**Comment by dks17** [comment]
@chaitanya-nyros hello.
Do you want sign up user with the same email more at once?

**Comment by chaitanya-nyros** [comment]
Yes I want signup user with same email more at once

But the provider is same.

I want to work this gem as bellow. Could you please guide me on this

Same email and provider bind to scope like organisation_id

**Comment by dks17** [comment]
@chaitanya-nyros 
I am not sure, but you can't sing up with the same email more than once. I think it is impossible.
You can try to set `max_number_of_devices` option and use the same email to sign in in different devices.
https://github.com/lynndylanhurley/devise_token_auth/blob/fcb1e6d22666175aa31945f7b4f0593dc111ff1c/lib/generators/devise_token_auth/templates/devise_token_auth.rb#L14-L16

**Comment by chaitanya-nyros** [comment]
Okay then is it possible to create user with same email and different provider?

**Comment by dks17** [comment]
@chaitanya-nyros 
> Okay then is it possible to create user with same email and different provider?

Try. I have just assumed this.

You should also consider [OmniAuth](https://devise-token-auth.gitbook.io/devise-token-auth/config/omniauth).
Actually I don't understand what you want from simple authentication by unique email.

You should also ask someone else.

**Comment by chaitanya-nyros** [comment]
Yes I tried it is working thanks :)

**Comment by MaicolBen** [comment]
You can have the same email with different providers, if you want inside the same provider, you can override `email_provider?` in user and return false, but that won't work because we always return the first user matched with that email.

**Comment by chaitanya-nyros** [comment]
@MaicolBen 

I customized the gem to work with same emails and different providers.

Thanks.
