### ISSUE TITLE
Is uid mandatory for devise token auth to find current user?

### ISSUE THREAD

**Issue by Usarshakya** [lynndylanhurley/devise_token_auth#1214]
With default configuration of devise token auth, uid is identical to user’s email and is mandatory to find current user. Is it possible to
1. Remove 'uid' from http header and use something else to find current user
2. Hash 'uid' so it is not revealed (same way to be used for password in devise token auth)

**Comment by MaicolBen** [comment]
1. Yes, you can override the method `provider` in the controllers 
2. You have to override some code from the gem to achieve that:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L178

I will close this, feel free to reopen for the enhancement request, if you can create a PR fro that, awesome!

**Comment by lightninglu10** [comment]
@MaicolBen When you say override the method `provider` what exactly do you mean?

Also is there a way to rename the uid field to something like uuid?

**Comment by MaicolBen** [comment]
@lightninglu10 override the method `provider` in your controller (it should inherit the DTA's controller).

**Comment by ziaulrehman40** [comment]
Why we need email in UID?
Is there a tradeoff if we remove this field?

**Comment by MaicolBen** [comment]
You can use something else, but you need something to identify the user, otherwise, how do you know who is?
