### ISSUE TITLE
Password controller : edit does not use default password reset url ?

### ISSUE THREAD

**Issue by proxygear** [lynndylanhurley/devise_token_auth#1219]
Everything is in the title.
I was just surprised, is there a reason of that ?

In create you have :

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/passwords_controller.rb line 14

```
@redirect_url = params.fetch(
        :redirect_url,
        DeviseTokenAuth.default_password_reset_url
      )
```

:)

**Comment by MaicolBen** [comment]
@proxygear The title doesn't match the description, can you explain a little bit more?

**Comment by proxygear** [comment]
You can set a default password reset url.
This url is used in the `create` action, in case`redirect_url` isn't provided in the params.
I was surprised that the same "defaulting" is not done in the `edit` action.

I guess I got confused with all the redirection happening in the story :

* API create -> Mail -> link to API edit (with default_password_reset_url)
* API edit -> Redirect to UI edit (no default url ???)
* UI edit -> post to API update

**Comment by MaicolBen** [comment]
Edit is supposed to receive it when you click in the email, doesn't the confirmation link have the redirect url? or you are requesting this endpoint directly?

**Comment by proxygear** [comment]
I have it all working, so no request.
Just while I was doing it, it felt not really clear, and I was confused with :

* create action as a default url : default_password_reset_url
* edit and update does not ...

It's not really consistant to me.
I guess, It's probably more documentation issue.

**Comment by MaicolBen** [comment]
I saw the documentation and you might be right, but `update` shouldn't have it because it comes from the redirect url

**Comment by MaicolBen** [comment]
You might be right, the documentation isn't clear there, but `update` shouldn't have the redirect url because it is where comes from.

**Comment by MaicolBen** [comment]
I closed this by mistake, I opened a PR
