### ISSUE TITLE
devise_token_auth for multiple client

### ISSUE THREAD

**Issue by obsidienne** [lynndylanhurley/devise_token_auth#122]
Hi,

We want to create a REST server and are investigating RAILS and your gem for authentication.
The REST server will be used by Android/iOS/Windows Phone apps and a web app.

Do you think your gem is the right tool for this ?

Thanks

**Comment by lynndylanhurley** [comment]
Possibly. Do you have any specific questions?

**Comment by zachfeldman** [comment]
Hi there @obsidienne  ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
