### ISSUE TITLE
Update token_lifespan in production remove response headers

### ISSUE THREAD

**Issue by StephaneJuban** [lynndylanhurley/devise_token_auth#1227]
I wanted to change the token life time to match the session duration of my front app (1 day). So I uncommented the line in `config/initializers/devise_token_auth.rb`:
`config.token_lifespan = 1.day`

In development environment everything still works perfectly but when I push it to production, when I want to log in, I get the right response from the server with the user informations but the headers response doesn't contains the `uid`, `client`, `access-token`, `expiry`, etc.

Any idea why ?

I also confirmed this behavior using Postman, so nothing to do with the frontend app.

* **Version**: 0.2.0

**Comment by MaicolBen** [comment]
@StephaneJuban I don't think the token lifespan is related because it only changes the expiration time, are you sure that you didn't change something else? Also, use `v1.0.0rc2` instead

**Comment by StephaneJuban** [comment]
Sorry for the delay but I will try it as soon as I come back to it and update this issue. It's not a top priority yet :)

To be continued...

**Comment by luvcjssy** [comment]
Yup, I have the same issue, I have 3 models user using devise token auth. Everything is OK, but when I change token_lifespan and 2 models still token in headers normally and 1 model not return token. (In development environment)
