### ISSUE TITLE
undefined method `authenticate_user!' when User class nested in module

### ISSUE THREAD

**Issue by WojciechKo** [lynndylanhurley/devise_token_auth#1234]
Hey!
I've seen a few of the issues that describes following error and gives us a way to deal with it when `mount_devise_token_auth_for` is nested inside of `namespace` in Rails routing. https://github.com/lynndylanhurley/devise_token_auth/issues/182

```
*** NoMethodError Exception: undefined method `authenticate_user!' for"
```
I found out that when you nest your model inside of a module, the helper-methods names changes as well.
```ruby
module Models
  class User < ApplicationRecord
    include DeviseTokenAuth::Concerns::User
  end
end
```

```ruby
Rails.application.routes.draw do
  mount_devise_token_auth_for 'Models::User', at: 'auth'
end
```

```ruby
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  before_action :authenticate_models_user!
end
```
Do you have any proposition how to get `authenticate_user` in given example without method aliasing?

**Comment by MaicolBen** [comment]
@WojciechKo and how can we find the class? `User` itself doesn't exist in your codebase, and I don't think method aliasing for this case is bad. Sorry about that!

**Comment by WojciechKo** [comment]
Probably we can't. Was hoping for some kind of configuration option or something.
Anyway, thanks for clarification and for this awesome gem!

**Comment by MaicolBen** [comment]
Yeah sorry, we have tons of configurations and we cannot contemplate each case (that's the problem with engines).
