### ISSUE TITLE
Could not find generator 'devise_token_auth:install_mongoid'

### ISSUE THREAD

**Issue by ypicard** [lynndylanhurley/devise_token_auth#1239]
Can't run `rails g devise_token_auth:install_mongoid User auth`.
I tried restarting my computer as suggested in other issues, and restarting spring, but still doesn't work.

* **Version**: 1.0.0
* **Rails Stacktrace**: 
```
Could not find generator 'devise_token_auth:install_mongoid'. Maybe you meant 'devise_token_auth:install_views', 'devise_token_auth:install' or 'devise:install'
Run `rails generate --help` for more options.
```
  * **Gems**: 
```
mongoid >= 5.1.1
rails 4.2.8
devise 4.5.0
```

**Comment by dks17** [comment]
@ypicard Hello. Use `master` branch. Version with `mongoid` has not released.

**Comment by fjvalles** [comment]
Hi, is there an estimated date to release mongoid support for rails 5?

**Comment by MaicolBen** [comment]
@ypicard Yes, it's in 1.1.0
