### ISSUE TITLE
Error sending password reset email when not using confirmable

### ISSUE THREAD

**Issue by sdornan** [lynndylanhurley/devise_token_auth#124]
I disabled confirmable on my Devise-backed user model for now because this gem doesn't yet honor the ```allow_unconfirmed_access_for``` config setting. Unfortunately, doing this makes sending a password reset email raise ```NoMethodError (undefined method `pending_reconfirmation?' for #<User:0x007fafc5849ff0>)``` due to that method not being present.

**Comment by sdornan** [comment]
It seems that vanilla Devise doesn't call this method in in ```allow_unconfirmed_access_for```, presumably because if the email address hasn't yet been confirmed then it's possible that someone is trying to hijack your account. Would the best solution be to just remove this call from ```send_reset_password_instructions```?

**Comment by sdornan** [comment]
```PasswordsController#edit``` also calls ```@resource.skip_confirmation! unless @resource.confirmed_at```, which can't happen if you're not using confirmable.

**Comment by ACPK** [comment]
@sdornan Any chance you created a fix?  I just hit this issue.

**Comment by ACPK** [comment]
@sdornan Based on your comments above, I added a check that sees if the User model is :confirmable. Here's the pull request - https://github.com/lynndylanhurley/devise_token_auth/issues/124.

**Comment by vikashvikram** [comment]
Is the issue fixed now... because I am getting the same issue. I am not using confirmable module but still facing the same error while trying for password reset.

**Comment by jaysson** [comment]
Looks like it's not fixed... I am getting same issue.

**Comment by thomasdavis** [comment]
Also getting this

**Comment by nicolas-besnard** [comment]
It's fixed now. @lynndylanhurley / @booleanbetrayal you can close this

**Comment by booleanbetrayal** [comment]
Nice!

**Comment by qx** [comment]
Is it has been fixed? I still get the error.
NoMethodError - undefined method `pending_reconfirmation?' for #<User:0x007fa12b3b0230>:
   () Users/ok/.rvm/gems/ruby-2.2.0@global/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
  devise_token_auth (0.1.31) app/models/devise_token_auth/concerns/user.rb:70:in `send_reset_password_instructions'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/passwords_controller.rb:42:in `create'

**Comment by fertingoff** [comment]
Folks, I'm using devise_token_auth 0.1.31 and still have the same issue too. Should I reopen the issue or I and @qx are doing something wrong? @nicolas-besnard @lynndylanhurley, please, advise. 
@sdornan, @thomasdavis, @vikashvikram, @jaysson do you still have this problem?
Thx!

**Comment by fertingoff** [comment]
Looks like I'm not alone with this problem. Please, see reopened issue #321 for more info.
