### ISSUE TITLE
How to check Client value is expired or not?

### ISSUE THREAD

**Issue by zeshan9128** [lynndylanhurley/devise_token_auth#1254]
How to check Client value is expired or not?

**Comment by dks17** [comment]
@zeshan9128 Hello.
For [api usage](https://devise-token-auth.gitbook.io/devise-token-auth/usage) see `/validate_token`.
For [model usage](https://devise-token-auth.gitbook.io/devise-token-auth/usage/model_concerns) see `valid_token?`.

If you need full text search through all docs see old docs (almost the same) in [one place](https://github.com/lynndylanhurley/devise_token_auth/tree/v0.1.43).
