### ISSUE TITLE
Sign in with login instead of email

### ISSUE THREAD

**Issue by Le6ow5k1** [lynndylanhurley/devise_token_auth#126]
Hi!
Is it possible to sign in using login and password instead of email and password?

**Comment by nicolas-besnard** [comment]
You should take a look [at the sign-in controller source](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb).

Seems like you __can't__. For now ;)

**Comment by Le6ow5k1** [comment]
Thank you, Nicolas. I already looked at it and it seems that this feature can be easily implemented.

**Comment by lynndylanhurley** [comment]
@Le6ow5k1 - see my comment in #127
