### ISSUE TITLE
Would it be useful to integrate login with username ?

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#127]
Has mentionned in #126

**Comment by lynndylanhurley** [comment]
I just scanned the devise documentation and found this:
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

So it is possible with standard devise, but the process seems to be rather involved. Also, I'm not sure if this gem will require any modifications to accommodate for this kind of setup.

And in addition to following the steps from the wiki, a new config option will need to be added to ng-token-auth to specify which params are sent to the sessions controller (i.e. `username` instead of `email`).

I think the best course of action is to add a test suite that follows the example in the devise wiki. If it works, then that's great, and if not then we can modify this gem as is needed. I'm short on time right now, but I'll get around to it as soon as I can.

**Comment by nicolas-besnard** [comment]
I'm available to do it, but I don't use to work with `MiniTest` :( I'll try tomorrow to work with ``MiniTest`

**Comment by lynndylanhurley** [comment]
Thanks @nicolas-besnard - I appreciate any help I can get :smiley:

To get the dev environment set up, you can follow [these steps](https://github.com/lynndylanhurley/devise_token_auth#contributing).

I recommend the following approach to testing this feature:

1. Create a new model and migration in the [test app](https://github.com/lynndylanhurley/devise_token_auth/tree/master/test/dummy) that follows the [example](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address) in the devise wiki. The existing models are [here](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address) - you can just follow those for examples.
2. Create tests for each of the cases described in the wiki example. This includes:
  * registration ([link to existing tests](https://github.com/lynndylanhurley/devise_token_auth/blob/master/test/controllers/devise_token_auth/registrations_controller_test.rb))
  * confirmation ([link](https://github.com/lynndylanhurley/devise_token_auth/blob/master/test/controllers/devise_token_auth/confirmations_controller_test.rb))
  * sign in ([link](https://github.com/lynndylanhurley/devise_token_auth/blob/master/test/controllers/devise_token_auth/sessions_controller_test.rb))
  * password reset ([link](https://github.com/lynndylanhurley/devise_token_auth/blob/master/test/controllers/devise_token_auth/passwords_controller_test.rb))
  * test using both case-sensitive and [case-insensitive](https://github.com/plataformatec/devise/wiki/How-To:-Use-case-insensitive-emails) authentication keys for all of the above
3. Once all of the tests pass, make sure they pass using the following:
  * ruby 1.9.3
  * ruby 2.1
  * sqlite
  * mysql
  * postgresql

Let me know if you run into any trouble!

Thanks in advance :+1:

**Comment by nicolas-besnard** [comment]
What happened if validation is required and you sign-in with username ? Email HAS to be present right ?

**Comment by lynndylanhurley** [comment]
Just to clarify, are you asking if an email address is required to use `confirmable`? In that case, yes - we would require an email address to create the account. But subsequent sign-ins should be possible using the the user's username (or whatever the authentication key is called).

**Comment by nicolas-besnard** [comment]
Yes, but when a new user register, he should have specified an email, right ? With or without `confirmable`.

**Comment by lynndylanhurley** [comment]
I'm not sure about this actually. I don't see any explicit references to an `email` param in the devise source for [registrations](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb) or [sessions](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb).

I think devise may rely on the [`authentication_keys`](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address#tell-devise-to-use-username-in-the-authentication_keys) array, but I'm not sure how this works for modules like `confirmable` and `recoverable` that require emails to be sent.

You may need to check the devise source code on this.

**Comment by nicolas-besnard** [comment]
I will dig into it. I usually use `rspec` for my test. Is there any way to run a single test ?

**Comment by lynndylanhurley** [comment]
To run a single test, just type the word `focus` right above the test. I'm using [this gem](https://github.com/seattlerb/minitest-focus) I think.

**Comment by nicolas-besnard** [comment]
I just made a PR. The login looks good to me, I need to dig into the registration now.

**Comment by lynndylanhurley** [comment]
@nicolas-besnard - I just merged your PR - this should be fixed as of `v0.1.32.beta2`.

I pushed everything up to the [demo site](http://ng-token-auth-demo.herokuapp.com/) and it seems to be working there. Let me know if you see any issues.

**Comment by lynndylanhurley** [comment]
Oh and congratulations, you're now an official contributor:
https://github.com/lynndylanhurley/devise_token_auth#callouts

:boom: :sparkles: :bouquet:
