### ISSUE TITLE
Database index question

### ISSUE THREAD

**Issue by pioz** [lynndylanhurley/devise_token_auth#1272]
In file https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L71
I can see the query `User.find_by(uid: uid)` so I think that we need a index in our db like this `add_index :users, :uid, unique: true`, BUT when I run the command `rails g devise_token_auth:install User auth` the migration file does not add this index but `add_index :users, [:uid, :provider], unique: true` (file https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/templates/devise_token_auth_create_users.rb.erb#L44). Is this correct and wanted, or we should add the right index?

**Comment by MaicolBen** [comment]
You can change the migration generated but we cannot make the index only scoped to `uid` as you can have the same `uid` in different providers.
