### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by stoivo** [lynndylanhurley/devise_token_auth#1275]
Is there are changelog since 0.1.43?

**Comment by esambo** [comment]
I was just looking for an updated [CHANGELOG.md](https://github.com/lynndylanhurley/devise_token_auth/blob/master/CHANGELOG.md) too.
Looking through the [last commits](https://github.com/lynndylanhurley/devise_token_auth/commits/master) doesn't provide much help either, besides:
- Bump version 1.0.0 #1229
- Bump version to 1.0.0.rc1 721b3806ea6995d0ca457d118d8c0425a74e09f4
