### ISSUE TITLE
Any way to "become" user?

### ISSUE THREAD

**Issue by iamnader** [lynndylanhurley/devise_token_auth#1291]
There are a couple common use cases for programmatically logging in as another user.
1) In development it's faster than logout/login
2) In production there are times when an admin may want to see an app as a user does to reproduce an issue.

Given the tokens are hashed (as they should be!) is there any way for an admin to programmatically "become" another user?

**Comment by MaicolBen** [comment]
Did you try with https://github.com/ankane/pretender? It works with Devise but I am not sure if it works with DTA

**Comment by iamnader** [comment]
Thanks @MaicolBen. I wasn't aware of pretender, and just implemented something very similar.   I'm going to close this as I think the functionality is outside the scope of the gem.  Might be useful to add to the wiki though.

**Comment by MaicolBen** [comment]
Great! If you want to explain here how you achieved it, I can add it to the documentation.

**Comment by iamnader** [comment]
I just meant a link to Pretender for this use case.

I implemented passing a special request header that contains a user id, that my controller can look for and if present AND the current user is an admin set current_user to the passed in user_id so that that is used everywhere

**Comment by josephecombs** [comment]
This is my step by step process to "Become" customer. Slightly complicated but works:

### Step 1
Put this link somewhere on your Admin page.
`<a href="/admin/customers/1/become">Click to Become Customer!</a>`

### Step 2
(note - I am not using token auth for my admin site)
```
class Admin::CustomersController < AdminController
  before_action :authenticate_admin_user!
  layout 'admin'
  
  def become
    @customer = Customer.find(params[:id])
    @client_id, @token = @customer.create_token
    @customer.save

    # this redirects to unauthenticated endpoint
    redirect_to "/customer/become?uid=#{@customer.email}&access_token=#{@token}&client=#{@client_id}"
  end
end
```

### Step 3
Admin site redirects to consumer site with the correct stuff in query string:
```
class CustomerController < ApplicationController
  layout 'consumer'
  # unauthenticated
  
  def become
    @customer = Customer.find_by_email(params[:uid])
    @token = params[:access_token]
    @client = params[:client]
    if @customer && @customer.valid_token?(@token, @client)
      sign_in(:user, @customer, store: false, bypass: false)

      @become_customer_hash = {
        customer: @customer.reload,
        access_token: @token,
        client: @client,
      }
    else
      render json: { errors: ['invalid tokens'] }, status: 404
      return
    end    
  end
end
```

### Step 4
Object is constructed for my SPA to utilize in initial state
```
# consumer.html.erb
...
if @become_customer_hash
  becomeCustomer = {
      uid: @become_customer_hash[:customer].email,
      client: @become_customer_hash[:client],
      accessToken: @become_customer_hash[:access_token]
  }.delete_if { |k, v| v.blank? }
end
...

```

### Step 5
I use the library redux-token-auth, which means changing the stuff in localStorage triggers successful client/server handshake:
```
...
componentDidMount() {
  window.localStorage.setItem('access-token', this.props.becomeCustomer.accessToken);
  window.localStorage.setItem('client', this.props.becomeCustomer.client);
  window.localStorage.setItem('uid', this.props.becomeCustomer.uid);
}

componentDidUpdate() {
  const canRedirect = this.props.reduxTokenAuth.currentUser.isSignedIn;
  if (canRedirect) {
    // logged in account page for customer you've become
    this.props.history.push('/customer/account');
  }
}
...
```
