### ISSUE TITLE
Missing user credential in confirmation redirect url querystring

### ISSUE THREAD

**Issue by CDimonaco** [lynndylanhurley/devise_token_auth#1292]
After upgrading from `devise_token_auth ->  1.0.0` to `devise_token_auth: -> 1.1.0'`, when a user sign up and receive the confirmation email, the backend will redirect to the confirmation redirect url, without `client`, `access-token`, `token-type` and the other related user authentication stuff as query string params.

With the version '1.1.0', the only querystring params passed to the redirect confirmation url is the `account_confirmation_success` set to true.

Is an intended behavior? I can't found anything really useful on the docs or changelog.

Thanks in advance.
 **Version**: 1.1.0
 * **Ruby**: 2.6.1
  * **Gems**: ActiveRecord
  * **Custom Overrides**: none
  * **Custom Frontend**: none

**Comment by MaicolBen** [comment]
That's expected from that version, we don't sign in anymore as we don't want to depend in the trackable module (awful design and a majority of people isn't using it), also it's kind of insecure logging there. If you are already logged in, we send you the credentials. 

Check #1075
