### ISSUE TITLE
Sudo action / confirm your identity protocol

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#131]
I would like to implement a "confirm your identity" protocol. It's the same thing Github do when you try to change some of your personal information.

For example, when you want to change your password, even if you have a valid token, you'll be required to enter your password.

When you'll hit the route `/users` with the `PUT` header, the server return something like "you need to confirm your identity". Then a request is made at `/users/sudo` with your password, and you can now change your password or do whatever action that require a confirmation.

I don't know if understandable, seems good in my head ^^

**Comment by lynndylanhurley** [comment]
I agree that this would be a useful feature. 

The question is, how do we determine which information requires "sudo" access? For example, do we require confirmation by model, or by model attribute? And do we need it to behave differently for admins, moderators, etc.?

I guess I'm asking if this is something that we can generalize, or is this something that must be handled differently for each individual app?

**Comment by nicolas-besnard** [comment]
This idea came on a need of one application I'm working on. I originally plan to create it has a gem.

So the idea is:
- You are using an authentication system on a API and you when your user to prove his identity on a critical action.
- You can easily specify which information the "Resource" has to validate. I was thinking of something like that :

```ruby
class User
    act_as_sudo field: :pin_code # :password is the default 
end

- Next, I don't think you need to set an "information" who requires sudo, it's more a route who need sudo. Like on Github, you can't access the page to associate third-applications without confirms your password.

```ruby
class UserController
   before_action :requiere_sudo, only: [:critical_method]
end
````
- For the implementation, I was thinking of adding a new field to the user : `sudo_valide_until` or something like that (you see the idea, the name is just an example).

**Comment by nicolas-besnard** [comment]
FYI : WIP (wow such acronym)

**Comment by lynndylanhurley** [comment]
Cool man, I'm excited to see what you come up with!

**Comment by lynndylanhurley** [comment]
You mentioned this as a possible implementation:

~~~ruby
class UserController
   before_action :require_sudo, only: [:critical_method]
end
~~~

I'm assuming that the `before_action` would require the `act_as_sudo` field to be present in the `:critical_method` request, and | think that's a great idea.

My question is, how would this behave for users that signed up via OAuth? Would they be required to set a password / `act_as_sudo` field at signup, or would they be forced to re-authenticate using their OAuth provider for sudo access?

**Comment by nicolas-besnard** [comment]
Great question, this case didn't come up to my mind ... I'll dig into into it tomorrow. What would be your approach ? Seems really heavy to ask user to re-authenticate ...

**Comment by lynndylanhurley** [comment]
> Seems really heavy to ask user to re-authenticate

Yeah I agree. Maybe this feature should be restricted to users with `provider: email` for now.

**Comment by zachfeldman** [comment]
Hi there @nicolas-besnard  ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
