### ISSUE TITLE
Change how to update existing user migration

### ISSUE THREAD

**Issue by GMolini** [lynndylanhurley/devise_token_auth#1311]
I have encountered some trouble with this part:

    # updates the user table immediately with the above defaults
    User.reset_column_information

    # finds all existing users and updates them.
    # if you change the default values above you'll also have to change them here below:
    User.find_each do |user|
      user.uid = user.email
      user.provider = 'email'
      user.save!
    end

Because I had some validations on the user, and the migration uses the User model, the migration would fail. My suggestion would be to replace those lines with  the following:

    execute "update users set uid = email"
    execute "update users set provider = 'email'"

This updates the database directly using SQL, thus avoiding the model validations

**Comment by MaicolBen** [comment]
That skip callbacks, this is generated code and you can change the save for `save(validate: false)`. It seems nasty to do that change in the gem codebase because you have invalid data.
