### ISSUE TITLE
uninitialized constant DeviseTokenAuth::Concerns in development.

### ISSUE THREAD

**Issue by wongy91** [lynndylanhurley/devise_token_auth#1312]
When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**: 1.1.0
* **Request and response headers**: NA
* **Rails Stacktrace**: 
class User < ApplicationRecord
  include DeviseTokenAuth::Concerns::User
end
* **Environmental Info**: only in DEV for some reasons
  * **Gems**: are you using MongoDB, Grape, RailsApi, ActiveAdmin, etc.? yes

it happens like 50%, startup rails server is fine but going to any route gives the error

**Comment by MaicolBen** [comment]
That happens when the gem isn't installed, otherwise, it would be very weird that is only happening to you. Do you have `mount_devise_token_auth_for` in the routes?

**Comment by namolnad** [comment]
@MaicolBen I'm currently running into this same issue, though the app never successfully boots at all in dev/test environments unlike the @wongy91's 50% success rate.

**Comment by namolnad** [comment]
@wongy91 were you ever able to solve this?

**Comment by MaicolBen** [comment]
> That happens when the gem isn't installed, otherwise, it would be very weird that is only happening to you. Do you have mount_devise_token_auth_for in the routes?

I guess you have this okey, can you post the backtrace?
