### ISSUE TITLE
Missing template /omniauth_response 

### ISSUE THREAD

**Issue by fikriauliya** [lynndylanhurley/devise_token_auth#132]
I use latest Rails-API & latest devise_token_auth (beta), after successful callback from Facebook OmniAuth, the following errors happen:

    ActionView::MissingTemplate (Missing template /omniauth_response with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in:
      * "/home/vagrant/.rvm/gems/ruby-2.2.0/gems/devise_token_auth-0.1.32.beta1/app/views"
      * "/home/vagrant/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/app/views"
    ):
It could be fixed by replacing (in omniauth_callbacks_controller.rb):

    format.html { render :layout => "omniauth_response", :template => "devise_token_auth/omniauth_success" }

to

    format.html { render :layout => "layouts/omniauth_response", :template => "devise_token_auth/omniauth_success" }

**Comment by lynndylanhurley** [comment]
Thanks @fikriauliya - I'll look into this right away.

**Comment by fikriauliya** [comment]
And probably it would be better to drop those `respond_to` statements, e.g. change:

    respond_to do |format|
        format.html { render :layout => "omniauth_response", :template =>   "devise_token_auth/omniauth_failure" }
    end

to just:

    format.html { render :layout => "omniauth_response", :template =>   "devise_token_auth/omniauth_failure" }

The inclusion of `respond_to` drags `ActionController::MimeResponds` to rails-api (https://github.com/rails-api/rails-api#adding-other-modules) which drags `gem "responders"` (https://github.com/rails-api/rails-api/issues/179)

**Comment by lynndylanhurley** [comment]
@fikriauliya - I'm unable to reproduce this bug. I just pushed the latest code up to the [demo site](http://ng-token-auth-demo.herokuapp.com/) and everything seems to be working fine.

Are there any notable differences between your app and the [reference implementation](https://github.com/lynndylanhurley/devise_token_auth_demo)?

**Comment by fikriauliya** [comment]
Perhaps because I use Rails API? https://github.com/fikriauliya/angularjs-rails-api-devise-bootstrap
Probably the view engine doesn't auto include about `layouts/` folder

**Comment by lynndylanhurley** [comment]
@fikriauliya  - version `0.1.32.beta5` contains the changes that you suggested. Please confirm that the issues are resolved.
