### ISSUE TITLE
CookieOverflow with 

### ISSUE THREAD

**Issue by jachwe** [lynndylanhurley/devise_token_auth#1322]
Hi, i have the problem that my session data size grows a lot. (1.6GB in DB for ~ 40k rows)
(i clean old sessions every night using rake task, but individual size is still to big)

I figured out that the reason behind this is, that my entire `User` object is serialized into the session data, including some blobs and keys etc ...

Is there any way to override what's being stored in the session? `id` and/or `email` would be sufficiant. I`d also would like to move back to `cookie_store` which is not possible at the moment because i hit the 4k cookie limit.

thanks 

* **Version**: 0.2.0
* **Rails Stacktrace**:  `ActionDispatch::Cookies::CookieOverflow - ActionDispatch::Cookies::CookieOverflow:`
  * **Routes**: in api namespace
  * **Custom Overrides**:  none
  * **Custom Frontend**:  no

**Comment by MaicolBen** [comment]
Is that a gem's issue? Did you override `as_json` ? Are you using Omniauth?

Check also if [this](https://github.com/lynndylanhurley/devise_token_auth/issues/718#issuecomment-289247662) works

**Comment by jachwe** [comment]
Sorry, I somehow missed the notifications for this thread. 🙈
I will investigate further. The problem persists.
