### ISSUE TITLE
OmniAuth redirect doesn't work if using the generated mount_devise_token route

### ISSUE THREAD

**Issue by fikriauliya** [lynndylanhurley/devise_token_auth#133]
If the following is configured in routes.rb:

    mount_devise_token_auth_for 'User', at: '/auth'

After OmniAuth server callback (I tried on Facebook Omniauth), the server will redirect_to "//auth/facebook/callback", which would rendered to auth:3000/facebook/callback in browser.

It can be fixed by replacing routes.rb into:

    mount_devise_token_auth_for 'User', at: 'auth'  # (delete /)

Unfortunately, the generator create the wrong one. In install_generator.rb:

    argument :mount_path, type: :string, default: '/auth'
    def add_route_mount
       f    = "config/routes.rb"
       str  = "mount_devise_token_auth_for '#{user_class}', at: '#{mount_path}'"

We can fix that by fixing mount_path argument...

... or change the following (in omniauth_callbacks_controller.rb):

    redirect_route = "/#{Devise.mappings[devise_mapping].as_json["path"]}/#{params[:provider]}/callback"

into 

    redirect_route = "#{Devise.mappings[devise_mapping].as_json["path"]}/#{params[:provider]}/callback"

**Comment by lynndylanhurley** [comment]
Thanks @fikriauliya - this behavior changed with the last release and it looks like I forgot to update the template. I'll push this fix ASAP.

**Comment by lynndylanhurley** [comment]
This should be fixed as of version `0.1.32.beta4`.
