### ISSUE TITLE
Rails email change not send confirmation emaill 

### ISSUE THREAD

**Issue by niusmake** [lynndylanhurley/devise_token_auth#1338]
Excuse me, I use devise_token_auth for devise, 

and I want to send a email Confirmation when I update my email.

But only update email, there is no way to send email Confirmation, 

what is missing? Please Help me..

I also opened the settings. 

### devise.rb
```
config.reconfirmable = true
```

I create a new account, will send confirm email,
but not send it when I update the email.

### Routes
```
mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'api/v1/auth/users/registrations',
    omniauth_callbacks: "api/v1/auth/users/omniauth_callbacks"
}

```

### Model
```
include DeviseTokenAuth::Concerns::User
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable, :lockable,
  :omniauthable,
```

### Controller
```
class RegistrationsController < DeviseTokenAuth::RegistrationsController
    
    private
    def sign_up_params
    params.require(:user).permit(:base64_image,
                                    :image,
                                    :name,
                                    :email,
                                    :birthday,
                                    :address,
                                    :sex,
                                    :password,
                                    :password_confirmation)
    end

    def account_update_params
    params.require(:user).permit(:base64_image,
                                    :image,
                                    :name,
                                    :email,
                                    :birthday,
                                    :address,
                                    :sex,
                                    :password,
                                    :password_confirmation)
    end
end
```

Only the update will not send confirmation email.

**Comment by makicamel** [comment]
Hi.
I just met this problem too, few days ago!
I think it is the same problem as [this issue](https://github.com/lynndylanhurley/devise_token_auth/issues/1013).
It may help you to try the code at the bottom of this issue.

**Comment by yoshitsugu** [comment]
@makicamel @niusmake
It seems that the issue already solved, right?
I found the `send_confirmation_email` option here
https://github.com/makicamel/devise_token_auth/blob/1ec6f7e01db0b9fb2b80c1c93ffc59e72f16f373/docs/config/initialization.md

**Comment by niusmake** [comment]
@yoshitsugu 
Thanks, issue already solved.
