### ISSUE TITLE
NoMethodError (undefined method `name' for nil:NilClass) - devise_controller.rb:22

### ISSUE THREAD

**Issue by rmagnum2002** [lynndylanhurley/devise_token_auth#134]
Scenario - I log in successfully, and navigate through pages as a logged in user until I hit refresh.
Happens with this line:

``` ruby
# config.change_headers_on_each_request = true
```

commented, uncommented, set to true or false.. all cases. 

```
NoMethodError (undefined method `name' for nil:NilClass):
  devise (3.4.1) app/controllers/devise_controller.rb:22:in `resource_name'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/application_controller.rb:10:in `resource_class'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:19:in `set_user_by_token'
```

line 22 from devise_controller:

```
21  def resource_name
22    devise_mapping.name
23  end
```

**Comment by lynndylanhurley** [comment]
What do the request and response headers look like? This can be found in the "network" tab of your web inspector.

**Comment by rmagnum2002** [comment]
@lynndylanhurley you mean headers at foe the sign_in action? or at the moment when I hit refresh?
Thank you.

**Comment by rmagnum2002** [comment]
@lynndylanhurley the response tab was a bunch of html code that looked like usual rails exception errors, so I am not sure this is what you need, however, I'll post the info I have step by step:

1. Headers when I sign in successfully:

https://gist.github.com/rmagnum2002/8f86bcfb84d3f64ce2cc 

2. Console logs when I sign in successfully:

https://gist.github.com/rmagnum2002/93be6c4ab7ca20f66104

Nothinf to show when I navigate through pages, it's all angular and I have the sign out link in the menu, so I think so far so good.

3. Headers when I refresh the page (error comes when app does a request to `/api/auth#validate_token`)
https://gist.github.com/rmagnum2002/58508565bb7147acffbf
and
4. console logs for step 3
https://gist.github.com/rmagnum2002/013bd50a14ea905565d7

**Comment by babelfish** [comment]
I had this same problem when mounting under a namespace (/api/v1 in my case). The problem disappeared after moving the devise mounting out of the namespace.

**Comment by aihaddad** [comment]
Hi,
I had the same issue as mentioned, and it actually works if the routes are places outside the namespace. But is there a way to make it work within the name space? I tried extracting the token_validations_controller out into my API module, but it doesn't seem to work

**Comment by lauborges** [comment]
+1

**Comment by nicolasiensen** [comment]
+1

**Comment by kimooz** [comment]
+1

**Comment by gueorgui** [comment]
+1. @aihaddad's solution works, but that hardly sounds like the way it should be.

**Comment by xanthfan** [comment]
I'm getting this problem as well. Moving the devise mounting out of the namespace, gets me past the "undefined method `name' for nil:NilClass" error. But the validate request is stopped at a different error:

"ArgumentError (wrong number of arguments (2 for 1)):"

Gist with my routes.rb file : 
https://gist.github.com/anonymous/c70726923548716fc236

Gist with the console output:
https://gist.github.com/anonymous/0d27838fc166796cd4ca

I've been trying to get ng_token_auth and devise_token_auth to work all week. Love the work you're doing, please help!

**Comment by xanthfan** [comment]
Also here are my versions:

    devise_token_auth (0.1.32)
      devise (~> 3.3)
      rails (~> 4.2)

**Comment by aihaddad** [comment]
I think you need to revise your route to "/auth" instead of "auth"

**Comment by xanthfan** [comment]
As it turned out, my bug was not the fault of devise_token_auth. Other git branches of my app (which use the original devise gem) were giving me the same "wrong number of arguments" error.  So the problem was with a dependent gem somewhere. Clearing gems and re-bundling solved the problem.

**Comment by dkoloditch** [comment]
I experienced the same issue in regard to the /api/v1/ name space. I moved the mount line from within the namespace in routes...:

```
namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      ...
    end
end
```

...to outside of the namespace while referencing the correct path:

```
mount_devise_token_auth_for 'User', at: 'api/v1/auth'

namespace :api do
    namespace :v1 do
      ...
    end
end
```

**Comment by ksinghal** [comment]
when I move it out of the namespace as @dkoloditch suggested, the before_filter authenticate_user! conflicts with that of devise. Is there any other way to resolve this issue?

**Comment by toshimaru** [comment]
@dkoloditch thaanks for the solution. It works.

**Comment by Salet** [comment]
I'm experiencing exact same problems @xanthfan had. When devise_token is mounted under a namespace, I get logged out after page refresh, and when it's outside I hit:
> ArgumentError (wrong number of arguments (2 for 1)):
> devise (3.5.2) lib/devise.rb:454:in `[]'

However, my Gemfile is almost empty and I continue failing on making this work. Any help appreciated.

**Comment by duleorlovic** [comment]
+1 for @dkoloditch solution

**Comment by Salet** [comment]
Solution provided by @dkoloditch works. If you however encounter following error:
> ArgumentError (wrong number of arguments (2 for 1)):
devise (3.5.2) lib/devise.rb:454:in `[]'

like I and @xanthfan did, clear up your cookies. I had cookies set up by other application using older devise which were causing this.

**Comment by andoq** [comment]
The namespaced auth route issue is also discussed in #219

**Comment by zachfeldman** [comment]
Hi there @rmagnum2002   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
