### ISSUE TITLE
Rails 6.1 DEPRECATION WARNING: Uniqueness validator case sensitivity

### ISSUE THREAD

**Issue by ch-tactica** [lynndylanhurley/devise_token_auth#1345]
I'm getting the following error in Rails 6, which I believe is coming from this gem:

```
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :email attribute in User model, pass `case_sensitive: true` option explicitly to the un
iqueness validator.
```

**Comment by ayza-hamid** [comment]
Try this.
It worked for me.
```validates_uniqueness_of :email, case_sensitive: true```

**Comment by ch-tactica** [comment]
Doesn't fix that problem at all.

**Comment by ch-tactica** [comment]
To fix this, I had to make `default_callback` setting false. Why I'm getting omniauth validations added when I'm not even using omniauth... 🤷‍♂

**Comment by MaicolBen** [comment]
Are you sure it comes from this gem? Doesn't it print the line of the warning? Because it isn't happening to me in rails 6. Should we remove `case_sensitive: false` ? from the next line:
```ruby
validates :email, uniqueness: { case_sensitive: false, scope: :provider }, on: :create, if: :email_provider?
```

**Comment by resogomes** [comment]
Even being closed, I'll comment. I got the same Deprecation Warning just after installing devise_token_auth and also found this on Stackoverflow: https://stackoverflow.com/questions/63165940/warnings-about-case-sensitive-cant-be-erased.

It seems that this gem is causing this deprecation warning. And I don't know why, but even on lines where my tests are not related to :email, the deprecation warning is shown.
