### ISSUE TITLE
Error when loging with facebook the second time without logout

### ISSUE THREAD

**Issue by williamweckl** [lynndylanhurley/devise_token_auth#135]
Error:

    NoMethodError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success

    undefined method `[]' for nil:NilClass

    Extracted source (around line #24):
        
      22 # find or create user by provider and provider uid
      23 @resource = resource_class.where({
      24  uid:      auth_hash['uid'],
      25  provider: auth_hash['provider']
      26 }).first_or_initialize

How to reproduce:
1- Login with facebook using omniauth-facebook
2- Remove the auth token cookie
3- Click again on facebook login button

**Comment by nicolas-besnard** [comment]
- Have you specified your `APP_ID` and `SECRET_ID`?
- Have you specified your callback url on facebook ?
- Try to add your `callback_path` to the Omniauth Initializer [doc here](https://github.com/mkdynamic/omniauth-facebook)

**Comment by williamweckl** [comment]
* yes
* yes
* I've added `callback_url`

My first login is successful. The problem happens only when I remove the cookie and try to login again.

**Comment by williamweckl** [comment]
Happens if I don't remove the cookie too. Just try to login twice.

**Comment by nicolas-besnard** [comment]
Which version of this gem are you using ? How do you proceed to Faceboon log ?

**Comment by williamweckl** [comment]
###Gemfile

    gem 'devise_token_auth'
    gem 'omniauth'
    gem 'omniauth-twitter'
    gem 'omniauth-facebook'
    gem 'omniauth-google-oauth2'

I'm using ng-token-auth with an angular app.
Authentication with google and twitter gives me the same error.
Debuging I found that `auth_hash` is nil on amniauth_success method.

Will try to use master branch.

**Comment by williamweckl** [comment]
Using master and happens too.

**Comment by nicolas-besnard** [comment]
I faced this error once, and it was because the Facebook callback url on https://developers.facebook.com was wrong. Is there any to access to you code ? (Rails + Angular)

**Comment by williamweckl** [comment]
I think is not any facebook configuration, if it were I were not able to login the first time and google and twitter providers were work.
I found a pattern, the error happens when I already allowed the app on the provider. Every first time logging with facebook, twitter and google, was successful. 

Now if I go to my facebook and remove the app, I get another error:

    NoMethodError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success

    undefined method `constantize' for nil:NilClass

    def resource_class
      if omniauth_params
        omniauth_params['resource_class'].constantize
      end
    end

My app is not public, but I'll make another only with auth and will put it on github.

**Comment by williamweckl** [comment]
My files:

    #initializers/devise_token_auth.rb
    DeviseTokenAuth.setup do |config|
      config.change_headers_on_each_request = true
      config.token_lifespan = 1.day
      config.omniauth_prefix = "/auth"
    end

    #initializers/omniauth.rb
    Rails.application.config.middleware.use OmniAuth::Builder do
      provider :twitter,        'id',   'secret', callback_path: '/auth/twitter/callback'
      provider :facebook,      'id', 'secret', callback_path: '/auth/facebook/callback'
      provider :google_oauth2, 'id', 'secret', callback_url: 'http://lvh.me:3000', callback_path: '/auth/google_oauth2/callback'
    end

    #controllers/application_controller.rb
    class ApplicationController < ActionController::Base
      include DeviseTokenAuth::Concerns::SetUserByToken
      protect_from_forgery with: :exception

      after_filter :set_csrf_cookie_for_ng

      def set_csrf_cookie_for_ng
        cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
      end

      protected

      def verified_request?
        super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
      end
    end

    #config/routes.rb
    Rails.application.routes.draw do
      mount_devise_token_auth_for 'User', at: '/auth'
      root 'static_pages#index'
    end

    #main.js.coffee
    ...
    @app.config ($authProvider) ->
      $authProvider.configure({
        apiUrl: '',
        authProviderPaths: {
          twitter:    '/auth/twitter',
          facebook:  '/auth/facebook',
          google:    '/auth/google_oauth2'
        }
      });
    ...

Of course, I've changed keys and screts on omniauth.rb

### Facebook config:

Valid OAuth redirect URIs: 
* http://lvh.me:3000/auth/facebook/callback#_=_
* http://lvh.me:3000/auth/facebook/callback

Site URL: http://lvh.me:3000/
Mobile Site URL: http://lvh.me:3000/

**Comment by nicolas-besnard** [comment]
Ok. When you do a `rake routes` what are the routes for Omniauth controller ?

**Comment by williamweckl** [comment]
Prefix Verb   URI Pattern                        Controller#Action
            new_user_session GET    /auth/sign_in(.:format)            devise_token_auth/sessions#new
                user_session POST   /auth/sign_in(.:format)            devise_token_auth/sessions#create
        destroy_user_session DELETE /auth/sign_out(.:format)               devise_token_auth/sessions#destroy
               user_password POST   /auth/password(.:format)           devise_token_auth/passwords#create
           new_user_password GET    /auth/password/new(.:format)       devise_token_auth/passwords#new
          edit_user_password GET    /auth/password/edit(.:format)      devise_token_auth/passwords#edit
                             PATCH  /auth/password(.:format)           devise_token_auth/passwords#update
                             PUT    /auth/password(.:format)           devise_token_auth/passwords#update
    cancel_user_registration GET    /auth/cancel(.:format)             devise_token_auth/registrations#cancel
           user_registration POST   /auth(.:format)                    devise_token_auth/registrations#create
       new_user_registration GET    /auth/sign_up(.:format)            devise_token_auth/registrations#new
      edit_user_registration GET    /auth/edit(.:format)               devise_token_auth/registrations#edit
                             PATCH  /auth(.:format)                    devise_token_auth/registrations#update
                             PUT    /auth(.:format)                    devise_token_auth/registrations#update
                             DELETE /auth(.:format)                    devise_token_auth/registrations#destroy
           user_confirmation POST   /auth/confirmation(.:format)       devise_token_auth/confirmations#create
       new_user_confirmation GET    /auth/confirmation/new(.:format)   devise_token_auth/confirmations#new
                             GET    /auth/confirmation(.:format)       devise_token_auth/confirmations#show
         auth_validate_token GET    /auth/validate_token(.:format)     devise_token_auth/token_validations#validate_token
                auth_failure GET    /auth/failure(.:format)            devise_token_auth/omniauth_callbacks#omniauth_failure
                             GET    /auth/:provider/callback(.:format) devise_token_auth/omniauth_callbacks#omniauth_success
                             GET    /auth/:provider(.:format)          redirect(301)
                        root GET    /                                  static_pages#index
                             GET    /auth/:provider/callback(.:format) devise_token_auth/omniauth_callbacks#redirect_callbacks

**Comment by williamweckl** [comment]
I created an example app. Fresh new rails project with devise_token_auth gem and angular with ng_token_auth. Just set your fb app key and secret and test.

https://github.com/williamweckl/token_auth_example

**Comment by lucasloliveira** [comment]
I'm facing the same issue. I've managed to login yesterday on another computer I was using for development and today when trying to login with facebook on a different computer I had those same issues that @williamweckl described.

Using devise_token_auth version 0.1.32.beta5

**Comment by williamweckl** [comment]
Will try it @lucasloliveira. Thank you.

**Comment by williamweckl** [comment]
@lucasloliveira how is your routes.rb file?

Are you using ng-token-auth too? If yes, when you removed the scope `api` what did you put on apiUrl at ng-token-auth config?

**Comment by lucasloliveira** [comment]
Yes, I'm using ng-token-auth too. Here's my routes.rb:

```ruby 
Rails.application.routes.draw do

    mount_devise_token_auth_for 'User', at: 'auth'
end
```

And here's my apiUrl config: 

```javascript
$authProvider.configure({
      apiUrl: ENV.apiEndpoint,
      authProviderPaths: {
        facebook: '/auth/facebook'
      }
    });
```
where ENV.apiEndpoint is an ngconstant defined (for development) as:

```javascript
apiEndpoint: 'http://localhost:3000'
```

**Comment by williamweckl** [comment]
Same error still... =(

How is your omni_auth initializer?

**Comment by lucasloliveira** [comment]
It's just like the documentation suggests:

```ruby
# config/initializers/omniauth.rb
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook,      ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

I've seen the files you posted before. Did you do the following changes?

1. remove config.omniauth_prefix = "/auth" from devise_token_auth.rb
2. change your routes from 
*mount_devise_token_auth_for 'User', at: '/auth'* 
to 
*mount_devise_token_auth_for 'User', at: 'auth'*
3. remove the callback_path from facebook provider on omniauth.rb

**Comment by williamweckl** [comment]
Worked man! 

But this don't make any sense.

The callback url now is /omniauth instead /auth and at angular we put `facebook:  '/auth/facebook'`.

**Comment by lynndylanhurley** [comment]
@williamweckl - OmniAuth doesn't normally support multiple user models. I'm using some magic to provide this support, but it requires OmniAuth to have its own dedicated route that isn't accessed directly.

**Comment by ryaz** [comment]
Hi!
I faced issue with "No resource_class found" on callback from slack and I can't see how to solve it.
But I see those line in dummy folder:
```
mount_devise_token_auth_for 'User', at: 'auth'
mount_devise_token_auth_for "Mang", at: 'mangs'
```
So I was wondering maybe it makes sense to pass resource name in callback url:
```
auth/users/facebook/callback
auth/mangs/facebook/callback
```
