### ISSUE TITLE
Force users to reset passwords on the first logins

### ISSUE THREAD

**Issue by K-Sato1995** [lynndylanhurley/devise_token_auth#1354]
I want admin users to manually create other users and make the created users reset their passwords on their first logins.
How can I implement a feature like this with devise_token_auth???

**Comment by pedrofs** [comment]
Not sure, but devise_invitable can help you to accomplish what you need.

https://github.com/scambra/devise_invitable

**Comment by Tioneb12** [comment]
=> create(user)
=> reset_password_token
=> send an email with a link to reset password (with token)

**Comment by K-Sato1995** [comment]
@Tioneb12 
Thanks for replying!
I think that would be the most straightforward way to achieve it with this gem. You can just restrict users from accessing the content unless they've changed the default passwords.

As for checking if the users changed their default passwords, you can add a column called `password_updated_at: DateTime` to your user's table and set the default value to `CURRENT_TIMESTAMP` and update it every time a user changes its password. That way, you can compare `password_udpated_at` to `created_at` and can know whether the user updated the default password or not.
(This is just an example and there are many other ways to check it)
