### ISSUE TITLE
Why is Trackable option still active?

### ISSUE THREAD

**Issue by SugiKent** [lynndylanhurley/devise_token_auth#1356]
This gem is awesome and helpful for me! Thanks for Contributors !
But I have a question about devise_auth_token:install command.

* **Version**: which version of this gem (and [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth), [jToker](https://github.com/lynndylanhurley/j-toker) or [Angular2-Token](https://github.com/neroniaky/angular2-token) if applicable) are you using?
```
devise_token_auth (1.1.3)
devise (4.7.1)
rails (6.0.1)
```
* **Environmental Info**: How is your application different from the [reference implementation](https://github.com/lynndylanhurley/devise_token_auth_demo)? This may include (but is not limited to) the following details:

I'm using RailsAPI mode.

## Question

Why does a model have Trackable option after `rails g devise_auth_token:install User auth`?
When I did the command and tried to log in by Postman, the following error was occurred.

```
Started POST "/api/auth/sign_in" for 172.24.0.1 at 2019-11-16 07:01:57 +0000
Processing by DeviseTokenAuth::SessionsController#create as */*
  Parameters: {"email"=>"admin@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "session"=>{"email"=>"admin@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
Unpermitted parameters: :password_confirmation, :session
Unpermitted parameters: :password_confirmation, :session
  User Load (1.3ms)  SELECT `users`.* FROM `users` WHERE (BINARY email = 'admin@example.com' AND provider= 'email') ORDER BY `users`.`id` ASC LIMIT 1
Unpermitted parameters: :password_confirmation, :session
Unpermitted parameters: :password_confirmation, :session
   (0.6ms)  BEGIN
  User Update (0.8ms)  UPDATE `users` SET `users`.`tokens` = '{\"Yyo_9HeIa8IWPe4HlWl_KQ\":{\"token\":\"$2a$10$xezZ80NcEPTNGSLtM9hf1OTGwcXrtxG/KCXLncn61OhLjemZVGQW.\",\"expiry\":1576479431},\"7QLXe4cmya6gSgUpyqnhqg\":{\"token\":\"$2a$10$D62DWXQWOXGw7wcWaiAu1.JZkxHBZ3ae/zDvEzFssu6NWLtMnMWbC\",\"expiry\":1576479651},\"Pv2_ppcBK05SmSlTA7QVfA\":{\"token\":\"$2a$10$fRTY3j6wJFTqrBh5dZJZU.iqGwreW3ZdE2CWNjJv9mr6.XSFRNs/O\",\"expiry\":1576479717}}', `users`.`updated_at` = '2019-11-16 07:01:57.655591' WHERE `users`.`id` = 1
   (4.2ms)  COMMIT
Completed 500 Internal Server Error in 192ms (ActiveRecord: 6.9ms | Allocations: 5801)



NoMethodError (undefined method `current_sign_in_at' for #<User:0x000055586157b638>):

activemodel (6.0.1) lib/active_model/attribute_methods.rb:431:in `method_missing'
devise (4.7.1) lib/devise/models/trackable.rb:21:in `update_tracked_fields'
devise (4.7.1) lib/devise/models/trackable.rb:39:in `update_tracked_fields!'
devise (4.7.1) lib/devise/hooks/trackable.rb:9:in `block in <main>'
warden (1.2.8) lib/warden/hooks.rb:15:in `block in _run_callbacks'
warden (1.2.8) lib/warden/hooks.rb:10:in `each'
warden (1.2.8) lib/warden/hooks.rb:10:in `_run_callbacks'
warden (1.2.8) lib/warden/manager.rb:52:in `_run_callbacks'
warden (1.2.8) lib/warden/proxy.rb:191:in `set_user'
devise (4.7.1) lib/devise/controllers/sign_in_out.rb:53:in `sign_in'
devise_token_auth (1.1.3) app/controllers/devise_token_auth/sessions_controller.rb:32:in `create'

・・・
```

After a searching, I understood that  a migration file that was created by `devise_auth_token:install` didn't include columns even commented out code for Trackable.

I've found [a PR that the trackable option was removed](https://github.com/lynndylanhurley/devise_token_auth/pull/1075) from devise by default to support GDPR.
And also I've found [a PR of this repository to remove some trackable options](https://github.com/lynndylanhurley/devise_token_auth/commit/7eeed8695280b83c9e408ac59a1c186f45769c4e) from code.

I thought that some developers were confused by the error and all of them need to search to  avoid it, so Trackable option should be removed from all of generator code.

**Comment by aarona** [comment]
I've encountered this recently also. DTA's migration generator should probably include all of the standard Devise modules supported in Devise's migration file. I didn't need `Trackable` so I just removed it from my `User` model.

**Comment by MichalBryxi** [comment]
I believe that it was already removed from the source code: https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/templates/user.rb.erb, but for whatever reason given patch #1362 did not make it to the build.
I think this would be auto-fixed if current `master` would be released.

**Comment by MaicolBen** [comment]
I released a version a couple of days ago, so this should be fixed
