### ISSUE TITLE
The gem is too big. Please take care of it.

### ISSUE THREAD

**Issue by jerry-tao** [lynndylanhurley/devise_token_auth#136]
The gem of 0.1.31 is 6.1Mb. 

When i look into it  i found the dummy in test with 66Mb log. 

Please take care of it. It shouldn't be there.

**Comment by lynndylanhurley** [comment]
Thx, I'll look into this ASAP.

**Comment by lynndylanhurley** [comment]
The logs should be ignored:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/.gitignore

**Comment by nicolas-besnard** [comment]
They is no 'log' directory on /dummy

**Comment by jerry-tao** [comment]
I'm sorry. I'm talking about 0.1.31. I check the latest you have remove it. So i close the issue.
See this https://rubygems.org/gems/devise_token_auth for details.
```
0.1.32.beta1 - February 3, 2015 (6.25 MB)
0.1.31 - January 28, 2015 (6.12 MB)
0.1.31.beta10 - January 28, 2015 (6.11 MB)
0.1.31.beta9 - January 9, 2015 (5.92 MB)
0.1.31.beta8 - January 7, 2015 (5.65 MB)
```

**Comment by lynndylanhurley** [comment]
It's not checked into git in any version of this gem. The `log` folder isn't even present `v0.1.31`:
https://github.com/lynndylanhurley/devise_token_auth/tree/v0.1.31/test

Rubygems must be including the log file even though it's ignored by git. Thanks for reporting, I'll see what I can do.
