### ISSUE TITLE
How do i authenticate with graphql-ruby?

### ISSUE THREAD

**Issue by yuta17** [lynndylanhurley/devise_token_auth#1360]
I am trying to authenticate with graphql-ruby.
The following is the default graphql controller.

```ruby
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    # I need to get the user
    context = {
      current_user: current_user
    }
    result = SampleSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end
```

I need to get the user for authentication.
Can I get the user using the request header content? (client, access-token, uid)

Another idea is to create a Sessions table.

```ruby
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    # I need to get the user
    Session.find_by(
      client: request.headers['client'],
      access_token: request.headers['access-token'],
      uid: request.headers['uid']
    )&.user
    context = {
      current_user: current_user
    }
    result = SampleSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end
```

Any best practice or other good idea?

**Comment by aarona** [comment]
I would take a look at a new gem that's been in the works for the last few months. It's not fully featured yet but its a GraphQL wrapper around Devise Token Auth. You can check out the project here: https://github.com/graphql-devise/graphql_devise

**Comment by K-Sato1995** [comment]
I believe you can just authenticate the user with `  before_action :authenticate_user!` in your ApplicationController or  GraphqlController and use `current_user` to get the authenticated user Object.

**Comment by yuta17** [comment]
@aarona Thanks!
@K-Sato1995  It does!
When I wrote `before_action :authenticate_user!`, what if access doesn't require authentication?
In this case, may be due to having only one endpoint..

**Comment by aarona** [comment]
@yuta17, I haven't tried this so no guarantee but I think you can put this in your `GraphqlController`:

```ruby
include GraphqlDevise::Concerns::SetUserByToken
```
which will set `current_user` (or `current_user` will be nil if the user isn't authenticated) then you store `current_user` in the GraphQL context object. Inside your resolvers you can access the context like a hash to determine if `current_user` is set or not. Hope that helps.

**Comment by avogel3** [comment]
@yuta17 `before_action :authenticate_user!` tries to set the user by token, then raises a 401 if the current_user is nil. https://github.com/lynndylanhurley/devise_token_auth/blob/72976d8d3a0cd8f24578138f9edb7e7930fb75b2/lib/devise_token_auth/controllers/helpers.rb#L44

If you need “optional” authentication in your graphql controller, just call `current_user`; this method will attempt to set the user by token. It will return nil if the user is not authenticated.
https://github.com/lynndylanhurley/devise_token_auth/blob/72976d8d3a0cd8f24578138f9edb7e7930fb75b2/lib/devise_token_auth/controllers/helpers.rb#L59

**Comment by yuta17** [comment]
Thanks!!
