### ISSUE TITLE
Does DTA support HTTP Only Cookie Refresh tokens along site access tokens?

### ISSUE THREAD

**Issue by aarona** [lynndylanhurley/devise_token_auth#1371]
Also, does it have JWT support? I'd like to have silent refresh support.

**Comment by theblang** [comment]
@aarona As of #1453 you can now use HttpOnly cookies for transferring the token. In #1281 I've also brought up adding the ability to turn off the token transfer via headers entirely for the security aspect.

**Comment by MaicolBen** [comment]
>does it have JWT support? 

It doesn't, feel free to add it. But I'd recommend just going straight to `jwt` and implement auth with that
