### ISSUE TITLE
Change controller inheritance

### ISSUE THREAD

**Issue by TomasAchmedovas** [lynndylanhurley/devise_token_auth#138]
I noticed that by default controllers inherits from ApplicationController. How should I change it to different controller? I really don't want to rewrite all controllers in my app although it's a solution.

**Comment by nicolas-besnard** [comment]
What do you want to achieve ?

**Comment by lynndylanhurley** [comment]
@TomasAchmedovas - The modules in this controller inherit from `DeviseTokenAuth::ApplicationController`.

**Comment by TomasAchmedovas** [comment]
Oh. I created controller with same name and namespace and it seems to work. I though it will not overwrite it. Thanks :)

**Comment by TomasAchmedovas** [comment]
I need to add some code to it. How can i do that?
