### ISSUE TITLE
Can't get omniauth to work (error in redirect_callbacks)

### ISSUE THREAD

**Issue by davidtlee** [lynndylanhurley/devise_token_auth#139]
Hi, I've been trying to set up devise_token_auth and can't figure out what's wrong. I have a simple button for signing in with Google. When I click the button and sign in, I get this error. Does anyone know why?

![image](https://cloud.githubusercontent.com/assets/863081/6094848/892d91f8-aef2-11e4-807f-b0d881f18bfe.png)

Thanks! Also, just as an fyi, I didn't separately install devise (not sure if that's necessary); I just followed the directions from the README. It seems like Devise.mappings is nil, but not sure how I can fix that...

**Comment by lynndylanhurley** [comment]
What do your routes look like?

**Comment by davidtlee** [comment]
This is my rails routes file. Really appreciate your help!

```
Rails.application.routes.draw do

  root 'angular_app#index'

  mount_devise_token_auth_for 'User', at: '/auth'

  namespace :api, defaults: { format: 'json' } do

    # List a user's rooms, create and show a room (including the messages within it)
    resources :rooms, only: [:index, :create, :show] do
      # Create and retrieve a message
      resources :messages, only: [:create], shallow: true do
      end
    end

    # Join and leave a room
    resources :participations, only: [:create, :destroy] do
    end
  end

  get '/omniauth/:provider/callback', to: 'devise_token_auth/omniauth_callbacks#redirect_callbacks'
  get '*path', to: 'angular_app#index'
end
```

**Comment by lynndylanhurley** [comment]
This may be the issue:

~~~ruby
get '/omniauth/:provider/callback', to: 'devise_token_auth/omniauth_callbacks#redirect_callbacks'
~~~

The route needs to be mounted within a [`devise_scope`](http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper:devise_scope), otherwise it won't know which mapping to use.

I would recommend finding a more precise way to do this:

~~~ruby
get '*path', to: 'angular_app#index'
~~~

**Comment by davidtlee** [comment]
Thanks @lynndylanhurley! That does it. I changed to:

`get '*path', to: 'angular_app#index', constraints: { path: /(?:(?!omniauth\/).)*/ }`

to avoid the omniauth callbacks collision and that seems to do it :)
