### ISSUE TITLE
Add some tags to this project?

### ISSUE THREAD

**Issue by aneilbaboo** [lynndylanhurley/devise_token_auth#1399]
Simple request. 

I couldn't remember the name of this project and was searching for "devise jwt". I thought it might be helpful to add some tags: devise jwt rails.

**Comment by MaicolBen** [comment]
DTA doesn't use JWT, but it's good suggestion. However I am not owner of this repo, so I cannot add tags, maybe @lynndylanhurley

**Comment by lynndylanhurley** [comment]
@aneilbaboo I just added the following tags:
`devise`, `rails`, `authentication`, `api`, `oauth`, `omniauth`

Can you guys think of any more relevant tags?

**Comment by MaicolBen** [comment]
No, thank you!
