### ISSUE TITLE
Generator doesn't work correctly with mongoid and/or rails-api

### ISSUE THREAD

**Issue by smarquez1** [lynndylanhurley/devise_token_auth#14]
Hi, I'm using your gem for a rails-api / mongoid project and I had a couple of issues using the generator:

Mongoid: it doesn't add the concern to the model, also it creates a migration (not necessary since it doesn't use activerecord)

Rails-api: it doesn't add the concern to ApplicationController, rails-api uses controllers based on ActionController::API so maybe that's where the issue is

Thanks!

**Comment by andimal** [comment]
@jasonswett: thankyouthankyouthankyou!

ApplicationController << `include DeviseTokenAuth::Concerns::SetUserByToken` for rails-api

**Comment by scanferla** [comment]
+1

ApplicationController << include DeviseTokenAuth::Concerns::SetUserByToken for rails-api

**Comment by booleanbetrayal** [comment]
accepting PRs for this if anyone would like to implement this feature

**Comment by aarongray** [comment]
The rails-api issue (the concern not getting inserted into the application controller) has been fixed on https://github.com/lynndylanhurley/devise_token_auth/pull/350.
