### ISSUE TITLE
Generator is not compatible with Rails 6

### ISSUE THREAD

**Issue by btrewern** [lynndylanhurley/devise_token_auth#1400]
Using Rails 6.0.2.2, devise 4.7.1 and devise_token_auth 1.1.3.

On a new app when I run the generator
`$ rails g devise_token_auth:install User auth`
I get
`File unchanged! The supplied flag value not found!  app/models/user.rb`

It looks as if the generator is hard coded to only look for `class User < ApplicationRecord` if you are using Rails 5.

from lib/generators/devise_token_auth/install_generator.rb line 29 you have:
`active_record_needle = (Rails::VERSION::MAJOR == 5) ? 'ApplicationRecord' : 'ActiveRecord::Base'`

I'm guessing something like:
`active_record_needle = ([5,6].include?(Rails::VERSION::MAJOR)) ? 'ApplicationRecord' : 'ActiveRecord::Base'`
would fix it.  Should I create a pull request or is there more to this?

**Comment by Bdoom** [comment]
It does not work for rails 6, I can confirm

**Comment by Bdoom** [comment]
@btrewern looks like you also can't use it if your routes.rb file also has: devise_for :users you can see it in the issue I made here: #1409
