### ISSUE TITLE
possible to disable the self-registration endpoint?

### ISSUE THREAD

**Issue by breathe** [lynndylanhurley/devise_token_auth#1402]
Hi I would like to disable the self-registration endpoint that devise_token_auth publishes ...

![image](https://user-images.githubusercontent.com/434034/81609051-6eb4b180-9394-11ea-9e4a-55821aa6c8e6.png)

I don't want users to be able to self-register.

I use code like this to mount devise_token auth but don't really understand how it works ...

My multiple goals are:

- ensure that devise is in control where expected for all api's published by the legacy rails app
- ensure devise_token_auth is used for routes in namespace below
- ensure that POST's to the user self-registration endpoint are not possible ...

Is there a way to achieve all these goals at once?

```
  namespace :token_api do
    # token auth routes available at /token_api/auth
    mount_devise_token_auth_for "User", at: "auth", controllers: {
                                          application: "token_api/application",
                                          sessions: "token_api/sessions",
                                        }
```

**Comment by AhmadMohsen46** [comment]
1-Remove registerable from user model to stop registration on the app level
2-As per the discussion in [70](https://github.com/lynndylanhurley/devise_token_auth/issues/70) 
and [docs](https://devise-token-auth.gitbook.io/devise-token-auth/usage/excluding_models) 
you can add 
`skip: [:registration]`
```
    mount_devise_token_auth_for "User", at: "auth", skip: [:registration], controllers: {
                                          application: "token_api/application",
                                          sessions: "token_api/sessions",
                                        }
```

**Comment by breathe** [comment]
Thank you @AhmadMohsen46 !  Works for me!
