### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by iMacTia** [lynndylanhurley/devise_token_auth#1403]
Hello,

I noticed there've been quite some PRs merged since the last release (1.1.3) last year.
I'm currently working on a project and I need to use the master branch in it as the features/fixes I need are not in the latest released version.

Maybe it's about time to cut a new release?

**Comment by MaicolBen** [comment]
yep, soon!

**Comment by MaicolBen** [comment]
Done! it's v1.1.4

**Comment by iMacTia** [comment]
Thanks!
