### ISSUE TITLE
Rails 6.0.3.1 generate error

### ISSUE THREAD

**Issue by Bdoom** [lynndylanhurley/devise_token_auth#1409]
I'm using the latest version of rails: 6.0.3.1, and Ruby 2.7. 

However, when I run:
`rails g devise_token_auth:install User auth`

I get this:

`Running via Spring preloader in process 2341
      create  config/initializers/devise_token_auth.rb
      insert  app/controllers/application_controller.rb
        gsub  config/routes.rb
      create  db/migrate/20200606225526_devise_token_auth_create_users.rb
File unchanged! The supplied flag value not found!  app/models/user.rb`

It looks like it worked fine, but that last line:
`File unchanged! The supplied flag value not found!  app/models/user.rb`

That last line really bothers me, it's in red and it's acting as if it can't find that model, but the model is definitely there.

**Comment by Bdoom** [comment]
Also if I try to run rake db:migrate, this happens:

`rake db:migrate
rake aborted!
ArgumentError: Invalid route name, already in use: 'new_user_session' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
/home/decil/humans_vs_supernaturals/config/routes.rb:3:in `block in <main>'
/home/decil/humans_vs_supernaturals/config/routes.rb:1:in `<main>'
/home/decil/humans_vs_supernaturals/config/environment.rb:5:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)`

**Comment by Bdoom** [comment]
@MaicolBen hey have you seen these issues? Also the other issue the guy submitted?

**Comment by Bdoom** [comment]
As I dig, I find more errors, with each one I resolve, I find more. First, when making an http request, I had the InvalidToken  (csrf thing), this was easy to resolve, not really a bug, I just disable it for json requests. Then we have another issue... So I added

`include DeviseTokenAuth::Concerns::ActiveRecordSupport
  include DeviseTokenAuth::Concerns::User`

I added those to my user.rb model. Which fixed some issues. Now I got this when making a request: 

`PG::UndefinedColumn: ERROR: column users.provider does not exist LINE 1: ...rs".* FROM "users" WHERE "users"."email" = $1 AND "users"."p... ^
`

However, there is a column called 'provider' as defined when creating the table:
`t.string :provider, null: false, default: "email"`


However, when I do:
`irb(main):002:0> User.column_names
=> ["id", "email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "created_at", "updated_at"]
irb(main):003:0> `

Inside of the rails console it comes up with the column being named "email." I need it to work side by side with the built in devise stuff. I want people to be able to login using devise views, but also be able to login using the auth token that this gem is supposed to provide. 

Am I doing something wrong? @MaicolBen

**Comment by Bdoom** [comment]
How is this supposed to work side by side with devise if you need both a "provider" column, for devise_token_auth, and a 'email' column for regular devise...?

**Comment by Bdoom** [comment]
ok well, after about 3 hours of fiddling around with this, and modifying some of the devise base settings I got everything to work. 

https://i.imgur.com/MqjIzcq.png 

you can see the headers in postman, they are returning a Bearer access-token. :)

**Comment by Bdoom** [comment]
![image](https://user-images.githubusercontent.com/1284431/84330143-9a25ea00-ab54-11ea-8e4f-df29d5debd22.png)
Now for some reason, every time I sign in it just creates new tokens...

**Comment by dchersey** [comment]
@Bdoom did you ever get this to work? I'm walking the same path and seriously considering using devise-jwt for now even though I like the functionality of this gem better.

**Comment by Bdoom** [comment]
> @Bdoom did you ever get this to work? I'm walking the same path and seriously considering using devise-jwt for now even though I like the functionality of this gem better.

Yep! I got it working. What part were you struggling with?

**Comment by dchersey** [comment]
I got to where you got to in the OP, and was planning on solving the remaining problems but thought maybe you got stuck with your last post (always creating new tokens).   Was that your last problem, and what was your solution?

**Comment by Bdoom** [comment]
> I got to where you got to in the OP, and was planning on solving the remaining problems but thought maybe you got stuck with your last post (always creating new tokens). Was that your last problem, and what was your solution?

```
DeviseTokenAuth.setup do |config|
  # By default the authorization headers will change after each request. The
  # client is responsible for keeping track of the changing tokens. Change
  # this to false to prevent the Authorization header from changing after
  # each request.
  config.change_headers_on_each_request = false
```

Inside of your initializer you have to set this to true if you want it to change headers on each request. This means, if you first sign in with a token, it will give you the token, but then a second time if you do another request with that token, it will send you a new token in the header file. If this is set to true, it will simply keep making new tokens when you login, but if it's false it won't make new ones, and will just send you new ones instead... Both are not very good solutions in my opinion.

**Comment by MaicolBen** [comment]
` config.change_headers_on_each_request = false`

This is ok, the true option causes more headaches than the security feature that adds. 

> Is there any helper methods for checking if an "incoming auth token" for a "user" is valid?

You can use the `/validate_token` endpoint for the frontend or `user.valid_token?(token)` internally


I'm trying to catch with this thread, @Bdoom is there any but that you found with rails 6.0.3.1? Because as my help is limited, I cannot help answering doubts all the time.

**Comment by Bdoom** [comment]
> 
> 
> ` config.change_headers_on_each_request = false`
> 
> This is ok, the true option causes more headaches than the security feature that adds.
> 
> > Is there any helper methods for checking if an "incoming auth token" for a "user" is valid?
> 
> You can use the `/validate_token` endpoint for the frontend or `user.valid_token?(token)` internally
> 
> I'm trying to catch with this thread, @Bdoom is there any but that you found with rails 6.0.3.1? Because as my help is limited, I cannot help answering doubts all the time.

I got it to work after a long period of time. However, the problem I noticed is that tokens don't actually automatically delete from the User.first.tokens object. The tokens are supposed to expire. Is there a way we could make it auto-delete tokens after a time period? Also, /auth/sign_in returns the token, but you are saying /auth/validate_token can do the same? What does /auth/validate_token return in the request headers and body?

**Comment by MaicolBen** [comment]
> Is there a way we could make it auto-delete tokens after a time period?

You can change the token lifespan, by default is 2 weeks (https://devise-token-auth.gitbook.io/devise-token-auth/config/initialization)

> Also, /auth/sign_in returns the token, but you are saying /auth/validate_token can do the same?

One stores the token and the other just check if it's valid

>What does /auth/validate_token return in the request headers and body?

You can check the API in https://devise-token-auth.gitbook.io/devise-token-auth/usage


I'm going to close this as your issues have nothing to do with rails 6

**Comment by Bdoom** [comment]
> 
> 
> > Is there a way we could make it auto-delete tokens after a time period?
> 
> You can change the token lifespan, by default is 2 weeks (https://devise-token-auth.gitbook.io/devise-token-auth/config/initialization)
> 
> > Also, /auth/sign_in returns the token, but you are saying /auth/validate_token can do the same?
> 
> One stores the token and the other just check if it's valid
> 
> > What does /auth/validate_token return in the request headers and body?
> 
> You can check the API in https://devise-token-auth.gitbook.io/devise-token-auth/usage
> 
> I'm going to close this as your issues have nothing to do with rails 6

Yeah but the token timeout for 2 weeeks does not work. It does not delete the key from the database.
