### ISSUE TITLE
Getting 401 unauthorized on login attempt

### ISSUE THREAD

**Issue by rodrigoalvesvieira** [lynndylanhurley/devise_token_auth#142]
Hi everyone,

I setup a new Rails app with the dta gem and the ng-token-auth module and in my login form, when I try to login I get this:

```
Started POST "/api/auth/sign_in" for ::1 at 2015-02-09 08:46:26 -0300
Processing by DeviseTokenAuth::SessionsController#create as HTML
  Parameters: {"email"=>"rodrigovieira1994@gmail.com", "password"=>"[FILTERED]", "session"=>{"email"=>"rodrigovieira1994@gmail.com", "password"=>"[FILTERED]"}}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE (uid = 'rodrigovieira1994@gmail.com' AND provider='email')  ORDER BY "users"."id" ASC LIMIT 1
Completed 401 Unauthorized in 96ms (Views: 0.2ms | ActiveRecord: 0.9ms)
```

My `application_controller.rb` looks like this:

```ruby
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_filter :set_csrf_cookie_for_ng
  before_filter :clean_parameters

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  rescue_from ActiveRecord::RecordNotFound do
    respond_to do |type|
      type.all  { render nothing: true, status: 404 }
    end
  end

protected

  def clean_parameters
    params.delete :session
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :session
    devise_parameter_sanitizer.for(:sign_up) << :daily_calories
    devise_parameter_sanitizer.for(:account_update) << :daily_calories
  end

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end
```
I performed the very same query on the console and a object does exist:

![screen shot 2015-02-09 at 8 49 08 am](https://cloud.githubusercontent.com/assets/134733/6105682/8a4d1634-b038-11e4-82ba-7d32c85732d7.png)

Do you guys know what could be wrong? I put the `clean_parameters` method above so Rails would stop telling me I was trying to push a bad parameter (`session).

**Comment by lynndylanhurley** [comment]
Have you tried using `protect_from_forgery with: :null_session`? I see that you're using `:exception` now.

**Comment by rodrigoalvesvieira** [comment]
Hey, I did it and now both the registration and login are working, at least on the Angular.js side.

However, Rails can't identify the user as logged in so `current_user` evaluates to nil. Do you know what may be causing this behavior?

**Comment by jasonswett** [comment]
Hmm, I'm having this same issue (at least the same symptom) and I can't try the `protect_from_forgery` solution because I'm using Rails::API which I understand doesn't have `protect_from_forgery`. Any troubleshooting suggestions would be greatly appreciated.

**Comment by jasonswett** [comment]
Okay, nevermind. I was getting a 401 because I had my test user's `provider` set to "asdf" but it needed to be set to "email".

**Comment by gblakeman** [comment]
I'm also getting the same symptom. I'm trying to authenticate via API:

![screenshot on 2015-02-10 at 18-06-21](https://cloud.githubusercontent.com/assets/867428/6139988/961615d4-b14f-11e4-8909-7d77870a09bd.png)

```
Started POST "/api/v1/auth/sign_in" for 127.0.0.1 at 2015-02-10 18:05:49 -0700
Processing by DeviseTokenAuth::SessionsController#create as */*
  Parameters: {"email"=>"test@test.com", "password"=>"[FILTERED]"}
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)
```

I'm copying/pasting the credentials right from my seeds file.

Anyone have any ideas?

**Comment by nicolas-besnard** [comment]
You should try to set the content-type header to be json

**Comment by gblakeman** [comment]
@nicolas-besnard I don't think that should matter, but I tried it anyway. Same error. Results in an unpermitted _json parameter blob.

![screenshot on 2015-02-10 at 18_36_03](https://cloud.githubusercontent.com/assets/867428/6140371/012615be-b154-11e4-8651-a20104d1891e.png)

**Comment by nicolas-besnard** [comment]
The _json came from Postman. Do the request with curl in a terminal

**Comment by nicolas-besnard** [comment]
```http
curl -XPOST -H 'Content-Type: application/json' http://localhost:3000/api/v1/auth/sign_in -d '{"email": "test@test.com", "password": "12345678" }'
```

**Comment by lynndylanhurley** [comment]
This comes up a lot - we should probably include instructions for use with `curl`, postman, etc. in the README.

**Comment by jasonswett** [comment]
I can imagine a "Troubleshooting 401 Errors" page being helpful. It seems that there are multiple potential causes, some of them non-obvious.

**Comment by nicolas-besnard** [comment]
Well, you don't send json, so you have an error. Next you send an Array, so you have an error.

**Comment by gblakeman** [comment]
I really appreciate the help. Unfortunately I still get the same result via curl (tried both with webrick and POW):

![screenshot on 2015-02-11 at 11_56_57](https://cloud.githubusercontent.com/assets/867428/6153915/21fa9878-b1e5-11e4-9f7d-11cd296c1fb1.png)

**Comment by lynndylanhurley** [comment]
@gblakeman - 

1. What do your routes look like?
1. Is `provider` set to `email` on the user that you're trying to authenticate?
1. Has the user's account been confirmed? In other words, what is the value of `confirmed_at` on your user model? 
1. Are you sure that you're using the correct credentials?

**Comment by gblakeman** [comment]
@lynndylanhurley Here is my current setup:

1. Routes
(I've also tried putting mount_devise_token_auth_for within the :api and :v1 namespaces)
```
  mount_devise_token_auth_for 'User', at: '/api/v1/auth'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update, :destroy]
    end
  end
```

2-3 Provider is set to email and confirmed_at is timestamped:

![screenshot on 2015-02-11 at 12_22_39](https://cloud.githubusercontent.com/assets/867428/6154427/e03c66a6-b1e8-11e4-91cd-59e0bdd699f8.png)

4. I’ve certainly done dumber things before, but right now I’m copying/pasting directly from my seeds file into the curl request:

Seeds:
```
set_time = (Time.zone.now + 1.minute)
users = User.create!([
  {
    role_id: Role.first.id,
    first_name: "Test",
    last_name: "Guy",
    username: "testguy",
    email: "test@test.com",
    password: "12345678",
    password_confirmation: "12345678",
    confirmed_at: set_time,
    updated_at: set_time
  }
])
```

Curl:
```
curl -XPOST -H 'Content-Type: application/json' http://everydb.dev/api/v1/auth/sign_in -d '{"email": "test@test.com", "password": "12345678" }'
```

Thanks for taking a look!

**Comment by nicolas-besnard** [comment]
You seed is not valid. You didn't specify an uid nor a provider.

**Comment by gblakeman** [comment]
@nicolas-besnard In my user model:

```
before_validation :set_provider

private

def set_provider
  self.provider = "email"
end
```

As far as I can tell, the devise_auth_token concern sets the UID to the email address when the provider is set to email. I tried explicitly providing a different UID and it wouldn’t work.

**Comment by lynndylanhurley** [comment]
@nicolas-besnard - the `uid` will be generated automatically when `provider` is set to `email`.

@gblakeman - thanks for the detailed report!

Just to eliminate any uncertainty, can you try mounting the dta routes exactly as they appear in the README?

Like this:

~~~ruby
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end
~~~

The namespace stuff has been tricky to implement, but I'm 100% certain that this format works.

**Comment by gblakeman** [comment]
@lynndylanhurley Whew, got it working, but it wasn’t route related. My apologies for the wild goose chase, but this was my own idiocy. I set up an overly-aggressive `before_filter :clean_parameters` trying different things yesterday (I’d originally been getting an unpermitted parameters error before I upgraded to the current beta and I think I was trying to compensate for that) and had forgotten about it. Now things are working as they should.

It might be helpful to know that the route below is working just fine in the beta5, so perhaps you’ve gotten past those issues:

```rails
namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :users, only: [:index, :show, :create, :update, :destroy]
  end
end
```

Thanks for the help!

**Comment by lynndylanhurley** [comment]
@gblakeman - no problem! This stuff is tricky. I'm glad to hear that you got it all sorted out :smiley:

**Comment by olore** [comment]
Thiis discussion was very helpful. Thank you.

**Comment by acmel067** [comment]
hi 

`namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :users, only: [:index, :show, :create, :update, :destroy]
  end
end`

**Comment by acmel067** [comment]
```
namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :users, only: [:index, :show, :create, :update, :destroy]
  end
end
```

**Comment by Babbz75** [comment]
@acmel067 if you haven't found the answer already it's because you need 
  devise_for :user
outside of 
namespace :api, defaults: {format: 'json'} do

**Comment by mamadoutourelacapitale** [comment]
I'm having a  401, when I try to send a password reset by sending a post on /auth/password, and in the payload I have an email and redirect_url. What could cause this ? When requesting a password change, we should not get an 401

**Comment by ifasanelli** [comment]
> hi @gblakeman
> 
> with the route below that you mentioned, have you encountered an error like this:
> 
> ```
> "#<NoMethodError: undefined method `authenticate_user!' for #<Api::V1::MessagesController:0x007fc36f487468>\nDid you mean?  authenticate_api_v1_user!>"
> ```
> 
> ```ruby
> namespace :api, defaults: {format: 'json'} do
>   namespace :v1 do
>     mount_devise_token_auth_for 'User', at: 'auth'
>     resources :users, only: [:index, :show, :create, :update, :destroy]
>   end
> end
> ```

Use `before_action :authenticate_api_v1_user!` as suggested
