### ISSUE TITLE
Trying to integrate with devise-multi_email

### ISSUE THREAD

**Issue by mgmodell** [lynndylanhurley/devise_token_auth#1421]
devise_token_auth seems to ignore the emails provided by devise-multi_email. As you can see, it seems to error out in sessions_controller#create when it doesn't find the email field. In this case, I could probably hack the `resource_finder` concern and hardcode the emails table in, but I'd like to do it the right way - except I don't know either package well enough to do so and I'm not sure if that'd be sufficient anyway.

If you can guide me a bit, I can probably put together a PR for this. Am I on the right track? Where should I be expecting to make these changes?

* **Version**: 
- devise_token_auth: 1.1.4
- devise: 4.7.2
- devise-multi_email: 3.0.0

* **Request and response headers**: 
Request URL: http://localhost:3000/api/v1/auth/sign_in
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 1477
Content-Type: text/html; charset=UTF-8
X-Request-Id: 8c652be9-3dce-44dc-a996-189979a94f0c
X-Runtime: 0.530246
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ko;q=0.8,he;q=0.7
Connection: keep-alive
Content-Length: 27
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: 
_session_id=834a0a4e9a7243567f916f63dba41b90
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
x-kopernio-plugin-version: 0.12.18
X-Requested-With: XMLHttpRequest
email: dfgs
password: sdgfsfd

* **Rails Stacktrace**:
Started POST "/api/v1/auth/sign_in" for ::1 at 2020-07-20 00:25:12 -0400
Processing by DeviseTokenAuth::SessionsController#create as */*
  Parameters: {"email"=>"dfgs", "password"=>"[FILTERED]"}
  User Load (0.8ms)  SELECT `users`.* FROM `users` WHERE (BINARY email = 'dfgs' AND provider= 'email') ORDER BY `users`.`id` ASC LIMIT 1
Completed 500 Internal Server Error in 10ms (ActiveRecord: 6.1ms | Allocations: 3496)

  
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'email' in 'where clause'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:131:in `_query'
mysql2 (0.5.3) lib/mysql2/client.rb:131:in `block in query'
mysql2 (0.5.3) lib/mysql2/client.rb:130:in `handle_interrupt'
mysql2 (0.5.3) lib/mysql2/client.rb:130:in `query'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block (2 levels) in execute'
activesupport (6.0.3.2) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (6.0.3.2) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (6.0.3.2) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:200:in `block in execute'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:199:in `execute'
activerecord (6.0.3.2) lib/active_record/connection_adapters/mysql/database_statements.rb:41:in `execute'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:210:in `execute_and_free'
activerecord (6.0.3.2) lib/active_record/connection_adapters/mysql/database_statements.rb:46:in `exec_query'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:489:in `select'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `block in select_all'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/query_cache.rb:122:in `block in cache_sql'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `select_all'
activerecord (6.0.3.2) lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
activerecord (6.0.3.2) lib/active_record/querying.rb:46:in `find_by_sql'
bullet (6.1.0) lib/bullet/active_record60.rb:19:in `find_by_sql'
activerecord (6.0.3.2) lib/active_record/relation.rb:821:in `block in exec_queries'
activerecord (6.0.3.2) lib/active_record/relation.rb:839:in `skip_query_cache_if_necessary'
activerecord (6.0.3.2) lib/active_record/relation.rb:808:in `exec_queries'
activerecord (6.0.3.2) lib/active_record/relation.rb:626:in `load'
activerecord (6.0.3.2) lib/active_record/relation.rb:250:in `records'
bullet (6.1.0) lib/bullet/active_record60.rb:46:in `records'
activerecord (6.0.3.2) lib/active_record/relation.rb:245:in `to_ary'
activerecord (6.0.3.2) lib/active_record/relation/finder_methods.rb:527:in `find_nth_with_limit'
activerecord (6.0.3.2) lib/active_record/relation/finder_methods.rb:512:in `find_nth'
activerecord (6.0.3.2) lib/active_record/relation/finder_methods.rb:120:in `first'
/Users/micah/dev/devise_token_auth/app/controllers/devise_token_auth/concerns/resource_finder.rb:27:in `find_resource'
/Users/micah/dev/devise_token_auth/app/controllers/devise_token_auth/sessions_controller.rb:24:in `create'
actionpack (6.0.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.2) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
react-rails (2.6.1) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
bullet (6.1.0) lib/bullet/rack.rb:15:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

* **Environmental Info**: 

I am attempting to convert an existing application that successfully uses Devise + OmniAuth (Google OAuth2) + [devise-multi_email](https://github.com/allenwq/devise-multi_email)
I'm using the `config.enable_standard_devise_support = true` option, but I'd be fine with jettisoning this and going token-only to render it an API-only app.

The OmniAuth implementation of [Google OAuth is pretty standard](https://github.com/zquestz/omniauth-google-oauth2).

  * **Custom Frontend**:

I'm working to implement [jToker](https://github.com/lynndylanhurley/j-toker). It seems to be functioning mostly OK but I cannot authenticate.

**Comment by MaicolBen** [comment]
>  I could probably hack the resource_finder concern and hardcode the emails table in,

Yeah, you're in the right track, probably check if that gem is present so you can do a SQL query with multiple emails. Any PRs are welcome.

**Comment by mgmodell** [comment]
Thanks! I've got that in there and Guard works, but now I'm trying to track down a create error where it is throwing:

`NoMethodError (undefined method 'case_sensitive?' for nil:NilClass)`

I've been banging my head against this for 2 months and I think it's getting to the email attribute and trying to save it (or add it to the transaction) but since `devise-multi_email` has replaced that attribute with a method, it's getting a `nil`. However, I'm having a heck of a time trying to find _where_ this is happening. Any pointers/guidance would be greatly appreciated...

**Comment by mgmodell** [comment]
@MaicolBen , I've gone ahead and submitted #1455 for this and I'm really eager to hear back from you. No new tests because I wasn't sure how. My test environment has become unstable (lots of machines moving around) and I don't want to hold off until I can dig in and figure out my issues. Hopefully you can run the existing tests and merge into the current code base.

**Comment by mgmodell** [comment]
@MaicolBen, #1469 offers much cleaner code, but I still need help with tests. I have not used minitest or guard before and I don't know how to set up the environment to dynamically load/unload the [devise-multi_email](https://github.com/allenwq/devise-multi_email) gem and its initializers fully to prep for a run.

Can you help?

**Comment by MaicolBen** [comment]
I saw the PR, we shouldn't have that dependency unless a big amount of people are using it. Sorry but I changed my mind and I think the code shouldn't be in the codebase, probable we should implement in house instead of having another dependency. Anyway, I hope you made it work for you and it might be usuful for future people (if there are a lot of 👍 , we can revisit adding this to the code).

**Comment by mgmodell** [comment]
Understood. I'll maybe package up my fork that does include multi-email.

Thanks anyway!
