### ISSUE TITLE
Wrong tokens after server restarts?

### ISSUE THREAD

**Issue by newfylox** [lynndylanhurley/devise_token_auth#1430]
version: 0.1.43

Hi guys, I have a weird issue.

When I deploy my API on the server (staging and production) with Capistrano, it restarts the server with Puma. The tokens stay the sames, but it invalidates the users for a weird reason. When people refresh the page, it calls "validate_token" with the good credentials (uid, token, client) but the server returns 401.

It occurs when I restart my server. Do you know why?

Thanks

**Comment by MaicolBen** [comment]
Did you try with the last version?

**Comment by newfylox** [comment]
I guess I was wrong. I forgot some of my users may exceeded their max number of open sessions. My bad! I have some users that must have shared their passwords to others!

thanks though!
