### ISSUE TITLE
Is there a way to configure apiUrl for both dev and prod?

### ISSUE THREAD

**Issue by davidtlee** [lynndylanhurley/devise_token_auth#144]
In order for me to get apiUrl to work on dev, I currently have to set it as:

`$authProvider.configure({ apiUrl: 'http://localhost:3000/' });`

I would like to set it as:

`$authProvider.configure({ apiUrl: '/' });`

so that it would be independent of dev and prod. Unfortunately, this doesn't seem to work. Does anyone have suggestions for how to do that? Thanks!

Currently I have my rails route as follows:

```
Rails.application.routes.draw do

  root 'angular_app#index'
  mount_devise_token_auth_for 'User', at: 'auth'

  namespace :api, defaults: { format: 'json' } do

    # List a user's rooms, create and show a room (including the messages within it)
    resources :rooms, only: [:index, :create, :show] do
      # Create and retrieve a message
      resources :messages, only: [:create], shallow: true do
      end
    end

    # Join and leave a room
    resources :participations, only: [:create, :destroy] do
    end
  end

  get '*path', to: 'angular_app#index', constraints: { path: /(?:(?!omniauth\/).)*/ }
end
```

**Comment by lynndylanhurley** [comment]
What is the issue when using this setting?

~~~javascript
$authProvider.configure({ apiUrl: '/' });
~~~

**Comment by davidtlee** [comment]
When I use that setting, clicking on a simple "Sign in with Google" button goes to

 `http://auth/google_oauth2?auth_origin_url=http%3A%2F%2Flocalhost%3A3000%2Flogin`

In other words, it doesn't seem to know to append urls to the root...

**Comment by lynndylanhurley** [comment]
@davidtlee - did you get this sorted out?

**Comment by davidtlee** [comment]
nope, whoops, I must've accidentally closed it.

**Comment by davidtlee** [comment]
So I didn't fix it, but now the problem is no longer relevant since I just decided to change to:

`$authProvider.configure({ apiUrl: 'api' });`

and then change the rails route to:

`mount_devise_token_auth_for 'User', at: 'api/auth'`
