### ISSUE TITLE
Update dependency to support Rails 6.1/6.1.0.rc1

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [lynndylanhurley/devise_token_auth#1443]
Any change you can update the rails dependency. Rails 6.1 comes with a bunch of active storage updates that many in the community are asking for.

Thanks!

**Comment by muyiwaoyeniyi** [comment]
Thanks!

**Comment by csalvato** [comment]
Are we planning to create a `1.1.5` version so that we don't need to reference the `master` of this branch?  I'm trying to plan our upgrade to Rails 6.1, so thank you in advance!
