### ISSUE TITLE
Twitter OAuth always throughs CookieOverflow

### ISSUE THREAD

**Issue by mkhatib** [lynndylanhurley/devise_token_auth#145]
I've tried to fix this up and a lot of what I read online suggests to either not use cookies for the session storage or to remove some attributes from the auth response from twitter which has extra parameter which seems to be too big to store.

**Comment by lynndylanhurley** [comment]
Thanks @mkhatib - I'll look into this ASAP.

**Comment by tbloncar** [comment]
I went with the suggestion of removing the `extra` section from the Twitter auth response, and that seemed to fix this. In `DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks`:

    session['dta.omniauth.auth'] = request.env['omniauth.auth'].except('extra')

Maybe there's a more future-proof solution, but this did the trick.

**Comment by lynndylanhurley** [comment]
@tbloncar - if you send me a PR with that fix I'll merge it right away.

**Comment by tbloncar** [comment]
@lynndylanhurley Will do this evening. Thanks.

**Comment by mkhatib** [comment]
:+1: :dancer: thank you guys for getting this in! Will try it as soon as possible and report back!

**Comment by lynndylanhurley** [comment]
Thanks @mkhatib! I'll cut a release later tonight, and I'll post a note here when it's up.
