### ISSUE TITLE
Tokens field on database

### ISSUE THREAD

**Issue by williamweckl** [lynndylanhurley/devise_token_auth#146]
I don´t have much knowledge in database performance and patterns, but I have doubts about the field tokens on user table. Should not be better to put tokens on a separate table, each token on one row?

Don´t know if this is the right place to write this, so, sorry if there isnt.

**Comment by lynndylanhurley** [comment]
@williamweckl - what would be the advantage of using a separate table?

**Comment by williamweckl** [comment]
@lynndylanhurley - don´t know. I usually do so, don´t know why but for me a text field with all tokens sounds wrong. But, as I sayed, don´t know much about database patterns and which one is more performative. That´s why I brought this discussion.

**Comment by lynndylanhurley** [comment]
I haven't performed a detailed analysis, but I can't imagine that querying against another table would improve performance. 

The `tokens` column is a serialized JSON object. Expired tokens are removed with each save, so it shouldn't be able to grow very large. I don't think performance will be an issue, but I'll re-consider the current implementation if I see evidence to the contrary.
