### ISSUE TITLE
Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated

### ISSUE THREAD

**Issue by shrik450** [lynndylanhurley/devise_token_auth#1474]
When posting issues, please include the following information to speed up the troubleshooting process:

* **Version**: 1.1.5 (Reproduced with github master as well)
* **Request and response headers**: N/A
* **Rails Stacktrace**: 
  ```
   DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use  Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from <top (required)> at ...)
  ```
* **Environmental Info**: N/A - unrelated to app.

See the change in the changelog: https://github.com/heartcombo/devise/blob/master/CHANGELOG.md

The issue is in https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/blacklist.rb.

**Comment by shrik450** [comment]
PR #1473 is on this, but seems to require a devise update.

**Comment by MaicolBen** [comment]
This was merged to master

**Comment by regedarek** [comment]
temporary solution: ```gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth', branch: 'master'```

**Comment by shqear93** [comment]
isn't fixed yet?

**Comment by urbanrotnik** [comment]
Release for this?
