### ISSUE TITLE
Can we have a new version released?

### ISSUE THREAD

**Issue by mhenrixon** [lynndylanhurley/devise_token_auth#1483]
When posting issues, please include the following information to speed up the troubleshooting process:

I am currently on version `1.1.5` and while everything works my console gets spammed with:

```console
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead) (called from call at /usr/src/app/app/controllers/api/v1/sessions_controller.rb:73)
```

There is also the issue with:

```console
DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from <main> at /usr/src/app/config/application.rb:20)
```

Those have been fixed on master so it would be great to have a new release with these fixes.

**Comment by garrettd714** [comment]
downgrading devise dependency to `4.7.3` from `4.8.0` in Gemfile.lock (& bundle install) silences the second warning

**Comment by mhenrixon** [comment]
@garrettd714 but then you crash when trying to write to the database replica when checking the session of the logged in user.

**Comment by garrettd714** [comment]
@mhenrixon Ah, different setups in play then. I was not getting the first WARNING, just the second, and bumping down 1 release of devise works for me, satisfies dependencies and silences the 2nd WARNING from devise 4.8. Cheers
```
ruby '2.7.3'
rails '6.0.3.7'
devise (4.7.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
devise_invitable (2.0.5)
      actionmailer (>= 5.0)
      devise (>= 4.6)
devise_token_auth (1.1.5)
      bcrypt (~> 3.0)
      devise (> 3.5.2, < 5)
      rails (>= 4.2.0, < 6.2)
```

**Comment by rafahuaman** [comment]
+1 there seem to have been a few fixes since the last version 
I am getting an error for which I need  #1447

**Comment by openscript** [comment]
I also would love to have a new release so we can remove some patches

**Comment by kenoga** [comment]
When new version will be published? 
I would like to use `cookie_enabled` configurations. 
That function is not on the latest version, but on the [doc](https://devise-token-auth.gitbook.io/devise-token-auth/config/initialization).
I understand the function is avaialble when we use gem from master branch, but the new version release is desirable.

**Comment by LandonSchropp** [comment]
Bump @lynndylanhurley

**Comment by mhenrixon** [comment]
Anyone from @graveflex here that can notify @lynndylanhurley?

**Comment by MaicolBen** [comment]
Done! It's 1.2.0

**Comment by TonyArra** [comment]
@MaicolBen am I missing something? I see that you bumped the version number on master, but there's no tag or release.

**Comment by openscript** [comment]
@TonyArra It was released to https://rubygems.org/gems/devise_token_auth, but you are right, no tag or release on Github.
