### ISSUE TITLE
Omniauth: New user or not ?

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#151]
For my project, I need to know if my user is a new user or not. To do it, I have to override the whole controller and add to the response :

``` ruby
@is_new_user = false
@is_new_user = true if @resource.id.nil?

render json: { user: @resource.as_json.merge(is_new_user: @is_new_user) }
```

Do you think we should include this in the gem by default ?

Moreover, I think we should add a features to get more information from Omniauth connection such as : gender, first_name etc ...

**Comment by TomasAchmedovas** [comment]
+1

**Comment by TomasAchmedovas** [comment]
+1 Totally agree with both points

**Comment by lynndylanhurley** [comment]
> Do you think we should include this in the gem by default?

This could be useful, and I can't see it causing any problems. LGTM.

> I think we should add a features to get more information from Omniauth connection such as : gender, first_name etc ...

I agree. The challenge will be to find the most flexible, least invasive implementation. I'll look into this ASAP.

**Comment by nicolas-besnard** [comment]
Just realise that this is can't be done because the Omniauth use a strange HTML render.
Actually, the current version of the Omniauth Callback Controller can't be used on a pure API. Had to write my own controller to handle this . Maybe there's some change to do on this controller.

**Comment by lynndylanhurley** [comment]
@nicolas-besnard - I think this will still work. The HTML page is used to send the user's auth info via `postMessage`. We can send anything we want from there.

**Comment by nicolas-besnard** [comment]
Yes, I know, but if you is this gem for an iOS application, you can't use this method.

**Comment by zachfeldman** [comment]
Hi there @nicolas-besnard  ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
