### ISSUE TITLE
Got "ActionDispatch::Request::Session::DisabledSessionError"

### ISSUE THREAD

**Issue by EvitanRelta** [lynndylanhurley/devise_token_auth#1521]
I'm new to Ruby on Rails and have no clue what im doing but
I managed to sign in via email, and got the `access-token` `client` `expiry` `uid` headers.
But when i try to GET my data with those headers, it gave me 

```
"status": 500,
"error": "Internal Server Error",
"exception": "#<ActionDispatch::Request::Session::DisabledSessionError: Your application has sessions disabled. To write to the session you must first configure a session store>",
```

What do i do?

**Comment by EvitanRelta** [comment]
nevermind, it seems to be a devise bug for Rails 7

https://github.com/heartcombo/devise/issues/5443

**Comment by arpu** [comment]
do you found a solution for this?

**Comment by EvitanRelta** [comment]
> do you found a solution for this?

Oh i just downgraded to Rails 6.1 and it worked :D

**Comment by arpu** [comment]
ok, this is the last option for me :>

**Comment by Vector54** [comment]
Helloo, got into the same problem here, and [this comment](https://github.com/waiting-for-dev/devise-jwt/issues/235#issuecomment-1116864740) solved it for me without the downgrading. Just making it more visible for passersby.
