### ISSUE TITLE
Trouble accessing provider auth key and secret

### ISSUE THREAD

**Issue by danimalkelley** [lynndylanhurley/devise_token_auth#153]
Hi,

I'm having trouble accessing my user's twitter key and secret on my Rails backend server using this gem.  Everything seems to be working fine with the oauth, I just can't access the twitter key and secret on the backend to make a request on behalf of the user to Twitter.

I'm using your gem along with the ng-token-auth AngularJS module in my application.  My app is decoupled with a Rails backend server and Angular on the front end (currently served with Python SimpleHTTPServer).

Any help/advice would be greatly appreciated.

Thanks,
Daniel

**Comment by lynndylanhurley** [comment]
@danimalkelley - I don't think we're saving the provider credentials. This might be an easy fix tho - I'll look into it ASAP.

**Comment by zachfeldman** [comment]
Hi there @danimalkelley   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
