### ISSUE TITLE
Rails 7 support?

### ISSUE THREAD

**Issue by jeygeethan** [lynndylanhurley/devise_token_auth#1533]
I am currently using the gem directly from github for rails 7. Any idea (or help needed) to get the rails 7 version out soon?

**Comment by kennym** [comment]
bumping this one, would also love to see that.

**Comment by hernanat** [comment]
bump

**Comment by kpheasey** [comment]
bump

**Comment by szpasztor** [comment]
bump

**Comment by ismaelisuani** [comment]
bump

**Comment by chileap** [comment]
bump

**Comment by urbanrotnik** [comment]
bump

**Comment by CerteXCm** [comment]
bump

**Comment by juanmamaffei** [comment]
bump

**Comment by sujh** [comment]
bump

**Comment by MaicolBen** [comment]
is there anything else besides #1517 ? any help is welcome!

**Comment by alec-c4** [comment]
any update?

**Comment by remy727** [comment]
Until new release will be pushed to RubyGems you can point the gem to GitHub `master` branch:
```
gem "devise_token_auth", github: "lynndylanhurley/devise_token_auth"
```

**Comment by MaicolBen** [comment]
v1.2.1 was released!
