### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by samh0lmes** [lynndylanhurley/devise_token_auth#1552]
I see the gem supports rails 7, but the version hasn't been bumped, so I'm forced to pull directly from github. Could we get a published version with rails 7 support, so that I don't need to pull directly from github?

This is already posing problems as a bug was introduced to the code `ja.yml`.

Can this PR https://github.com/lynndylanhurley/devise_token_auth/pull/1547 also be merged in to fix this bug?

Thank you!

**Comment by haffla** [comment]
Duplicate https://github.com/lynndylanhurley/devise_token_auth/issues/1533

@samh0lmes we are all waiting for it. You can pin the version you pull from Github to a specific commit. I think that's what everybody's doing.

**Comment by samh0lmes** [comment]
ok cool - thank you!
