### ISSUE TITLE
list with http response codes

### ISSUE THREAD

**Issue by AlanHassen** [lynndylanhurley/devise_token_auth#157]
Hi folks,
I wanna use this gem with an android client. Therefore i need a list of the http response codes for each endpoint. Is it somewhere available?
greez

**Comment by nicolas-besnard** [comment]
In the source code :)

**Comment by lynndylanhurley** [comment]
@AlanHassen - we've been talking about formalizing this list, but we haven't gotten around to it yet. 

If you have the time to create a list, you can post it here and I'll include it in the README. Otherwise I'll post back to this issue as soon as we have a list in place.

**Comment by dyaa** [comment]
+1

**Comment by booleanbetrayal** [comment]
Accepting documentation PRs for this response code audit!

**Comment by zachfeldman** [comment]
Hi there @AlanHassen   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
