### ISSUE TITLE
Unpermitted parameter: redirect_url

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#160]
I'm testing the password reset endpoint via my post to my API but get an unpermitted parameter error (redirect_url).

I got it working by doing by adding an ENV in app/controllers/overrides/passwords_controller.rb, though it's definitely a hack.

**Comment by ACPK** [comment]
All set as I just had to add the line below:

     config.action_controller.action_on_unpermitted_parameters = :log

**Comment by vipin8169** [comment]
https://github.com/lynndylanhurley/devise_token_auth/issues/588
