### ISSUE TITLE
POTENTIAL SECURITY RISK: Setting confirm_success_url and redirect_url via API

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#162]
By including confirm_success_url and redirect_url as fields in the API, wouldn't this make my app susceptible to spoofing?  For example, I could manually do a reset password POST statement where I include a known user's email and my spoofed reset password page. Unfortunately, many people keep their passwords the same for multiple sites so I now (potentially) have one of their passwords.

**Comment by lynndylanhurley** [comment]
Those fields haven't been used for several versions now. 

The values are now taken from the registration request and rendered directly to the sent email, no need for saving.

You could send a password reset request for a known user, but that would just send the known user an email containing a single-access token. This won't reveal anything to the attacker.

Please let me know if I've misunderstood the issue.

**Comment by ACPK** [comment]
@lynndylanhurley - First, thanks for your quick reply! I was following along in the readme about params you can pass to /auth/password, and was surprised to read that a user could set it via an API call though I was getting an error.

If you have a second, what is setting the confirm_success_url as I just want to make sure it's not a value set by the user? When I included :confirmable in the user model, I started getting "Missing `confirm_success_url` param."

**Comment by lynndylanhurley** [comment]
When a new user registers for an account (when using `:confirmable`), they are sent a confirmation email. The email contains a link to the API that includes a confirmation token as one of the parameters.

But after the API has verified the user's account, where should the user be redirected to?

Often times, the API and the client live on different domains. And sometimes an API has multiple clients that all live on different domains.

This gem assumes that the user should be redirected back to the domain where they initially registered. So a param is passed to the registration action from the client called `confirm_success_url`. (This happens automatically when using ng-token-auth). The value of this param defaults to the site that the user was on when they registered. But it can be customized using the `confirmationSuccessUrl` [configuration option](https://github.com/lynndylanhurley/ng-token-auth#configuration) of ng-token-auth.

I'm closing this out so it doesn't create panic, but please re-open (or better yet, send me a private email!) if you can demonstrate a successful attack.

**Comment by ACPK** [comment]
@lynndylanhurley How do you set the confirm_success_url when using the API for a native iOS app?
