### ISSUE TITLE
Different rails versions supported

### ISSUE THREAD

**Issue by owalmirneto** [lynndylanhurley/devise_token_auth#1622]
I'm trying update my rails application version to 7.1.3.2, but I can't because there is different rails versions supported in rubygems and GitHub

----

My current versions:

```
rails (7.0.8.1)
  ...
devise (4.9.3)
  bcrypt (~> 3.0)
  orm_adapter (~> 0.1)
  railties (>= 4.1.0)
  responders
  warden (~> 1.2.3)
devise_token_auth (1.2.2)
  bcrypt (~> 3.0)
  devise (> 3.5.2, < 5)
  rails (>= 4.2.0, < 7.1)
                   ^^^^^
```

My issue:

Like a said in https://rubygems.org/gems/devise_token_auth supports only `< 7.1`

<img width="668" alt="Screenshot 2024-05-13 at 17 41 18" src="https://github.com/lynndylanhurley/devise_token_auth/assets/378380/ba655286-21d4-44a4-996d-cc71db1b53b7">

And here in github https://github.com/lynndylanhurley/devise_token_auth/blob/master/devise_token_auth.gemspec#L25 supports `< 7.2`

<img width="604" alt="Screenshot 2024-05-13 at 17 55 58" src="https://github.com/lynndylanhurley/devise_token_auth/assets/378380/14ec1cef-380a-42f6-b19b-7ca3b47da669">

Because that, in my Gemfile I've to use

```rb
gem "devise_token_auth", github: "lynndylanhurley/devise_token_auth"
```

Do you intend to push a new version for add `< 7.2` to rubygems?

**Comment by MaicolBen** [comment]
It was done in 1.2.3, I just tested in a rails repo
