### ISSUE TITLE
Storing token in Redis?

### ISSUE THREAD

**Issue by bizmurr** [lynndylanhurley/devise_token_auth#163]
Rather than storing the token inside the database, is there a way to store in Redis?

**Comment by nicolas-besnard** [comment]
I'm reading a lot of people saying that storing the token in Redis is better. Can you explain me why ?

So far, I don't think it's possible as the Tokens (with an S) are stored as a string in DB.

**Comment by lynndylanhurley** [comment]
@bizmurr - can you describe the advantage that this would offer over the current setup?

I agree with @nicolas-besnard - I can only see disadvantages:

* Increase of complexity
* Increase in number of steps to set up
* Increase in number of dependencies
* Increase in number of server processes / services
* Increase in number of trips to DB for each request

The current setup is simple and performant - I'll need a really convincing argument to change it.

**Comment by tzumby** [comment]
@nicolas-besnard, @lynndylanhurley, why would storing the tokens in Redis increase the number of trips to the DB? Wouldn't storing them in Redis make things faster as you're accessing data from memory as opposed to disk ?

**Comment by nicolas-besnard** [comment]
The first thing that came in my mind:
- find user in DB
- find user in Redis
- return token

Seems really cumbersome

**Comment by zachfeldman** [comment]
Hi there @bizmurr   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
