### ISSUE TITLE
Request for a RubyGems release with Rails 7.2 support

### ISSUE THREAD

**Issue by StalemateInc-gg** [lynndylanhurley/devise_token_auth#1637]
Greetings👋 

Rails 7.2 was [released on Aug 10, 2024](https://rubyonrails.org/2024/8/10/Rails-7-2-0-has-been-released) with the [7.2.1 following shortly after](https://rubyonrails.org/2024/8/22/Rails-7-2-1-has-been-released). Since the PR unblocking the usage with Rails 7.2 [was merged](https://github.com/lynndylanhurley/devise_token_auth/pull/1632) into main long time ago - can we get an official release of this gem on RubyGems with this change included? `devise_token_auth` is still being used by a number of people and I would imagine that they could benefit from having one less obstacle before the Rails upgrade.

The changes can be used when fetching the gem directly from the git source, but sadly not everyone's workplace policy allows installing the libraries from anywhere that is not an official package registry.

Thanks!

**Comment by owalmirneto** [comment]
@lynndylanhurley do you intend to push a version to rubygems with support to rails v7.2?

**Comment by MaicolBen** [comment]
It's done! It's v1.2.4
