### ISSUE TITLE
expired confirmation & reset link 

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#164]
When I create a new user, or ask to reset my password, a confirmation or reset url is sent by email. 

Everything works perfectly. But when reclicking to that same link I got a "Routing Error Not Found".

I want to be able to say to the user, after reclicking that the link is now expired for example.

``` url
http://localhost:3000/auth/confirmation?config=default&confirmation_token=a4-MgzesYWTwqAyfXx6C&redirect_url=http%3A%2F%2Flocalhost%3A3000%2F
```

I have the same issue with confirmation and reset password link.

I'm using the 0.1.29 version.

Thanks for your help !

**Comment by lynndylanhurley** [comment]
@m2omou - would you be ok with an error that reads "Invalid or expired confirmation token"?

**Comment by m2omou** [comment]
Yes that would be great ! :) 

I'm also using ng-token-auth gem.

Will it be possible to catch the "Invalid or expired confirmation token" using the following event ?

```angularjs
$scope.$on('auth:registration-email-error', function(ev, reason) {
    alert("Registration failed: " + reason.errors[0]);
});
```

**Comment by lynndylanhurley** [comment]
@m2omou - try [this](https://github.com/lynndylanhurley/ng-token-auth/blob/master/README.md#authemail-confirmation-error) event instead.

**Comment by camolin3** [comment]
What can I do to avoid the "Routing Error Not Found" error in rails?
I'd like to just redirect to the main page if the user clicks a link in his/her email again.

**Comment by tmlee** [comment]
@camolin3 You may override the controller with your custom setup

For instance,

controllers/devise/passwords_controller.rb
```
class Devise::PasswordsController < DeviseTokenAuth::PasswordsController

  def render_edit_error
    raise "Do something else other than Routing Error Not Found"
  end

end
```

config/routes.rb
```
mount_devise_token_auth_for 'User', at: 'auth', controllers: { passwords: 'devise/passwords' }
```
In config/routes.rb set the custom controller to point to passwords. You can see why this works here https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/rails/routes.rb

**Comment by zachfeldman** [comment]
Hi there @m2omou   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
