### ISSUE TITLE
Pessimistic Locking produces ArgumentError

### ISSUE THREAD

**Issue by dasgib** [lynndylanhurley/devise_token_auth#165]
I get "ArgumentError - wrong number of arguments (1 for 0)" @ https://github.com/lynndylanhurley/devise_token_auth/blob/v0.1.32.beta5/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L57

Anyone has an idea why? When I comment out the lock everything works fine. I don't get this.

I had to use the beta because of https://github.com/lynndylanhurley/devise_token_auth/issues/134 and https://github.com/lynndylanhurley/devise_token_auth/issues/101

**Comment by lynndylanhurley** [comment]
That's strange - what version of Rails are you using?

**Comment by dasgib** [comment]
I'm sorry... it was some code written by another developer, which does "lock" accounts (using a method called "lock!"). I should have noticed that earlier.
