### ISSUE TITLE
How can i authenticate using curl and get private entries !

### ISSUE THREAD

**Issue by dyaa** [lynndylanhurley/devise_token_auth#167]
I'm Searching over the web about how can i authenticate devise using curl and to get private entries !

Can anybody please help me about that?

**Comment by nicolas-besnard** [comment]
```http
curl -XPOST -H 'Content-Type: application/json' -H 'access-token: e3xOfHG-SRkrAWwBS6MgHA' -H 'client: default' -H "uid: user@gmail.com" localhost:3000/YOUR_ROUTE 
````

**Comment by dyaa** [comment]
i was trying this to get the access-token

    curl -XPOST -v -H 'Content-Type: application/json' http://example.com/api/auth/sign_in -d '{"email": "mail@example.com", "password": "password" }'

then 

    curl -XPOST -v -H 'Content-Type: application/json' -H 'access-token: 0t3l9Z8JR3EGdJpV6l5jwQ' -H 'client: default' -H "uid: mail@example.com" http://example.com/api/v1/posts/

it gave me `< HTTP/1.1 401 Unauthorized`

**Comment by nicolas-besnard** [comment]
CSRF didn't occur with an API. Have you try to do the request in a `rails c` ?

**Comment by c0mrade** [comment]
This works for me :
curl -XPOST -v -H 'Content-Type: application/json' http://lvh.me/api/v1/auth/sign_in -d '{"email": "testemail@mydomain.com", "password": "tralalal" }

So I get back the response (something like below, only important part) :

```
< access-token: lW1c60hYkRwAinzUqgLfsQ
< token-type: Bearer
< client: W_xCQuggzNOVeCnNZbjKFw
< expiry: 1426610121
< uid: testemail@mydomain.com
```

Then I can validate the token, using the client and token previously obtained from the above request, I do it like this :

```
curl -XGET -v -H 'Content-Type: application/json' -H 'access-token: lW1c60hYkRwAinzUqgLfsQ' -H 'client: W_xCQuggzNOVeCnNZbjKFw' -H "uid: testemail@mydomain.com" http://lvh.me/api/v1/auth/validate_token
```

**Comment by nicolas-besnard** [comment]
So, it's working ?

**Comment by c0mrade** [comment]
@nicolas-besnard I wasn't the one who reported it's not working. I just tried with the latest code `devise_token_auth (0.1.32.beta5)` and it works for me. Waiting for OP to try the same, and report the result

**Comment by nicolas-besnard** [comment]
@c0mrade sorry, didn't see it in my mail :)

**Comment by dyaa** [comment]
The `curl -XGET -v -H 'Content-Type: application/json' -H 'access-token: lW1c60hYkRwAinzUqgLfsQ' -H 'client: W_xCQuggzNOVeCnNZbjKFw' -H "uid: testemail@mydomain.com" http://lvh.me/api/v1/auth/validate_token`

worked well, final question can you give me an example for XPUT or XDELETE !

Thank you guys.

**Comment by nicolas-besnard** [comment]
You'll have to use the same curl request. Nothing change whatever your request type.

**Comment by dyaa** [comment]
Sorry but i'm trying 

    curl -XDELETE -v -H 'Content-Type: application/json' -H 'access-token: o4JDhkzqAqf_lrklCnURCA' -H 'client: KlEK7aLWZmfoeUKGAn1o0Q' -H "uid: mail@example.com" http://example.com/api/v1/blogs/test

with the last client and access_token and it giving me 401

**Comment by nicolas-besnard** [comment]
Did you do this request right after the login ?

**Comment by c0mrade** [comment]
Or you can try this in your initializer:

```
DeviseTokenAuth.setup do |config|
  config.change_headers_on_each_request = false
end
```

And your access token won't change for every request.

**Comment by ACPK** [comment]
@c0mrade  - Any experience setting the confirmation url and password redirect_url via  curl. The urls are working when using the Angular.JS but not manually for our iOS app.

**Comment by c0mrade** [comment]
@ACPK Unfortunately no, don't have phone apps just yet, but I think I did saw somebody having issues with it I think (should be somewhere in the open issues).

**Comment by nicolas-besnard** [comment]
No problem with iOS / Android app here.

**Comment by Asnadatta** [comment]
Thanks @c0mrade your answer worked for me.

**Comment by Theni-N-Lingeswaran** [comment]
hi 
   am lingeswaran form chennai
i just use 
curl -XPOST -v -H 'Content-Type: application/json' http://192.168.10.184:3000/api/auth/sign_in -d '{"api_key": "E6BkQNJPE6BzZ601M5ENzxu343FExK" }'

i got correct output 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< X-XSS-Protection: 1; mode=block
< access-token: o5IgZro5E6khds_A-pqT5A
< X-Request-Id: ae12f3ff-2826-470d-b130-476acdad2335
< token-type: Bearer
< expiry: 1544269896
< uid: VEYy0GeaEmp3TDvUIkfK0k9xbLtcu7
< client: GgrHfydDnm7qnmiMD2qSZQ
< X-Frame-Options: SAMEORIGIN
< ETag: W/"dc8df0141c437a35f85725b36c98cc10"
< X-Content-Type-Options: nosniff
< X-Runtime: 0.101321
< Date: Thu, 08 Dec 2016 11:51:36 GMT
< X-Powered-By: Phusion Passenger 5.0.30
< Server: nginx/1.10.1 + Phusion Passenger 5.0.30


then i used get method for getting content using

curl -XGET -v -H 'Content-Type: application/json' -H 'access-token: o5IgZro5E6khds_A-pqT5A' -H 'client: GgrHfydDnm7qnmiMD2qSZQ' -H "uid: VEYy0GeaEmp3TDvUIkfK0k9xbLtcu7" http://192.168.10.184:3000/api/products/find_by


but i didn't get output i just got

< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 500 Internal Server Error
< Cache-Control: no-cache
< X-XSS-Protection: 1; mode=block
< X-Request-Id: 686dd0c7-4756-4c8b-8460-f02e27996bf6
< X-Runtime: 0.006672
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Date: Thu, 08 Dec 2016 11:53:52 GMT
< X-Powered-By: Phusion Passenger 5.0.30
< Server: nginx/1.10.1 + Phusion Passenger 5.0.30
< 
* Connection #0 to host 192.168.10.184 left intact
* Closing connection #0
{"errors":[{"status":500,"title":"Internal Server Error","detail":"We're sorry, but something went wrong. Please contact support@qadex.com to report this problem and we'll take a look at it shortly."}]}

please help me
