### ISSUE TITLE
Sign_in / Sign_up via token_auth and via session

### ISSUE THREAD

**Issue by patricks** [lynndylanhurley/devise_token_auth#168]
Hello,
I have setup devise_token_auth for api / json communication and everything works nicely. I can sign_up / sign_in ... and get json responses.
Now I want some features to accessible via a web interface. How do I setup a sign_up / sign_in via this gem? Or is this possbile? 
I tried to generate devise views (like it did on other projects, where i only use devise) via rails generate devise:views. Put this doesn't work. Is this even possible with this gem? Or maybe there is an alternative gem?

**Comment by nicolas-besnard** [comment]
You can use [this library for AngularJS](https://github.com/lynndylanhurley/ng-token-auth) which was created by the creator of this gem.

**Comment by nickL** [comment]
I think you would need to use normal Devise for your web routes and DeviseTokenAth for your api/json communication. See #120, i believe there's a similar need there?

**Comment by zachfeldman** [comment]
Hi there @patricks   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
