### ISSUE TITLE
Cannot use + sign in email address.

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#171]
For testing, we use + signs in the email (ex: ak+testing@gmail.com is automatically sent to ak@gmail.com).  However, the gem is saving ak+testing@gmail.com as ak test@gmail.com.

**Comment by nicolas-besnard** [comment]
That why I hate Regex to check email, and I prefer to send an email to my user. To check email with a regex, you need to cover ALL the possibility. For example `me@møteiv.priv.no` won't work with this gem.

**Comment by lynndylanhurley** [comment]
@ACPK - I can't replicate this bug. The `+` sign seems to work ok on [the demo site](http://ng-token-auth-demo.herokuapp.com/).

Is there something else that could be causing this issue?
