### ISSUE TITLE
Using Google's Authenticator 2FA Mobile app

### ISSUE THREAD

**Issue by dyaa** [lynndylanhurley/devise_token_auth#172]
Hello Guys i'm just wondering how can i use the **_devise_token_auth**_ and **_ng-token-auth**_ Gem with the [Devise_Google_Authenticator](https://github.com/AsteriskLabs/devise_google_authenticator) Gem

**Comment by c0mrade** [comment]
I'm using it with ``gem 'omniauth-google-oauth2'`` not sure if you need that one or do you have any specific questions?

**Comment by dyaa** [comment]
No i mean Google Authenticator the APP

https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en

**Comment by ethagnawl** [comment]
@dyaa Did you ever figure out a workable solution?
