### ISSUE TITLE
Architecture Q: Why did you not use Warden?

### ISSUE THREAD

**Issue by hwhelchel** [lynndylanhurley/devise_token_auth#180]
Devise has a strong pattern of using warden strategies for authentication. Any reasoning for using the `SetUserByToken` controller concern instead of a warden strategy?

Thanks for y'alls great contribution to the rails and angular communities.

**Comment by lynndylanhurley** [comment]
That's a good question. I wasn't familiar with Warden strategies when I built this gem initially. I'll have to do some research to weigh the benefits and drawbacks of strategies against the current implementation.

Can you spot any obvious issues with the current approach?

**Comment by hwhelchel** [comment]
Thanks for the quick reply.

I do not have an immediate use case for a [Warden Strategies](https://github.com/hassox/warden/wiki/Strategies) over a concern but the nice thing about them is that they're composable. The developer adds them to an array inside Warden and then Warden tries the strategies in order. Strategies can `#fail` which moves to the next strategy or `#fail!` which throws an error stopping execution. A `SetUserByToken` strategy could then be easily composed with other Warden Strategies or Devise Strategies. 

Also from [Warden docs](https://github.com/hassox/warden/wiki/Overview):

> Warden allows all downstream middlewares and endpoints to share a common authentication mechanism, whilst still allowing the overall application to manage it. Each application can access the authenticated user, or request authentication in the same way, using the same logic throughout the Rack graph. Each application can layer whatever sugary API on top, and the underlying system will still work.


However implementing custom strategies for the app developer is more complex since rack middlewares aren't available in controller specs by default. So the concern makes it easier to extend the library and test in RSpec (I'm adding a guest user feature for gradual engagement).

If you have a moment check out the strategies in Devise--they're good examples. Thanks again.

**Comment by lynndylanhurley** [comment]
Cool that makes total sense. 

I'll look into this when I get a chance, and feel free to send a PR if you have time.

**Comment by paulius005** [comment]
@hwhelchel  what was your strategy for implementing a guest feature? I'm in the middle of doing the same thing

**Comment by hwhelchel** [comment]
I experimented with a guest strategy that ran after all other strategies. It would create a guest user as a placeholder. I never ran it in production though.

**Comment by zachfeldman** [comment]
Hi there @hwhelchel   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
