### ISSUE TITLE
Best way to set up migration for installation on existing User table already using Devise?

### ISSUE THREAD

**Issue by wrburgess** [lynndylanhurley/devise_token_auth#181]
I am attempting to install `devise_token_auth` but almost everything I've read thus far seems to refer to a freshly created Rails app.

Here's the migration I came up with, but it seems like I'm leaving out the various validations and indexes that exist in the `devise_token_auth` CreateUser migration.

``` ruby
class DeviseTokenAuthChangeUsers < ActiveRecord::Migration
  def change
    change_table :users do |t|
      t.string :provider
      t.string :uid
      t.text :tokens
    end
  end
end
```

Here's an example of one of the errors I received when trying to migrate with an index on a field that's obviously going to be blank with existing users. I'm not sure what I'm supposed to do in the migration to ensure uid is unique for existing users is part of the problem.

``` ruby
PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_uid"
DETAIL:  Key (uid)=() is duplicated.
```

**Comment by lynndylanhurley** [comment]
[Here](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/templates/devise_token_auth_create_users.rb.erb) is the template I'm using for new users.

The index on `uid` should only be unique by `provider` (so no two email users with the same `uid`, etc.).

Try adding something like this:

~~~ruby
    add_index :users, :email
    add_index :users, [:uid, :provider],     :unique => true
    add_index :busts_in_silhouette: , :reset_password_token, :unique => true
~~~

**Comment by wrburgess** [comment]
The migration does not add a value to the `uid` or `provider` fields, thus the unique index bombs out.

**Comment by lynndylanhurley** [comment]
I'm not sure I follow - what do you mean by "add a value"?

Just to clarify, the `uid` and `provider` fields are necessary for this gem to function.

**Comment by wrburgess** [comment]
How can a unique index be created on a table of 1000+ users that all have blank uid and provider attributes *at the point of the index being created*?

**Comment by lynndylanhurley** [comment]
Try setting the `provider` value to `"email"` on each of the existing users, and then saving them. The uid should be set automatically.

Something like this:

~~~ruby
User.all.each{|u|
  u.provider = "email"
  u.save!
}
~~~

At this point the users should all have `provider` and `uid` field values, and it should be safe to create the indices.

**Comment by mkhatib** [comment]
For me, in my migration adding `devise_token_auth` required columns I added this to update existing users.

    User.find_each do |user|
      if user.uid.blank?
        user.uid = user.email
        user.provider = 'email'
        user.save!
      end
    end

**Comment by c0mrade** [comment]
@wrburgess also I think (I might be wrong). if you wrap your updates in a `transaction` block, then indexes will be created after the transaction has completed successfully and not on each update.

**Comment by Vanuan** [comment]
> Just to clarify, the uid and provider fields are necessary for this gem to function.

Does it mean that there's no way to have the same user login via multiple OAuth providers?

**Comment by tbloncar** [comment]
@Vanuan See #23. It isn't supported out of the box, but you could implement the foundation fairly easily by use of different "identities" for a given user and some controller overrides. Some good discussion on the linked issue.

**Comment by Vanuan** [comment]
I'm asking in the context of existing user database: I have one table row per user. Each user has a password and email. Each user can login via Google. As I see in this gem, it implies that I should have a separate table rows: one for email login, another for google login. So it seems to be impossible to migrate to this gem.

**Comment by rk-panchal** [comment]
PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_user_mail"
DETAIL:  Key (user_mail)=() is duplicated

How to resolve this. Please give any suggestion.

**Comment by lesreaper** [comment]
I know this is way late, but I just ran into this as well @rk-panchal . I ran @mkhatib information above and it updated the current users with unique ids. I'm not sure how it's going to work for people who sign up by email, but I'll update that if I run into it again.

**Comment by rk-panchal** [comment]
Hello sir,

 I want to integrate a functionality in my rails application that email
send by user from an application , how to get status of a email that is
seen or unseen by admin.
 If any suggestion  please share.

On Sat, Nov 21, 2015 at 8:47 AM, Richard Everts <notifications@github.com>
wrote:

> I know this is way late, but I just ran into this as well @rk-panchal
> <https://github.com/rk-panchal> . I ran @mkhatib
> <https://github.com/mkhatib> information above and it updated the current
> users with unique ids. I'm not sure how it's going to work for people who
> sign up by email, but I'll update that if I run into it again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lynndylanhurley/devise_token_auth/issues/181#issuecomment-158581772>
> .
>



-- 
Thanks & Regards
Ravinder Kumar <panchal17101989@gmail.com <aniltimt@gmail.com>>
Mobile No- 0720628403

**Comment by rruettimann** [comment]
I had to add the line Login.reset_column_information
after adding the columns, otherwise the update of the uids was not executed on the mysql db.

```ruby
  def up
    add_column :logins, :provider, :string, null: false, default: 'email'
    add_column :logins, :uid, :string, null: false, default: ''
    add_column :logins, :tokens, :text

    # inspired by https://github.com/lynndylanhurley/devise_token_auth/issues/181
    Login.reset_column_information
    Login.find_each do |login|
      login.uid = login.email
      login.provider = 'email'
      login.save!
    end

    add_index :logins, [:uid, :provider], unique: true
  end

  def down
    remove_columns :logins, :provider, :uid, :tokens
    remove_index :logins, name: :index_logins_on_uid_and_provider
  end
```

**Comment by valasensio** [comment]
Thanks rruettimann! That's what I needed.

**Comment by rruettimann** [comment]
@valasensio I'm glad if it saved you some time.. :)

**Comment by whossname** [comment]
I'm new to Rails, so I'd just to clarify with @rruettimann 's answer. Is he using a Login model instead of a User model? Could that be rewritten as something like:

```
def up
  change_table :users do |t|
        t.String :provider, null: false, default: 'email'
        t.String :uid, null: false, default: ''
        t.Text :tokens
    end 

    User.reset_column_information

    User.find_each do |u|
      u.uid = login.email
      u.provider = 'email'   # is this necessary?
      u.save!
    end

    add_index :users, [:uid, :provider], unique: true
  end

  def down
    remove_columns :user, :provider, :uid, :tokens
    remove_index :user, name: :index_users_on_uid_and_provider
  end
```

**Comment by kylepickering** [comment]
I was having the same issue, so thank you!

@whossname I think that should work, but change `u.uid = login.email` to `u.uid = u.email`

**Comment by JustinSeidl** [comment]
@rruettimann @whossname trying to use the `reset_column_information` but my migration keeps failing because I am trying to validate `:name` and `:zip` on my user model. How do I get around this with the above solution?

![Uploading Screen Shot 2017-02-20 at 9.57.07 AM.png…]()

**Comment by whossname** [comment]
Use the default keyword.

t.String :name, null: false, default: 'tempName'

For the name you could try using the first part of the users email. Something like

User.find_each do |u|
  u.name = login.email.split('@')[0]
end

**Comment by JustinSeidl** [comment]
That above actually overwrote the values of my current records which wasn't what I was looking for. I need to retain my current records but needed name and zip because of my validation...

Did the following and it worked with my issue:

`class DeviseTokenAuthCreateUsers < ActiveRecord::Migration
  def up
    change_table :users do |t|
      t.string :provider, null: false, default: 'email'
      t.string :uid, null: false, default: ''
      t.text :tokens
    end

    User.reset_column_information
    User.find_each do |u|
      u.uid = u.email
      u.name = u.name
      u.zip = u.zip
      u.provider = 'email'   # is this necessary?
      u.save!
    end

    add_index :users, [:uid, :provider], unique: true
  end

  def down
    remove_columns :user, :provider, :uid, :tokens
    remove_index :user, name: :index_users_on_uid_and_provider
  end
end`

**Comment by mapreal19** [comment]
maybe we should add @rruettimann solution to the FAQ and close this one

**Comment by sachinprasad** [comment]
I already have UUID for unique user identification. Can I use it? Also Can someone explain the use of  `'provider', 'uid' and 'tokens' `that we add for devise_token_auth implementation.

**Comment by danielricecodes** [comment]
For those of you with *lots* of users in your user table, issue a SQL query instead.  Place the following between changing the database and adding the new indexes.  

If your Devise model is `User`:

```
  User.connection.execute(<<~SQL
      UPDATE users
        SET
          uid = email,
          provider = 'email'
        WHERE uid = ''
    SQL
  )
```

This is *much much* faster than the `find_each` solution.
