### ISSUE TITLE
undefined method `authenticate_user!'

### ISSUE THREAD

**Issue by acmitch** [lynndylanhurley/devise_token_auth#182]
Using the **rails-api** gem along with **versionist**. First time using this gem, hoping this is a simple fix on my end. Any suggestions or ideas?

```ruby
class ApplicationController < ActionController::API
	include ActionController::Serialization
	include DeviseTokenAuth::Concerns::SetUserByToken
	before_action :configure_permitted_parameters, if: :devise_controller?

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) << :username
	    devise_parameter_sanitizer.for(:sign_up) << :mobile
	  end
 end
```
```ruby
class V1::UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def show
		user = User.find_by_username(params[:username]) if params[:username].present?
		user = User.find_by_email(params[:email]) if params[:email].present?
		if user.present?
			render json: user, status: 200
		else
			render :json => { :error => "bad_request" }, :status => 400
		end
	end
end
```

```ruby
class User < ActiveRecord::Base
	include DeviseTokenAuth::Concerns::User
  	# Include default devise modules.
  	devise :database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable,
          	:confirmable
end
```

![screen shot 2015-03-12 at 9 46 35 pm](https://cloud.githubusercontent.com/assets/4482055/6632276/849ebe90-c901-11e4-87b4-e156b75872d4.jpg)

**Comment by acmitch** [comment]
Solved! Issue was in the routes.rb file.

**changed this**

```ruby
   constraints :subdomain => "api" do
    	api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => :json} ) do
    		mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
    		resources :users, only: [:index, :show] do
    			resources :circles, only: [:index, :show, :create, :update, :destroy], shallow: true
    		end
    	end
    end
```
**to this**

```ruby
  constraints :subdomain => "api" do
       mount_devise_token_auth_for 'User', at: 'v1/auth', skip: [:omniauth_callbacks]
    	api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => :json} ) do
    		resources :users, only: [:index, :show] do
    			resources :circles, only: [:index, :show, :create, :update, :destroy], shallow: true
    		end
    	end
    end
```

**Comment by lynndylanhurley** [comment]
Nesting the routes within namespaces and scopes is tricky, especially when the controllers themselves don't share the same nesting. I'm currently testing against the `namespace` and `scope` methods, but I'm not familiar with the `api_version` method. If it's from a gem, then I'll probably need to add a specific case (and tests) for it.

Are you using [versionist](https://github.com/bploetz/versionist)?

**Comment by acmitch** [comment]
Yep using [versionist](https://github.com/bploetz/versionist), the ```api_version``` method is defined from that gem and used to version the api.

Probably not a high priority, but the only issue I can think of is that, someone might run into issues if needing to override the devise_token_auth controllers, while having differences between the api versions: 

```
 mount_devise_token_auth_for 'User', at: 'v1/auth', controllers: {
    token_validations:  'overrides/v1/token_validations'
  } 
mount_devise_token_auth_for 'User', at: 'v2/auth', controllers: {
    token_validations:  'overrides/v2/token_validations'
  } 
```

**Comment by lynndylanhurley** [comment]
Cool, I'll look into it when I get a chance. Thx for reporting the fix :)

**Comment by m2omou** [comment]
any news ? :) I am having the same issue.

**Comment by amitfriedman12** [comment]
I added this line to my controller which did the trick for me:
```ruby
    include Devise::Controllers::Helpers
```

**Comment by AndreiMotinga** [comment]
for future reference posting this here. has an issue with it just now. 
Docs suggest [here](https://maicolben.gitbooks.io/devise-token-auth/content/docs/usage/controller_methods.html) that `:authenticate_user!` will be available, but it isn't. 
`before_action :authenticate_api_user!`  is.

**Comment by AndreiMotinga** [comment]
```
NoMethodError (undefined method `authenticate_user!' for #<Api::SubscriptionsController:0x007f80edcd9e78>
Did you mean?  authenticate_api_user!):
```

related to #219. 

In my case 
routes.rb
```
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json }  do
    mount_devise_token_auth_for "User", at: "auth"
  end
end
```
so instead of `:authenticate_user!` I had to use `:authenticate_api_user!`
