### ISSUE TITLE
Devise and devise_token_auth omniauth callbacks

### ISSUE THREAD

**Issue by springerigor** [lynndylanhurley/devise_token_auth#184]
I'm using devise_token_auth version 0.1.30 with Devise 3.4.0

`routes.rb` looks like:
```
devise_for :users, controllers: { omniauth_callbacks: "omniauth_sessions", sessions: "sessions", registrations: "registrations", passwords: "passwords"}

namespace :api, defaults: { format: :json } do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: { omniauth_callbacks: "omniauth_token_callbacks" }
...
```
Sign up and sign in paths for devise_token_auth works fine. But `/api/auth/:provider/` returns
```
undefined method `valid_encoding?' for :json:Symbol
```

When I moved `mount_devise_token_auth_for ` outside `api` namespace an error occured:
`ArgumentError: Invalid route name, already in use: 'new_user_session'` as both Devise and devise_token_auth_for generate the same route `new_user_session`.

My main goal is to have different omniauth callbacks for Devise and token authentication (mobile app). I have two different controllers but I am unable to provide two different routes for them.

**Comment by lynndylanhurley** [comment]
It [is possible](https://github.com/lynndylanhurley/devise_token_auth#can-i-use-this-gem-alongside-standard-devise) to use this gem alongside standard Devise. 

What are the steps to reproduce the `undefined method` error?

**Comment by springerigor** [comment]
It occurs when I am trying to access `/api/:provider/`

**Comment by springerigor** [comment]
@lynndylanhurley Any insight on this issue?

**Comment by ACPK** [comment]
@springerigor Did you find a solution?

**Comment by springerigor** [comment]
Nope, it's obsolete so I'm closing this issue.
