### ISSUE TITLE
Unable to override OmniauthCallbacksController#redirect_callbacks

### ISSUE THREAD

**Issue by tbloncar** [lynndylanhurley/devise_token_auth#186]
I noticed that my `OmniauthCallbacksController#redirect_callbacks` override implementation wasn't being used. I dug into this a bit, and it turns out that the override for `omniauth_callbacks` will never touch this particular route, as it is defined in [config/routes.rb](https://github.com/lynndylanhurley/devise_token_auth/blob/master/config/routes.rb#L3) (and not [lib/devise_token_auth/rails/routes.rb](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/rails/routes.rb#L51)).

I was able to fix this by moving the route definition to the latter file (where the overrides are considered).

    match "#{DeviseTokenAuth.omniauth_prefix}/:provider/callback", controller: omniauth_ctrl, action: "redirect_callbacks", via: [:get]

Does this present other issues? Or can we safely move this route definition and remove `config/routes.rb`?

I can put a PR together with the update if we're okay with moving forward.

**Comment by nbrustein** [comment]
I think we're succeeding in doing what you're talking about like this:

    mount_devise_token_auth_for 'User', at: 'api/auth', controllers: {
      omniauth_callbacks: 'devise_token_auth/custom_omniauth_callbacks',
    }

That helpful?

**Comment by frankjwu** [comment]
@nbrustein That doesn't override the `redirect_callbacks` method for me (it works for other methods but not that specific one). Having the same problem as @tbloncar... any updates?

**Comment by tbloncar** [comment]
@nbrustein @frankjwu Right. FWIW, I haven't encountered any issues since implementing the fix I described above.

**Comment by nbrustein** [comment]
@frankjwu I just noticed that we also have this in our routes.  So I guess this is why it's working for us:

    post "/omniauth/:provider/callback(.:format)", to: 'devise_token_auth/custom_omniauth_callbacks#redirect_callbacks'

I thought that was just ensuring that we handle posts appropriately (as opposed to gets) when using omniauth-saml, but maybe that's the reason it works at all.

**Comment by medaglia** [comment]
@tbloncar i think i'm having the same problem as you. i tried moving the route into lib/devise_token_auth/rails/routes.rb with no luck, however. does your current fork have this change implemented?

**Comment by tbloncar** [comment]
@medaglia I don't have this change on my fork, but it looks like I just added the following beneath [this line](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/rails/routes.rb#L53).

`match "#{DeviseTokenAuth.omniauth_prefix}/:provider/callback", controller: omniauth_ctrl, action: "redirect_callbacks", via: [:get]`

Is this—save the specific location on line 54—the same change that you implemented?

**Comment by medaglia** [comment]
thanks @tbloncar, that resolved my issue.

**Comment by tbloncar** [comment]
Okay. Cool. Welcome.

**Comment by frankjwu** [comment]
This seems like it should probably get merged into master, especially if you haven't seen any problems with it (@tbloncar).

**Comment by booleanbetrayal** [comment]
@tbloncar - if you have a PR for this already, I'll merge it!

**Comment by m2omou** [comment]
Is the fix from @tbloncar been merged ? @booleanbetrayal  thanks.
