### ISSUE TITLE
Some headers without "access-token" (and friends) while testing with Rspec 

### ISSUE THREAD

**Issue by FabFab** [lynndylanhurley/devise_token_auth#188]
While testing my rails-api with devise_token_auth with Rspec Requests, 

if I don't add `response.headers.merge!(auth_header)` in the batch request treatment here:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L75

I get headers without "access-token".

Is it normal? Is there a cleaner way to test this?

**Comment by jasonswett** [comment]
I wonder why control isn't getting to that point. The first thing I'd want to find out is if maybe line 60 is returning false (`return unless @resource and @resource.valid? and @client_id`).

**Comment by booleanbetrayal** [comment]
Is this still presenting an issue for you @FabFab ? Going to close due to inactivity, but can re-open as needed.

**Comment by maukoquiroga** [comment]
I have the very same issue

**Comment by booleanbetrayal** [comment]
@maukoquiroga - What version of devise_token_auth (and ng-token-auth if used) are you on?

**Comment by FabFab** [comment]
I am not working on this project anymore and don't have access to the source code. 
I think the solution I came up with was the one I've mentioned previously. 
I was just looking for a cleaner way to do it.

**Comment by zachfeldman** [comment]
Hi there @maukoquiroga   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by callmarx** [comment]
I got the same behavior in my application when implement a test for `validate_token` request because I overridden with some extra values. This test was something like: 

```ruby
RSpec.describe "V1 User Validate Token API", type: :request do
  let!(:user) { create(:user, password: "Strong#123Password") }
  let!(:auth_headers) { user.create_new_auth_token }

  describe "GET /api/v1/auth/validate_token" do
    context "when token is valid" do
      before(:each) { get "/api/v1/auth/validate_token", headers: auth_headers }

      it "returns refreshed token" do
        expect(response.headers["access-token"]).not_to eq auth_headers["access-token"]
      end
      ...
    end
  end
end
````

And my `response.headers["access-token"]` was empty. To avoid this you need to disable the [batch request](https://github.com/lynndylanhurley/devise_token_auth/blob/master/docs/conceptual.md#about-batch-requests) time for you test environment in your `config/initializers/devise_token_auth.rb`:

```ruby
DeviseTokenAuth.setup do |config|
  ...
  config.batch_request_buffer_throttle = Rails.env.test? ? 0.seconds : 5.seconds
  ...
end
```

After this setup my `response.headers["access-token"]` stopped to be empty.
