### ISSUE TITLE
GET requests to sign_in shouldn't raise an exception

### ISSUE THREAD

**Issue by milesmatthias** [lynndylanhurley/devise_token_auth#190]
I don't think it's very helpful for get requests to sign_in to raise a vague exception. The [creator has made the choice](https://github.com/lynndylanhurley/devise_token_auth/issues/141#issuecomment-82802797) to leave the method in the code, which is fine, but the results of that method should direct people to use the POST method. See [original comment](https://github.com/lynndylanhurley/devise_token_auth/issues/141#issuecomment-83031660).

**Comment by salmanasiddiqui** [comment]
Nice @milesmatthias 
+1

though i think this should be done for other actions in other controllers which are not being used aswell. And should be merged once its done in all controllers, to keep the behavior consistent.

**Comment by booleanbetrayal** [comment]
Closing since this has been addressed by #191. We can open separate issues for any other routes which may be similar.
