### ISSUE TITLE
DELETE method becoming OPTIONS @ Heroku

### ISSUE THREAD

**Issue by scanferla** [lynndylanhurley/devise_token_auth#197]
Hi,

First of all, thanks for this gem. It is working perfectly except that when I try to `delete` from AngularJS (I'm using ng-token-auth, Restangular and rails-api) my request is sent as `DELETE` but Heroku console shows it as `OPTIONS`. 
Chrome says `net::ERR_EMPTY_RESPONSE`.

AngularJS and Rails are using different domains and the only thing that doesn't work is `delete`. 

It works 100% (including `delete`) in development mode (localhost:3000 and 0.0.0.0:5000).

I've seen many resources talking about "preflight", etc, etc but nothing has worked for me so far. I don't know how to handle this `options` method and haven't found any answers on the web.

Thanks in advance!

**Comment by scanferla** [comment]
I guess I haven't tried this one: I've moved all `rack-cors` config from `config/application.rb` to `config.ru`.

```ruby
require 'rack/cors'
use Rack::Cors do
 	allow do
	    origins '*'
	    resource '*',
	    :headers => :any,
	    :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client', 'authorization'],
	    :methods => [:get, :post, :options, :delete, :put],
	    :credentials => true
	end
end
```

Souce: https://stackoverflow.com/questions/18538549/cant-get-rack-cors-working-in-rails-application/20464939#20464939

It fixed my problem on Heroku.

Thanks anyway for this great gem and I apologize for any inconvenience. I hope this issue can help someone in the future.

**Comment by scanferla** [comment]
@lynndylanhurley strangely it only fixed it for a few days, now it's not working again (as described in my first post). And I haven't changed anything in my code.

**Comment by lynndylanhurley** [comment]
Hi @scanferla - this is normal behavior for cross-domain requests. It's called a [pre-flight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests). Thanks for posting the solution!
