### ISSUE TITLE
No route matches [GET] "/omniauth/sign_in"

### ISSUE THREAD

**Issue by andreydeineko** [lynndylanhurley/devise_token_auth#199]
In `routes.rb` I have following:

``` ruby
namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      mount_devise_token_auth_for 'Tester', at: 'auth'
     # resources
    end
  end
```

It produces such route:

``` ruby
new_api_tester_session_path GET /auth/sign_in(.:format) devise_token_auth/sessions#new {:format=>:json, :subdomain=>"api"}
```

But when visiting the route, it changes path to

``` ruby
http://localhost:3000/omniauth/sign_in?resource_class=Tester
```

saying `No route matches [GET] "/omniauth/sign_in"`.

When I simplify routes to 

``` ruby
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'Tester', at: 'auth'
    end
  end
```

it produces  

``` ruby
new_api_tester_session GET    /api/v1/auth/sign_in(.:format)                                 devise_token_auth/sessions#new
```

but throws:
`Unknown action
The action 'new' could not be found for DeviseTokenAuth::SessionsController`

Some additional info:
Gem versions:
   `devise_token_auth (0.1.31), devise (~> 3.3)`
Also I try to use [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth).

Any chance to get it working? Huge thanks for advice

**Comment by andreydeineko** [comment]
Some additional info:
Gem versions:
   ` devise_token_auth (0.1.31), devise (~> 3.3)`
Also I try to use [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth)

**Comment by baramik** [comment]
Hi, Andrey. Try to mount devise token auth outside api namespace like this 
 ```ruby
  mount_devise_token_auth_for 'User', at: '/auth'
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do      
      resources :users do 
      end
    end
  end
```

**Comment by andreydeineko** [comment]
Hi @baramik, when I do that I again get
`
Unknown action The action 'new' could not be found for DeviseTokenAuth::SessionsController
`

**Comment by andreydeineko** [comment]
@lynndylanhurley hey, how would i deal with `Unknown action The action 'new' could not be found for DeviseTokenAuth::SessionsController`? Please, advise..

**Comment by nicolas-besnard** [comment]
Why do you want to deal with it, as you don't need it ?

**Comment by andreydeineko** [comment]
The only thing I want is to be able to reach /auth/sign_in point without having this error :)

**Comment by nicolas-besnard** [comment]
Why do you want to reach /auth/sign_in with a GET request ?

**Comment by andreydeineko** [comment]
How would I change the request type? I was following [this tutirial](https://www.airpair.com/ruby-on-rails/posts/authentication-with-angularjs-and-ruby-on-rails) on establishing authentication and apparently author doesn't say anything regarding request method.

**Comment by nicolas-besnard** [comment]
What do you want to do ? Register a new user ? Login an existing user ? Can you show me some code ?

**Comment by andreydeineko** [comment]
My code is pretty much what is shown in the tutorial I linked in previous comment..

**Comment by boyfunky** [comment]
i am getting this error too when i try to sign up. I get the error  the action 'new' could not be found for DeviseTokenAuth::RegistrationsController. How do i solve this problem? I cant seem to find any solution online

**Comment by nicolas-besnard** [comment]
You don't need to access this route.

**Comment by zachfeldman** [comment]
Hi there @andreydeineko   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
