### ISSUE TITLE
Limit tokens hash?

### ISSUE THREAD

**Issue by npearson72** [lynndylanhurley/devise_token_auth#208]
I don't have a use case where the user will be hitting the server with multiple clients, but we do deploy changes often and it seems that resets the user's client, causing a new token to be saved to the the tokens field.

After a while, the number of tokens grows, and each request passes a lot of unneeded data.

Is there a way to limit the max number of tokens saved?

**Comment by ncri** [comment]
+1 Why are there so many tokens saved in the user? If there is no limit, the field will overflow at some point.

**Comment by npearson72** [comment]
@ncri I ended up writing my own solution for this. Aside from the unmanaged list of tokens, the overall performance of this gem is poor in my experience -- even with configuring it re-use the token per request.

**Comment by ncri** [comment]
Oh dear. Well, I use this in conjunction with https://github.com/lynndylanhurley/j-toker. It works quite well so far, haven't noticed any issues, except the huge amount of tokens stored in the user.

**Comment by nicolas-besnard** [comment]
@nickL The maximum size of a field this is 1GO - quite a lot of data ;)
@ncri What's your solution for this ?

**Comment by ncri** [comment]
Oh, yes, it is, but they get loaded every time the user is loaded. That brings performance down. More and more as the number of tokens are growing. I wonder why so many need to be stored? Those are all old tokens, right? Why are they stored?

**Comment by ncri** [comment]
Well, the tokens are only kept for 2 weeks and that timespan can be reduced via the config. So I don't see an issue here... ;-)
