### ISSUE TITLE
Oauth broken when attributes have a new line

### ISSUE THREAD

**Issue by mkhatib** [lynndylanhurley/devise_token_auth#211]
`oauth_omnisuccess.html.erb` loops over attributes and prints them out to the javascript to post a message. When the value of an attribute contains a carriage return '\r\n', the string is broken into two lines hence the browser would raise a `SyntaxError: Unexpected token ILLEGAL`.

```
    var usingExternalWindow = function() {
    ...
      if (usingExternalWindow()) {
        window.addEventListener("message", function(ev) {
          if (ev.data === "requestCredentials") {
            ev.source.postMessage({
                "uid": "110558993300943324830",
  // This is where the syntax error occurs.
  "bio": "this is a string 
with a carriage return",
...
```

**Comment by mkhatib** [comment]
Any chance this has been addressed?

**Comment by zachfeldman** [comment]
Hi there @mkhatib   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
