### ISSUE TITLE
AbstractController::ActionNotFound (The action 'new' could not be found for DeviseTokenAuth::RegistrationsController):

### ISSUE THREAD

**Issue by boyfunky** [lynndylanhurley/devise_token_auth#212]
Has anyone been able to solve this issue? I am still facing this issue. Infact I am facing two issues at them moment. 
1. For some weird reasons, the route for my sign_up.html only posts http://localhost:3000/api/auth not http://localhost:3000/api/auth/sign_up while for sign_in it works perfectly fine. 
2. I keep getting the error AbstractController::ActionNotFound (The action 'new' could not be found for DeviseTokenAuth::RegistrationsController). How do i solve this issue. 

My code is on here https://github.com/boyfunky/project_teh_o_ais but the core is as follows 

applicaition.rb 
class ApplicationController < ActionController::Base
    include ActionController::MimeResponds
  include DeviseTokenAuth::Concerns::SetUserByToken

  #respond_to :html, :json
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

   protected

  def json_request?
    request.format.json?
  end
end

usersessions.js 
angular.module('letsSchedulecommyApp').controller('UserSessionsCtrl', function ($scope, $auth, $location) {

```
$scope.$on('auth:login-error', function(ev, reason) {
$scope.error = reason.errors[0];
});
```

 $scope.handleRegBtnClick = function() {
    console.log("im here now")
    $auth.submitRegistration($scope.registrationForm).then(function() { 
        console.log($scope.registrationForm)
      $auth.submitLogin({
        email: $scope.registrationForm.email,
        password: $scope.registrationForm.password
      });
    });
  };

  $scope.$on('auth:registration-email-error', function(ev, reason) {
    $scope.error = reason.errors[0];
    });
});

sign_up.html 

<form ng-submit="handleRegBtnClick()" role="form" ng-init="registrationForm = {}">
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email"
           name="email"
           id="email"
           ng-model="registrationForm.email"
           required="required"
           class="form-control">
  </div>

  <div class="form-group">
    <label for="password">Password</label>
    <input type="password"
           name="password"
           id="password"
           ng-model="registrationForm.password"
           required="required"
           class="form-control">
  </div>

  <div class="form-group">
    <label for="password_confirmation">Password confirmation</label>
    <input type="password"
           name="password_confirmation"
           id="password_confirmation"
           ng-model="registrationForm.password_confirmation"
           required="required"
           class="form-control">
  </div>

  <button type="submit" class="btn btn-primary btn-lg">Register</button>
</form>

routes.rb
  scope '/api' do
    mount_devise_token_auth_for 'User', at: '/auth'
      #namespace :api, defaults: { format: :json } do
    resources :groups, except: [:new, :edit]
  end

app.js

angular
  .module('letsSchedulecommyApp', [
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ui.bootstrap',
    'ui.calendar',
    'ngSanitize',
    'ui.router',
    'ng-token-auth',
    'Devise'
  ])
  .config(function ($stateProvider, $routeProvider, $authProvider) {
    $routeProvider
      .when('/sign_in', {
        templateUrl: 'views/user_sessions/sign_in.html',
        controller: 'UserSessionsCtrl'
      })
      .when('/sign_up', {
        templateUrl: 'views/user_sessions/sign_up.html',
        controller: 'UserSessionsCtrl'
      })
      .when('/', {
        templateUrl: 'views/cleaning_services/homepage.html',
        controller: 'CleaningServicesCtrl'
      })
      $authProvider.configure({
        apiUrl: 'http://localhost:3000/api'
      });  
  });

Is there anything really that I have missed out? Why am I getting this error and I cant seem to get any good answers from any resource online. Any help appreciated

**Comment by zachfeldman** [comment]
Hi there @boyfunky    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
