### ISSUE TITLE
Which software did you use to create the workflow ?

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#215]

**Comment by zachfeldman** [comment]
Hi there @nicolas-besnard    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by lynndylanhurley** [comment]
@nicolas-besnard I think I used Omnigraffle
