### ISSUE TITLE
The omniauth implementation on this gem use redirection. We need to get around these.

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#216]
it can't work on mobile application, or without using the JS library provided by the author

**Comment by lynndylanhurley** [comment]
I'm just using [OmniAuth](https://github.com/intridea/omniauth) for OAuth. I'm afraid that building a custom OAuth implementation is out of the scope of this gem. Do you know of any other gems that can be used for this?

**Comment by zachfeldman** [comment]
Closed as out of scope. @nicolas-besnard feel free to reopen if you disagree.
