### ISSUE TITLE
undefined method `authenticate_user!'

### ISSUE THREAD

**Issue by spheregenomics** [lynndylanhurley/devise_token_auth#219]
There are some other tickets around this issue, and I have tried to follow the answers there

https://github.com/lynndylanhurley/devise_token_auth_demo/issues/4

https://github.com/lynndylanhurley/devise_token_auth/issues/182

But no luck ... I can't seem to make it work. I'm on Rails 4.2.

```
class Api::BaseController < ActionController::API
   include DeviseTokenAuth::Concerns::SetUserByToken
   include ActionController::ImplicitRender
```

```
class Api::SentencesController < Api::BaseController
   before_filter :authenticate_user!
```

```
Rails.application.routes.draw do

   namespace :api, defaults: { format: :json } do
      mount_devise_token_auth_for 'User', at: '/auth'
      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sentences 
   end
end
```

Any assistance, or advice on how to debug would be really appreciated. Great libraries by the way :-)

**Comment by brain64bit** [comment]
It is happen because namespace inside routes. You can use **authenticate_{namespace}_user!** instead using standard **authenticate_user!**, for your case it should be **authenticate_api_user!**, for another helper methods you need to add namespace:

* current_api_user
* api_user_signed_in?

**Comment by spheregenomics** [comment]
Thanks for the tip. I did actually try the *authenticate_api_user! *but no
luck.

How would I debug this issue?

**Comment by brain64bit** [comment]
what about to puts **binding.pry** somewhere inside your controller, check and see ?

**Comment by chirag7jain** [comment]
@brain64bit it worked for me. thanks

**Comment by falegk** [comment]
@brain64bit thanks. It worked :)

**Comment by stevehanson** [comment]
It seems like this works too, outside the `api` namespace:

```
mount_devise_token_auth_for 'User', at: 'api/auth'
```

I'm sure there are caveats to this approach, just not sure yet, since I just started playing with it.

**Comment by andoq** [comment]
@stevehanson did this ever work out for you?  I am going to try it as well.

is there any reason that mount_devise_token_auth_for (in routes.rb) doesn't pass along the opts to the devise_for method?  Devise has support for this using the :as option or :singular option, but this isn't passed through in the mount_devise_token_auth_for method.

I suppose there could be some devise options that cause conflicts with devise_token_auth, but it seems viable to pass through the opts and then exclude or fix the options that cause conflicts as they are discovered.

**Comment by stevehanson** [comment]
@andoq I ended up going with another approach with my app and don't think I really explored it further. Sorry I can't be of more help.

**Comment by zachfeldman** [comment]
Hi there @spheregenomics    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
