### ISSUE TITLE
omniauth_success.html.erb JSON bug

### ISSUE THREAD

**Issue by davidtlee** [lynndylanhurley/devise_token_auth#221]
I realized that, in the current way omniauth_success.html.erb is written (copied below), the JSON returned gives booleans and numbers as strings, e.g. "false", rather than false or "5" rather than 5. This gave me some problems cause I use coffeescript, which only supports the === or !== equalities which means that "5" !== 5. Any way to fix this easily?

```
<% @resource.as_json.each do |attr, val| %>
  "<%= attr %>": "<%= val %>",
<% end %>

"auth_token": "<%= @token %>",
"message":    "deliverCredentials",
"client_id":  "<%= @client_id %>",
"expiry":     "<%= @expiry %>",
"config":     "<%= @config %>"
```

**Comment by tbloncar** [comment]
You could override this view with something like:

    <% @resource.as_json.each do |attr, val| %>

        # Check for number/boolean
        <% if val.is_a?(Numeric) || !!val == val %>
            "<%= attr %>": <%= val %>,
        <% else %>
            "<%= attr %>": "<%= val %>",
        <% end %>
    <% end %>

    "auth_token": "<%= @token %>",
    "message":    "deliverCredentials",
    "client_id":  "<%= @client_id %>",
    "expiry":     "<%= @expiry %>",
    "config":     "<%= @config %>"

Then you'd just need to make sure that your override view is rendered in `OmniauthCallbacksController#omniauth_success`. I had previously written an [override for this controller](https://github.com/lynndylanhurley/devise_token_auth#custom-controller-overrides), so I just replaced [this line](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb#L73) with:

    render :layout => "layouts/omniauth_response", :template => "path_to_my_view_overrides/omniauth_success"

Hope this helps.

**Comment by davidtlee** [comment]
ahhh, good idea :) thanks!

**Comment by nbrustein** [comment]
Here is a more general solution, which worked for me with array values as well:

        <% @resource.as_json.each do |attr, val| %>

            "<%= attr %>": <%= val.to_json.html_safe %>,
        <% end %>

        "auth_token": "<%= @token %>",
        "message":    "deliverCredentials",
        "client_id":  "<%= @client_id %>",
        "expiry":     "<%= @expiry %>",
        "config":     "<%= @config %>"
