### ISSUE TITLE
Namespaced Models

### ISSUE THREAD

**Issue by kaevee** [lynndylanhurley/devise_token_auth#228]
Hi,

I am using devise_token_auth with namespace models. My model is V1::Party. Even though authentication is working fine, the authenticate method is `authenticate_v1_v1_party!`. I suppose it should have been `authenticate_v1_party!`

I had modified the migration and model for namespaces 

```
create_table :v1_parties, id: :uuid do |t| 
# Snipped
end

module V1
  class Party < ActiveRecord::Base
  rolify :role_cname => 'V1::Role'
    # Include default devise modules.
    devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable,
      :confirmable, :omniauthable
    include DeviseTokenAuth::Concerns::User
  end
end
```

Any suggestions?

Thanks,

V

**Comment by zachfeldman** [comment]
Hi there @kaevee    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
