### ISSUE TITLE
Devise email validation disabled...why?

### ISSUE THREAD

**Issue by hiattp** [lynndylanhurley/devise_token_auth#229]
You are overriding the devise `email_required?` and `email_changed?` methods in `DeviseTokenAuth::Concerns::User`, any particular reason? It seems like that should be beyond the scope of the token auth concern.

**Comment by lynndylanhurley** [comment]
@hiattp - it was necessary to modify the redirect url. If you can find a better way please let me know.

**Comment by daslicious** [comment]
@lynndylanhurley Excuse me for being a noob, still trying to understand.  I can't find which redirect you're referring in the code.  Could you help me out?
