### ISSUE TITLE
Remove ('#') symbol when using html5mode in locationProvider

### ISSUE THREAD

**Issue by v3rtx** [lynndylanhurley/devise_token_auth#232]
I'm using html5 navigation in my angular app and I faced with the problem that I can't parse options passed by passwords_controller.
I've made local changed in my fork that checks params[:html5] and if it true removes '#' symbol form the url.

This changes also requires corresponding changes in the ng-token-auth module (which I also made locally and haven't forked and commited this changes).

I have a question if you are or anyone who use this gem is interested in such functionality (or maybe it was created already and I just don't see the obvious way to use html5 routing without any changes)?

I haven't tested my changes so I don't create a pull request, but if anyone interested in this functionality I will continue contribution procedure.

**Comment by aihaddad** [comment]
I am interested

**Comment by masanorinyo** [comment]
I am interested too!

**Comment by MichalZalecki** [comment]
+1

**Comment by v3rtx** [comment]
Works on current version, so closing the issue.
