### ISSUE TITLE
Expected params don't match Devise itself

### ISSUE THREAD

**Issue by pupeno** [lynndylanhurley/devise_token_auth#233]
Hello,

First, my apologies if this report is wrong. I'm new to token auth and javascript frameworks. ember-simple-auth-devise sends the params mimicking devise itself, so that rails receives:

``` ruby
{"user"=>{"email" => "email@example.com",
                "password"=>"supersecret"},
 "controller"=>"sessions",
 "action"=>"create"}"
```

but apparently devise_token_auth expects:

``` ruby
{"email" => "email@example.com",
 "password"=>"supersecret",
 "controller"=>"sessions",
 "action"=>"create"}"
```

**Comment by colindensem** [comment]
Hopefully long since resolved for you.
For reference this is how I overcame it.
```
//app/authenticators/devise.js
import DeviseAuthenticator from 'ember-simple-auth/authenticators/devise';
export default DeviseAuthenticator.extend({
  serverTokenEndpoint: '/auth/sign_in',
  resourceName: '',
});

```

**Comment by zachfeldman** [comment]
Seems like this one is solved.

**Comment by MichalBryxi** [comment]
Seems like the solution only applies to older version of `empler-simple-auth`. I raised an [issue with ember-simple-auth here](https://github.com/simplabs/ember-simple-auth/issues/2206). Cross linking to make sure people are not confused.

Some workaround for this sort of problem on `devise_token_auth` would be nice though.

Would it be possible to add support for a root key? i.e:

```json
{ 
  user: { 
    email: 'xxx', 
    password: 'yyy' 
  } 
}
```
