### ISSUE TITLE
Devise.secret_key was not set. Please add the following to your Devise initializer

### ISSUE THREAD

**Issue by karimbutt** [lynndylanhurley/devise_token_auth#235]
I am getting the following error when I try to migrate my database or run my app in production: Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'my secret key'

When I add this secret key, I get the following error:

NoMethodError: undefined method `secret_key=' for DeviseTokenAuth:Module

I am not sure why this error keeps occurring - note this issue only occurs in production.

**Comment by vsnguyen** [comment]
check your config/secrets.yml file.  most likely you'll need to set an environment variable for it.

**Comment by gamesover** [comment]
I have a local `secrets.yml` file, so locally, I have no issue. But when I push the code, travis-ci cannot pass since there is no `secrets.yml` at github repository. Thus, I have to create a `devise.rb` with setup 
```
config.secret_key = FreeSms::Application.config.secret_key_base || ENV['SECRET_KEY_BASE']
```
since `devise_token_auth` does not know `config.secret_key`

**Comment by osazemeu** [comment]
Set SecretKey

```
config/initializers/devise_token_auth.rb
config.secret_key = ENV[ 'DEVISE_TOKEN_AUTH_SECRET_KEY' ]
```

http://stackoverflow.com/questions/30089977/devise-token-auth-error-devise-secret-key-was-not-set

**Comment by zachfeldman** [comment]
Seems solved. Reopen if not @karimbutt
