### ISSUE TITLE
Name conflict with inherited_resources

### ISSUE THREAD

**Issue by anggiaj** [lynndylanhurley/devise_token_auth#236]
`DeviseTokenAuth::Concerns::SetUserByToken.resource_class` with
https://github.com/josevalim/inherited_resources/blob/master/app/controllers/inherited_resources/base.rb.

**Comment by booleanbetrayal** [comment]
@anggiaj - Is this collision still affecting you? It appears that inherited_resources is deprecated. Going to close this since it's been awhile, but can re-open as needed.

**Comment by anggiaj** [comment]
Hey sorry for the late reply, i know inherited_resources is deprecated, but some other gem still using it, for example: activeadmin
