### ISSUE TITLE
Headers required for different methods

### ISSUE THREAD

**Issue by lumenlunae** [lynndylanhurley/devise_token_auth#243]
A few pieces of the docs refer to an "auth_token" and not an "access-token".... and, for example, validate_token says it expects only the token and uid. Is this the case? I couldn't get it to work unless I had "access-token", "uid", and "client." I'd be more than happy to make a PR to update the readme but I want to double-check if this is the case or I may have missed something.

Thanks!

**Comment by nicolas-besnard** [comment]
I think "auth_token" means "access-token, uid and client". Not sure but
anyway, you should always send access-token, uid and client when you need
to get logged.

**Comment by lumenlunae** [comment]
Cool. Appreciate it, thanks!
