### ISSUE TITLE
Should a 404 reset tokens?

### ISSUE THREAD

**Issue by lumenlunae** [lynndylanhurley/devise_token_auth#244]
I'm building out parts of an API while working with devise_token_auth and I noticed this flow:

First request: Make a valid API response: 200
Second request: Hit an unmatched route: 404
Third request: Make another valid API response with the same token as the first request: 401

I would get the 404 but no return headers, so I'm using the same access-token as the first request. It seems like the server is still changing my tokens. 

I'm trying to write tests for this but I don't know how to mock a proper 404 response. This is up to where I've gotten: https://github.com/lumenlunae/devise_token_auth/blob/404-token-error/test/controllers/demo_user_controller_test.rb#L262

**Comment by zachfeldman** [comment]
Hi there @lumenlunae   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
