### ISSUE TITLE
Info: is devise_token_auth compatible with rails 3.2.19?

### ISSUE THREAD

**Issue by anpa** [lynndylanhurley/devise_token_auth#245]
Hi,

I added this gem to my Gemfile, I did bundle install and got this message:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 3.2.19)

  In Gemfile:
    devise_token_auth (>= 0) x86-mingw32 depends on
      rails (~> 4.1) ruby

    rails (~> 4.1) x86-mingw32

    rails (= 3.2.19) ruby

    rails (= 3.2.19) x86-mingw32
```

Does this means that devise_token_auth is not available for rails 3.2.19? Is there any way (or any other devise_token_auth version) to get around with this?

Thanks in advance!

**Comment by booleanbetrayal** [comment]
@anpa - I don't believe there are any particular issues with 3.2.19 support, besides just being locked at 4.2. Are you still having this issue? Closing for now, but can re-open if needed.
