### ISSUE TITLE
File download with query params

### ISSUE THREAD

**Issue by jakemauer** [lynndylanhurley/devise_token_auth#246]
Hey there!

We're using Rails as an API backend to an Ember app using token auth. One issue I'm running into is we have a few API endpoints to download a file. Since we're no longer using cookies and since I can't set auth headers for a GET the download gets a big fat 401. 

Is it possible to pass the token/email as query params for authenticating certain requests? If that suggestion makes your spidey sense go off, what's a good pattern for this case? 

Thank you!

**Comment by nicolas-besnard** [comment]
You can set auth headers on a GET request

**Comment by jakemauer** [comment]
Well that’s cool, thanks Nicolas! 
-- 
Jake Mauer
414-712-6786

On May 16, 2015 at 2:07:33 AM, Nicolas Besnard (notifications@github.com) wrote:

You can set auth headers on a GET request
