### ISSUE TITLE
reset password link is not getting to redirection

### ISSUE THREAD

**Issue by nitingrewal** [lynndylanhurley/devise_token_auth#247]
In logs 

Redirected to localhost:3000/update#?client_id=CJxleBtYwUgPl8IHYpvnKA&config=default&expiry=&reset_password=true&token=YYY&uid=nial%40b.com

Completed 302 Found in 186ms (ActiveRecord: 6.2ms)

but page is not getting redirected.
http://localhost:3000/api/auth/password/edit?config=default&redirect_url=localhost%3A3000%2Fupdate&reset_password_token=XXXX

I am getting this error in log and there is no redirection happening.

**Comment by fertingoff** [comment]
Folks, it looks like I have a similar problem.
Link from a letter (stated above) goes to the correct redirect route (here is extract from server log):
```
Redirected to localhost:9000/#/reset_password?client_id=xxxxxxx&config=default&expiry=&reset_password=true&token=dddd&uid=dddddd%40kmhow.com
Completed 302 Found in 214ms (ActiveRecord: 19.2ms)
```
But it doesn't redirect. However, if I copy and paste this link manually, everything works.
Any ideas?

**Comment by ACPK** [comment]
@fertingoff @nitingrewal Did you solve the issue?

**Comment by fertingoff** [comment]
@ACPK an old question. Eventually it worked for my case. I suspect that the reason was some custom changes to the process (i.e. not to proceed the advisable path for 100%).

**Comment by elja** [comment]
having the same issue, in my case I think it's all because of ui-router

**Comment by zachfeldman** [comment]
Seems like cases are mostly solved here. Feel free to reopen if not.
