### ISSUE TITLE
Custom Serializer like ActiveModel Serializer

### ISSUE THREAD

**Issue by stephenbaidu** [lynndylanhurley/devise_token_auth#249]
Is there some easy way of forcing my custom serializer on the object I get at $auth.user? Apart from overriding the controller that is rendering and specifying the active model serializer class to use?.

**Comment by rentziass** [comment]
Hi @stephenbaidu , did you find a way to do it? I'm looking for the same thing.

**Comment by rentziass** [comment]
FYI I only managed to do it by overriding the controllers, didn't find another way for now.

**Comment by stephenbaidu** [comment]
@rentziass Still search since I do not want to override the controller.

**Comment by DeanSolecki** [comment]
@stephenbaidu, don't suppose you have any tips on that hack?  I'm looking into the overrides right now and not seeing much help anywhere, docs or otherwise.  A working example would be invaluable. :)

**Comment by rentziass** [comment]
@DeanSolecki I managed to get the response in the format I needed by overriding this:
https://github.com/lynndylanhurley/devise_token_auth/blob/c11dd18c4cc9a78ab60cd668f06cfd5b2d13e4ec/app/models/devise_token_auth/concerns/user.rb#L216-L220

That's just "to_jsoning" the resource, aka User, excluding some of the attributes. Nothing prevents you from replacing those lines with a serializer of yours.
```ruby
def token_validation_response
  YourUserSerializer.new( self, root: false )
end
```

**Comment by DeanSolecki** [comment]
@rentziass Thanks!  This is exactly what I was looking for. :)

**Comment by rentziass** [comment]
@DeanSolecki No problem, I'm glad it helped, I spent hours trying to figure this out :)

**Comment by stephenbaidu** [comment]
@rentziass Brilliant and thank.

**Comment by AlexVKO** [comment]
I wrote it in User model, but doest work, should i doing something wrong?

```ruby
class User < ActiveRecord::Base
  include DeviseTokenAuth::Concerns::User
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable
  # Exclude: confirmable

  validates_presence_of :name

  def token_validation_response
    UserSerializer.new( self, root: false )
  end
end
```

**Comment by juddey** [comment]
@AlexVKO I had success with:
`UserSerializer.new( self, root: false ).as_json`

**Comment by AlexVKO** [comment]
Thank you @juddey

**Comment by AlexVKO** [comment]
Does it still works? I can't do it work on my api....
rails 5 api, active model serializer 0.10

**Comment by tesser** [comment]
Please close this. This is the preferred solution: https://github.com/lynndylanhurley/devise_token_auth#overriding-rendering-methods

**Comment by booleanbetrayal** [comment]
agree

**Comment by rmcsharry** [comment]
Preferred solution docs moved:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/docs/usage/overrides.md
