### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by stephenbaidu** [lynndylanhurley/devise_token_auth#259]
The error message returned when email is already in use becomes weird in full_messages. This is as a result of the following line in `models/devise_token_auth/concerns/user.rb`
`errors.add(:email, :already_in_use, default: "This email address is already in use")`

Since rails concatenates the field to associated errors for full_messages, this becomes
`Email This email address is already in use`

I suggest the offending line be changed to
`errors.add(:email, :already_in_use, default: "address is already in use")`

Or better still, an extra line can be added like below
```
errors.add(:email, :already_in_use, default: "address is already in use")
errors.add(:base, "This email address is already in use")
```

I would also like to know if this behaviour was requested earlier.

**Comment by booleanbetrayal** [comment]
This should be addressed as part of some recent localization changes. Can re-open as needed.
