### ISSUE TITLE
How To Handle Guest Account

### ISSUE THREAD

**Issue by JoshuaNovak919** [lynndylanhurley/devise_token_auth#264]
I'm trying to figure out the best way to handle a guest account using this gem. Should I just designate an account as a guest, generate guest accounts, or is there a better option?

**Comment by JoshuaNovak919** [comment]
Anyone have any ideas?

**Comment by BjornMelgaard** [comment]
Maybe (in my opinion this is the most beautiful way)
```ruby
  authenticated :user do
    root 'application#index', as: :authenticated_root
  end

  root to: redirect('/auth/login'), as: :unauthenticated_root
```
but i have some [issue](https://github.com/lynndylanhurley/devise_token_auth/issues/312) :smile:

**Comment by zachfeldman** [comment]
Hi there @JoshuaNovak919    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
