### ISSUE TITLE
resource_class wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by casertap** [lynndylanhurley/devise_token_auth#268]
![error_devise_token_auth](https://cloud.githubusercontent.com/assets/284394/8082659/21295e46-0f7f-11e5-8159-96fb6eeaccec.jpg)

This error happens when I try to connect with facebook.
I am really imitating the devise_token_auth_demo app so I do nothing fancy.

Thanks,

**Comment by casertap** [comment]
Anyone?

**Comment by nicolas-besnard** [comment]
You should avoid to create issue each time you get an error. You should also describe the steps you do to try to solve your issue.

**Comment by casertap** [comment]
I have progressed a little on this issue.
I have opened an issue on the paper_trail gem because it is this gem that is calling the current_user during the initialization of the omniauth authentication.

https://github.com/airblade/paper_trail/issues/548

Thanks, guys. I think whose issues are relevant.

**Comment by ArneZsng** [comment]
I am currently having the same issue. I am still researching but I am using it together with ActiveAdmin and it seems to me that ActiveAdmin overrides the resource_class method with its own implementation when calling it from an ActiveAdmin controller. 

Thus, I would suggest renaming the method "resource_class" to something more unique, e.g. resource_klass. Would you accept a pull request for that change?

**Comment by ajahongir** [comment]
Having same issue, It seams it conflicts with inhereted_resource/

**Comment by gavin1818** [comment]
I have the same issue, the reason is that the method name "resource_class" conflicts with the method in Devise, hence instead of calling the set_user_b_token#resource_class, it calls the devise's app/controllers/devise_controller.rb#resource_class

**Comment by MaicolBen** [comment]
I will close for now since I don't want to break people's overrides in `resource_class`, please comment if this still happening
