### ISSUE TITLE
include associations on login

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#269]
Hey !

Is it possible to tell devise to include associations into the json on login / auth ?

For example I have a tables "links" and the current user has 4 links. I want to add those links into the user json.

I have tried to edit the as_json method inside the user model:

```ruby
def as_json(options = {})
hash = super
hash[:links] = self.links
hash
end
```

But still get the same json.

Thank you

**Comment by jasonswett** [comment]
I'm using `as_json` in a couple different apps and it works for me. Here's one example of how I'm successfully doing it.

```ruby
def as_json(options = {})
  super(options).merge("organization" => self.organization)
end
```

I'm curious what would happen if you tried:
```ruby
def as_json(options = {})
  super(options).merge("links" => self.links)
end
```

**Comment by booleanbetrayal** [comment]
I think overriding `as_json` is a suitable implementation. Closing but can re-open if needed.
