### ISSUE TITLE
Shouldn't validate_token param be access-token, not auth_token?

### ISSUE THREAD

**Issue by wjdhamilton** [lynndylanhurley/devise_token_auth#270]
I note that in the doc entry for validate_token the params specified are auth_token and uid. When trying to use the endpoint in cURL I can only make it work with uid, access-token, and client. Shouldn't the docs reflect this or am I missing something?

**Comment by jasonswett** [comment]
I believe `access-token` as opposed to `auth_token` is correct. That's what's working for me.
