### ISSUE TITLE
How to refresh token/expiry?

### ISSUE THREAD

**Issue by JoshuaNovak919** [lynndylanhurley/devise_token_auth#275]
I have an iOS/Android app that I am connecting to my API and I obviously don't want the user's session to expire if they've opened the app recently simliar to facebook etc. Is there a way to refresh the token/expiry so they can stay logged in?

**Comment by nickL** [comment]
@JoshuaNovak919 would `user#create_new_auth_token` work for you?

**Comment by JoshuaNovak919** [comment]
I actually had to switch to a different system since I could not get Facebook/Twitter working properly with this gem. I have them nested in an api and v1 namespace so it wouldn't work.
