### ISSUE TITLE
Facebook Auth isn't working for Google Chrome users that have Data Compression set to on

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#279]
When a user who is using Google Chrome's Data Compression feature on their iPhone tries to sign in via /users/auth/facebook, they're getting the error message below:

```
"This page cannot be loaded via chrome data compression proxy. Try reloading the page."
```

If the users click back and visits "/users/auth/facebook" for a second time, it works.

**Comment by zachfeldman** [comment]
Nobody else has reported this and it's been more than 2 years, so I'll be closing for now @ACPK .
