### ISSUE TITLE
No route matches [GET] "/users/facebook/callback"

### ISSUE THREAD

**Issue by JoshuaNovak919** [lynndylanhurley/devise_token_auth#280]
When I try to login with omniauth using facebook I get the following error:

`No route matches [GET] "/users/facebook/callback"`

Do I need to define the callback somewhere?

My routes:

```
devise_for :users, controllers: { registrations: "users/registrations", sessions: 'users/sessions' }
  devise_scope :user do
   root :to => 'devise/sessions#new'
  end
  
  # Api name space
  namespace :api, defaults: { :format => 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end
end
```

**Comment by JoshuaNovak919** [comment]
It looks like it has to do with this line in the `omni_auth_callbacks_controller.rb`:

`redirect_route = "/#{Devise.mappings[devise_mapping].as_json["path"]}/#{params[:provider]}/callback"`

It seems the `Devise.mappings` are wrong for some reason.

**Comment by booleanbetrayal** [comment]
did you figure this issue out @JoshuaNovak919 ?

**Comment by JoshuaNovak919** [comment]
@booleanbetrayal No I didn't. I had so many issues I switched to Doorkeeper for now.

**Comment by booleanbetrayal** [comment]
Sorry to hear that @JoshuaNovak919
