### ISSUE TITLE
NoMethodError (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#286]
I have this error for a couple of day now. Any leads to solve ti ?

```
NoMethodError (undefined method `[]' for nil:NilClass):
  devise_token_auth (0.1.32.beta10) app/models/devise_token_auth/concerns/user.rb:180:in `build_auth_header'
  devise_token_auth (0.1.32.beta10) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:68:in `update_auth_header'
````

**Comment by nicolas-besnard** [comment]
The error disapear on 0.1.31 (was using 0.1.32.beta10)

**Comment by booleanbetrayal** [comment]
We ran into a similar issue because we had a query parameter called `client` which was not supposed to have anything to do with devise token auth.  In certain cases, devise token auth was assuming that that value was a `client_id` and using it for that.

Kind of a long shot, but are you maybe doing the same thing?

**Comment by danubekas** [comment]
I have the same issue on some requests.
I will try to find the differences between the working requests. 

using 0.1.32-beta10.

**Comment by chirag7jain** [comment]
even I am getting the same error - /sigin_in post request - sending email and password parameters

**Comment by chirag7jain** [comment]
I made this hack and it worked

        tokens = @resource.tokens.nil? ? {} : eval(@resource.tokens)

        tokens[@client_id] = {
          token: BCrypt::Password.create(@token),
          expiry: (Time.now + DeviseTokenAuth.token_lifespan).to_i
        }

       @resource.tokens = tokens

but I am getting another error - undefined method `create_new_auth_token' for #<Account:0x000000067b3378>

Relevant back trace

  activemodel (4.2.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:78:in `block in update_auth_header'
  activerecord (4.2.3) lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.3) lib/active_record/transactions.rb:277:in `transaction'
  activerecord (4.2.3) lib/active_record/locking/pessimistic.rb:70:in `with_lock'
  devise_token_auth (0.1.31) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:57:in `update_auth_header'
  activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:237:in `block in halting'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'

**Comment by chirag7jain** [comment]
good news - the master fixes the above issue

bad news - there is another undefined method issue  - token_validation_response - line 55 session controller

**Comment by chirag7jain** [comment]
master seems to work fine

**Comment by JGantner** [comment]
I encountered the same issue with the 0.1.32 version from rubygems. My solution was to disable the cookie stuff that i hadn't removed until then. Now every thing is fine.

**Comment by hiattp** [comment]
Seeing this as well, does anyone have a good sense for what causes this issue or a reliable way to reproduce locally? It seems to be sporadic.

We are using 0.1.32-beta9.

**Comment by hiattp** [comment]
This seems to be caused by a threadsafety issue in how tokens are being set for a resource (user). If two requests come in simultaneously (e.g. a client sends duplicate sessions create requests) on a multi-threaded server the second token update will overwrite the first, so when `build_auth_header`runs and looks for the token with the first `client_id` it will return nil and throw this error.

**Comment by nitsujri** [comment]
+1 having `500`'s all over the place because of this.

any quick solution/fix?

**Comment by ecauli** [comment]
+1 any solution?

**Comment by nitsujri** [comment]
@ecauli We migrated to `redis_store` and `redis sentinel` for our sessions. Since then, we haven't had an issue.

**Comment by mustela** [comment]
Guys, same error with `devise_token_auth-0.1.37`, any clue what is it about?

**Comment by booleanbetrayal** [comment]
Merged #523 which adds some additional resiliency. Closing this issue, but would love to hear a reproducible scenario where `client_id` is being legitimately omitted, etc.

**Comment by arfrank** [comment]
Seeing this error when doing a password reset password change.  I believe it might be all old tokens being wiped out with the PW update, but no new token existing yet, but haven't been able to dig into internals enough to confirm.

**Comment by alexeyShumakov** [comment]
devise_token_auth-0.1.37 same error.  
I just set 'change_headers_on_each_request' to true.

But devise_token_auth-0.1.36 have not this error.

**Comment by TBurk83** [comment]
+1

Do we know when this will get fixed? I am having the same issue...

**Comment by pablodv** [comment]
Im having the same problem with `v1.1.3`

**Comment by vixtoria** [comment]
For me adding
> include DeviseTokenAuth::Concerns::User
to > app/models/user.rb
fixed it

**Comment by vixtoria** [comment]
For me adding
```include DeviseTokenAuth::Concerns::User```
to ```app/models/user.rb``` fixed it
