### ISSUE TITLE
Using alongside "normal" rails app

### ISSUE THREAD

**Issue by alextakitani** [lynndylanhurley/devise_token_auth#290]
I'm trying to use the gem on a existing rails app, witch uses devise for authentication.

On my application controller, I have protect_from_forgery with: :exception

How can I make devise_token_auth use a alternative application_controller?

I saw

https://github.com/lynndylanhurley/devise_token_auth#im-having-trouble-using-this-gem-alongside-activeadmin

But could not figure out how to.

Thanks!

**Comment by vic700208** [comment]
You may want to check this out:  https://github.com/lynndylanhurley/devise_token_auth/issues/159

**Comment by zachfeldman** [comment]
Hi there @alextakitani    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
