### ISSUE TITLE
set_user_by_token not called in overriden controller

### ISSUE THREAD

**Issue by wjdhamilton** [lynndylanhurley/devise_token_auth#291]
In the documentation section entitled "Custom Controller Overrides" it is stated that @user should have been set by the concern using set_user_by_token. However, on my system it isn't. I have to call set_user_by_token explicitly. Should the documentation be updated or have I found a bug?

**Comment by colavitam** [comment]
I believe you're looking for current_user instead of @user.

**Comment by booleanbetrayal** [comment]
I've just updated the documentation to reflect **@resource** as used in the code. **current_user** should also be accessible in your case.
