### ISSUE TITLE
Conder making view helpers available in token_validations_controller

### ISSUE THREAD

**Issue by wjdhamilton** [lynndylanhurley/devise_token_auth#292]
I need to create a more complex representation of the user for returning after a token is validated so I have overriden the token_validations_controller as per the documentation, except that I ask it to render a jbuilder view if @user is present. Jbuilder works perfectly well until I try and user a url or path helper; doing so just throws a NoMethodError (even if I use controller.view_context.url...). I've moved the logic to the model for now, but it would be a lot better if the url helpers were available in jbuilder.

**Comment by zachfeldman** [comment]
Hi there @wjdhamilton    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
