### ISSUE TITLE
undefined method `tokens' for #<Hash:0x000000063f0920>

### ISSUE THREAD

**Issue by adisos** [lynndylanhurley/devise_token_auth#297]
This part is triggering this exception, because `warden.user(rc.to_s.underscore.to_sym)` returns hash, not User object. What should I do?
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L32

**Comment by adisos** [comment]
Just cloned `devise_token_auth_demo`. It returns user object. Strange.

**Comment by adisos** [comment]
It works only on `0.1.32.beta9` version, in later versions error is raised.

**Comment by booleanbetrayal** [comment]
@adisos - are you still experiencing this issue? I'm currently unable to reproduce. Please try testing against the latest devise_token_auth 0.0.32 (and ng-token-auth 0.0.27 if you're using it)

**Comment by ysyyork** [comment]
I have the same problem with version 0.1.36. It only works for the first time when I start the server and use token to authenticate. From the second time on, it will raise this exception. But it can work will with version 0.1.32.beta9

**Comment by chirag7jain** [comment]
even I am facing the exact same issue
