### ISSUE TITLE
Getting 401's when making requests using iOS/Android clients

### ISSUE THREAD

**Issue by dcunited001** [lynndylanhurley/devise_token_auth#299]
I'm experiencing this problem with both Android and iOS.  After authentication, my app sends a few successful requests.  But after about 60 seconds, my client's token is invalidated and subsequent requests receive 401's.  On Angular, I don't see these problems.  My requests continue to be authenticated and my token is never invalidated.  

I've pasted the request headers i'm sending for both iOS and Angular.  Is there something else I need to configure to get this to work?  Why does my iOS client send the Cookie header with _rails42_session?

### Request Headers on iOS
- GET /auth/validate_token HTTP/1.1
- Host: myapi.dev:3000
- **uid: myemail@gmail.com**
- **token-type: Bearer**
- If-None-Match: W/"604fd9788e523bdd69019c1ce4bce058"
- Accept-Language: en;q=1.0
- Accept-Encoding: gzip;q=1.0,compress;q=0.5
- Accept: application/json;version=1
- **access-token: nO4wd44pqNqSX0LzofxSCQ**
- **expiry: 1437693818**
- User-Agent: MyApp (1; OS Version 9.0 (Build 13A4254u))
- Connection: keep-alive
- **client: j9VV-52LqMHH4Iwgb4OeJA**
- Cookie: _rails42_session=Lzc5cmN2NTkrQnB5WmFzYTZRTVRXeThjb1RqME1PYVQzajBDcmRKZ0ZUY1UrRnU4b3pLNTlpTXhGZUI4c29BYkppSkVEYmgvOTlPOEF4c2pSanl6TG5nZUdtZmlsVnRlQTdwOWQ2bi9sUkF4N3dWWk1TNkxwWUhwaUxoWDFJdkUxQ24vMThlWWVnaEdhWU1uNTV6WjNRPT0tLUgwVnRWQmUvQ2xPNVdQY0RLOVRaVmc9PQ%3D%3D--ea9c4fdba5a8797f5d1e936c3d19bedbecaf5412

### Request Headers with Angular
- Accept:application/json, text/plain, */*
- Accept-Encoding:gzip, deflate, sdch
- Accept-Language:en-US,en;q=0.8
- **access-token:YM73e8En3uAO0K0NTwImFA**
- Cache-Control:max-age=0
- **client:tqp1aD3uM7pI9w9fRmluzA**
- Connection:keep-alive
- DNT:1
- Host:api.myapp.io
- If-Modified-Since:0
- Origin:http://myapp.io
- Referer:http://myapp.io/
- **token-type:Bearer**
- **uid:myemail@gmail.com**
- User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/4
- not sending expiry at the moment

**Comment by dcunited001** [comment]
One thing i'm noticing is that, when my API server responds to each Angular request, it includes the headers for token, token-type, etc in the response.  

When the server responds to my original iOS sign in request, it includes those response headers.  But subsequent requests to validate_token do not include those response headers.

**Comment by dcunited001** [comment]
I got it, my Angular client was accounting for the changing access token, but my iOS/Android clients were not.  

```
# for now, setting this in devise_token_auth.rb solves the problem
config.change_headers_on_each_request = false
```

is there any way to set this to behave differently for the mobile and web clients?

**Comment by casertap** [comment]
@dcunited001 I could not solve this problem using your solution.
Do you have any idea what is the problem? check my issue #305, please.
Thanks

**Comment by booleanbetrayal** [comment]
Closing this since it seems like your particular issue is resolved @dcunited001 . Please let me know if you're experiencing additional issues or file a new issue if you have ideas around conditional `change_headers_on_each_request` support

**Comment by vipin8169** [comment]
I am getting a similar problem. When config.change_headers_on_each_request = false everything works fine, but when set to true i am getting this problem. Following rspec describes the scenario
```
AUTH_HEADER_KEYS = ['access-token', 'client', 'token-type', 'expiry', 'uid', 'Content-Type']
describe "AuthSign In" do
    it "allows api request with auth token" do
      post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json  	//Login Request
      expect_status(200)
      expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq 6
      auth_header = response.header.slice(*AUTH_HEADER_KEYS)
      get "/api/v1/cycle_days", {}, auth_header									//First request after login
      expect_status(200)
      expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq 6
      auth_header = response.header.slice(*AUTH_HEADER_KEYS)
      get "/api/v1/cycle_days?month=#{Date.today.month}&year=#{Date.today.year+1}&duration=2", {},auth_header	//Second request after login
      expect_status(200) #OK
      expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq 6
    end
end
```

After login I am getting the correct response headers containing all the AUTH_HEADER_KEYS, but on the response to First request, I am not getting the AUTH_HEADER_KEYS in the response, hence the Second request after login fails

**Comment by vipin8169** [comment]
Now I truly understand how this gem functions, it was unclear before. You may use the following rspec to grasp it completely:
`describe "Devise Token Auth" do
    describe "Sign In" do
      it "success with correct auth token and email" do
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        expect_status(200)
        expect_header('token-type', "Bearer")
      end

      it "allows api batch requests with auth token" do
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        expect_status(200)
        expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq AUTH_HEADER_KEYS.size
        auth_header = response.header.slice(*AUTH_HEADER_KEYS)
        get "/api/v1/cycle_days", {}, auth_header
        expect_status(200)
        expect((response.header.slice(*AUTH_HEADER_KEYS).size)).to eq 1 # AUTH_HEADER_KEYS will not be present in the response of simultaneous batch requests
        get "/api/v1/cycle_days", {}, auth_header                       # They must use the global values of AUTH_HEADER_KEYS, which were executed from the previous request
        expect_status(200) #OK
        expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq 1
      end

      it "allows api non-batch requests with auth token" do
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        expect_status(200)
        expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq AUTH_HEADER_KEYS.size
        auth_header = response.header.slice(*AUTH_HEADER_KEYS)
        Timecop.freeze(Time.now + DeviseTokenAuth.batch_request_buffer_throttle) do
          get "/api/v1/cycle_days", {}, auth_header
          expect_status(200)
          expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq AUTH_HEADER_KEYS.size
        end
      end

      it "allows api batch requests with auth token within an interval specified by batch_request_buffer_throttle parameter" do
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        expect_status(200)
        expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq AUTH_HEADER_KEYS.size
        auth_header = response.header.slice(*AUTH_HEADER_KEYS)
        Timecop.freeze(Time.now + DeviseTokenAuth.batch_request_buffer_throttle-1) do
          get "/api/v1/cycle_days", {}, auth_header
          expect_status(200)
          expect(response.header.slice(*AUTH_HEADER_KEYS).size).to eq 1
        end
      end
    end

    describe "Unsuccesful Sign In" do
      it "doesn't allow api request with auth token" do
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": ""}, :format => :json
        expect_status(401)
        auth_header = response.header.slice(*AUTH_HEADER_KEYS)
        get "/api/v1/cycle_days", {}, auth_header
        expect_status(401)
      end
    end

    describe "Sign Out" do
      it "should expire the auth token" do
        # Sign In
        post "/api/v1/auth/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        access_token = response.header['access-token']
        uid = response.header['uid']
        client = response.header['client']
        # Sign out
        delete "/api/v1/auth/sign_out", {'uid': uid, 'client': client,'access-token': access_token, 'Content-Type' =>'application/json'}
        expect_status(200) #OK
        expect_json("success": true)
      end
    end
end`

**Comment by vipin8169** [comment]
On successful login, a token is generated which keeps changing every 5 seconds. 
Every request generates a response which contains these parameters:
['access-token', 'client', 'token-type', 'expiry', 'uid']
However, for batch requests, i.e. the ones fired within an interval of 5 seconds these parameters will not be present, and should be extracted from previous request.
Alternately, you must maintain these 5 global variables which will be available for all the requests upon successful login.
If a request contains these 5 variables then those values should be used for authentication, otherwise the ones present in the global variables should be used.
If a request contains these 5 variables then, the global variables should also be updated.
