### ISSUE TITLE
HI, This is more of a doubt since I could not finding anything related to this in your documentation.

### ISSUE THREAD

**Issue by sonuoommen** [lynndylanhurley/devise_token_auth#300]
In devise it is configurable to use email or mobile_number or username as we wish with password for authentication or sign in.
   Is it possible with this gem ?. Can I use mobile_numer instead of email ?
I am getting this error  "undefined method `provider' for #<User:" which I can see from code is hardcoded to be email.

**Comment by booleanbetrayal** [comment]
`provider` refers to the mechanism used to distinguish the user (email, facebook, github, etc), where `uid` is the globally unique value for that provider. In theory, you could add support for any provider you'd like, but this is not a particular provider option that devise_token_auth supports out of the box. Hope this helps!
