### ISSUE TITLE
How to skip confirmation on register but possibility to ask later

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#303]
Some apps, automatically log the user after registration, but can ask to confirm the email to use a certain feature. Is it possible to do the same thing ?

Thanks !

**Comment by truthSeekr** [comment]
+1

**Comment by zachfeldman** [comment]
Seems like we have a solution for this one, so closing for now.

**Comment by mhluska** [comment]
Is this still relevant in 2019? The link posted above points to a line on the `master` branch so not sure what condition to remove.
