### ISSUE TITLE
The action 'twitter' could not be found for DeviseTokenAuth::OmniauthCallbacksController

### ISSUE THREAD

**Issue by PenguinOfWar** [lynndylanhurley/devise_token_auth#309]
Hi there,

Unfortunately getting this error on the oauth2 callback.

    The action 'twitter' could not be found for DeviseTokenAuth::OmniauthCallbacksController

Same thing happens for Facebook. The call redirects to the social network fine, but then fails on the callback.

As far as I can tell, routes and initializers are configured correctly and all gems are up to date.

**routes.rb**

     mount_devise_token_auth_for 'User', at: 'auth'

**config/initializers/omniauth.rb**

    provider :facebook,      [redacted], [redacted]
    provider :twitter, [redacted], [redacted]

Everything else in the gem works perfectly fine.

**Comment by akber4747** [comment]
@PenguinOfWar did you ever resolve this? I'm in the same boat.

**Comment by PenguinOfWar** [comment]
Unfortunately not. I need to delve into it in a bit more detail, but I just haven't had the time. 

If I find a solution, I'll definitely advise you.

**Comment by PenguinOfWar** [comment]
I updated everything once again to the latest versions and this went away, but was replaced with another issue. Am closing this to open a new issue.

**Comment by akber4747** [comment]
@PenguinOfWar thanks for replying.
