### ISSUE TITLE
Android native - Unpredictable 401

### ISSUE THREAD

**Issue by SvehlaJan** [lynndylanhurley/devise_token_auth#313]
Hello. I'm developing native Android app and using Rails 4.2.1 with devise_token_auth for backend. After hours of trying I managed to make communication working. I set config.change_headers_on_each_request = false and in Android headers I am sending the same values with every request.

However, the server responds unpredictably. Sometimes everything works fine, but more often requests are not authorized (even though they have still the same headers) and get authorized after a few tries. Crucial operation (which almost never works) is when device sends two request immediately.

I overrode SetUserByToken concern and in logs I can see that in case of unauthorized requests it is not executed at all. In my Rails project I am using Devise simultaneously so I have suspicion that Devise could overtake the execution but I have no idea what to research more. I am an Android developer and this is my fist project with Rails (and backend).

gems: http://pastebin.com/fZjbsJWp
routes.rb: http://pastebin.com/s802FzyK
stacktrace: http://pastebin.com/B0z2XiJL
Android APICall: http://pastebin.com/AbXgLmhD

I am grateful for any suggestion what to do.

**Comment by booleanbetrayal** [comment]
@SvehlaJan - Can you try re-pointing to master and see if that resolves your issue?

```ruby
gem 'devise_token_auth', :git => 'https://github.com/lynndylanhurley/devise_token_auth.git', :branch => 'master'
```

**Comment by SvehlaJan** [comment]
Hello. Thanks for your response. Unfortunately it didn't fix the issue.
At first it seemd to work, but the occurence-rate of the errors change with every restart of Rails (Unicorn).
I was trying to debug it some more with Curl and came up with these findings:
- it applies mostly to specific routes - here is a stacktrace with explanation - http://pastebin.com/Fvmr4zqc

So I assume there is a conflict with Devise - which tries to authenticate even in /api namespace.

I will try to reinstall Devise and some other gems and post the result.

**Comment by booleanbetrayal** [comment]
Have you figured out the issue @SvehlaJan? If not, how are you storing the token client-side? I've seen mixed issues with cookie-backed stores, where `localStorage` seems to handle things a bit better.

**Comment by SvehlaJan** [comment]
Hello. No, I didn't.
I reinstalled both devise_token_auth and Devise - problems remained
Then I divided users to two models:
- admins - which is used only through web - only Devise
- users - which is used only throught json API - only devise_token_auth
It remained the same - after start and sign_in, all request are unauthorized by Devise. Then, after I change something in controller, it is handled by devise_token_auth.

And a new problem came up - after I called bundle update there were some errors with BCrypt. When I resolved it, method valid_token? stopped working and valid tokens are no longer authorized.

After this I was so hopeless, desperate and disguised that I wrote my own token authentication.

**Comment by booleanbetrayal** [comment]
Sorry to hear that. Do you happen to remember what BCrypt errors you were seeing?

**Comment by zachfeldman** [comment]
Hi there @SvehlaJan and @booleanbetrayal    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
