### ISSUE TITLE
Devise Email Validation

### ISSUE THREAD

**Issue by BrunoRomes** [lynndylanhurley/devise_token_auth#314]
Hello,

in our application we use devise_token_auth, but right now we need to be able to use a solution implemented in devise (namely, the possibility to scope the login to subdomains[, as seen here](https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain)). The problem is that devise_token_auth ignores Devise's email validation and makes it own, thus preventing this feature from being used.
Making this change won't be easy, though, since adopting Devise's email validation will result in considerable changes and probably in breaking behaviours in projects that use devise_token_auth.
Still, having the same kind of validations in devise_token_auth seems a bad choice and ideally it should be fixed.

**Comment by neutronz** [comment]
Hey @BrunoRomes just submitted a PR for a similar issue because it seems there's no way of adding "subdomain" into the finder methods regardless of the email validations. I'd like your feedback https://github.com/lynndylanhurley/devise_token_auth/pull/382

**Comment by BrunoRomes** [comment]
Hey @neutronz , nice PR.
Although I can't try it out now (we adopted another solution), it seems your PR really solved the problem without producing undesired side effects (congratulations).

The only change I would make is to define the set_auth_hash! only once (right how you defined it in `app/controllers/devise_token_auth/concerns/set_user_by_token.rb` and `app/controllers/devise_token_auth/passwords_controller.rb`

**Comment by zachfeldman** [comment]
PR is closed and last post was 2 years ago, closing this one out for now
