### ISSUE TITLE
Can't authorize (user_signed_in? always show false)

### ISSUE THREAD

**Issue by BjornMelgaard** [lynndylanhurley/devise_token_auth#316]
`user_signed_in?` always show `false` in the [`_debug.slim`](https://github.com/BjornMelgaard/todoapp/blob/master/app%2Fviews%2Flayouts%2F_debug.slim#L4), even when I authorized using `devise_token_auth`

``` slim
p "user.signedIn" from "ng-token-auth" = {{ user.signedIn ? "true" : "false" }}
p "user_signed_in?" from "devise" = #{user_signed_in?}
```
### Video below

[![Video](http://img.youtube.com/vi/9Wek06pinBg/0.jpg)](https://www.youtube.com/watch?v=9Wek06pinBg)

**Comment by gadikotamohan** [comment]
@BjornMelgaard Yeah, it because of comparing two variable of different data types..

Here is the issue 
result = @token_equality_cache[key] ||= (BCrypt::Password.new(token_hash) == token)
BCrypt::Password.new(token_hash)  is of BCrypt::Password type
token is of string type 

as a fix in your user.rb you can write following in your user model.

  DeviseTokenAuth::Concerns::User.module_eval do
    def self.tokens_match?(token_hash, token)
      @token_equality_cache ||= {}

      key = "#{token_hash}/#{token}"
      result = @token_equality_cache[key] ||= (BCrypt::Password.new(token_hash).to_s == token)
      if @token_equality_cache.size > 10000
        @token_equality_cache = {}
      end
      result
    end
  end
  include DeviseTokenAuth::Concerns::User

**Comment by gadikotamohan** [comment]
@booleanbetrayal would suggest this fix.

**Comment by BjornMelgaard** [comment]
Thank, @gadikotamohan  and @booleanbetrayal :smile: 
I do not know why, but it did not work, maybe because `tokens_match?` never called.

`self.tokens_match?` was successfully substituted (I checked it with `show-method DeviseTokenAuth::Concerns::User.tokens_match?` in `pry` console), then I put [debug methods](https://github.com/BjornMelgaard/todoapp/blob/dcdc00b3092626938ca1458f81f27df542bfab43/app/models/user.rb#L7) and, as you can see, in [log](http://pastebin.com/VAKvYFGh) "tokens_match was called" never encountered, unlike "User was called"

**Comment by booleanbetrayal** [comment]
@gadikotamohan / @BjornMelgaard - I'm seeing the equality operator work as expected without any sort of explicit casting. BCrypt::Password overrides the [equality operator](http://bcrypt-ruby.rubyforge.org/classes/BCrypt/Password.html#M000009) for this very use-case

**Comment by BjornMelgaard** [comment]
@booleanbetrayal, Could I ask you deploy my app on your computer and test it? :smiley:

**Comment by booleanbetrayal** [comment]
I'm in the middle of a cross-country move, so will most likely be awhile before I could get around to looking at this. Sorry!

**Comment by BjornMelgaard** [comment]
You said that you'll do it, what could be better? :smile: 
In turn, I will also look for a solution

**Comment by BjornMelgaard** [comment]
I think I always something missing during installation.
I tried different versions of the gem, tried to use `bower` instead `rails-assets`, tried to alter a working applications to fit my needs and always `user_signed_in?` was equal to `false`.

**Comment by gadikotamohan** [comment]
@booleanbetrayal  my bad sorry to bother, I do see equality operator overridden in BCrypt::Password but that's how I fixed my issue.

**Comment by mrodal** [comment]
I have a similar problem: after logging in, on the controllers :authenticate_user! always fails, user_signed_in? is always false and current_user always nil.. but the angular app successfuly retrieves the user data and maintains the session 
Any ideas?

**Comment by klm88** [comment]
Why wasn't the .to_s ever integrated into the gem? I can see that if I change to:

(BCrypt::Password.new(token_hash).to_s == token)

The result from valid_token? then returns true...otherwise result is null.

**Comment by hugobast** [comment]
A word of caution here; this `to_s` shenanigans is clearly wrong during normal operations:

```
[1] pry(DeviseTokenAuth::Concerns::User)> token
=> "_-Yew_yUvXAiZTZy01mogw"
[2] pry(DeviseTokenAuth::Concerns::User)> token_hash
=> "$2a$10$YDkV9dtvlmh3B.ot53goQuwjEoAeiPZzipn4f5iyb2ZjOx1F4oWya"
[3] pry(DeviseTokenAuth::Concerns::User)> BCrypt::Password.new(token_hash).to_s == token
=> false
[4] pry(DeviseTokenAuth::Concerns::User)> BCrypt::Password.new(token_hash) == token
=> true
```

If for whatever reason `$2a$10$YDkV9dtvlmh3B.ot53goQuwjEoAeiPZzipn4f5iyb2ZjOx1F4oWya` is what you guys are sending up to the client then yes `to_s` will work but also `token_hash == token` will work (they both the same). If that's what's happening for people where the default implementation isn't working I'd recommend checking what is sent to the client and why it's not sending the pre-hashed value.

**Comment by zachfeldman** [comment]
Hi there @BjornMelgaard    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
