### ISSUE TITLE
delete tokens after password change

### ISSUE THREAD

**Issue by StringfellowHawke** [lynndylanhurley/devise_token_auth#318]
Using the email authentication, if I have 2 sessions on different browsers/devices and I reset my password using 1 of the sessions, my other session is still valid.  Wouldn't it be prudent to delete all the existing tokens so all my sessions are killed when the password is changed?

**Comment by booleanbetrayal** [comment]
I think that would break some expected use-cases. I could see token invalidation being a configurable feature though (defaulting to false to retain backwards compatibility). I'll take a look at a PR to that effect.

**Comment by booleanbetrayal** [comment]
Closed via #474

**Comment by StringfellowHawke** [comment]
Thanks @paulosoares86

**Comment by paulosoares86** [comment]
You're welcome, @StringfellowHawke :+1:
