### ISSUE TITLE
Getting `table_exists?' error when using devise_token_auth with Mongoid

### ISSUE THREAD

**Issue by WagnerMatos** [lynndylanhurley/devise_token_auth#325]
I've been reading and reading the documentation but couldn't find anything about different ORM and whether is there an issue. 

I've devise_token_auth in conjunction with Devise (3.2) and Mongoid (4), and I keep getting the above error (`undefined method`table_exists?' for User:Class (NoMethodError)`)

When I remove `include DeviseTokenAuth::Concerns::User` I don't get the error but the authentication doesn't work. What am I missing?

**Comment by kylessnell** [comment]
Not sure if you're still using this @WagnerMatos, but this gem presently relies on ActiveRecord (take a quick look at the source for all the touch points). About a year ago @ybian made some quick changes to the then current version of the gem (see the thread [here](https://github.com/lynndylanhurley/devise_token_auth/issues/15)) and also a working [demo app](https://github.com/ybian/devise_token_auth_demo/tree/mongoid) to get things up and running with Mongoid. If you're really in a pinch these changes work decently well, but don't include any of the changes from the last year. If I had more time I'd try and get a full fledged pull request together that totally works with Mongoid; maybe if enough people are willing we could make it a team effort.

**Comment by WagnerMatos** [comment]
Hey @kylessnell , thanks for the reply. Unfortunately I moved away from using Devise Token Auth and Devise in the project and have done my own authentication.

**Comment by zachfeldman** [comment]
Great. Closing this then
