### ISSUE TITLE
Concern causes app to connect to database when precompiling assets.

### ISSUE THREAD

**Issue by ArneZsng** [lynndylanhurley/devise_token_auth#327]
The user concern:

`include DeviseTokenAuth::Concerns::User`

causes the the app to try to connect to the database on initialize. This causes a problem when precompiling assets in a Dockerfile with 

`bundle exec rake assets:precompile` 

as no database is available during building the Docker image.

I have found a workaround for now by setting an environment variable dynamically:

```
  if ENV['INITIALIZE'] == "true"
    include DeviseTokenAuth::Concerns::User
  end
```

**Comment by booleanbetrayal** [comment]
Hmmm ... I'm open to suggestions on a generalized approach at resolving this in a way that is backwards compatible and remains performant for existing users. Maybe something along the lines of checking `ActiveRecord::Base.connection` and `rescue`ing gracefully upon failure?

**Comment by luyzdeleon** [comment]
Has there been any news on this?
