### ISSUE TITLE
group authentication not redirecting

### ISSUE THREAD

**Issue by StringfellowHawke** [lynndylanhurley/devise_token_auth#332]
``` ruby
class DemoGroupController < ApplicationController
  devise_token_auth_group :member, contains: [:user, :admin]
  before_action :authenticate_member!
.
.
.
end
```

If i try to access something in the controller above without the proper token headers of a user or admin, the authentication isn't redirecting and I can access the actions.

**Comment by betoharres** [comment]
same here

**Comment by zachfeldman** [comment]
Hi there @StringfellowHawke    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
