### ISSUE TITLE
NameError (uninitialized constant DeviseTokenAuth::Concerns::User::BCrypt)

### ISSUE THREAD

**Issue by danielBlowingNose** [lynndylanhurley/devise_token_auth#333]
I get error when doing multiple API requests in my ROR application running this gem which is deployed on heroku using Puma (based on this article https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server). Especially the error occurs when I have set Puma parameter -w (defining number of workers) to amount bigger than 1. Interestingly the error does not occur when I have set parameter -t (number of threads) to amount biger than 1. So it is probably solely connected to web concurrency defined by puma workes. Please see below details of the error:

app[web.1]: NameError (uninitialized constant DeviseTokenAuth::Concerns::User::BCrypt):
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/devise_token_auth-0.1.30/app/models/devise_token_auth/concerns/user.rb:111:in `token_is_current?'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/devise_token_auth-0.1.30/app/models/devise_token_auth/concerns/user.rb:86:in `valid_token?'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/devise_token_auth-0.1.30/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:40:in `set_user_by_token'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/devise_token_auth-0.1.30/lib/devise_token_auth/controllers/helpers.rb:115:in `current_user'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/devise_token_auth-0.1.30/lib/devise_token_auth/controllers/helpers.rb:103:in `authenticate_user!'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:424:in `block in make_lambda'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `call'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `call'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `block in halting'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `call'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `block in halting'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'

**Comment by salmanasiddiqui** [comment]
I am having this issue aswell

**Comment by booleanbetrayal** [comment]
thanks @andersonbrandon

**Comment by toshimaru** [comment]
@booleanbetrayal any plan to release new gem version?

**Comment by booleanbetrayal** [comment]
Would like to get a new gem version out in the next couple of days, but am waiting for one changeset to make it in. In the meantime, you could always point to master:

```ruby
gem 'devise_token_auth', :git => 'https://github.com/lynndylanhurley/devise_token_auth.git', :branch => 'master'
```

**Comment by toshimaru** [comment]
ok, thanks!!!
