### ISSUE TITLE
Ember Simple Auth

### ISSUE THREAD

**Issue by ghost** [lynndylanhurley/devise_token_auth#334]
Hey!

Ember simple auth sends a request with these headers, but according to the docs it wont work:

**Authorization:**Token token="Q1AyBcNUNEv65djHyYFu", uid="765611.........."

Any way we can get support for this type of request (token="") in the gem?

Thanks.

**Comment by mathiasAichinger** [comment]
I think the preferred way is to customize the ember-simple-auth plugin. I will look into that the next days.

**Comment by zachfeldman** [comment]
Hi there @ghost   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
