### ISSUE TITLE
Allow Omniauth user reset password

### ISSUE THREAD

**Issue by ianchen06** [lynndylanhurley/devise_token_auth#335]
Hi there thanks for this great gem, I currently have a working system with both Devise email&password authentication as well as Omniauth-Facebook authentication.

I'm aware that currently this gem does not allow Omniauth sign up users to reset their passwords, is this feature on the roadmap? Or is there any difficulties with implementing this feature? I'm willing to send in a PR for this feature.

Thanks,

**Comment by booleanbetrayal** [comment]
This feature isn't currently on the roadmap, but a few users have said they'd be interested in something along those lines. Today, you're fixed to a specific provider (email, fb, google, etc). So if you're user is registered using omniauth, devise_token_auth won't even attempt to do anything with email credentials, they aren't tied to your provider.

In essence, whatever implementation is made would have to be savvy enough to allow for any and all providers, as it seems somewhat arbitrary to allow FB and email, but not FB and Google, etc. It starts getting tricky as to how you want to handle those sort of provider validations, etc. 

Going to close this ticket and direct you to #23.
