### ISSUE TITLE
Restricting access to controllers methods

### ISSUE THREAD

**Issue by gkopylov** [lynndylanhurley/devise_token_auth#340]
Hi, there.

The idea of this gem to improve security aspects of a token authentication is very nice, but some moments are bowl me out, for example there is almost no restriction access to controllers methods. It is a bad practice to make all methods public in controller, you can read about it here https://www.safaribooksonline.com/library/view/rails-cookbook/0596527314/ch04s13.html and here http://stackoverflow.com/questions/4495078/protected-and-private-methods-in-rails

Btw, I think there are some long methods that need to be refactored and we need to add rubocop to make the code cleaner.

PS. Is there any serious apps using this gem in production or it would be better to handle token authorization by yourself?(just curious).

**Comment by lynndylanhurley** [comment]
@gkopylov - thanks for your feedback. We do accept pull requests.

**Comment by gkopylov** [comment]
Ok, I have done some improvements but we still need to make this code better :-)

**Comment by lynndylanhurley** [comment]
Thanks, we will review ASAP.

> Btw, I think there are some long methods that need to be refactored and we need to add rubocop to make the code cleaner.

I mostly agree with this, but let's proceed on a case-by-case basis. I worry sometimes about breaking up long functions just for the sake of it. I know that code climate complains about long functions, but there are also really good arguments for them. ([This article](http://number-none.com/blow/john_carmack_on_inlined_code.html) for example.)
