### ISSUE TITLE
Multiple Devise Models. One using token

### ISSUE THREAD

**Issue by pducks32** [lynndylanhurley/devise_token_auth#342]
So I have a rails app where Admins can login and also Clients, but Clients can only login from a separate app that uses j-toker to sign them in. The problem is allowing both. I created a seperate API controller for devise_token_auth but it doesn't seem to get called it always seems to call the standard ApplicationController's `:authenticate_admin!` method which tells me its using ApplicationController. Any ideas on how to fix the problem?

Update: From what I can tell its because this gem's main controller inherits from `DeviseController` which inherits from `Devise.parent_class` which is auto set to ApplicationController. Still can't get anything to work but if that helps anyone help me than awesome.

**Comment by frankmarineau** [comment]
Bump, I also have two models for Auth, and would like one of them to use tokens and the other to use normal Devise auth. Is there a way to do this right now?

**Comment by zachfeldman** [comment]
Hi there @pducks32 and @frankmarineau   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
