### ISSUE TITLE
Using devise and devise_token_auth side by side

### ISSUE THREAD

**Issue by abhayastudios** [lynndylanhurley/devise_token_auth#343]
I think this is more of a documentation issue than a coding issue, however considering that issues #43, #159 and #290, nor the docs are really clear to me I'd like to find out what the 'best practice' is and opt for it to be added more clearly to the docs.

So I want to use devise and devise_token_auth side by side. I am using this for routes which creates the regular devise routes and the devise_token_auth in the api namespace (as described in the docs):

```
devise_for :users
namespace :api, defaults: {format: 'json'} do
  scope :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
    resources :votes, only: [:index, :show, :create]
  end
end
```

Considering the conflict of the DeviseTokenAuth concern and protect_from_forgery with :null_session & :exception, I decided to use different application controllers. This is the 'regular' application controller:

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
```

This is the application controller for the API namespace:

```
class Api::ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  protect_from_forgery with: :null_session
  respond_to :json
end
```

Now when I access the votes resource through the API namespace the application controller for the API namespace is being used, so all is good. However, when I access any of the resources created by the mount_devise_token_auth_for method the regular ApplicationController is used and not the one from the API namespace. Looking at the routes indeed I see that the controller used is not in the API namespace.

```
api_user_session_path   POST    /api/v1/auth/sign_in(.:format)  devise_token_auth/sessions#create {:format=>"json"}
```

Short of copying the devise_token_auth controllers to the api namespace, I'm not sure what to do. Is there an easy way to make the devise_token_auth controllers inherit from the API application controller? What is the best way to handle this? Is there an easy way of installing the controllers (like: rails g devise_token_auth:controllers)?

Thanks!

**Comment by abhayastudios** [comment]
So it is indeed working when I do the following: 

I override the controllers used in the routes like this:
```
mount_devise_token_auth_for 'User', at: 'auth', controllers: {
  confirmations:      'devise_token_auth/confirmations',
  passwords:          'devise_token_auth/passwords',
  omniauth_callbacks: 'devise_token_auth/omniauth_callbacks',
  registrations:      'devise_token_auth/registrations',
  sessions:           'devise_token_auth/sessions',
  token_validations:  'devise_token_auth/token_validations'
}
```

Then copy the devise_token_auth controllers directory from the gem to my rails project controllers and then add the ````protect_from_forgery with: :null_session```` to the devise_token_auth/application_controller.rb.

Is there a better way?

**Comment by Dschee** [comment]
@abhayastudios: I don't think copying the gem logic into the project is a real solution, it's more like a hacky workaround because it prevents you from upgrading the gem without re-copying those files and testing if that still is a solution again and again in the future. I'd love to see official support for such use cases since I'm having them, too (as well as some others I've seen post issues here).

**Comment by abhayastudios** [comment]
ok re-opening

**Comment by fabiosammy** [comment]
I do it to workaround:

```ruby
# Devise authorize
  before_action :skip_authenticate

  private
  def skip_authenticate
    unless params[:controller].split('/')[0] == 'devise_token_auth'
      authenticate_user!
    end
  end
```

(Its same to CSRF)

**Comment by simon0191** [comment]
I'm having the same issue.
It would be great something like:
```
mount_devise_token_auth_for 'User', at: 'auth', base_controller: 'Api::V1::ApiController'
```

**Comment by LaurensN** [comment]
Same issue here, agree with Simon's proposal.

**Comment by farmisen** [comment]
Thanks to @fabiosammy snippet, that's what I ended doing:
```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: -> {params[:controller].split('/')[0] == 'devise_token_auth'}
end
```

**Comment by jotolo** [comment]
I was working in a similar case where I needed to use both, devise+devise_token_auth in a spree application. I was trying to implement authentication for spree_api and migrating the authentication of spree system(Full Stack App) to devise.
I found a way to do it and it's very simple.It's not a common thing in rails but it works great. The idea is to have a main application_controller.rb in your application and particular application_controllers for each section. In my case one for admin system in spree and the other one for API.
```
#controllers/api/v1/application_controller.rb
module Api
  module V1
    class ApplicationController < ApplicationController
      skip_before_action :verify_authenticity_token
      include DeviseTokenAuth::Concerns::SetUserByToken
    end
  end
end
```
In the API controller I included the regular DeviseTokenAuth concern to manage auth in the app that controls this application_controller.rb. Note that this controller inherits from the main application_controller.
```
#controllers/admin/application_controller.rb
  module Admin
    class ApplicationController < ApplicationController
      before_action :authenticate_user!
    end
  end
```
This controller is, well, natural behavior of devise. I just needed to add the before action method.
We just need the base application_controller ;)
```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, if: :verify_api

  def verify_api
    params[:controller].split('/')[0] != 'devise_token_auth'
  end
end
```
Our main application_controller.rb looks like this. You need to keep the CSRF token protection but you can avoid it when an API request arrive.
The idea is to redirect each flow in your application. the ones that belongs to your full-stack app and the other ones that belongs to your API. Well, in this case to my API :smile: 
This scenario was tested using [devise (4.2.0)](https://rubygems.org/gems/devise/versions/4.2.0) and [devise_token_auth (0.1.40)](https://rubygems.org/gems/devise_token_auth/versions/0.1.40).
I hope I can help someone with this example.
Regards

**Comment by zachfeldman** [comment]
Sounds like we have a solution here, so I'm going to close this one out for now.

**Comment by BKSpurgeon** [comment]
Just to make clear to future readers - you might not want to skip authentication entirely if you are running devise and devise_token_auth side by side as per the solution fabiosam suggests.

**Comment by matedemorphy** [comment]
Doesn't works with Rails 6 😢

**Comment by cpt22** [comment]
Seconded for Rails 6. I have tried both methods suggested in the Docs FAQ ([https://devise-token-auth.gitbook.io/devise-token-auth/faq](https://devise-token-auth.gitbook.io/devise-token-auth/faq)) but neither work. It appears that the controller that devise_token_auth is using is the main ApplicationController and not the API ApplicationController. When the skip CSRF before_action callback is specified in only the API controller, the missing CSRF exception is thrown, but when it is included in the main ApplicationController, the exception is not thrown.
