### ISSUE TITLE
Support for Lockable and Timeoutable when using Devise and DeviseTokenAuth

### ISSUE THREAD

**Issue by Dschee** [lynndylanhurley/devise_token_auth#346]
I'd like to use DeviseTokenAuth only for the API part of my application and continue using Devise for my normal application. This is to embrace maximum security without using a single-page application. I'm not sure if I'm on the right track, but my idea was to use this gem alongside devise where devise would be responsible for authenticating the website users and this gem would authenticate users through the API for clients (e.g. mobile).

First I want to point to the fact that the README kinda fails at explaining how this gem could be used for API only authentication continuing to use Devise for the website – at least I couldn't find the right section for that so that's why I'm kinda unsure how to do this. Just created an issue for that, too: https://github.com/lynndylanhurley/devise_token_auth/issues/345

**But here's the _real question_ I want to ask here:**
Can I use :lockable and :timeoutable for my Devise authentication while also including DeviseTokenAuth in my project or will this break something within DeviseTokenAuth or affect its security in any way?

**Comment by guentr** [comment]
Hi, have you found a solution for the :lockable and :timeoutable options in combination with DeviseTokenAuth?

**Comment by Dschee** [comment]
I didn't have time to continue my efforts on the project where I use devise_token_auth yet, sorry. But I will keep you updated in case I discover any solutions or workarounds.

**Comment by chrisroseuk** [comment]
+1

**Comment by lgrayland** [comment]
+1

**Comment by cerico** [comment]
+1

**Comment by johannasc** [comment]
+1

**Comment by genaromadrid** [comment]
+1

**Comment by zachfeldman** [comment]
Seems that this PR added support at least for lockable. If people feel strongly about timeoutable (and it's not already done/filed), feel free to file a new issue.

**Comment by manjinder98** [comment]
Is there any good documentation on how to configure this feature? I followed these [steps](https://github.com/heartcombo/devise/wiki/How-To:-Add-:lockable-to-Users) but it seems not working.
