### ISSUE TITLE
Is it possible to authenticate_user! without failing the filter chain?

### ISSUE THREAD

**Issue by ronshoshani** [lynndylanhurley/devise_token_auth#353]
I have an API that needs to return results based on whether there is a signed in user or not.

In my controller, I would like to do something like the following:
- Try to authenticate_user, but don't fail the filter chain if authentication failed
- Use current_user when creating the response payload (current_user will either contain nil or the authenticated user)

Is this possible?

**Comment by booleanbetrayal** [comment]
Why not just have the client handle the 401 unauthorized code appropriately?

**Comment by ronshoshani** [comment]
@booleanbetrayal How will this answer the above requirement?
I'm looking to *not fail* the request, and always return a response. The response will change a little based on whether there is a current_user or not.

**Comment by zachfeldman** [comment]
Hi there @ronshoshani   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
