### ISSUE TITLE
github provider callback url (?auth_token)

### ISSUE THREAD

**Issue by hoopoe** [lynndylanhurley/devise_token_auth#354]
Hello

I've application with github provider and it works locally (localhost:3000). 
But when app is published to heroku signin is not working. 
My return url looks like

<pre>
https://xxx.herokuapp.com/?auth_token=xxxxx&client_id=XXXXXQ&config=&created_at=2015-08-23+18%3A15%3A50+UTC&email=&expiry=1441631574&id=7&image=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F534606%3Fv%3D3&name=XXX+XXX&nickname=xxx&provider=github&uid=534606&updated_at=2015-08-24+13%3A12%3A54+UTC
</pre>

Is it looks good? (I've 2 applications with different secret configured on github, gem 'devise_token_auth', ">= 0.1.32.beta9")
Thanks!

**Comment by hoopoe** [comment]
ok. It doesn't work coz of gem 0.1.34 (selected by heroku). 
Probably "#" is missing and it should looks like 
<pre>
https://xxx.herokuapp.com/#?auth_token...
</pre>
I didn't test, stacked with 0.1.32.beta9...

**Comment by zachfeldman** [comment]
Closed due to lack of information and from 2 years ago
