### ISSUE TITLE
Devise replacement or add-on?

### ISSUE THREAD

**Issue by i8ramin** [lynndylanhurley/devise_token_auth#36]
Hi, I am trying to use this gem, but it is not clear to me if this gem is a replacement for Devise or if it compliments it as an add-on. I did notice that the gem depends on Devise, but when I try to add it to my project, I am faced with a number of issues. I will outline them below and hopefully you or someone else on this thread can help out.

In my Gemfile I've tried adding just this gem and also this gem along with Devise:

```
gem 'devise', '~> 3.2.x'
gem 'devise_token_auth'
```

I have both a devise.rb and devise_token_auth.rb config files. Their contents are as follows:
https://gist.github.com/i8ramin/ab325f2efb730931a5b5

Should my routes file have both the devise_for directive as well as the mount_devise_token_auth_for? My project which already had devise also has a devise_for in the routes, so I wasn't sure what to do there. When I have both, I get one set of errors, when I have one, I get another set of errors.

```
devise_for :users , :path => "auth"
mount_devise_token_auth_for 'User', at: '/auth'
```

The scenario I am trying to work with is as follows:
- I have a app written specifically for oauth authentication using devise which lives at id.mysite.com
- I have  SPA using angular that I would like to be able to authenticate using oauth, similar to how facebook, google and other oauth providers work. I want my id.mysite.com to behave just like those providers. A popup opens, you login, it closes and now you are logged into the provider site as well as the app
- The SPA has no server side back-end, so I cannot use gems like omniauth, etc. this has to be done all client-side

Is this the right tool for the job?

Thanks and sorry for the long post.

**Comment by gfauredumont** [comment]
Hi,

Sorry to bother you again on the same subject but I'd prefer to be sure before migrating everything:
I'm working on a Rails website (not SPA for now) which uses Devise.
I'm now exposing an API and I need a secure and reliable token authentication for it.
My problem is that I'm not sure that Devise_token_auth will take care of everything that I already have with Devise
The default views created by default by Devise are no concern, but all the rest is... !
Should I continue using Devise alongside with Devise_token_auth (as explained [here](http://www.developingandrails.com/2015/02/api-authentication-with-devisetokenauth.html) ) or can I remove Devise (but keep my User model) and use Devise_token_auth instead ?

Thanks a lot for your work in any case !

**Comment by gfauredumont** [comment]
OK, so it looks like I'm not the only one and you already know about it (so ... sorry for that :confused: ).
For anyone looking for the same thing, here are some interesting points #114 #159 #290 #343 
I'll try try and create a PR if I manage :pray:
