### ISSUE TITLE
Block isn't called in super do |resource| override.

### ISSUE THREAD

**Issue by DeanSolecki** [lynndylanhurley/devise_token_auth#363]
I can't get this to work.  I've been trying for two days.  Anything I put in the super do block is flatly ignored.  Anything I put outside of that block runs.

Could anyone give me a working example of this so I know where I might be going wrong?

**Comment by joekr** [comment]
What version of the gem are you using? It looks like you will want at least v.0.1.32.

I'm having the same issue and updating now to see if that helps.

**Comment by DeanSolecki** [comment]
@joekr, I ended up forking on github and putting the lines I needed right in the concern, but it looks like that may have been the issue, as I was on v0.1.3x, but not v0.1.34; I want to say v0.1.33, but no one take that as certain if you are having issues, it could have been an earlier version.

**Comment by zachfeldman** [comment]
No other reports of this, so closing for now.
