### ISSUE TITLE
discrepancy between registration events

### ISSUE THREAD

**Issue by abhayastudios** [lynndylanhurley/devise_token_auth#364]
From what I see there is a discrepancy between registration events. Registration through OAuth will trigger both the <b>auth:oauth-registration</b> and <b>auth:login-success</b> events. However, registration through email will trigger only the <b>auth:registration-email-success</b> event. I think it would make sense for it to also trigger a <b>auth:login-success</b> event and for it to be consistent with OAuth registration.

By the way, I opened a couple of issues since I started working with both devise_token_auth and ng-token-auth, but so far I failed to thank you for your work on these two excellent libraries! 

So thank you :)

**Comment by zachfeldman** [comment]
Hi there @abhayastudios    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by abhayastudios** [comment]
Not sure if the issue is still there or not, but I am not working with rails anymore. Thanks!
