### ISSUE TITLE
Passing access_token after signup

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#366]
I'm bring to life an old app (early 2015) that used devise_token, and noticed that the access_token, UID, expiry, and client are no longer getting passed after a user signs up. The site allows unconfirmed access, so how would I pass the header info after signup?

**Comment by ACPK** [comment]
It works locally but not on production.

**Comment by plodshooter** [comment]
As for me, it passed right way:
< HTTP/1.1 200 OK
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< access-token: OobH67eo1CotXHeUSSAgSw
< token-type: Bearer
< client: M7G7TbBxtacoFPm6OTKEcg
< expiry: 1442655591
< uid: test@test.test
< Content-Type: application/json; charset=utf-8
< ETag: W/"2c2ca7fd01e1597558b559555effe16f"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 3d59b70f-198a-4fc2-b9fd-383e3c086b97
< X-Runtime: 0.707628
< Connection: close

**Comment by zachfeldman** [comment]
Seems like this issue has an accepted solution, so closing for now.
