### ISSUE TITLE
when does tokens field get cleared

### ISSUE THREAD

**Issue by chirag7jain** [lynndylanhurley/devise_token_auth#372]

**Comment by fowkswe** [comment]
I have this question too.  Every request generates a new token.  After some clicking around:

[18] pry(main)> u.tokens.count
=> 50

Is this correct?  
Shouldn't the latest token be the only one that is needed?  
Is it safe to delete everything else?

**Comment by piya23300** [comment]
+1

**Comment by henadzit** [comment]
+1

**Comment by fowkswe** [comment]
It turns out this was caused by the CSRF token not being present.  I did this in my ApiController:

```
  # protect_from_forgery with: :exception
```

And things are now working!

**Comment by henadzit** [comment]
@fowkswe did you disable the forgery protection? I don't think it's acceptable for my use case.

If you mean the opposite, I have the protection enabled and still have my tokens growing.

**Comment by fowkswe** [comment]
@henadzit yes, I removed forgery protection which, from my understanding, is only something to be concerned about in a situation where a cookie is present.  

For me, the token authentication is in leiu of cookie / session based auth, so not having csrf protection is fine.   I think this is the case for most API based traffic.  

Someone please correct me if my thinking here is wrong.

**Comment by henadzit** [comment]
@fowkswe I gave it a bit of thought, you seem to be right. Even though I have a web client and ng-token-auth stores auth data in cookies, there is no way another site may get access to the cookie. It may send a request but it won't able to read the cookie which is needed in order to set auth headers.

Anyway, I tried to remove the forgery protection but it didn't solve the problem for me :(

**Comment by mustela** [comment]
Having the same issue here. The `tokens` array keep growing and growing.

**Comment by fowkswe** [comment]
@mustela, try adding   

''''
 protect_from_forgery with: :null_session 
''''

to your controller

**Comment by blogcraft** [comment]
I am using Rails 5 API and I get 

> undefined method `protect_from_forgery' for ApplicationController:Class (NoMethodError)

**Comment by twizzzlers** [comment]
4 months later and this is not answered? So is it safe to delete the tokens? Because if it is safe, should I do like a cron job to delete all tokens at the end of the day?

**Comment by krand7** [comment]
+1

**Comment by zachfeldman** [comment]
Hi there @chirag7jain    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by chirag7jain** [comment]
I am ok with it
