### ISSUE TITLE
React native signup/login using Facebook SDK

### ISSUE THREAD

**Issue by crysfel** [lynndylanhurley/devise_token_auth#385]
Hi Guys, I have a web app running this gem and ng-token-auth, it works great! I'm currently working on the app version using react native, but I don't know how to integrate it.

I already have the Facebook token on my react native app (Using facebook sdk), is is possible to login from a native app using this gem? is there any tutorial or guide?

I was looking at commit #323 and I'm not sure if is related or not, some advise would be great.

Thanks

**Comment by lynndylanhurley** [comment]
@crysfel - I'm working on a reflux library for this. It's 95% finished - I'm just writing the test suite now. I believe it should work with react native.

**Comment by ivks** [comment]
@lynndylanhurley sorry to disturb, but were you able to get it done. 
Can you share the link to the repo. 
In between thank you so much, for the awesome work and excellent docs for the following repos:
https://github.com/lynndylanhurley/devise_token_auth
https://github.com/lynndylanhurley/ng-token-auth

**Comment by zachfeldman** [comment]
I believe this is the library in question:
https://github.com/lynndylanhurley/redux-auth

Closing for now!
