### ISSUE TITLE
Cohabitation with doorkeeper

### ISSUE THREAD

**Issue by abarre** [lynndylanhurley/devise_token_auth#389]
I wonder if it's possible to use devise_token_auth along to doorkeeper.

I'm designing an api in grape that is documented with swagger.
In order to authenticate the swagger client, I have to use the implicit flow of oauth2. So, I'm trying to add doorkeeper for that.

For my application consuming the api written in react, I'm considering devise_token_auth but the problem is the fact that I can't understand how to protect the api endpoint between `doorkeeper_authorize` and `user_authenticate`.

I don't find any compatibility between the access_token of both system.

I would really appreciate any feedback on this subject.

**Comment by salmanasiddiqui** [comment]
@abarre were you successful? I am looking to do the same but havent started yet.

**Comment by abarre** [comment]
No, unfortunately, I decided to modify swagger in order to call devise_token_auth code.

**Comment by zachfeldman** [comment]
Closed due to inactivity and a possible solution.
