### ISSUE TITLE
Unable to Logout after sign up and/or sign in

### ISSUE THREAD

**Issue by JatinYadav1307** [lynndylanhurley/devise_token_auth#391]
Whenever I sign in to an account, I am unable to log out of it using

ROOT_URL/api/v1/auth/sign_out

I get this error every time - 

{
  "errors": [
    "User was not found or was not logged in."
  ]
}

I have tired - 

Passing
Client Header
Access Token Header
UID Header
Email Header

And nothing works.

And I am testing this on Postman for chrome REST Api tester.

Let me know how can I resolve this issue.

Thanks.

**Comment by harmoney-justins** [comment]
im observing this issue too

**Comment by alarv** [comment]
+1

**Comment by pdkproitf** [comment]
I got the same problem.

**Comment by zachfeldman** [comment]
Hi there @JatinYadav1307    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
