### ISSUE TITLE
Add better uid + provider unique support

### ISSUE THREAD

**Issue by booleanbetrayal** [lynndylanhurley/devise_token_auth#392]
This may be superseded by any of the "support multiple omniauth" tickets, but currently, we treat `uid` as unique despite the fact that we don't set relational constraints as such (just`uid` +`provider`), via a `find_by_uid` call. What should be happening at this point (if we don't get the consolidated multiple provider work done) is also passing up the`provider`.

**Comment by zachfeldman** [comment]
Hi there @booleanbetrayal   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
