### ISSUE TITLE
Errors after removing confirmable

### ISSUE THREAD

**Issue by Andrew-Max** [lynndylanhurley/devise_token_auth#397]
seems exactly like : https://github.com/lynndylanhurley/devise_token_auth/issues/58 although that issue was marked as resolved and I still see the error.

I removed `devise :confirmable`

and removed the confirmable lines from the migration by hand. Afterwards i see `NameError: undefined local variable or method `confirmed_at'`

as suggested in the other issue, adding the lines

```
  def confirmed_at
      DateTime.now
  end

  def confirmed_at=(val)
  end
```

To the my user model solves the problem but I would prefer to avoid this give that it is hacky

**Comment by fabiancarlos** [comment]
Yeah, mee to! Someone solved?

**Comment by MarketingAjay** [comment]
@Andrew-Max @fabiancarlos I just ran into the same issue.  The problem happens if your `include` statement is BEFORE the `devise` statement.  This is unfortunate because the generator puts it at the top of the model by default.  Switch the order and you should be good.

```
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include DeviseTokenAuth::Concerns::User
end
```

**Comment by jeryRazakarison** [comment]
Hi, I have a different error, while **removing :confirmable** from the `devise` statement.
I'm on Rails 5 beta, using Devise master branch, and devise_token_auth master branch.

When I make the post request, I have an error 500

    Unpermitted parameter: registration
    Completed 500 Internal Server Error in 78ms (ActiveRecord: 0.0ms)

And here is the stack
```
ArgumentError (After create callback :send_on_create_confirmation_instructions has not been defined):
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:637:in `each'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:637:in `block in skip_callback'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:568:in `block in __update_callbacks'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:566:in `reverse_each'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:566:in `__update_callbacks'
  activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:636:in `skip_callback'
  /Users/jery/.rvm/gems/ruby-2.2.2/bundler/gems/devise_token_auth-d154b0294006/app/controllers/devise_token_auth/registrations_controller.rb:39:in `create'
  actionpack (5.0.0.beta1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0.beta1) lib/abstract_controller/base.rb:183:in `process_action'
  actionpack (5.0.0.beta1) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0.beta1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```

(When I put :confirmable back in place, it works well).

Does anyone have an idea how to solve it?

Thank you very much for your help.

**Comment by zachfeldman** [comment]
Seems like the related issue has a possible fix, so closing for now.

**Comment by Herz3h** [comment]
@MarketingAjay I accidently put the include concern first and it caused this problem. I had no idea why it was asking for confirmable even tho i removed that from my user model. Thanks for the fix, works perfectly !!
