### ISSUE TITLE
Why should I use .to_json to get the right json object and not an array?

### ISSUE THREAD

**Issue by AdamQuadmon** [lynndylanhurley/devise_token_auth#400]
In order to have the correct response I need to add .to_json to render calls (`render json: {}.to_json`)

What's wrong with me?

```
#My routes
mount_devise_token_auth_for 'User', at: 'api/auth', controllers: {
      token_validations:  'overrides/token_validations'
  }

# token_validations

module Overrides
  class TokenValidationsController < DeviseTokenAuth::TokenValidationsController
    skip_before_filter :assert_is_devise_resource!, :only => [:validate_token]
    before_filter :set_user_by_token, :only => [:validate_token]

    def validate_token
      # @resource will have been set by set_user_token concern
      if @resource
        yield if block_given?
        render :json => {
                   :success => true,
                   :data => @resource.token_validation_response
               }.to_json
      else
        render json: {
                   success: false,
                   errors: [I18n.t("devise_token_auth.token_validations.invalid")]
               }.to_json, status: 401
      end
    end
  end
end
```

**Comment by zachfeldman** [comment]
Hi there @AdamQuadmon    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
