### ISSUE TITLE
change_headers_on_each_request and batch requests

### ISSUE THREAD

**Issue by AdamQuadmon** [lynndylanhurley/devise_token_auth#403]
If this flag is left true as default it's not possible to do parallel requests

to understand what I mean thake into account [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth) and an ui-route resolver:

```coffeescript
admin:
    url: '/'
    abstract: yes
    resolve:
      auth: ['$auth', '$state', ($auth, $state) ->
        $auth.validateUser()
        .catch (reason) ->
          $state.go 'sign_in', {}
          no
      ],
'admin.work':
    url: ''
    resolve:
      res1: ['Res1', 'auth', (Res1, auth) ->  Res1.get() ]
      res2: ['Res2', 'res1', (Res2, res1) ->  Res2.get() ]
'admin.work_only_not_changing_headers_on_each_request':
    url: ''
    resolve:
      res1: ['Res1', 'auth', (Res1, auth) ->  Res1.get() ]
      res2: ['Res2', 'auth', (Res2, auth) ->  Res2.get() ]

```

what can cause this?
I'm using the default configuration mounting the routes like that:

```ruby
mount_devise_token_auth_for 'User', at: 'api/auth'
```

**Comment by lynndylanhurley** [comment]
Try increasing the value of `batch_request_buffer_throttle` to something like `1.minute` and see if that fixes the issue.

**Comment by booleanbetrayal** [comment]
@AdamQuadmon - Definitely a tricky issue. we have a more detailed discussion of this issue here #51. Going to close this particular thread.
