### ISSUE TITLE
Avoid using respond_to in application controller

### ISSUE THREAD

**Issue by AlexRevin** [lynndylanhurley/devise_token_auth#41]
Hello

For API's using respond_to requires including the Mime parser, which is not needed most of the times.

Would suggest getting rid of this string:
`respond_to :json`
in
`devise_token_auth / app / controllers / devise_token_auth / application_controller.rb`

**Comment by lynndylanhurley** [comment]
I think all the `respond_to` calls have been removed now. Let me know if you find any that I missed.
