### ISSUE TITLE
Large Size on Disk

### ISSUE THREAD

**Issue by schneems** [lynndylanhurley/devise_token_auth#415]
```
~ $ du -h -d 1 vendor/bundle/ruby/2.2.0/gems/ | grep M  | sort
102M	vendor/bundle/ruby/2.2.0/gems/devise_token_auth-0.1.33
```

**Comment by tfentonz** [comment]
<pre>31K     vendor/bundle/ruby/2.2.0/gems/devise_token_auth-0.1.33/test/dummy/log/development.log
100M    vendor/bundle/ruby/2.2.0/gems/devise_token_auth-0.1.33/test/dummy/log/test.log</pre>

Picked up by the gemspec file after tests?

**Comment by booleanbetrayal** [comment]
Those files are not in the repo: https://github.com/lynndylanhurley/devise_token_auth/tree/master/test/dummy

**Comment by tfentonz** [comment]
They are ignored in the repo in .gitignore.
<pre>
test/dummy/db/*.sqlite3
test/dummy/db/*.sqlite3-journal
test/dummy/log/*.log
test/dummy/tmp/
</pre>

But they are in the gem.
<pre>
$ tar tvf data.tar.gz test/dummy/db/*.sqlite3  test/dummy/db/*.sqlite3-journal test/dummy/log/*.log test/dummy/tmp/
-rw-r--r--  0 wheel  wheel  155648  9 Aug 17:46 test/dummy/db/development.sqlite3
-rw-r--r--  0 wheel  wheel  155648  9 Aug 17:46 test/dummy/db/test.sqlite3
-rw-r--r--  0 wheel  wheel   31448  9 Aug 17:46 test/dummy/log/development.log
-rw-r--r--  0 wheel  wheel 104628803  9 Aug 17:46 test/dummy/log/test.log
-rw-r--r--  0 wheel  wheel       268  9 Aug 17:46 test/dummy/tmp/generators/app/models/user.rb
-rw-r--r--  0 wheel  wheel      1422  9 Aug 17:46 test/dummy/tmp/generators/config/initializers/devise_token_auth.rb
-rw-r--r--  0 wheel  wheel      1623  9 Aug 17:46 test/dummy/tmp/generators/db/migrate/20150809052321_devise_token_auth_create_users.rb
tar: test/dummy/db/*.sqlite3-journal: Not found in archive
tar: Error exit delayed from previous errors.
</pre>

**Comment by schneems** [comment]
Need to run 'git rm' and commit. Or add the test dummy dir to the ignored directories list

**Comment by booleanbetrayal** [comment]
Should be fixed in master and will be slimmer with next gem release. Nice catch!

**Comment by schneems** [comment]
Thanks!
