### ISSUE TITLE
password_confirmation not actually required

### ISSUE THREAD

**Issue by Animeye** [lynndylanhurley/devise_token_auth#419]
The current usage states that `password_confirmation` is "required" for POST / and PUT /password, as well as "accepted" by PUT /.

The current reality, however, is that only PUT /password actually [requires](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/passwords_controller.rb#L122) the value to be provided.  Neither POST / or PUT / actually _require_ `password_confirmation` to be provided (though if it is, it must match `password` and `password` must be provided).  Since the parameter checking logic is handled by devise, I'm not sure if this is a documentation issue (POST / should say it "accepts" `password_confirmation` rather than "requires") or if this is a logic error (POST / should actually require `password_confirmation`)

**Comment by Animeye** [comment]
It may also be worth noting that PUT /password will allow other non-password values to be changed if the `:account_update` sanitizer was configured to allow them.  This seems like something unintentional, since the standard Devise equivalent only allows changing the password

**Comment by lynndylanhurley** [comment]
Thanks @Animeye, I'll look into this ASAP

**Comment by wangbin62** [comment]
same issue with @Animeye.

**Comment by paulosoares86** [comment]
@lynndylanhurley, I've made a branch in my fork with a simple solution for this problem. With the proposed change, password_confirmation will be required by POST / and PUT /. I would be glad if you or @booleanbetrayal could review my PR. Thanks!

**Comment by lynndylanhurley** [comment]
@paulosoares86 - thanks! Please submit the PR and I'll review ASAP!

**Comment by zachfeldman** [comment]
Hi there @paulosoares86    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by beauraF** [comment]
Actually, it isn't fixed yet.

**Comment by zachfeldman** [comment]
@beauraF we closed issues that hadn't had activity in a while and this one hadn't in almost 2 years. Please feel free to submit a pull request if you feel strongly about it!
