### ISSUE TITLE
duplicate method  - resource_class

### ISSUE THREAD

**Issue by chirag7jain** [lynndylanhurley/devise_token_auth#433]
Why is this method written twice - SetUserByToken concern & Application Controller

```
def resource_class(m=nil)
  if m
      mapping = Devise.mappings[m]
  else
    mapping = Devise.mappings[resource_name] || Devise.mappings.values.first
  end

  mapping.to
end
```

since SetUserByToken is included in application_controller, it automatically gets a copy of the method
and we can remove this method from application_controller

**Comment by booleanbetrayal** [comment]
Sounds good to me. Would you like to put together a PR @chirag7jain ?

**Comment by chirag7jain** [comment]
Yup ... Will do that

**Comment by booleanbetrayal** [comment]
thanks!

**Comment by chirag7jain** [comment]
pull request https://github.com/lynndylanhurley/devise_token_auth/pull/435

**Comment by zachfeldman** [comment]
PR was closed a while ago, going to close this issue for now.
