### ISSUE TITLE
NoMethodError (undefined method `enable_standard_devise_support' for DeviseTokenAuth:Module): app/controllers/devise_token_auth/concerns/set_user_by_token.rb:35:in `set_user_by_token'

### ISSUE THREAD

**Issue by Haseeb717** [lynndylanhurley/devise_token_auth#437]
Using DeviseTokenAuth for authentication in rails api.It gives error in update user
On this line
if DeviseTokenAuth.enable_standard_devise_support
devise_warden_user = warden.user(rc.to_s.underscore.to_sym)
 if devise_warden_user && devise_warden_user.tokens[@client_id].nil?
 @used_auth_by_token = false
 @resource = devise_warden_user
 @resource.create_new_auth_token
 end
end

My routes.rb is
namespace :api, defaults: {format: 'json'} do

  mount_devise_token_auth_for 'User', at: '/auth'
  resources :users

end

While devise_token_auth.rb is
DeviseTokenAuth.setup do |config|
  # By default the authorization headers will change after each request. The
  # client is responsible for keeping track of the changing tokens. Change
  # this to false to prevent the Authorization header from changing after
  # each request.
  #config.change_headers_on_each_request = true

  # By default, users will need to re-authenticate after 2 weeks. This setting
  # determines how long tokens will remain valid after they are issued.
  #config.token_lifespan = 2.weeks

  # Sometimes it's necessary to make several requests to the API at the same
  # time. In this case, each request in the batch will need to share the same
  # auth token. This setting determines how far apart the requests can be while
  # still using the same auth token.
  #config.batch_request_buffer_throttle = 5.seconds
  # This route will be the prefix for all oauth2 redirect callbacks. For
  # example, using the default '/omniauth', the github oauth2 provider will
  # redirect successful authentications to '/omniauth/github/callback'
  #config.omniauth_prefix = "/omniauth"

  # By defult sending current password is not needed for the password update.
  # Uncomment to enforce current_password param to be checked before all
  # attribute updates. Set it to :password if you want it to be checked only if
  # password is updated.
  config.check_current_password_before_update = :password
end

**Comment by matisoffn** [comment]
+1

**Comment by matisoffn** [comment]
@Haseeb717 did you ever fix your problem here?  If so, mind sharing?

**Comment by Haseeb717** [comment]
@matisoffn this problem not solved by me.....

**Comment by zachfeldman** [comment]
Hi there @Haseeb717    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
