### ISSUE TITLE
Unable to add a new param for sign up 

### ISSUE THREAD

**Issue by vik-y** [lynndylanhurley/devise_token_auth#440]
I am trying to use devise_token_auth to add token based authentication for my mobile app. I have a another model in my db which uses devise (but not devise_token_auth). I am able to sign up /sign in without any problems. 
But if I want to add any other attribute in the api, it doesn't insert it into table. E.g. I had one more attribute first_name in my table, during sign_up I send that parameter in my api but it doesn't get inserted into db.

I did the following changes as per the documentation: 

```rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end
```

I also tried this method: 
```rb
class ApplicationController < ActionController::Base
  protected

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end
end

class User::ParameterSanitizer < Devise::ParameterSanitizer
  def sign_in
    default_params.permit(:username, :email)
  end
end
```

Nothing seems to be working for me till now. Any idea where am I going wrong?

**Comment by Haseeb717** [comment]
Same Issue I face

**Comment by vik-y** [comment]
:+1: If you happen to find a solution then do post it here.

**Comment by Haseeb717** [comment]
Do like this in registration_controller.rb

def sign_up_params
      params.permit(devise_parameter_sanitizer.for(:sign_up) << :name)
    end

**Comment by vik-y** [comment]
But what changes do I need to make to routes.rb file to make devise_token_auth use this controller? For example, I use devise, there I can create controllers to override basic devise functions but for them to work - I have to mention in the routes specifically. Do we have to do the same for devise_token_auth also?

**Comment by Haseeb717** [comment]
My routes is like that
namespace :api, defaults: {format: 'json'} do
      
      mount_devise_token_auth_for 'User', at: '/auth'
      resources :users
      
  end

**Comment by vik-y** [comment]
Your solution didn't work. I tried a fix which was kind of similar to devise. 

I generated controllers for my user model using: 
```rb
rails g devise:controllers user
```
Then I added the following to my routes.rb to override the default registrations controller

```rb
mount_devise_token_auth_for 'User', at: 'api' , controllers: {
                    registrations: 'user/registrations'
                   }
```

And then I modified my user/registrations_controller.rb file to look like this 
```rb
class User::RegistrationsController < DeviseTokenAuth::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    #render :text => "This "
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end
```
And it worked like a charm. Thankfully :D

**Comment by Haseeb717** [comment]
Meanz you use devise controller rather than deviseTokenAuth registration controller?

**Comment by vik-y** [comment]
No, I modified registrations_controller.rb . If you look carefully then my class User::RegistrationsController extends from  DeviseTokenAuth::RegistrationsController

```rb 
class User::RegistrationsController < DeviseTokenAuth::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

```

**Comment by Haseeb717** [comment]
Ok thanks :)

**Comment by vik-y** [comment]
Btw, for you routes.rb will be like. 

mount_devise_token_auth_for 'User', at: 'auth' , controllers: {
                    registrations: 'user/registrations'
                   }

I changed 'auth' to 'api' in my app.

**Comment by Haseeb717** [comment]
If u have one to many association then how to permit its paramaters?

**Comment by Haseeb717** [comment]
Where you place user folder?

**Comment by Haseeb717** [comment]
How you update user by this way?

**Comment by nandhini-ramanujam** [comment]
Hi,

I am getting the same issue in rails 4.2.6. Not able to fix by this way. Any other suggestions?

**Comment by sposmen** [comment]
Using the default devise way worked for me... 

```ruby
class ApplicationController < ActionController::Base    
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :email, bank_attributes: [:bank_name, :bank_account]])
  end
end
```

Took [here](http://stackoverflow.com/questions/19791531/how-to-specify-devise-parameter-sanitizer-for-edit-action)
