### ISSUE TITLE
Put Access Token in body

### ISSUE THREAD

**Issue by theaidorus** [lynndylanhurley/devise_token_auth#442]
Hey,

It is possible to put access-token in body?

Thanks

**Comment by ValentinTrinque** [comment]
Why would you do that ?

I guess it has been done that way for several reasons:
-  keep the payload dedicated to your API actions
- `Access-Token` is transaction related, just like any other field in the header

**Comment by booleanbetrayal** [comment]
I don't foresee devise_token_auth embedding authorization information in rendered views, as that's not how this mechanism works.  =]
