### ISSUE TITLE
It shows "An error occurred" after omniauth callback

### ISSUE THREAD

**Issue by TravisTam** [lynndylanhurley/devise_token_auth#445]
It seems no error in the bash. Also, the user login record is inserted into database. 
I am prefer it return a user json rather than error message

**Comment by TravisTam** [comment]
It is because there is no "omniauth_window_type" set

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb#L216

**Comment by galharth** [comment]
@TravisTam Hey, can you please describe more about how you solved this problem?

**Comment by TravisTam** [comment]
try this 
http://localhost:3000/auth/:provider?omniauth_window_type=newWindow

**Comment by galharth** [comment]
Thanks, worked!

**Comment by mgs96** [comment]
hey @SunnyTam, can you please explain me where did you put that url? I'm having the same issue

**Comment by mikeover** [comment]
After doing this it then just says "Redirecting..." on the page. How do I make it go back to my React/Redux frontend?

**Comment by FlandersBurger** [comment]
> After doing this it then just says "Redirecting..." on the page. How do I make it go back to my React/Redux frontend?

Did you figure this out? I'm having the exact same issue
