### ISSUE TITLE
HTTP Headers not being sent when using as an API from an Android Phone

### ISSUE THREAD

**Issue by rahulnht** [lynndylanhurley/devise_token_auth#448]
A similar issue with one of similar repository: https://github.com/lynndylanhurley/ng-token-auth/issues/93
However I'm not able to figure out the solution similar to above in this environment.

Note: Sign In is succesfully performed , but requests sent after sign in through android app, in response, do not bear the specific authentication headers for further use namely access-token, client, bearer, uid, expiry.

**Comment by zachfeldman** [comment]
Hi there @rahulnht    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
