### ISSUE TITLE
Null email causes NoMethodError (undefined method `downcase!' for nil:NilClass)

### ISSUE THREAD

**Issue by Folleo** [lynndylanhurley/devise_token_auth#457]
It happens when I try to pass "email":null in json while authenticating.

I.e. something like:

```
{
  "email":null,
  "password":"mypasshere"
}
```

leads to the `NoMethodError`. It happens in `sessions_controller.rb` in `create` method.

Note, I use devise with configuration: `config.authentication_keys = [ :email, :username ]`. But I also try without this option, and got the same error.

**Comment by Xanderwot** [comment]
it happens here
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L13
You can monkeypatch it and use `reject` to remove `nil` values from `resource_params` hash.

**Comment by zachfeldman** [comment]
Sounds like we have a proposed solution, so closing for now.
