### ISSUE TITLE
Rails 5 compatible?

### ISSUE THREAD

**Issue by oleg-kiviljov** [lynndylanhurley/devise_token_auth#458]
Hello! I am using rails 5 to build a json api. Could you tell me please if there will be any compatibility issues if I will use this gem with rails 5?

**Comment by AlexVKO** [comment]
Doest work here, displays this message on `bundle install`
![screen shot 2015-12-06 at 7 32 12 pm](https://cloud.githubusercontent.com/assets/8848152/11615732/196b7e24-9c50-11e5-8caa-5d0282b08db5.png)

**Comment by booleanbetrayal** [comment]
The project dependencies haven't been tested against Rails 5, to my knowledge. Could you report back your findings if you play with devise_token_auth with Rails 5? I'll relax the Bundler restrictions if there are no issues.

**Comment by djsegal** [comment]
:+1: i'm going to start testing this also

**Comment by booleanbetrayal** [comment]
Thanks @djsegal !

**Comment by zachfeldman** [comment]
Seems like it's compatible!
