### ISSUE TITLE
This gem change default omniauth path?

### ISSUE THREAD

**Issue by ysyyork** [lynndylanhurley/devise_token_auth#459]
I am trying to use a default omniauth module alongside with this gem. In that module I will call auth/:provide to do authentication. However, with this gem, it shows no path matching auth/:provide. I am wondering if this gem modifies the default omniauth? I looked into source code and only find ActionDispatch::Routing::Mapper class did some modification when it's calling mount_devise_token_auth_for. But I just saw some new mapping defined here. 

```
devise_scope resource.underscore.gsub('/', '_').to_sym do
          # path to verify token validity
          get "#{full_path}/validate_token", controller: "#{token_validations_ctrl}", action: "validate_token"

          # omniauth routes. only define if omniauth is installed and not skipped.
          if defined?(::OmniAuth) and not opts[:skip].include?(:omniauth_callbacks)
            match "#{full_path}/failure",             controller: omniauth_ctrl, action: "omniauth_failure", via: [:get]
            match "#{full_path}/:provider/callback",  controller: omniauth_ctrl, action: "omniauth_success", via: [:get]

            match "#{DeviseTokenAuth.omniauth_prefix}/:provider/callback", controller: omniauth_ctrl, action: "redirect_callbacks", via: [:get]
            match "#{DeviseTokenAuth.omniauth_prefix}/failure", controller: omniauth_ctrl, action: "omniauth_failure", via: [:get]

            # preserve the resource class thru oauth authentication by setting name of
            # resource as "resource_class" param
            match "#{full_path}/:provider", to: redirect{|params, request|
              # get the current querystring
              qs = CGI::parse(request.env["QUERY_STRING"])

              # append name of current resource
              qs["resource_class"] = [resource]

              set_omniauth_path_prefix!(DeviseTokenAuth.omniauth_prefix)

              # re-construct the path for omniauth
              "#{::OmniAuth.config.path_prefix}/#{params[:provider]}?#{{}.tap {|hash| qs.each{|k, v| hash[k] = v.first}}.to_param}"
            }, via: [:get]
          end
        end
```

 I don't know why the default mapping disappears. 

If I delete mount_devise_token_auth_for statement from routes.rb file, it could work if I set path_prefix='/auth' inside devise_token_auth.rb initialier file. But after mounting, it failed again. I don't understand why this mounting will make the default omniauth path invalid. Could anybody help with this?

**Comment by zachfeldman** [comment]
Hi there @ysyyork    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
