### ISSUE TITLE
skip: [:omniauth_callbacks] doesn't work in v0.1.37.beta3

### ISSUE THREAD

**Issue by pavloo** [lynndylanhurley/devise_token_auth#460]
I use `skip` as it's suggested in readme:

``` ruby
mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
```

but `rake routes` still has `omniauth` routes in the list. after downgrading to `0.1.36`, `skip` worked seamlessly, and I don't get `omniauth` routes in the list

**Comment by zachfeldman** [comment]
Hi there @pavloo    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
