### ISSUE TITLE
Active_admin issue

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#47]
The following code in my application_controller.rb is causing a "wrong number of arguments (1 for 0)".

When I take out "DeviseTokenAuth::Concerns::SetUserByToken", the error goes away....
I have:

```
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken

  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_device_type

  def authenticate_active_admin_user!
    authenticate_user!
    if current_user.superadmin?
    else
      flash[:error] = "Please Sign In"
      redirect_to '/signin'
    end
  end

end
```

**Comment by aesnyder** [comment]
Hey, I'm seeing this issue as well.

I was planning to create an ApiController and have the devise_token_auth routes inherit from that. Can you point me in the right direction @lynndylanhurley ?

Thanks

**Comment by lsarni** [comment]
I have tried what @wkoffel said but I still get this error:

```
activesupport (5.1.3) lib/active_support/core_ext/class/attribute.rb:110:in `block (2 levels) in class_attribute'
  devise_token_auth (0.1.42) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:21:in `set_user_by_token'
  devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:123:in `current_admin_user'
  devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:111:in `authenticate_admin_user!'
  activeadmin (1.1.0) lib/active_admin/base_controller.rb:39:in `authenticate_active_admin_user'
```

**Comment by lsarni** [comment]
I tried @wkoffel  workaround and it does get ActiveAdmin working but `authenticate_api_v1_user!` returns an error and `current_api_v1_user` returns `nil` for my api controllers.
I have some custom controllers:
```
class Api::V1::UsersPasswordsController < DeviseTokenAuth::PasswordsController
end
```
And they don't seems to be using `ApiController`, kind of like in this [question](https://stackoverflow.com/questions/37997887/make-a-seperate-apicontroller-from-applicationcontroller-with-devise).

**Comment by lsarni** [comment]
I got it working based on @wkoffel answer but without subdomains (a great thing if you are using Heroku without a custom domain):

**routes.rb**
```
Rails.application.routes.draw do
  get '/' => redirect('/admin')
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'admin/dashboard#index'

  concern :api_endpoints do
    mount_devise_token_auth_for 'User', at: 'users'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      concerns :api_endpoints
    end
  end
end
```

**app/controllers/application_controller.rb**
```
class ApplicationController < ActionController::Base
  include DeviseAuthHelpers
end
```

**app/controllers/api/api_controller.rb**
```
class Api::ApiController < ApplicationController
  protect_from_forgery with: :null_session
  include DeviseTokenAuth::Concerns::SetUserByToken
end
```
And all of my api controllers (except the ones from Devise) do:
`class Api::V1::MenusController < Api::ApiController`
