### ISSUE TITLE
Unable to override sessions controller

### ISSUE THREAD

**Issue by dgoradia** [lynndylanhurley/devise_token_auth#471]
Or any controller. I really just need to override the render methods.

Following from the readme under https://github.com/lynndylanhurley/devise_token_auth#custom-controller-overrides, it just isn't working for me.

``` ruby
Rails.application.routes.draw do

  mount_devise_token_auth_for 'User', at: 'auth', skip: [:sessions, :registrations, :passwords, :omniauth_callbacks]

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
    scope module: :v1 do

      # devise_for :users
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations],
      controller: {
        sessions: 'devise_token_auth/sessions'
      }
      ...
```

app/controllers/api/v1/devise_token_auth/sessions_controller.rb

``` ruby
  class Api::V1::SessionsController < DeviseTokenAuth::SessionsController

    protected

    def render_create_success
      data = @resource.token_validation_response

      role = Role.find(@resource.id)
      data[:role] = role.name
      render json: {
        data: data
      }
    end

  end
```

It doesn't use this controller and just returns the default. Any suggestions would be appreciated!

**Comment by proxygear** [comment]
Get a similar problem.
The call to auth/sign_in return the desired JSON ( I checked with the browser inspector).

However :
    $scope.send = ()->
      $auth.submitLogin($scope.user)
        .then (response)-> console.log "response", response

The logged `response` object contains the default data ...

**Comment by dgoradia** [comment]
I was able to workaround this by overriding the `token_validation_response` method in the model since I'm using `active_model_serializers`:

```ruby
  def token_validation_response
    UserSerializer.new( self, root: false )
  end
```

and adding the uid and provider back using my serializer:
```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :provider, :uid, :name, :nickname, :image, :email, :created_at, :updated_at
  has_one :role
end
```

...but the issue still stands. If I wanted to override any of the controllers, it's still not working.

**Comment by essn** [comment]
I have this problem with SessionsController as well, I've been able to override Registrations and OmniAuthCallbacks no problem.  Been using the same workaround as @dgoradia to serialize the validation response but now I need to get inside the SessionsController#new method, any insight is greatly appreciated.

**Comment by llaine** [comment]
+1

**Comment by tbloncar** [comment]
@dgoradia In your example, you're keying the overrides hash with `controller` rather than `controllers`. Maybe this is just a typo, as it seems that others are having issues with this, as well; just wanted to point that out to be sure.

**Comment by vr4b4c** [comment]
Define full module nesting to overriding controller
```ruby
# confg/routes.rb
mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations],
  controller: {
    sessions: 'api/v1/devise_token_auth/sessions' # full module nesting
  }
```
Define controller in specified file system nesting(to be picked up by autoloading system)
```ruby
# app/controllers/api/v1/devise_auth_token/sessions_controller.rb
class Api
  module V1
    module DeviseTokenAuth
      class SessionsController < ::DeviseTokenAuth::SessionsController
        # note :: for loading root constants(::DeviseTokenAuth::SessionsController)
        # otherwise you'll get circular dependency error
        protected
        # custom rendering
      end
    end
  end
end
````

**Comment by kaiomagalhaes** [comment]
@vr4b4c the right would be:

```
mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations],
  controllers: {
    sessions: 'api/v1/devise_token_auth/sessions' # full module nesting
  }
```
It is controller*S* and not controller.

Am I wrong?

**Comment by vr4b4c** [comment]
@kaiomagalhaes you're correct(edited my post)

**Comment by kaiomagalhaes** [comment]
@vr4b4c and it should be:

```
module Api
  module V1
    module DeviseTokenAuth
```

**Comment by vr4b4c** [comment]
true, apparently my solution has more problems than original issue... ;)

**Comment by albertsaave** [comment]
While implementing what @vr4b4c suggested and writing tests to my api controllers, I now get `application controller token uninitialized constant Concerns::SetUserByToken` in my tests only. Previously, my tests were passing.

**Comment by zachfeldman** [comment]
Hi there @dgoradia and @albertsaave    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by CostaRico** [comment]
also cant override :(

**Comment by zachfeldman** [comment]
Hi @CostaRico, this issue is closed. If you're having a similar problem, please open a new issue with more specifics and we can try to look into it.
