### ISSUE TITLE
Reading logged user in constraint

### ISSUE THREAD

**Issue by mustela** [lynndylanhurley/devise_token_auth#475]
I'm trying to restrict some routes base on user roles. So I create a constraint

``` ruby
class BackendConstraint
    def self.matches?(request)
      current_user = request.env['warden'].user
      return false if current_user.blank?
      current_user.role?(:admin)
    end
  end
```

But `request.env['warden'].user` is always null. Am I'm missing something? 

Thanks

**Comment by zachfeldman** [comment]
Hi there @mustela    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by v3rron** [comment]
Just stumbled upon the same issue. Is there any way around this? I'm trying to constraint routes for different roles of users.
