### ISSUE TITLE
Unpermitted paramter: session (401 Unauthorized) for only one particluar user

### ISSUE THREAD

**Issue by fertingoff** [lynndylanhurley/devise_token_auth#477]
When an existing user try to sign_in he gets 401. User signed in before without problems.
Logs from server: `Unpermitted parameter: session`

```
Parameters: {
    "email"=>"foo@gmail.com",
    "password"=>"[FILTERED]", 
    "session"=> {"email"=>"foo@gmail.com", "password"=>"[FILTERED]"}
}
```

Other users sign_in without any problems. Would appreciate any help how I can debug issue with this user.

I found similar issues https://github.com/lynndylanhurley/devise_token_auth/issues/142 and https://github.com/lynndylanhurley/devise_token_auth/issues/432 but they didn't help me, since only one particular user can't login in my case.

**Comment by zachfeldman** [comment]
Hi there @fertingoff    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
