### ISSUE TITLE
Would like to know is there any missing for i18n translation file?

### ISSUE THREAD

**Issue by SunnyTam** [lynndylanhurley/devise_token_auth#479]
It seems to me that there are some missing in locale file. 
While I am calling post /auth (registration), there will be error message that is not well translated. Would like if I can make some customise translation on it. Below is the examples. 

P.S. I am using zh-TW 

```
{
  "status": "error",
  "data": {
    "id": null,
    "provider": "email",
    "uid": "",
    "name": null,
    "nickname": null,
    "image": null,
    "email": "XXX@gmail.com",
    "created_at": null,
    "updated_at": null
  },
  "errors": {
    "email": [
      "address is already in use"
    ],
    "full_messages": [
      "Email address is already in use"
    ]
  }
}
```

**Comment by booleanbetrayal** [comment]
Additional locales would be fantastic if you're willing to provide them. [Here's](https://github.com/lynndylanhurley/devise_token_auth/tree/master/config/locales) where they can currently be found. Definitely missing zh-TW!  =]

**Comment by zachfeldman** [comment]
Hi there @SunnyTam    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
