### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated. Rails 5

### ISSUE THREAD

**Issue by pette9** [lynndylanhurley/devise_token_auth#482]
I am using devise_token_auth gem for a rails 5 JSON API but i'm getting this error when i run rake `db:migrate` after generating the user model and defining routes.

    DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead.

**Comment by jeryRazakarison** [comment]
That's because of the Devise gem, needed by devise_token_auth.
For now, you can force the master branch of Devise, which fixes the problem. In your Gemfile:
```
gem "devise", :github => 'plataformatec/devise', :branch => 'master'
gem "omniauth"
```

**Comment by jbhatab** [comment]
I still have these warnings on app start and on testing. any reason why?

**Comment by satishchhibba** [comment]
I don't think it has anything to do with Devise Gem.
I don't have Devise and I am getting it too -- it started happening with adding "hairtrigger" gem.
So there must be another underlying cause.

**Comment by jeryRazakarison** [comment]
Hi @satishchhibba in fact, you do have the Devise gem but it is implicitly included in your project. It is a dependency of devise_token_auth
(see the line `s.add_dependency "devise", "> 3.5.2", "<= 4.2"` in devise_token_auth.gemspec)
