### ISSUE TITLE
I want to use a different column for provider instead of defalut "email"

### ISSUE THREAD

**Issue by prakash-alpine** [lynndylanhurley/devise_token_auth#485]
I am running into a problem using "email" as a provider in my User table.  I am using the 
symmetric_encryption gem to encrypt the email column in my postgres database. This requires to change the name of "email" column to "encrypted_email".  Also I am using "username" and "password" as login credentials with Devise instead of "email / password".

With standard Devise gem everything works fine and I am able to login using regular HTML version of login page. However, I can not get the authentication to work with devise_token_auth, since it insists of
using "email" as provider.  

My question is: Is there any way I can use a different column (e.g. username) as a provider instead of 
default "email" ? I browsed through the code, and it seems that "email" is hard-coded as a provider in session_controller.rb->create() method.  

Please help !!!

**Comment by campo** [comment]
This it similar and related to: https://github.com/lynndylanhurley/devise_token_auth/issues/563#issuecomment-195094536

My comment there has some information that might be able to help you get the sign in working, but it would be a hacky solution. I suspect it would require your email field be named exactly `email`, and the `uid` set in the headers in responses would be the value of that field.

**Comment by zachfeldman** [comment]
Closed in favor of #563
