### ISSUE TITLE
Does anyone try to link current omniauth account to devise-token-auth account?

### ISSUE THREAD

**Issue by SunnyTam** [lynndylanhurley/devise_token_auth#487]
I am doing something like link current account with facebook. And try to get current_user when omniauth_success callback so that I can know is this auth/["provider] already login. However it seems to me that it is unable to get the login token. Does any of you trying to link omniauth account to current devise-token-auth account?

**Comment by stephanebruckert** [comment]
Trying to do this as well, did you figure it out @SunnyTam ?

**Comment by zachfeldman** [comment]
Hi there @stephanebruckert    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
