### ISSUE TITLE
Unpermitted Parameters: confirm_success_url, config_name, registration

### ISSUE THREAD

**Issue by michaelstokes** [lynndylanhurley/devise_token_auth#489]
Hi, 

I'm new to using devise token auth and ng token auth and I seem to be getting the following error

```
Started POST "/auth" for ::1 at 2016-01-02 11:47:15 +0000
Processing by User::RegistrationsController#create as HTML
  Parameters: {"email"=>"email@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/register", "config_name"=>"default", "registration"=>{"email"=>"email@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/register", "config_name"=>"default"}}
Unpermitted parameters: confirm_success_url, config_name, registration
Unpermitted parameters: confirm_success_url, config_name, registration
Unpermitted parameters: confirm_success_url, config_name, registration
   (0.1ms)  BEGIN
   (0.4ms)  SELECT COUNT(*) FROM "users" WHERE "users"."provider" = $1 AND "users"."email" = $2  [["provider", "email"], ["email", "email@gmail.com"]]
   (0.1ms)  ROLLBACK
Completed 403 Forbidden in 76ms (Views: 0.3ms | ActiveRecord: 0.6ms)
```

After playing around, It seems to happen when your password is less than a length of 8 or if that the account already has been registered but then if this is the case I don't understand the reason for the Unpermitted parameters and also how do I catch the failed response i.e. password length must be 8 or user already registered?

Thank you.

**Comment by zachfeldman** [comment]
Hi there @michaelstokes    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
