### ISSUE TITLE
Sign in from controller

### ISSUE THREAD

**Issue by nixv2** [lynndylanhurley/devise_token_auth#494]
hi, am using the this gem and it works great...
i just have one question is it possible to sign in a user from a controller??
am trying to do something like this:

``` ruby
class Api::V1::SessionsController < DeviseTokenAuth::SessionsController
    def create
        begin
            ldap_user = User.someService # Call a service with login data...
            if ldap_user
                # sing in user
            else
                render json: {:error => 'Invalid Login'}.to_json, status: :bad_request
            end
        rescue Exception => ex
            render json: {:error => ex.message}.to_json, status: :bad_request
        end
    end
end
```

so what am trying to do is:
before the user is sign in, get some external data and if the data is returned sing in the user (i have access to the user data)... 
the problem is that am not sure how to sing in the user... is there a helper to sing in the user?? or do i have to overwrite the whole sessions controller??

any help will be appreciated and thanks in advance.

to handle my views am using angular with [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth)

**Comment by zachfeldman** [comment]
Hey @nixv2 , you can use the same helpers that devise uses to sign in users:
http://www.rubydoc.info/github/plataformatec/devise/Devise/Controllers/SignInOut

Going to close this but feel free reopen if you'd like!
