### ISSUE TITLE
tokens not being serialized!

### ISSUE THREAD

**Issue by killerham** [lynndylanhurley/devise_token_auth#495]
Pull request https://github.com/lynndylanhurley/devise_token_auth/pull/276 conditional serialize doesn't serialize for sqlite. This bug re-introduces issue https://github.com/lynndylanhurley/devise_token_auth/issues/121

I'm not sure if its the ruby version I'm running (tested on 2.1.1 and 2.2), but I'm running rails 4.2. I'm on the latest commit of devise_token_auth.

To fix the issue simply put `serialize :tokens, JSON` above `include DeviseTokenAuth::Concerns::User` in the user model to override the conditional serialize OR remove the condition check from the concern.

**Comment by mada41** [comment]
hi @killerham , i have same problem and follow your instruction, but i get "
no implicit conversion of Hash into String" error.

**Comment by killerham** [comment]
It sounds like you have the opposite problem. In your schema, are tokens a json type or string type?

**Comment by alfredoreduarte** [comment]
Just had this issue and @killerham 's tip fixed it. This should be somehow included in the gem though 🤔

**Comment by dijonkitchen** [comment]
Looks like the relevant lines are here:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L250
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L245

**Comment by zachfeldman** [comment]
Seems like we have an accepted solution here, so closing this for now.
