### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated

### ISSUE THREAD

**Issue by Fudoshiki** [lynndylanhurley/devise_token_auth#514]
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at ~/.rvm/gems/ruby-2.3.0/bundler/gems/devise_token_auth-129025b080aa/lib/devise_token_auth.rb:1)

**Comment by davegreco** [comment]
Did you ever figure this out?

**Comment by nlemire** [comment]
Same here, getting this message as soon as I try to run the migrations:

> DEPRECATION
>
> WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /my-app/config/application.rb:17)
>[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rails aborted!

another closed ticket indicates that we should add manually the dependency to devise, but even this doesn't change the situation...

Assistance would be much appreciated :)

**Comment by nlemire** [comment]
OK, my bad, I've had it working eventually :)
doing this:
>gem "omniauth"
>gem 'devise_token_auth', :github => 'lynndylanhurley/devise_token_auth', :branch => 'master'

I still have a deprecation warning but otherwise it works 👍

**Comment by concopetti** [comment]
Hi.
I have the same problem that Fudoshiki but not corrected with the change in the gem version.
To compile on test mode works but not for production.
Can someone help me?
