### ISSUE TITLE
render_create_success should return 201 code not 200?

### ISSUE THREAD

**Issue by Fedcomp** [lynndylanhurley/devise_token_auth#516]
When i register using api, i expect it to be restful and receive 201 code if register was successful.
However, render_create_success does not set response code, so it stays 200.
Why is it important at all? well, for example i use rack-minitest, and it has convenient methods like `assert_created` which expect response to return 201. [The method itself](https://github.com/lynndylanhurley/devise_token_auth/blob/30f2703b2237ba302cdcfdafbc042f09c2dd665e/app/controllers/devise_token_auth/sessions_controller.rb#L109-L113)

Yes i know, i can redefine methods with my own controller, however i think 201 on success should be default behavior.

**Comment by zachfeldman** [comment]
Nobody else seems to have a problem with this in the last 1.5 years so I'm going to close this for now.
