### ISSUE TITLE
Error Response as HTML

### ISSUE THREAD

**Issue by alfmatos** [lynndylanhurley/devise_token_auth#522]
I've hit an error `DeviseTokenAuth::Registrations#create ArgumentError` as detailed in #21 and fixed it with the instructions in https://github.com/lynndylanhurley/devise_token_auth#email-authentication.

My problem is that the exception is being raised as HTML. I've got `defaults: {format: 'json'}` on my routes, and the request accepts json:
`Accept:application/json, text/plain, */*`

However, the response is always HTML containing the full error and the trace:
`content-type:text/html; charset=utf-8`

Shouldn't this raise a standard 500 error in JSON, and return that to the client?

**Comment by zachfeldman** [comment]
Hi there @alfmatos    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
