### ISSUE TITLE
check_current_password_before_update still requires password when resetting password

### ISSUE THREAD

**Issue by paulius005** [lynndylanhurley/devise_token_auth#526]
I have `config.check_current_password_before_update = :password` enabled. So when the user updates his/her password, the `current_password` field is required. This becomes a problem when implementing `Password reset` because the user does not know his/her current password. How do I bypass this and still require the `current_password` when the user is not resetting his/her password?

**Comment by tmjfitch** [comment]
I've run into the same issue when trying to handle the password reset workflow. Any suggestions?

**Comment by paulius005** [comment]
I see this ```
# ensure that user is confirmed
@resource.skip_confirmation! if @resource.devise_modules.include?(:confirmable) && !@resource.confirmed_at
```

inside of `devise_token_auth/passwords_controller.rb`

but `update` seems to be being called instead of edit when I use `$auth.updatePassword` within `ng-token-auth`

**Comment by paulius005** [comment]
Hmm just overrode the controller. Edit sets `@resource.allow_password_change` to true, so that's fine, by the time `update` is called `@resource.allow_password_change` is false again. So then `"update_attributes"` never gets called. I'm assuming this is because calling `update` creates a new instance of `@resource`

**Comment by paulius005** [comment]
Checked. This situation is not covered by unit tests and is not used in the demo code

**Comment by paulius005** [comment]
Currently going to solve by passing another `resource_param` called `:allow` and let `update` set `@resource.allow_password_change` to true until someone can help with a better solution
