### ISSUE TITLE
Is it a hybrid authentication system?

### ISSUE THREAD

**Issue by d3crypt3d** [lynndylanhurley/devise_token_auth#527]
Hello.
As I know, token-based authentication system assumes stateless server-side, which means no session is persisted. But I [discovered](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L5) it still uses sessions under the hood. Seems because it is build on the top of Devise, which, in turn, uses Warden's functionality. If it's true, which piece of information is stored in a session variable and which one in the token (in comparison with traditional Device)?
Thanks in advance.

**Comment by rdupz** [comment]
+1

**Comment by lynndylanhurley** [comment]
I think Omniauth is the only part of this system that uses session storage.

Consider this chain of events:

~~~
Client -> Rails API -> Provider Auth -> Rails API -> Client
~~~

Session storage is used when going from the Rails API to the Provider and back.
