### ISSUE TITLE
set a no reply email adresse

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#542]
I have an email adresse like `contact@mywebsite.com`

And when I create an account or reset a password I receive an mail with: 
- sender "contact"
- subject "reset password"
- reply to "contact@mywebsite.com"

Is it possible to have something like:
- sender: "mywebsite"
- subject "reset password"
- reply to "no-reply@mywebsite.com"

Thank you ! :)

**Comment by zachfeldman** [comment]
You can change the default from: in action mailer! Closing this for now. http://guides.rubyonrails.org/action_mailer_basics.html
