### ISSUE TITLE
Failed migration: how to handle existing user db

### ISSUE THREAD

**Issue by MatthewMDavis** [lynndylanhurley/devise_token_auth#544]
I have already built up an app around devise authentication, and nothing I've tried will get vanilla Devise to work with implementing AJAX logins the way I want them.

So I installed devise_token_auth and ran the generator. The db:migrate command won't run after that because there's already a users db from installing Devise the first time. And my app won't run because of pending migrations.

Can I just delete the migration that was created and use the existing Devise users db? Or will I need to roll back the db schema to a pre-Devise state and start over?

**Comment by campo** [comment]
@MatthewMDavis, you can get this to work by "massaging" the migration that gets generated by the devise_token_auth install command.

Most of the fields in the migration were already created by your original devise install. As an example this is what my migration ended up being (which ran cleanly):

```ruby
class DeviseTokenAuthCreateUsers < ActiveRecord::Migration
  def change
    change_table(:users) do |t|

      # NOTE: The provider `email` really just refers to
      # a standard devise user authentication. I use username
      # but devise_token_auth only looks for users with provider
      # `email` when signing in (even if Devise is set to use
      # something else like username)
      #
      ## Required
      t.string :provider, :null => false, :default => "email"
      t.string :uid, :null => false, :default => ""

      ## Tokens
      t.json :tokens
    end

    add_index :users, [:uid, :provider],     :unique => true
  end
end
```

The key thing was to change `create_table` to be `change_table` so the migration modifies the existing table. The only columns I then needed to add were `:provider`, `:uid`, and `:tokens`, (though your needs may be slightly different). A thoughtful comparison of your original devise users migration and the one created by devise_token_auth should make it clear to you which parts you need and which parts you don't. Good luck!

**Comment by edwinramirez** [comment]
I'm getting this error when running my Devise Token Auth migration, which looks exactly like yours @campo 
"UniqueViolation: ERROR:  could not create unique index "index_users_on_uid_and_provider"
DETAIL:  Key (uid, provider)=(, email) is duplicated."

**Comment by bernardkroes** [comment]
@edwinramirez I just split up the migration into these three migrations:

1. Create the new columns
`class DeviseTokenAuthCreateUsers < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :provider, :string, :null => false, :default => "email"
    add_column :users, :uid, :string, :null => false, :default => ""
    add_column :users, :tokens, :text
  end
end`

2. Copy the email field to the uid field
`class SetUidForUsers < ActiveRecord::Migration[5.0]
  def self.up
    User.update_all("uid=email")
  end

  def self.down
  end
end
`

3. Add the index
`class CreateAuthIndex < ActiveRecord::Migration[5.0]
  def change
    add_index :users, [:uid, :provider],     unique: true
  end
end
`

**Comment by campo** [comment]
@edwinramirez The reason you get this error is because the index that gets added is based on the `uid` and the `provider` for each row and is `unique: true`. If you happen to have two rows that have the same `uid` and the same `provider`, the unique constraint on that index causes it to fail.

The "real" way to fix the problem would be to eliminate the situation where both the `uid` and `provider` would be the same for multiple rows. That could mean preventing it from happening in the first place, or by making a well-reasoned decision about how to change the values for the affected rows in your particular situation.

**Comment by bernardkroes** [comment]
If you have a database with multiple existing users, the migration will always fail.
The two new columns have default values "email" and "". In that case there will always be duplicate values ("email, "") for the unique index. 

The second migration above is an example of how you could fix that (by generating a unique uid (assuming that email is unique for existing users in your database).

**Comment by zachfeldman** [comment]
Sounds like we have a proposed solution, so closing this for now.
