### ISSUE TITLE
Confirmation controller does not response with JSON

### ISSUE THREAD

**Issue by djsegal** [lynndylanhurley/devise_token_auth#546]
Confirmation controller doesn't match the rest of the controllers in that it doesn't respond with JSON (it actually sends back a redirect).

Also, the action is a show instead of a create

**Comment by cristhiano** [comment]
Actually, does anyone knows how to make this redirect work without a CORS block?

Am I missing something? Because it seems to be just the basic behavior of a 1.4K stars gem and I can't find nobody reporting this issue.

**Comment by zachfeldman** [comment]
Hi there @djsegal and @cristhiano    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
