### ISSUE TITLE
Yielding Resource to Overriding Controller

### ISSUE THREAD

**Issue by bezreyhan** [lynndylanhurley/devise_token_auth#548]
I'm trying to extend the create action for the Sessions Controller

When I do this:

```
class SessionsController < DeviseTokenAuth::SessionsController

  def create
    super do |resource|
      puts resource
    end
  end
end
```

`resource == nil`

however `@resource` does return the resource.

Is this the expected behavior?

Also, I was wondering how I can get access to the token that will be returned to the user? I was able to access it via `@token`.

**Comment by richardmable** [comment]
I literally just asked the same question! See #549 
I've also had issues with not being able to pass a super block to a DeviseTokenAuth controller, doesn't seem to do anything, and I'm pretty sure I'm inheriting it correctly.

**Comment by richardmable** [comment]
We have been able to figure this out with a lot of experimentation. `@resouce` does return `nil` for us too, but we did find the access-token and all the other information returned from the omniauth provider, located in `request.env['omniauth.auth']`, located in the `redirect_callbacks` action of the OmniAuthCallbacks controller. We also needed to set up 

`mount_devise_token_auth_for 'User', at: 'auth', controllers: {
  omniauth_callbacks: 'registrations'}`

in `routes.rb`, and create the custom controller which we named `RegistrationsController`. 
So our block looked like this: 
`def redirect_callbacks
super
puts "REDIRECT:"
puts request.env['omniauth.params']
puts "AUTH INFO"
puts request.env['omniauth.auth'].credentials['token']
puts "REDIRECT END"
# create the user_strava_key and save it.
@strava_token = request.env['omniauth.auth'].credentials['token']
UserStravaKey.create(key_secret: @strava_token)`

I hope this helps, and also thanks to @JonathanWexler for helping to figure this out.

**Comment by bezreyhan** [comment]
@richardmable thanks for documenting your findings `@resource` in not `nil` for me. Rather `resource`m which should be returned by the block, is `nil`.

I am also able to get access to the token via `@token`

**Comment by zachfeldman** [comment]
Sounds like we have a proposed solution here? Closing for now.
