### ISSUE TITLE
/auth/validate_token works but getting 401 unauthorized when sending request with auth headers

### ISSUE THREAD

**Issue by galharth** [lynndylanhurley/devise_token_auth#550]
Hi,
I'm building an iOS that works with rails API.
I'm sending the request with the headers using postman.
Using the last devise-token-auth '0.1.37' and rails '4.2.5'.
When using postman I set the content type JSON. 
Thanks,
Gal

**Comment by phspies** [comment]
Did you managed to resolve this issue?

**Comment by Loschcode** [comment]
Did you ?

**Comment by phspies** [comment]
For me it seemed to start working when I passed all 5 variables to the endpoint. But I got around this issue by overriding the authentication class with my own.
