### ISSUE TITLE
Models other than `User` not returning auth headers after each request

### ISSUE THREAD

**Issue by bobmshannon** [lynndylanhurley/devise_token_auth#552]
When setting up multiple [user models](https://github.com/lynndylanhurley/devise_token_auth#using-multiple-models), the auth headers (`access-token`, `client`, etc.) do not get updated nor added in each response unless the corresponding model is `User`. The only time these headers are present are in the response after POST'ing to `/sign_in`.

**Comment by zachfeldman** [comment]
Hi there @bobmshannon   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
