### ISSUE TITLE
get Authorized users only when use devise with devise_token_auth

### ISSUE THREAD

**Issue by RailsDevKH** [lynndylanhurley/devise_token_auth#553]
When i use devise and devise_token_auth together i alway get message like below.

Filter chain halted as :authenticate_user! rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.9ms | ActiveRecord: 0.0ms)

If use with api is work well but when i use with rails it now work by show Authorized users

**Comment by mikevic** [comment]
+1 for this! :)

**Comment by ingolfured** [comment]
+1

**Comment by RailsDevKH** [comment]
I have solve this problem by remove 
_before_action :authenticate_user!_ from my application controller

**Comment by gfauredumont** [comment]
Same here but I didn't have this issue before; is it from an update ?
@RailsDevKH solution worked for me as well (I'm glad removing authentication from App controller wasn't a big deal on this app...)

**Comment by AhmedAtef07** [comment]
Any updates on this issue?
I am adding the :authenticate_user! in each controller instead of the application controller one and I still face this problem.

**Comment by zachfeldman** [comment]
Hi there @RailsDevKH   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
