### ISSUE TITLE
Use devise_token_auth with facebook iOS login SDK

### ISSUE THREAD

**Issue by galharth** [lynndylanhurley/devise_token_auth#556]
Hey,
How can I use devise_token_auth to create a new user that I fetched his details from iOS login SDK?
Thanks

**Comment by zachfeldman** [comment]
Hi there @galharth    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
