### ISSUE TITLE
omiauth-google

### ISSUE THREAD

**Issue by ghost** [lynndylanhurley/devise_token_auth#558]
Hi,

I used omiauth google to sign up and sign in users on my application.
When I sign up (or sign in) a user I have a error on my browser "An error occurred" but nothing is log.
I don't known where is the error.
Have got an Idea ?

**Comment by oema** [comment]
I think a found the problem it's because a use rails-api So i have not component to display HTML.

**Comment by zachfeldman** [comment]
Closed due to lack of information
