### ISSUE TITLE
Extend token lifespan on use?

### ISSUE THREAD

**Issue by Animeye** [lynndylanhurley/devise_token_auth#573]
Is there a way to "refresh" the token lifespan on use?
Currently, if change_headers_on_each_request is true, then each request generates a new set of headers with a new expiration, effectively extending the lifespan of the session.
However, if change_headers_on_each_request is false, there does not seem to be a way to extend the lifespan of the token when its used to authenticate.  Is there something I am missing, or is this intended behavior?

**Comment by campo** [comment]
I think the conceptual idea is that you have the ability to just generate another token and use that, which serves as a refresh.

This is pure speculation on my part, and I know doesn't sounds like an answer to your question, but it's what I would do.

**Comment by MrNagoo** [comment]
@campo is there a minimum limit on the token_lifespan? I want the token to only last 30.minutes but if I put anything lower than .week it doesn't authorize my user.

**Comment by ebosantos** [comment]
I've realized the same, @MrNagoo !

Did you solve that? @lynndylanhurley any ideas?

**Comment by MrNagoo** [comment]
@ebosantos Yes, I converted it into seconds and it worked.

**Comment by ebosantos** [comment]
How? I'm trying 20 minutes and even `config.token_lifespan = 1200.seconds` is not working properly. Tks!!

**Comment by MrNagoo** [comment]
ill look at my code tomorrow and let you know if I did anything else.

**Comment by campo** [comment]
@MrNagoo @ebosantos Sorry for the delayed response. Off the top of my head, I don't recall any minimum limit from when I was using this code. Good luck sorting it out guys.

**Comment by MrNagoo** [comment]
Ahh yes, it has come back to me. I think I did 1.week - x.seconds. Basically subtract a large number of seconds to get to however many minutes you need. Give that a try.

**Comment by ebosantos** [comment]
Just tried `2.weeks - 1209480.seconds` and didn't work. No idea why it isn't working with a value less than 2 weeks. I'd appreciate if you have some new insights. Tks in advance.

**Comment by MrNagoo** [comment]
```
DeviseTokenAuth.setup do |config|
  config.change_headers_on_each_request = true
  config.token_lifespan = 1800.seconds
  config.batch_request_buffer_throttle = 30.seconds
end
```
This is my entire devise token auth. I change the headers on each request because if you don't you will only have 30 min of activity, I want people logged out after 30 minutes of inactivity. I use the buffer throttle because I'm using angular with a decoupled rails api. The dashboard uses a bunch of requests and I don't want new tokens EVERY time. The default is 10 tokens, and without the throttle it's easy to have 10 tokens pretty quick from a dashboard. you can also up the token array to a higher number but 10 should suffice. The app I'm using this on is for a large logistics company and they haven't had issues.

**Comment by ebosantos** [comment]
Perfect! Tks very much, @MrNagoo

**Comment by zachfeldman** [comment]
Sounds like we have a proposed solution here, closing for now.
