### ISSUE TITLE
Do we have any rspec helpers to sign_in an user?

### ISSUE THREAD

**Issue by ingolfured** [lynndylanhurley/devise_token_auth#577]
In devise, we can sign in a user using `sign_in(user)`. Is there anything similar that comes with this gem?  If not, what's the best way to authenticate / disable the authentication when I'm testing?

**Comment by ingolfured** [comment]
Looks like #521 solves it. However, I'm creating a helper method in my support file.

```ruby
def token_sign_in user
  auth_headers = user.create_new_auth_token
  request.headers.merge!(auth_headers)
end
```

Thanks!

**Comment by dannymockaitis** [comment]
If anyone is using Rspec requests, you can define @ingolfured method above but instead return the auth_header

    def token_sign_in user
        return user.create_new_auth_token
    end

Then on any call you want to have an authenticated user just define the headers
Also make a factory for your users

Then 
    before { get "/api/v1/beers/#{breweries.first.id}/#{beers.first.id}", headers: token_sign_in(user) }
