### ISSUE TITLE
current_user seems to be nil after doing requests from different tabs

### ISSUE THREAD

**Issue by lucas-aragno** [lynndylanhurley/devise_token_auth#579]
Hey,

I'm testing out this gem and seems that the `current_user` variable disappears after several requests

on my `application_controller` I have 

```ruby
...
  include DeviseTokenAuth::Concerns::SetUserByToken
  protect_from_forgery with: :null_session
  before_filter :show_user
  
  def show_user
    Rails.logger.debug "==== #{current_user.inspect}"
  end

...
```

navigating trough the app this are the outputs of that logger
```bash
==== #<User id: ...
==== #<User id: ...
==== #<User id: ...
==== nil
==== nil
```

I'm also tailing the controllers involved

```bash
Processing by Admin::Api::SomethingController#index as JSON
Processing by Admin::Api::SomethingController#index as JSON
Processing by HomeController#index as HTML
Processing by Admin::Api::SomethingController#index as JSON
```

I'm not seeing anything weird but on the last call to the SomethingController I get

`Filter chain halted as :authenticate_user! rendered or redirected`

but at that point the `current_user` is nil already

any thoughts?

**Comment by rohitsiddha** [comment]
I'm facing the same issue. In my case the scenario is bit different, I've a scaled architecture, where there are 5 API servers has been placed behind a load balancer, all are connected with a common db server. When I do batch requests, requests are being routed to different API servers by load balancer. However I get following message as a response to API-
`Authorized users only`

Any thought about how to use this gem with scaled architecture?

**Comment by lucas-aragno** [comment]
I've solved this issue doing a little rework over the `devise.rb` initializer could you share yours? perhaps I can help.

**Comment by lucas-aragno** [comment]
Closing this issue now
