### ISSUE TITLE
Confirmable - unconfirmed email

### ISSUE THREAD

**Issue by Urbanviking** [lynndylanhurley/devise_token_auth#58]
*Test A*
1. Added ```before_create :skip_confirmation!``` in User model
2. Disabled the Confirmable columns in the migration file
3. Ran db:migration

*Result of test A*
db:migration fails during execution of seed.rb with message:
*NameError: undefined local variable or method `confirmed_at' for #<User:0x007fabb13dcae8>*

*Test B*
4. Enabled the Confirmable columns in the migration file
5. Ran db:migration

*Result of test B*
Confirmation columns are all updated except unconfirmed_email

*Test C*
6. Removed ``before_create :skip_confirmation!``` in User model
7. Kept the Confirmable columns enabled in the migration file
8. Ran db:migration

*Result of test C*
Confirmation columns are all updated except unconfirmed_email and confirmed_at

**Question 1**
Are the Confirmation columns necessary, if ```before_create :skip_confirmation!``` is implemented ?

**Question 2**
Shouldn't unconfirmed_email be set when confirmation is implemented or could this column be omitted ? You already have uid and email columns.

**Comment by lynndylanhurley** [comment]
This should be fixed as of version `0.1.31.beta7`. Module exclusion docs are [here](https://github.com/lynndylanhurley/devise_token_auth#excluding-modules).
