### ISSUE TITLE
Dynamic token lifespan based on user input

### ISSUE THREAD

**Issue by matisoffn** [lynndylanhurley/devise_token_auth#580]
I have the option `config.token_lifespan` set in my initializer for Devise Token Auth, but I want it to be dynamic.

For example, most websites have a checkbox for "Remember Me" or "Stay Signed In"

How (with DTA) can I set the default lifespan to 2 hours, but months long if the user hits the checkbox?

**Comment by ebosantos** [comment]
@matisoffn Did you solve that? if so, could you share the solution? Tks

**Comment by acegilz** [comment]
+1

**Comment by MaicolBen** [comment]
You can achieve it with #704
