### ISSUE TITLE
Mails are not being sent

### ISSUE THREAD

**Issue by Quintasan** [lynndylanhurley/devise_token_auth#581]
My application is using both `devise_token_auth` and `devise`. My users are able to register and everything but sending emails does not work. For example when one registers an email should be sent to them requiring them to confirm their account. The log files indicate that the user was successfully created and the email (supposedly) sent to the user appears in the server log. The email however is not sent at all and I can confirm this by looking in Mailgun logs which show no mail requests being made.

At the same time I can just open up rails console and do `User.last.send_confirmation_instructions` and the mail is actually getting sent (as in it reaches the destination email address and shows up in the Mailgun logs).

Any ideas on how can I debug this?

The code is available here: [TeMoMuKo/asrapi](https://github.com/TeMoMuKo/asrapi)

**Comment by thelastinuit** [comment]
with devise alone, you are able to send emails?
