### ISSUE TITLE
Preventing creation of users in an oauth scenario

### ISSUE THREAD

**Issue by chriskozlowski** [lynndylanhurley/devise_token_auth#583]
We have a situation where we want to use our Google apps accounts to authenticate against an internal rails app.  We are using devise_token_auth and redux_auth to accomplish this.  It works great so far.

To perfect this, we need to prevent the creation of new user accounts upon a successful omniauth authentication.  We want to pre-register our users as the app is internal and the default behavior means that anyone can log in to the system with a google account.  Maybe there is not an option for this ATM because the [omniauth_success method](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb#L39) in the `omniauth_callbacks_controller.rb` saves the resource after sign_in?  Or, is there a way I'm not thinking of?

**Comment by zachfeldman** [comment]
Hi there @chriskozlowski    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
