### ISSUE TITLE
empty request.env['omniauth.params'] causes exception

### ISSUE THREAD

**Issue by anklos** [lynndylanhurley/devise_token_auth#586]
Hi there,

I open `localhost:300/omniauth/facebook` and authorize the app, then I see this error:

```
NoMethodError in DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks

undefined method `underscore' for nil:NilClass

in devise_token_auth (0.1.37) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:14:in `redirect_callbacks'
```

The line of the code is:

```
devise_mapping = request.env['omniauth.params']['resource_class'].underscore.gsub("/", "_").to_sym
```

I set a debugger there and found that `request.env['omniauth.params']` is an empty hash `{}`.

Same issue happened for google oauth login.

Is there any omniauth params I miss in the setup? 

Thanks!

**Comment by daudt** [comment]
I'm getting the same error with facebook oauth. @anklos any luck solving this?

**Comment by anklos** [comment]
@daudt https://github.com/lynndylanhurley/devise_token_auth/pull/540#issuecomment-202298945

**Comment by anklos** [comment]
@daudt in summary, use `/auth/facebook`, not `/omniauth/facebook`. and pass `auth_origin_url` in the url query param

**Comment by daudt** [comment]
Ok, so I've tried passing `auth_origin_url` both as a query param and as a header param and I'm still getting the same error. I'm using /auth/facebook:
`NoMethodError (undefined method `underscore' for nil:NilClass)`

**Comment by zachfeldman** [comment]
Hi there @anklos @daudt    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by caseyprovost** [comment]
I still have this issue on the latest tag v0.1.43.beta1. 0.1.42 was not working either. By this I mean when my redirect was issued to https://my.host/iauth/saml/callback?resource_class=User I saw the following error.

<img width="1438" alt="screen shot 2018-03-02 at 5 10 24 pm" src="https://user-images.githubusercontent.com/210048/36924471-adda2086-1e3c-11e8-8b7d-2dc16036a923.png">

**Comment by mgs96** [comment]
Same error as @caseyprovost here!

**Comment by yortz** [comment]
same here, actually tried with several strategies, it looks like that `request.env['omniauth.params']` is always nil, literally not clear why this is happening also commented about this here[](https://github.com/lynndylanhurley/devise_token_auth/issues/910#issuecomment-371554605)

**Comment by muhammadyana** [comment]
hallo, i still get error when i try access `http://localhost:4001/users/auth/google_oauth2?auth_origin_url=localhost:4001/` it still error `undefined method underscore for nil:NilClass`
anyone can inform me where i have to locate the `auth_origin_url ` ? thanks.
![image](https://user-images.githubusercontent.com/7847990/59411549-baa65180-8de5-11e9-9259-5efbf0d3f254.png)

**Comment by yortz** [comment]
@muhammadyana have you tried to configure the `redirect-uri` as described [here](https://github.com/lynndylanhurley/devise_token_auth/issues/910#issuecomment-372287844)? This solved my issue

**Comment by muhammadyana** [comment]
@yortz i have tried configure the `redeirect_ui`, in my devise.rb like 
`config.omniauth :twitter, ENV['TWITTER_CLIENT_ID'], ENV['TWITTER_CLIENT_SECRET'], redirect_uri: 'http://localhost:4001/users/auth/twitter/callback'`
but it still error `undefined method underscore for nil:NilClass`
here the full code 
![image](https://user-images.githubusercontent.com/7847990/59429422-feab4d80-8e09-11e9-9aa2-b455c382d211.png)
