### ISSUE TITLE
Password reset allows user to bypass confirmable

### ISSUE THREAD

**Issue by dchersey** [lynndylanhurley/devise_token_auth#590]
In [passwords_controller.rb](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/passwords_controller.rb#L90), the following code: 

``` ruby
        # ensure that user is confirmed
        @resource.skip_confirmation! if @resource.devise_modules.include?(:confirmable) && !@resource.confirmed_at
```

actually sets the confirmed_at property of a resource if the resource has not been confirmed. 

This effectively allows the user to bypass email confirmation by resetting their password. 

I'd like to remove this line, so that the user IS able to change their password with the reset link but will not be able to log in until they confirm the email.

Thoughts?

**Comment by cars10** [comment]
Why would you? There is no security issure there. If the user can change the password then he can access his email account and  that means that he is able to confirm the account.

**Comment by dchersey** [comment]
But the email is passed as a parameter for reset; it could be different
than the one used for userid.

**Comment by dchersey** [comment]
Also, the comment seems to communicate the correct intention but the code actually does the opposite.

**Comment by MidnightWonderer** [comment]
But in which case the email for password resetting is different than the user id?

**Comment by zachfeldman** [comment]
Seems like a nonissue from the discussion so far, so I'm closing for now.
