### ISSUE TITLE
Problem with CORS setup and exposing special headers

### ISSUE THREAD

**Issue by GarPit** [lynndylanhurley/devise_token_auth#591]
Problem with CORS setup and exposing special headers (using master branch):

```
config/initializers/cors.rb:7:in `block (2 levels) in <top (required)>': undefined method `headers_names' for DeviseTokenAuth:Module (NoMethodError)
```

**Comment by nwade615** [comment]
+1

**Comment by y4ashida** [comment]
I don't know why headers_names is undefined, but you can write its values.
Like this:
```ruby
allow do
  origins '*'
  resource '*',
    headers: :any,
    expose: ['access-token', 'expiry', 'token-type', 'uid', 'client'],
    methods: [:get, :post, :options, :delete, :put]
end
```
(see. [lib/devise_token_auth/engine.rb#L38-L42](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/engine.rb#L38-L42))

**Comment by zachfeldman** [comment]
Seems like we have a proposed solution, so closing this for now
