### ISSUE TITLE
overriding rendering methods in devise_token_auth

### ISSUE THREAD

**Issue by omar28** [lynndylanhurley/devise_token_auth#597]
I am currently building a rails api and I am using your devise_token_auth. 

I’ve been stuck for a while on how to render custom data for user model. Rather than getting a ison like this:

{
  "data": {
    "id": 316,
    "provider": "email",
    "uid": "omar28112@hotmail.com",
    "name": "olahlou",
    "nickname": "olahlou",
    "email": "omar28112@hotmail.com",
    "score": 2,
    "image": null
  }
}

Let’s say the user has_many :posts, I would like to apply a user serializer(I am using active model serializers) to render something like (without the “data” key):

{
  “id”:316,
  “name”:”olahlou”,
  “posts”:[{
	#first post,
	#second post...  
  }]
}

I’ve read the documentation an I guess I have to override the SessionController#render_create_success but I really don’t know how to do it.

Thank you in advance for your  help.

**Comment by thelastinuit** [comment]
@omar28 

in your "User" model, try something like this:

```
def token_validation_response                                                                                                                                         
  UserSerializer.root = false
  UserSerializer.new(self).as_json
end
```

And in your user_serializer. you can set up whatever you want to render. 
Please let me know if that helps.

**Comment by thelastinuit** [comment]
@omar28 

```
def token_validation_response                                                                                                                                         
  UserSerializer.root = false
  UserSerializer.new(self).as_json
end
```

This will render your serializer.
Now for the data thingy, you need to look at session_controller:

```
def render_create_success
  render json: {
    data: resource_data(resource_json: @resource.token_validation_response)
  }
end
```

**Comment by thelastinuit** [comment]
Look at:

```
# config/routes.rb
Rails.application.routes.draw do
  ...
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    sessions_controller:  'overrides/sessions_controller'
  }
end

# app/controllers/overrides/sessions_controller.rb
module Overrides
  class SessionsController < DeviseTokenAuth::TokenValidationsController
    def render_create_success
      render json: resource_data(resource_json: @resource.token_validation_response)
    end
  end
end
```

**Comment by thelastinuit** [comment]
@omar28 Please close the issue if that worked for you. Otherwise, let me know so I can help you out ^_^

**Comment by kjakub** [comment]
why you inheriting 

`class SessionsController < DeviseTokenAuth::TokenValidationsController`

to override SessionsController ?

it should be `class SessionsController < DeviseTokenAuth::SessionsController` ?

**Comment by adisos** [comment]
Why `resource_data` method is not available when I override `SessionsController`?

I have this error:
```
NoMethodError (undefined method `resource_data' for #<Overrides::TokenAuth::SessionsController:0x007fc21abe6958>):
  app/controllers/overrides/token_auth/sessions_controller.rb:6:in `render_create_success'
```

**Comment by thelastinuit** [comment]
@kjakub sorry! You are right. I didn't pay attention to that. 
@adisos This is what I have:
```
class Api::V1::SessionsController < DeviseTokenAuth::SessionsController

  def resource_data(opts = {})
    opts[:resource_json] || @resource.as_json
  end

  def render_new_error
    render json: {
      errors: [I18n.t("devise_token_auth.sessions.not_supported")]
    }, status: 405
  end

  def render_create_success
    render json: {
      sponsor: resource_data(resource_json: @resource.userable.token_validation_response)
    }
  end

  def render_create_error_not_confirmed
    render json: {
      errors: [I18n.t("devise_token_auth.sessions.not_confirmed", email: @resource.email)]
    }, status: 404
  end

  def render_create_error_bad_credentials
    render json: {
      errors: [I18n.t("devise_token_auth.sessions.bad_credentials")]
    }, status: 402
  end

  def render_destroy_success
    render json: {
    }, status: 200
  end

  def render_destroy_error
    render json: {
      errors: [I18n.t("devise_token_auth.sessions.user_not_found")]
    }, status: 404
  end
end
```

It works fine. I made the mistake @kjakub mentioned. Use 
```
DeviseTokenAuth::SessionsController
```

instead of

```
DeviseTokenAuth::TokenValidationsController
```

My bad!

**Comment by adisos** [comment]
I know, I solved by defining method `resource_data` in my controller. But this method was already defined in `DeviseTokenAuth::ApplicationController` from which `DeviseTokenAuth::SessionsController` was inherited. Sorry for offtopic, but could somebody explain me?

**Comment by thelastinuit** [comment]
Well, the "why this works like that", only the creators/maintainers know. I'm here because I use it and maybe I might be useful. 
I would have done somethings in a diff way, though.

**Comment by adisos** [comment]
Well, I found out. I'm using rubygems version, which doesn't have `resource_data` method.

**Comment by thelastinuit** [comment]
Me too! This is strange... any one?

**Comment by adisos** [comment]
I think it's simple because gem author didn't update rubygems for a long time.

**Comment by AlbertoCamargo** [comment]
Take a look to this

ROUTES
 mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks], controllers: { sessions:  'overrides/sessions' }

Controller overwrite
module Overrides
  class SessionsController < DeviseTokenAuth::SessionsController
    protected
    def render_create_success
      render json: @resource
    end
  end
end


Credits to Doncote, here original post https://gitter.im/lynndylanhurley/devise_token_auth/archives/2015/12/18

**Comment by Meekohi** [comment]
I solved this by:
```
# user.rb
def token_validation_response                                                                                                                                         
    self.as_json(include: :posts)
end
```

This is pretty easy. The documentation at https://github.com/lynndylanhurley/devise_token_auth#overriding-rendering-methods makes it sound WAY more confusing, it would be great to add a section describing this common and much simpler case (i.e. don't need custom JSON per controller method, just in general for devise-token-auth, but don't want to change it everywhere else in the app).

**Comment by jachwe** [comment]
@Meekohi your answer is working perfectly and solved it for me.
(Unfortunately, I tried all the other ones before scrolling all the way down )
Really hope, people will read the full thread. Thank you!
