### ISSUE TITLE
Problem with auth headers and multiple models

### ISSUE THREAD

**Issue by ArmandoMendoza** [lynndylanhurley/devise_token_auth#602]
Hi. This is my problem, I override the controllers for an User model:
`mount_devise_token_auth_for 'User', at: 'auth', controllers: {`
   `registrations:      'v1/authentication/registrations',`
   `sessions:           'v1/authentication/sessions',`
   `token_validations:  'v1/authentication/token_validations'`
`}`
This work well, no problems. But, when i add a new Model using the same controllers:
`mount_devise_token_auth_for 'Admin', 'admin_auth', controllers: {`
   `sessions:           'v1/authentication/sessions',`
   `token_validations:  'v1/authentication/token_validations'`
`}`
`mount_devise_token_auth_for 'User', at: 'auth', controllers: {`
   `registrations:      'v1/authentication/registrations',`
   `sessions:           'v1/authentication/sessions',`
   `token_validations:  'v1/authentication/token_validations'`
`}`
Them the response header for Admin model dont have the auth keys. The response is ok(200) but dont return the auth headers. But if remove the controllers part(the override) for the Admin model the response return the auth keys. By the way, the overrides only change the render methods of the controllers. Any can help to find the way to solve this?

**Comment by ryankc33** [comment]
Same problem here.

**Comment by webgago** [comment]
yep, use [JWT](http://jwt.io)

**Comment by BrahimDahmani** [comment]
i have the same issue here, @ArmandoMendoza do you solve it?

**Comment by bskelton** [comment]
Are you using active_model_serializers?

**Comment by zachfeldman** [comment]
Hi there @ArmandoMendoza    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
