### ISSUE TITLE
Previous authentication params remain in url after sign out when using OAuth

### ISSUE THREAD

**Issue by volfgox** [lynndylanhurley/devise_token_auth#605]
For the first time the user log in using OAuth there is no problem; the session created and the token is validated. After the user sign out, the session is destroyed by devise_token_auth, also, the signed out session's parameters remain in url. So, after that, when the user tries to sign in for the second time, the url which contains previous session parameters, set as `auth_origin_url` in `omniauth.params` for the new authentication process and session creation phase. After that during the authentication phases, the new authentication params concat the previous params in url.

This event causes to `validate_token` action confused to use which params available in url. So, the second time and so on authentication with OAuth provider are failed, because the `validate_token'  action can not validate auth_token.

In my mind, the remaining params in url associated with previous session and authentication process should be deleted as a job in sign out action.

**Comment by zachfeldman** [comment]
Hi there @volfgox    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
