### ISSUE TITLE
Rails 5 API Mode - no headers in response

### ISSUE THREAD

**Issue by muzykabartek** [lynndylanhurley/devise_token_auth#606]
Hi everyone, we're trying to add authentication with `devise_token_auth` to an API we're building. We're using `Rails (5.0.0.beta3)` and `devise_token_auth (0.1.37)`.

```ruby
# Gemfile

ruby '2.3.0'
gem 'rails', '>= 5.0.0.beta3', '< 5.1'

gem 'pg', '~> 0.18'
gem 'puma'

gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'rack-cors'

gem 'devise', github: 'plataformatec/devise'
gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth'
gem 'omniauth', '>= 1.0.0'
```

Our routes look like that:
```ruby
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    scope module: 'api' do
      mount_devise_token_auth_for 'User', at: 'users', skip: [:omniauth_callbacks]
      ...
    end
  end
end
```

We set CORS with `rack-cors` following your [README.md#cors](https://github.com/lynndylanhurley/devise_token_auth#cors):
```ruby
# config/initializers/cors.rb

Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'
    resource '*',
             headers: :any,
             expose: %w(access-token expiry token-type uid client),
             methods: [:get, :post, :put, :patch, :delete, :options]
  end
end
```

Then we added `SetUserByToken` concern to the `ApplicationController`:
```ruby
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
end
```

Also, we set `DeviseTokenAuth.change_headers_on_each_request` to `false`.

Now, we start server with `rails s -b api.example.dev` (we'd set it up in `/etc/hosts`).
Then when we send `curl` request there is no [`access-token`, ..] headers:
```shell
curl -v -X POST -H 'Content-Type: application/json' -d '{"email": "admin@user.com", "password": "admin123"}' http://api.example.dev:3000/users/sign_in
```
```shell
*   Trying 127.0.0.1...
* Connected to api.example.dev (127.0.0.1) port 3000 (#0)
> POST /users/sign_in HTTP/1.1
> Host: api.example.dev:3000
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 51
> 
* upload completely sent off: 51 out of 51 bytes
< HTTP/1.1 200 OK
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: application/json; charset=utf-8
< ETag: W/"0145160dc42d2b8f0aa70ee5ed079729"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: c5d4b4f4-ce39-409c-b0c4-ce2ed607ee69
< X-Runtime: 0.271850
< Vary: Origin
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.example.dev left intact
{"data":{"id":1,"email":"admin@user.com","provider":"email","uid":"admin@user.com","name":"Admin","nickname":null,"image":null}}
```

Is there anything we're doing wrong? How can we fix it?
Thanks in advance!

**Comment by jpmermoz** [comment]
Same issue here... Not getting access token in response :(

**Comment by jpmermoz** [comment]
Setting:

config.enable_standard_devise_support = true 

worked for me

**Comment by muzykabartek** [comment]
Thanks @jpmermoz

Setting `DeviseTokenAuth.enable_standard_devise_support = true` fixed the issue in an ugly way: headers are present in the response but it creates 3 different tokens for the User.

**Comment by jpmermoz** [comment]
I think the problem is that `devise_token_auth` regards on devise 3.5, but we need devise 4.0 in order to work with rails 5 api, and that comes into these issues.

**Comment by muzykabartek** [comment]
@jpmermoz Hmm, I don't think that's the problem, we're using:
- `devise (4.0.0.rc2)`
- `devise_token_auth (0.1.37)`

**Comment by aaronshim** [comment]
I'm still having this problem, even after changing `enable_standard_devise_support = true` in my DeviseTokenAuth config file.

```
curl -v -H -XPOST http://localhost:3000/auth/sign_in -d email=test@email.com -d password=password
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> POST /auth/sign_in HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Length: 43
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 43 out of 43 bytes
< HTTP/1.1 200 OK
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: application/json; charset=utf-8
< ETag: W/"5b0131d12c193a3ca5468920bf0ecf4a"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 9937f64e-13b4-4c61-9ade-0ef9f153b7bd
< X-Runtime: 0.399675
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"data":{"id":6,"email":"test@email.com","provider":"email","uid":"test@email.com","name":null,"nickname":null,"image":null}}
```

**Comment by jpmermoz** [comment]
@muzykabartek exactly.. i'm using those same versions too. I guess `devise_token_auth` is not fully compatible with devise 4.0.0 yet

**Comment by bobmshannon** [comment]
Same issue here.

**Comment by muzykabartek** [comment]
@bobmshannon Just ran `bundle update` and it still works. **Devise** version has changed, now we're using:
* `devise (4.0.0)`
* `devise_token_auth (0.1.37)`

**Comment by bobmshannon** [comment]
@muzykabartek I should clarify that was with `config.enable_standard_devise_support = false`. I was running those two versions for a few months without issues, and it wasn't until I ran a bundle update that this issue started occurring.

What does your `Gemfile.lock` look like?

**Comment by bobmshannon** [comment]
@muzykabartek @jpmermoz @aaronshim Looks like there is a bug in active_model_serializers `v0.10.0.rc5` that is causing this issue, see https://github.com/rails-api/active_model_serializers/issues/1667.

Try downgrading to `v0.10.0.rc4` for the time being until a patch is released.

**Comment by tommoor** [comment]
@bobmshannon do you have a working setup now? Struggling to find the precise combination of gems that will enable this to work correctly!

**Comment by bobmshannon** [comment]
@tommor Hey Tom -- I do have everything working right now. This is what I am currently using:
- active_model_serializers `v0.10.0.rc4`
- devise_token_auth `v0.1.37`
- devise `v4.0.0`

It was downgrading active_model_serializers to `v0.10.0.rc4

**Comment by tommoor** [comment]
Thanks @bobmshannon - that seems to have it working - turns out on my end the new JavaScript `fetch` api was returning cached headers including cached tokens from previous responses. That took some figuring out 😄

**Comment by fowkswe** [comment]
I was also having issues with w/ v0.10.0.rc5, though different than described above.  

Login was creating multiple tokens, always one w/ the hashed client_id, and one with a client_id of 'default'.

Downgrading to v.0.10.0.rc4 fixed the issue for me.

**Comment by muzykabartek** [comment]
Downgrading `active_model_serializers` to `v0.10.0.rc4` fixes the issue. Newest version (`0.10.0`) doesn't seem to have fix for it.

**Comment by jeremyrajan** [comment]
I tried the above setup but doesnt fix it. I still dont get the access_token back after an api from postman.

```
#Gemfile
gem 'active_model_serializers', '~> 0.10.0.rc4'
gem 'friendly_id', '~> 5.1.0'
gem 'devise_token_auth', '~> 0.1.37'
gem 'devise', '~> 4.0.0'
```

```
#devise_token_auth.rb
enable_standard_devise_support = true
```

![image](https://cloud.githubusercontent.com/assets/2890683/15989658/78b962b2-30af-11e6-86ec-dc3649fd3c16.png)

Any help will be highly appreciated.

**Comment by jeremyrajan** [comment]
worked now :D apparently, my gemfile.lock was getting update with the one in gemfile. I have to manually add rc4 to it and things work :D. Not sure, why tho...

Cheers!

**Comment by fernandobrito** [comment]
I also had the same problem (no headers in response) and downgrading 'active_model_serializers' to ' 0.10.0.rc4' fixed the problem. Using enable_standard_devise_support = true was not necessary for me.

Current versions:
```
Installing active_model_serializers 0.10.0.rc4 (was 0.10.1)
Using devise 4.1.1
Using devise_token_auth 0.1.37 from git://github.com/lynndylanhurley/devise_token_auth.git (at master@bc04747
```

**Comment by kleber-gueriero** [comment]
Was this problem solved in current version?
I'm still not receiving the token in header of my requests

**Comment by kleber-gueriero** [comment]
OK, I figured out that I was expecting the wrong behavior, as mentioned in https://github.com/lynndylanhurley/devise_token_auth/issues/851
