### ISSUE TITLE
Override devise token auth response

### ISSUE THREAD

**Issue by NetanelBasal** [lynndylanhurley/devise_token_auth#609]
After the user signup I want to: 
1. Add fields to the response
2. Remove fields from the user object

How can I do that?

Thanks

**Comment by zachfeldman** [comment]
Hi there @NetanelBasal    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by karan101292** [comment]
Hi, Any update on this issue?
