### ISSUE TITLE
Allow updating of default attributes by default?

### ISSUE THREAD

**Issue by jasonswett** [lynndylanhurley/devise_token_auth#61]
I finished a rudimentary user profile feature today. In order to be able to update a user's `name`, I had to add `devise_parameter_sanitizer.for(:account_update) << :name`. Since `name` is an attribute that comes with Devise by default, it was confusing to me why I wasn't able to edit it and it took me kind of a long time to track down the reason.

I don't have a super strong opinion on this either way but it seems like maybe fields like `name` should be included in the attributes under `:account_update` by default.

As usual, I'd be willing to make it happen. I haven't looked into what that would involve but I'd assume it wouldn't be a huge amount of work.

**Comment by jasonswett** [comment]
FYI, I haven't forgotten I said I would do this, I'm just taking forever, sorry. I've been out of the Angular/Rails game for a while but now I'm back.

**Comment by zachfeldman** [comment]
Hi there @jasonswett ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if you're ready to contribute! Hope all is well.
