### ISSUE TITLE
Devise omniauth_path_prefix overriden

### ISSUE THREAD

**Issue by vdruon** [lynndylanhurley/devise_token_auth#610]
Can you tell me where this route redirects ?

`/api/auth/:provider`

in rake routes : 

`GET       /api/auth/:provider(.:format)                                                             redirect(301)`

**Comment by vdruon** [comment]
I found it, but can you tell me why this line in 'lib/devise_token_auth/engine.rb' ?

` ::OmniAuth::config.path_prefix = Devise.omniauth_path_prefix = self.omniauth_prefix`

It makes Devise.omniauth_path_prefix being overriden and when working with Devise + devise_token_auth getting conflicts when using omniauth

**Comment by zachfeldman** [comment]
Hi there @vdruon    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
