### ISSUE TITLE
exclude devise validatable module?

### ISSUE THREAD

**Issue by salmanasiddiqui** [lynndylanhurley/devise_token_auth#613]
Devise token auth overrides `email_required?` and `email_changed?` methods just to disable devise validations. Overriding `email_required?` seems ok as its a method defined by devise so people can expect devise token auth to override it. But overriding `email_changed?` is not the cleanest way to disable validations. I wanted to use it in condition for callbacks but ended up using `email_change` after coming to know that `email_changed?` is overridden by devise token auth

As devise suggests itself, that if there is a need to modify devise validations, then its better to just implement your own validators and exclude validatable module.

**Comment by zachfeldman** [comment]
Closed in favor of #662 (just to consolidate)
