### ISSUE TITLE
Email uniqueness on both email and oauth provider

### ISSUE THREAD

**Issue by PaulRenvoise** [lynndylanhurley/devise_token_auth#617]
I'm using devise_token_auth v0.1.37 and devise v3.5.7 along with omniauth v1.2.2.

Currently, devise_token_auth only provides email uniqueness on email provider. Is it possible to validate the uniqueness of an email for both email and oauth providers?
If so, how can I do it?

Thanks

**Comment by zachfeldman** [comment]
Hi there @PaulRenvoise    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
