### ISSUE TITLE
Retrieve from (local) cache first?

### ISSUE THREAD

**Issue by hrangel** [lynndylanhurley/devise_token_auth#622]
Hi,

I'm using **carrierwave** (+ carrierwave-ftp) in a Rails API project that uses **devise token auth**, but I'm getting ftp (too many connections) errors since everytime a rest API call is made, it loads up the current_user and retrieves the image from the FTP (even tough it won't be used in the response).

I've already contacted the project host providers but I was wondering if there is any way to:
- Skip the automatic retrieval from store when current_user is loaded
- ... or Force carrierwave to try loading file/image first from (local) cache

Any suggestions?

Regards,

Henrique

**Comment by zachfeldman** [comment]
Hi there @hrangel    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
