### ISSUE TITLE
user_signed_in? VS user.signedIn ?

### ISSUE THREAD

**Issue by FredHasselot** [lynndylanhurley/devise_token_auth#623]
I posted here : https://github.com/lynndylanhurley/ng-token-auth/issues/284 but maybe it's a server issue then i also post here.

On client side, using ng-token-auth and after submit login, this:  {{ user.signedIn ? "true" : "false" }} return "true"
so on client side i'm connected.

but if i use the devise helper on a rails controller that need authentification before action  : user_signed_in? it return "false"

so if i use `before_filter :authenticate_user!` it return a 401 response.

What's happening

**Comment by 7urkm3n** [comment]
I am struggling with it almost two weeks, did you find a solution in that ?

**Comment by FredHasselot** [comment]
No i did not ...

I used an other solution.
this post helped me a lot : http://blog.sundaycoding.com/blog/2015/04/04/token-authentication-with-tiddle/

**Comment by zachfeldman** [comment]
Seems like we have a solution/workaround, closing for now.
