### ISSUE TITLE
NoMethodError (undefined method `find_by_uid') in production.

### ISSUE THREAD

**Issue by dukeimg** [lynndylanhurley/devise_token_auth#625]
I have `NoMethodError (undefined method 'find_by_uid' for #<Class:0x007f0b056cb5d0>)` when I run Rails in production. Everything works fine in development. Gems I use:

`gem 'rails', '>= 5.0.0.beta3', '< 5.1'`
`gem 'devise', '~> 4.0.0.rc2'`
`gem 'devise_token_auth', github:"lynndylanhurley/devise_token_auth", branch: "master"`

**Comment by godinezb** [comment]
How did you solved the issue?

**Comment by thomasbromehead** [comment]
Would have liked to know too!
