### ISSUE TITLE
Rails 5 generator doesn't insert concern

### ISSUE THREAD

**Issue by TheDeadCode** [lynndylanhurley/devise_token_auth#627]
See this file [install_generator.rb](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/install_generator.rb#L32).

It specifies `after: "class #{user_class} < ActiveRecord::Base\n"`. Although Rails 5 doesn't specify `ActiveRecord::Base`, it specifies `ApplicationRecord` in the user models.

**Comment by booleanbetrayal** [comment]
Should be fixed via #636
