### ISSUE TITLE
Override default routes

### ISSUE THREAD

**Issue by tagCincy** [lynndylanhurley/devise_token_auth#628]
Is it possible to override/change the default routes generated?

We have an existing client side app that points new user registrations to `<path>/register` and logins to `<path>/login` and would like to not touch that code as much as possible.

In standard devise, you would use `devise_scope`;  is that the support means with this gem?

**Comment by mgokul595** [comment]
Yes, you can use devise_scope to change the routes..

**Comment by zachfeldman** [comment]
Workaround posted, closing issue
