### ISSUE TITLE
undefined method 'render' at devise_token_auth/controllers/helpers.rb

### ISSUE THREAD

**Issue by Abeleda** [lynndylanhurley/devise_token_auth#630]
Hi,

I have these error: undefined method 'render'

At: authenticate_user!devise_token_auth (0.1.37) lib/devise_token_auth/controllers/helpers.rb

**Gems**
gem 'rocket_pants', '~> 1.0'
gem 'devise', '~> 3.5.6'
gem 'devise_token_auth' 
gem 'omniauth'

**routes.rb**
devise_for :users
namespace :api, defaults: {format: :json} do
    api version: 1, module: 'v1' do
      mount_devise_token_auth_for 'User', at: 'auth'
      resources :users, :only => [:show]
    end
  end

**users_controller.rb**
class Api::V1::UsersController < Api::V1::BaseController
  include Devise::Controllers::Helpers
  include DeviseTokenAuth::Concerns::SetUserByToken
  version 1

  before_action :authenticate_user!

  def show
    expose User.find(params[:id])
  end

end

**Works**
- I can call /api/1/auth/sign_in
- /api/1/auth/validate_token
- /api/1/users/1 

But if I tried to call /api/1/users/1 without login it should respond: {"error":"You need to sign in or sign up before continuing."} but is not. It return:  undefined method 'render' 

Now in the controller I switch the includes as:
  include DeviseTokenAuth::Concerns::SetUserByToken
  include Devise::Controllers::Helpers

Then /api/1/users/1 without sing_in return the correct message: {"error":"You need to sign in or sign up before continuing."}; but the correct logged session not longer works, returns: {"error":"You need to sign in or sign up before continuing."}

So the order in the includes affects how it works.

Any solution ?

TIA

**Comment by zachfeldman** [comment]
Hi there @Abeleda    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
