### ISSUE TITLE
Relax devise dependency to allow 4.1

### ISSUE THREAD

**Issue by mtarnovan** [lynndylanhurley/devise_token_auth#631]
Devise master branch is now at [4.1](https://github.com/plataformatec/devise/blob/master/lib/devise/version.rb), but `devise_token_auth` lists the dependency as:

`s.add_dependency "devise", "> 3.5.2", "< 4.1"`

Can we relax it to <= 4.1?

**Comment by bousquet** [comment]
:+1: if this has been tested against devise 4.1.  However, I haven't personally done that yet.

**Comment by booleanbetrayal** [comment]
looks like @TGRGIT has tested some on 4.1, so relaxing a bit.
