### ISSUE TITLE
is possible to use provider and uid columns on the authentications table? 

### ISSUE THREAD

**Issue by Rovel** [lynndylanhurley/devise_token_auth#633]
I'm getting the classic error:
undefined method `provider' for #User:0x007f8867a82ce8

I know there is already an issue about that and all its config is described on the docs, but my issue is some sort different...

I've saw that it needs a method to get the provider and uid and set it on the user table as the registration goes on, but I already have these columns on the authentications table and it seems weird to have the same column in the both tables since user has_many authentications, but thinking about it the registration method, it doesn't make an authentication as it goes on right? so just for best practices is ok to have a provider and uid in both tables?

I've tried to find this relation on the user and authentication around provider and uid in the documentation and didn't found id so if it exists I would like to read it, please send reference.

So some help here would be great! :)

Thanks.

**Comment by zachfeldman** [comment]
Hi there @Rovel    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by Rovel** [comment]
Hi @zachfeldman,  you can close it, thanks
