### ISSUE TITLE
make use of max_number_of_devices on sign_in

### ISSUE THREAD

**Issue by Hasan-a-ayar** [lynndylanhurley/devise_token_auth#637]
Hi everybody, 

The `create_new_auth_token` method in `DeviseTokenAuth::Concerns::User` actually maintains the maximum count of tokens per user according to the `max_number_of_devices` parameter. 

But create method of `DeviseTokenAuth::SessionsController` does not use `create_new_auth_token` so a new token is added on each login. 

Is this something that needs to be fixed?

Thanks, Hasan.

**Comment by zachfeldman** [comment]
Hi there @Hasan-a-ayar    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
