### ISSUE TITLE
Oauth2 - Android Authentication - one-time-code flow 

### ISSUE THREAD

**Issue by philippe3973** [lynndylanhurley/devise_token_auth#639]
Im trying to implement oauth authentication (google) on my android app, instead of using custom devise authentication.
Im using the one time code flow : by sending one-time code to the server from my android app, server can fetch user informations.

Im not sure how : /:provider/callback route handle with one-time code flow.

The documentation shows that its easy to implement browser client oauth authentication.
Does this gem provide one time-code flow for an android app that authenticate with Oauth Provider?

**Comment by augustosamame** [comment]
+1

**Comment by killerham** [comment]
I'm also having issues with Facebook login from my iOS app.

Sending to ```auth/:provider``` simply puts it into this state:

```INFO -- omniauth: (facebook_access_token) Request phase initiated.```

**Comment by gutosanches** [comment]
+1

**Comment by at-anhlt** [comment]
+1

**Comment by zachfeldman** [comment]
Hi there @philippe3973 and @r0ckkhuya    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
