### ISSUE TITLE
Error with devise

### ISSUE THREAD

**Issue by yovasx2** [lynndylanhurley/devise_token_auth#643]
I'm using Devise Token Auth gem and, everytime I run my test suite in Rails 4.2.5 app, I'm getting this deprecation warning from Devise:

DEPRECATION WARNING: [Devise] config.email_regexp will have a new default on Devise 4.1 To keep the current behavior please set in your config/initializers/devise.rb the following:

```
Devise.setup do |config|
   config.email_regexp = /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/
end
```

If you want to use the new default:

```
Devise.setup do |config|
   config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
end
```

(called from block in tsort_each at /usr/local/lib/ruby/2.2.0/tsort.rb:226)
I've already added config/initializers/devise.rb file manually and have set email_regex as suggested by the message above, but the annoying message persists.

How can I disable this message?

**Comment by RobAWilkinson** [comment]
Not a full fix but [this SO answer](http://stackoverflow.com/questions/37240629/how-to-get-rid-of-email-regex-message-on-devise) hid the deprecation warning for me

**Comment by yovasx2** [comment]
In fact thats my answer
