### ISSUE TITLE
Issues with active_model_serializers

### ISSUE THREAD

**Issue by virginia-rodriguez** [lynndylanhurley/devise_token_auth#644]
I was using active_model_serializers 0.9.5 with last released version of devise_token_auth (0.1.37) and everything worked fine. Then I tried to use devise_token_auth master branch to use a fix that was present there. But other changes introduced to master branch cause devise_token_auth to stop working properly (ex. sign in is broken). An exception is raised in https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/application_controller.rb#L38, because ActiveModel::Serializer config is not defined.
`NoMethodError (undefined method 'config' for ActiveModel::Serializer:Class):
`

Also, since devise_token_auth seems to be having some issues with last version of active_model_serializers (see https://github.com/lynndylanhurley/devise_token_auth/issues/600), why force to use last version? 

What about just replacing the conflictive line with:
`ActiveModel::Serializer.respond_to?(:config) && ActiveModel::Serializer.config.adapter == :json_api`

Anyone is having similar issues?

**Comment by SarSar440** [comment]
Not sure if this is related but I have since updated my Active model serializer gem and suddenly the client authentication header is now default.

**Comment by SebAshton** [comment]
@virginia-rodriguez I had this issue, and solved it by specifying version `'~> 0.10.0'` in my Gemfile.

e.g. `gem 'active_model_serializers', '~> 0.10.0'`

**Comment by augustosamame** [comment]
I am getting a similar error on sign-in / sign-up:

NoMethodError (undefined method `setup' for ActiveModel::Serializer:Class):
  
/home/augusto/.rvm/gems/ruby-2.3.0@faces/bundler/gems/devise_token_auth-81fc7b40998d/app/controllers/devise_token_auth/application_controller.rb:38:in `is_json_api'

I have the following in my gem file:

gem 'devise'
gem 'devise_token_auth', :git => 'git://github.com/lynndylanhurley/devise_token_auth.git'
gem 'active_model_serializers', '~> 0.10.0'

Any ideas?

**Comment by augustosamame** [comment]
This https://github.com/lynndylanhurley/devise_token_auth/commit/7b9727995e1eb42385a2a4102516fcd3a372ad81 commit is not compatible with current 0.10.0 version of Active Model Serializer. Patching now

**Comment by booleanbetrayal** [comment]
i'll take that PR whenever you get a chance @augustosamame -- the state of things in AMS is kinda confusing these days.

**Comment by bf4** [comment]
@augustosamame just submit a revert of https://github.com/lynndylanhurley/devise_token_auth/pull/648 and all will be well

**Comment by bf4** [comment]
@booleanbetrayal nah, it's pretty simple

- 0.8 was great
- 0.9 was a rewrite, people still use 0.8
- 0.10 is a 0.8-incomptabile rewrite of 0.8 that was in rc for a year, and is finally out, people still use 0.8 and 0.9

:trollface: myself

**Comment by booleanbetrayal** [comment]
github has made it super-easy to revert without typing, which is what i just did via #652

**Comment by augustosamame** [comment]
a revert won't do since it will break compatibility with AMS 0.9.2
patch almost ready

**Comment by booleanbetrayal** [comment]
Should be resolved as of #651 ... Please verify as I don't have access to my dev env atm.

**Comment by augustosamame** [comment]
@woodcrust beat me to it Confirmed issue is resolved as of #651 .
