### ISSUE TITLE
headers_names is not defined in 0.1.37

### ISSUE THREAD

**Issue by tvilon** [lynndylanhurley/devise_token_auth#645]
I set up a basic new Rails app with rails-api (0.4.0), devise (4.0.3) and devise_token_auth (0.1.37).
I followed the guide provided in devise_token_auth `README` (including setting up CORS). 

The User Sign up worked nicely and I could create new user by calling `/auth/` but `/sign_in/` would fail during Serialization with: 

```
NoMethodError (undefined method `[]' for nil:NilClass):
  devise_token_auth (0.1.37models) devise_token_auth/concerns/user.rb:202:in `build_auth_header'
  devise_token_auth (0.1.37controllers) devise_token_auth/concerns/set_user_by_token.rb:77:in `update_auth_header'
```

From what i could debug `headers_names` was not defined on `DeviseTokenAuth`. I fixed in my monkey patching the gem: adding in `devise_token_auth.rb`:

```
DeviseTokenAuth.class_eval do
    mattr_accessor :headers_names
    self.headers_names = {
        :'access-token' => 'access-token',
        :'client' => 'client',
        :'expiry' => 'expiry',
        :'uid' => 'uid',
        :'token-type' => 'token-type' }
end
```

And now it works. This code is present on master branch but not in last release. 

So I am curious how could it be that 0.1.37 doesn't define `headers_names`. Any idea? 

Is there a plan to release a new version with latest changes? (allowing me to remove my patch). 
Thanks for the awesome work on this 👍

**Comment by tvilon** [comment]
I also add to apply this patch: [#523](https://github.com/lynndylanhurley/devise_token_auth/pull/523)

**Comment by neilhanekom** [comment]
Has this been resolved in 0.1.38?? I am using 0.1.37 and having the same issue but would prefer to skip monkey patching if this is resolved by 0.1.38. Else I do this??

**Comment by tvilon** [comment]
I haven't checked in the new version yet. I'll try to get to that soon but for now I continue to use 0.1.37 with this at the end of /config/initializers/devise_token_auth.rb

```
...

# Monkey patch for
# https://github.com/lynndylanhurley/devise_token_auth/pull/523
DeviseTokenAuth::Concerns::User.class_eval do
	
  def build_auth_header(token, client_id='default')
    client_id ||= 'default'

    if !DeviseTokenAuth.change_headers_on_each_request && self.tokens[client_id].nil?
      create_new_auth_token(client_id)
    else

      # client may use expiry to prevent validation request if expired
      # must be cast as string or headers will break
      expiry = self.tokens[client_id]['expiry'] || self.tokens[client_id][:expiry]

      return {
        DeviseTokenAuth.headers_names[:"access-token"] => token,
        DeviseTokenAuth.headers_names[:"token-type"]   => "Bearer",
        DeviseTokenAuth.headers_names[:"client"]       => client_id,
        DeviseTokenAuth.headers_names[:"expiry"]       => expiry.to_s,
        DeviseTokenAuth.headers_names[:"uid"]          => self.uid
      }
    end
  end
end

# https://github.com/lynndylanhurley/devise_token_auth/issues/645
DeviseTokenAuth.class_eval do
	mattr_accessor :headers_names
	self.headers_names = {
		:'access-token' => 'access-token',
		:'client' => 'client',
		:'expiry' => 'expiry',
		:'uid' => 'uid',
		:'token-type' => 'token-type' }
end
```

**Comment by neilhanekom** [comment]
Thanks for reply. I have updated to version 0.1.38 and it seems to work successfully.

**Comment by zachfeldman** [comment]
Great!
