### ISSUE TITLE
confrimable registration token expire

### ISSUE THREAD

**Issue by piotr-galas** [lynndylanhurley/devise_token_auth#655]
When I click confirmation token from email it always login me into app . Even if token is expired. Action responsible for confirmation looks:

```
   def show

     @resource = resource_class.confirm_by_token(params[:confirmation_token])

      if @resource and @resource.id
              ....
```

Above condition which trigger success confirmation logic,  is always true, even `@resource.confirmed? = false` .

**Comment by bslipek** [comment]
I also have that problem

**Comment by zachfeldman** [comment]
Hi there @piotr-galas @bslipek   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
