### ISSUE TITLE
[Question] Using in mobile apps (pass reset/libs for major OSes)?

### ISSUE THREAD

**Issue by vanburg** [lynndylanhurley/devise_token_auth#657]
Hi! I had successfully setup token auth on backend + web client with `j-toker`, and now I wondering how to integrate it with mobile apps. To be short, here is two questions:
- password reset for email registration. This is most interesting. Once user click on reset pass link in email, this link will be opened in browser (user **can** open it in browser, he must not know all these technical things :) ). Next  `GET /password/edit` will return 302 status with `location` and all the necessary data in query string for mobile app. That's great, but how to handle this in mobile app? How to get this data? Any workarounds if it's not possible?
- more common question: tried to look for some libs for iOS and Android compatible with DTA (or at least configurable to support it), but didn't find... Do you know such?
  Thanks! And great work, BTW :)

**Comment by zachfeldman** [comment]
Hi there @vanburg    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
