### ISSUE TITLE
Password Reset Link doesn't work

### ISSUE THREAD

**Issue by umekun123** [lynndylanhurley/devise_token_auth#658]
I am using devise_token_auth on my Rails api for iOS and 
I have a problem for password reset link.

I set action_mailer with sendgrid and Heroku, so I can receive password reset mail on my mail box.

---

Hello world example@gmail.com!
    Someone has requested a link to change your password. You can do this through the link below.
    Change my password
    If you didn't request this, please ignore this email.

---

But, after I click the "Change my Passowrd" link, it jumps to the this address with token like this.

https://taxnote.herokuapp.com/api/auth/password/edit?config=default&redirect_url=http%3A%2F%2Fgoogle.com&reset_password_token=tysZ9UMUkwoian7JmUdf

And, it says "The page you were looking for doesn't exist." 
I thought it is simple routing error, but still cannot tell how to solve this.

According to the doc, 

 # this is where users arrive after visiting the email confirmation link
https://github.com/lynndylanhurley/devise_token_auth/blob/15bf7857eca2d33602c7a9cb9d08db8a160f8ab8/test/dummy/app/controllers/overrides/passwords_controller.rb

I  also wonder this issue is related to the reason I am using rails-api gem which doesn't have views in my projects.

**Comment by raghvendra** [comment]
I have a similar problem, the reset password link works for the first time I visit it.
But, if I don't change the password and re-visit the link then it doesn't work and return Route not found error.

**Comment by chayuto** [comment]
same here, but i get {"success":false} instead

**Comment by zachfeldman** [comment]
Hi there @umekun123    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
