### ISSUE TITLE
Bump version to support devise 4.1.1

### ISSUE THREAD

**Issue by samuelpismel** [lynndylanhurley/devise_token_auth#659]
Can you bump the version to add support do last devise version?

The 0.1.37 version doesn't have support yet.

Thanks

**Comment by v3rron** [comment]
Can't update my gems now, it says:
````
Bundler could not find compatible versions for gem "devise":
  In Gemfile:
    devise (>= 4.1.1, ~> 4.1)

    devise_token_auth (~> 0.1.37) was resolved to 0.1.37, which depends on
      devise (< 4.1, > 3.5.2)
````

**Comment by jclif** [comment]
Would love to have this working for devise 4.2!

**Comment by booleanbetrayal** [comment]
I just bumped the gem to `0.1.38` on RubyGems. Seemed to work fine with Devise 4.2. Will be prioritizing any Rails 5 bugs.
