### ISSUE TITLE
Seperate view files for different models.

### ISSUE THREAD

**Issue by balakarthik2011** [lynndylanhurley/devise_token_auth#664]
I have two models created using devise token auth namely user and admin.
The mail contents which is to be given for users and admins are different, is there any way to create multiple views for these models.

**Comment by kaiyzen** [comment]
Trying to figure this out myself, so far no luck.  First tried to look for certain variable values in the view to see if admin user but no luck.  After searching some found that devise itself natively supports this with "scoped views", looks like token auth doesn't support that by default however is passing things off.

**Comment by zachfeldman** [comment]
Hi there @balakarthik2011    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
