### ISSUE TITLE
Devise Omniauth and DeviseTokenAuth Omniauth

### ISSUE THREAD

**Issue by dtelaroli** [lynndylanhurley/devise_token_auth#666]
Is it possible use two way of authentication (devise and devise_token_auth)?

I'm trying but the devise omniauth uses same api path and the redirection (/omniauth/:provider/callback), and after redirect goes to api path with error (Could not authenticate you from Facebook because "Csrf detected".).

My route configuration:

```
devise_for :users
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
  end
```

In separated apps both works fine.

**Comment by poc7667** [comment]
Try this on your application_controller

> 
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format.json? }

**Comment by dtelaroli** [comment]
I've created a new application to test it.
I need now create two way of authentication.

1. Sign In/Up with Facebook and Devise (Rails)
2. Sign In/Up with Facebook and Devise Token Auth (Ionic App)

The step 1 works as well, but the step 2 uses same callback fase, and redirect to root_path like the step 1.
How can I configure different callback to Devise Token Auth? 

Now my route is:

```
  devise_for :users, controllers: {omniauth_callbacks: 'callbacks'}
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      as :user do
        resources :index
      end
    end
  end
  resources :home
```

**Comment by dtelaroli** [comment]
I started new blank application to try solve it.
I configured devise and now I have problem with devise_token_auth.
In callback fase, both return pass thought the devise callback. I don't know how can I separate it or to identify who start the authentication.

**Comment by macchie** [comment]
Any progress with this?

**Comment by steverob** [comment]
Any progress in this? :)

**Comment by sebfie** [comment]
I also need this!

**Comment by zachfeldman** [comment]
Hi there @dtelaroli    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by dtelaroli** [comment]
I did'nt saw this before, but, I give up this plugin because it has a lot of bugs and incompatibilities for me with no help.
Thanks.
