### ISSUE TITLE
0.1.36 to 0.1.37 Breaks Test Suite

### ISSUE THREAD

**Issue by jclif** [lynndylanhurley/devise_token_auth#670]
I'm developing a Rails project with the following versions:

```
ruby '2.3.1'
gem 'rails', '4.2.6'
```

I have a working test suite on 0.1.36 using the following approach:
- spec/support/devise.rb:

```
RSpec.configure do |config|
  config.include Devise::TestHelpers, :type => :controller
end
```
- spec/support/sign_in.rb

```
module ValidUserHelper
  def sign_in_as_valid_user
    @current_user ||= FactoryGirl.create :user
    @current_user.confirm
    sign_in @current_user
  end
end

RSpec.configure do |config|
  config.include ValidUserHelper, :type => :controller
end
```
- app/controllers/api/base_controller.rb

```
class API::BaseController < ApplicationController
  before_action :authenticate_user!
  respond_to :json
end
```

Upon upgrading to 0.1.37, I found that all of the requests in my controller specs were returning 401 Unauthorized. Has anyone else run into this issue?

**Comment by jclif** [comment]
Changing my `sign_in_as_valid_user` to this helped:

```
module ValidUserHelper
  def sign_in_as_valid_user
    @current_user ||= FactoryGirl.create :user
    @current_user.confirm
    sign_in @current_user
    request.headers.merge!(@current_user.create_new_auth_token)
  end
end

RSpec.configure do |config|
  config.include ValidUserHelper, :type => :controller
end
```

**Comment by adamsanderson** [comment]
Just wanted to mention that I ran into the same issue.  I upgraded both devise and devise_token_auth so I can't be sure which introduced the issue, but for minitest the following fixed the `sign_in` method:

```
class ActionController::TestCase
  include Devise::Test::ControllerHelpers
  
  def sign_in(user)
    super
    request.headers.merge!(user.create_new_auth_token)
  end
```

**Comment by ShaunSpringer** [comment]
👍 I am experiencing this issue too. The above solutions didn't work for me

**Comment by jclif** [comment]
This works for me:
```
module ValidUserHelper
  def sign_in_as_valid_user
    @current_user ||= FactoryGirl.create :user
    @current_user.confirm
    sign_in @current_user
    request.headers.merge!(@current_user.create_new_auth_token)
  end
end

RSpec.configure do |config|
  config.include ValidUserHelper, :type => :controller
end
```

**Comment by zachfeldman** [comment]
Hi there @jclif   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
