### ISSUE TITLE
rails g devise_token_auth:install User auth hangs and does nothing

### ISSUE THREAD

**Issue by throoze** [lynndylanhurley/devise_token_auth#671]
Hi! im trying to run the generator. I installed `devise_token_auth` via Gemfile. I'm using rbenv, with

    Rails 4.2.6
    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

And the output of my `uname -a` is:

    Linux daat 4.2.0-41-generic #48~14.04.1-Ubuntu SMP Fri Jun 24 17:09:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

When I run `rails g devise_token_auth:install User auth`, it just hangs and after some time I end up killing the process. I also tried running `bundle exec rails g devise_token_auth:install User auth` and `rbenv exec bundle exec rails g devise_token_auth:install User auth`, and the behavior is the same.

Any idea what could be happening? or how to debug this?

**Comment by throoze** [comment]
Well i just restarted my pc and it went well... That old trick did it. xD

**Comment by tomca32** [comment]
Yes, restarting the machine will fix it, but there's an easier way.

What actually happens is that spring preloader hangs somewhere. If you want to fix this without restarting the machine, kill the spring process(es). Here's a quick way to do it
```bash```
ps -ef | grep spring | grep -v grep | awk '{print $2}' | xargs kill -9

**Comment by henrique-ch** [comment]
@tomca32
Thank you very much! It really worked
