### ISSUE TITLE
Reset Password doesn't getting expired..

### ISSUE THREAD

**Issue by balakarthik2011** [lynndylanhurley/devise_token_auth#672]
@lynndylanhurley i have problem in resetting password process.
 The reset Password token which is sent to the mail id doesn't getting expired.

I have set the reset password token validity by using

`config.reset_password_within = 24.hours`

but even after if a use a reset password token which has been generated 6 hrs back i am able to get back the user access token, and client id etc.., by requesting the edit API in the password controller

```
def edit

      @resource = resource_class.reset_password_by_token({

        reset_password_token: resource_params[:reset_password_token]

      })



      if @resource and @resource.id

        client_id  = SecureRandom.urlsafe_base64(nil, false)

        token      = SecureRandom.urlsafe_base64(nil, false)

        token_hash = BCrypt::Password.create(token)

        expiry     = (Time.now + DeviseTokenAuth.token_lifespan).to_i



        @resource.tokens[client_id] = {

          token:  token_hash,

          expiry: expiry

        }



        # ensure that user is confirmed

        @resource.skip_confirmation! if @resource.devise_modules.include?(:confirmable) && !@resource.confirmed_at



        # allow user to change password once without current_password

        @resource.allow_password_change = true;



        @resource.save!

        yield @resource if block_given?



        redirect_to(@resource.build_auth_url(params[:redirect_url], {

          token:          token,

          client_id:      client_id,

          reset_password: true,

          config:         params[:config]

        }))

      else

        render_edit_error

      end

    end

```

when i had a look on how the reset password process works, i came accross a problem in the method..,
reset_password_by_token method in 

```
 @resource = resource_class.reset_password_by_token({

        reset_password_token: resource_params[:reset_password_token]

      })

```

this method is used to validate the the token, where the validity of the token is checked using the method

`reset_password_period_valid?`

in the 

```
def reset_password_by_token(attributes={})
  original_token       = attributes[:reset_password_token]
  reset_password_token = Devise.token_generator.digest(self, :reset_password_token, original_token)

  recoverable = find_or_initialize_with_error_by(:reset_password_token, reset_password_token)

  if recoverable.persisted?
    if recoverable.reset_password_period_valid?
      recoverable.reset_password(attributes[:password], attributes[:password_confirmation])
    else
      recoverable.errors.add(:reset_password_token, :expired)
    end
  end

  recoverable.reset_password_token = original_token if recoverable.reset_password_token.present?
  recoverable
end
```

where when the token is not valid the errors are added to the resource object,

```
 if recoverable.reset_password_period_valid?
      recoverable.reset_password(attributes[:password], attributes[:password_confirmation])
    else
      recoverable.errors.add(:reset_password_token, :expired)
    end
```

but it must be checked in the edit api in the password controller, but it is not done,

`if @resource and @resource.id`

A resource is alone checked, even though if any errors present in the resource object is present, it is not verified and the token details are sent.

i think the correct solution for verifying the validity of the token must be

`if @resource and @resource.id and @resource.errors.empty?`

**Comment by dks17** [comment]
@balakarthik2011 Hello. Looks like your problem was solved recently. Try to switch on master branch. Does your problem still occur?
