### ISSUE TITLE
E-mail confirmations sent twice (duplicate emails)

### ISSUE THREAD

**Issue by develop-test1** [lynndylanhurley/devise_token_auth#677]
Gem version: **0.1.38** (as well as from master branch latest)

Rails version: **5.0.0 API**

This version resolves #500, however it introduces error where same confirmation e-mail is sent **twice**, once the auth POST register action is performed resulting in duplicate e-mail sending.

MailCatcher screenshot:
![screenshot from 2016-07-12 12 10 13](https://cloud.githubusercontent.com/assets/17426509/16763564/a1e55fec-4829-11e6-9a55-2acb34ecc00b.png)

It is also worth noting that this **only happens for confirmation e-mails**. Password reset e-mails are sent once as expected.

**Comment by develop-test1** [comment]
I found out that removing these lines in registrations_controller fixes the problem and confirmation e-mails are sent once:
```
  unless @resource.confirmed?
              # user will require email authentication
              # @resource.send_confirmation_instructions({
              #   client_config: params[:config_name],
              #   redirect_url: @redirect_url
              # })

            else
```

**Comment by develop-test1** [comment]
Opened-up pull request: https://github.com/lynndylanhurley/devise_token_auth/pull/678

**Comment by develop-test1** [comment]
Other way to fix this problem is to include this in the user model:

```
  before_create :skip_duplicate_devise_confirmation_email

# Fixes problem with duplicate account confirmation emails
  def skip_duplicate_devise_confirmation_email
    skip_confirmation_notification!
  end
```

**Comment by brunowego** [comment]
@develop-test1 your solution works for me.

**Comment by MaicolBen** [comment]
#678 got it fixed, closing
