### ISSUE TITLE
skip_confirmation_notification! not working

### ISSUE THREAD

**Issue by arparthasarathi** [lynndylanhurley/devise_token_auth#679]
The confirmation mail is sent automatically when a user is created. But I need to send the mail through code manually after completing a few more steps.

I can't able to prevent the confirmation mail from sending.

User model
```
class User < ActiveRecord::Base
  include DeviseTokenAuth::Concerns::User
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  before_create :skip_confirmation_notification!
```

**Note:** If I try to use **skip_confirmation!** it works perfectly without any flaw. But I don't need that functionality because I want to confirm the users only through the confirmation link sent to their mail.

**Comment by lynndylanhurley** [comment]
Try removing `:confirmable` from the list of devise methods at the top of your `User` model, then removing the `before_create :skip_confirmation_notification!`.

```ruby
class User < ActiveRecord::Base
  include DeviseTokenAuth::Concerns::User
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
```

This should have the same effect as what you're trying to do. Then you can manually send the email later on if you want.

**Comment by arparthasarathi** [comment]
The basic confirmable functionalities as such like sending mail, updating confirmable columns in the db are working perfectly. I do not want to interrupt the existing functionalities. But only need to delay sending the notification so that this awesome gem is fully utilised.
