### ISSUE TITLE
client_id resets to default after session_controller#create

### ISSUE THREAD

**Issue by daggeto** [lynndylanhurley/devise_token_auth#680]
HI. I'm using: 'devise_token_auth', '~> 0.1.38'. 
Problem: I cant use auth token for multiple clients because client_id is always `default`.
Symptoms: After sessionController#create `set_user_by_token` and as header doesn't contain client id it sets to `default`.
Here is stack when `set_user_by_token` is called:

```
#0  current_user <ApplicationController#current_user()>
   #1 [method]  serialization_scope <ActionController::Serialization#serialization_scope()>
   #2 [block]   block in get_serializer <ActionController::Serialization#get_serializer(resource, options=?)>
   #3 [method]  get_serializer <ActionController::Serialization#get_serializer(resource, options=?)>
   #4 [block]   block (2 levels) in <module:Serialization> <ActionController::Serialization#_render_with_renderer_json(resource, options)>
   #5 [block]   block in _render_to_body_with_renderer <ActionController::Renderers#_render_to_body_with_renderer(options)>
   #6 [method]  each <Set#each(&block)>
   #7 [method]  _render_to_body_with_renderer <ActionController::Renderers#_render_to_body_with_renderer(options)>
   #8 [method]  render_to_body <ActionController::Renderers#render_to_body(options)>
   #9 [method]  render <AbstractController::Rendering#render(*args, &block)>
   #10 [method]  render <ActionController::Rendering#render(*args)>
   #11 [block]   block (2 levels) in render <ActionController::Instrumentation#render(*args)>
   #12 [block]   block in ms <Benchmark.ms()>
   #13 [method]  realtime <Benchmark.realtime()>
   #14 [method]  ms <Benchmark.ms()>
...
```

**Comment by joyeux7** [comment]
Maybe you can try, 

class SessionsController < DeviseTokenAuth::SessionsController
    skip_before_filter :authenticate_user!
  **skip_after_action :update_auth_header, :only => [:create]**
 
  def create
         ...................
        @client_id = SecureRandom.urlsafe_base64(nil, false)
        @token     = SecureRandom.urlsafe_base64(nil, false)
        @resource.tokens[@client_id] = {
              token: BCrypt::Password.create(@token),
              expiry: (Time.now + DeviseTokenAuth.token_lifespan).to_i
        }
        @resource.save
       sign_in(:user, @resource, store: false, bypass: false)
       yield @resource if block_given?
      **# generate auth headers for response
      new_auth_header = @resource.build_auth_header(@token, @client_id)
      # update response with the header that will be required by the next request
      response.headers.merge!(new_auth_header)**
      render_create_success
      ...............
   end

**Comment by zachfeldman** [comment]
Hi there @daggeto    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
