### ISSUE TITLE
undefined method `[]' for nil:NilClass during omniauth callback

### ISSUE THREAD

**Issue by franciscoml67** [lynndylanhurley/devise_token_auth#682]
I think there's some kind of problem with this line of code in omniauth_callbacks_controller (line 14):

```
...

  devise_mapping = [request.env['omniauth.params']['namespace_name'],
                    request.env['omniauth.params']['resource_class'].underscore.gsub('/', '_')].compact.join('_')
...
```

After successfully being prompted by facebook, the 'omniauth' object seems to be empty raising the following error:

```
undefined method `[]' for nil:NilClass

C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/bundler/gems/devise_token_auth-162967970c95/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:14:in `redirect_callbacks'
```

I think this issue has been addressed before, but I think it wasn't solved and it has now, resurfaced.

**Comment by franciscoml67** [comment]
A more detailed description of what is going on can be found [here](http://stackoverflow.com/questions/38662725/request-envomniauth-params-null-using-devise-token-auth-gem-for-rails-4)

**Comment by franciscoml67** [comment]
update: the request.env['omniauth.params'] is coming in null from the callback, as well as request.env['omniauth.auth'] for that matter...

would really appreciate some help in this @lynndylanhurley ! thank you in advance

**Comment by jaredcnance** [comment]
I'm also running into this issue

**Comment by zachfeldman** [comment]
Hi there @franciscoml67    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by mgs96** [comment]
hey @franciscoml67 @zachfeldman I'm having this same issue!

**Comment by fabien7337** [comment]
hey @franciscoml67 @zachfeldman I'm having this same issue!

**Comment by DumasOlivier** [comment]
@franciscoml67 did you find any solution ? Getting the same problem ...

**Comment by fabien7337** [comment]
Yes, I stopped using devise_token_auth and omniauth :)

**Comment by DumasOlivier** [comment]
> Yes, I stopped using devise_token_auth and omniauth :)
> 
> I did it from scratch by myself. It is not this complicated and at least you have no issue!

Ahaha maybe I will do the same in a few hours 🤯🤯🤯

**Comment by DaniyalBasit** [comment]
Trying a different version of `omniauth-google-oauth2` gem solved the issue for me.

**Comment by sumitmaurya021** [comment]
Error during Google OAuth callback: undefined method `persisted?' for nil:NilClass

**how to solve this problem?**
