### ISSUE TITLE
No Headers after sign_in for new Users created by Admin

### ISSUE THREAD

**Issue by BrahimDa** [lynndylanhurley/devise_token_auth#685]
I've created several admin-users, you can refer to the Create action in AdminUsersController as it's mentioned below, and when i tried to sign-in i didn't get the desired Headers such as "access_token, expiry,uid..."

```ruby
def create
      admin_user = AdminUser.new admin_user_params

      if admin_user.save
        render json: admin_user , status: :created
      else
        render json: admin_user.errors , status: :unprocessable_entity
      end
end
```

**Request**
```javascript
[POST] http://api.myapp.local:3000/admin/sign_in

//header
Accept:application/vnd.myapp.v1
Content-Type:application/json

//data
{
  	"email": "admin@simple.tn",
	"password": "password"
}


```
**Response:**
```http
Access-Control-Allow-Credentials →true
Access-Control-Allow-Methods →GET, POST, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin →chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Access-Control-Expose-Headers →access-token, expiry, token-type, uid, client
Access-Control-Max-Age →1728000
Cache-Control →no-cache
Content-Type →application/json; charset=utf-8
Transfer-Encoding →chunked
Vary →Origin
X-Content-Type-Options →nosniff
X-Frame-Options →SAMEORIGIN
X-Request-Id →bbc8662d-644f-4819-a074-9efc7dce2dc3
X-Runtime →0.069372
X-XSS-Protection →1; mode=block
```

**Comment by godinezb** [comment]
I'm having a similiar issue, whenever I try:

`curl -XPOST 'http://localhost:3000/api/v1/auth/sign_in' -d '{"email":"example@mail.mx","password":"mipassword"}' -H "Content-Type: application/json"`

I get this:

`{"data":{"id":1,"email":"example@mail.mx","provider":"email","uid":"example@mail.mx"}}%
`

I think it is supposed to return the token, any suggestions on what I might overlooked?

**Comment by BrahimDa** [comment]
any help here??

**Comment by biomancer** [comment]
I faced the same issue, I believe this regression is from this commit - https://github.com/lynndylanhurley/devise_token_auth/commit/afc9f6bc2f30c3ac738298af765f8f3bb604a591#diff-787ec1bd1e5a87dca1d85fa6f8b2f7b3R79

`return if @resource.reload.tokens[@client_id].nil?` prevents headers to be set if user has no tokens

**Comment by biomancer** [comment]
And I've found that this is has broken after I added 'active_model_serializers' gem to gemfile

**Comment by biomancer** [comment]
I do not need that scope, so in my case adding
`serialization_scope nil` to ApplicationController fixed the issue.

**Comment by BrahimDa** [comment]
thank you so match, your solution worked perfectly.
