### ISSUE TITLE
Live Demo on heroku crashes

### ISSUE THREAD

**Issue by nkanellopoulos** [lynndylanhurley/devise_token_auth#687]
The demo app on heroku does not currently work.
Perhaps a db cleanup is needed?

`PG::InsufficientPrivilege: ERROR: permission denied for relation users : INSERT INTO "users"`

![screen shot 2016-07-28 at 16 47 38](https://cloud.githubusercontent.com/assets/1705451/17214766/22d2b800-54e3-11e6-98d8-1114e1b9eb7a.png)

**Comment by zachfeldman** [comment]
Seems to be an old demo, closing for now.
