### ISSUE TITLE
Sign Up Permitted Parameters gets Passed but Never saves succesfully to Database

### ISSUE THREAD

**Issue by neilhanekom** [lynndylanhurley/devise_token_auth#688]
I am adding Nickname, Name and a Role field to the new user registration Parameter. This new added Parameters I passed show up in my Rails console. As seen below the SQL Insert State shows the following. 

SQL (23.3ms)  INSERT INTO "users" ("name", "nickname", "email", "encrypted_password", "role_id", "tokens", "uid", "created_at", "updated_at", "confirmation_token", "confirmation_sent_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"  [["name", "Neil Hanekom"], ["nickname", "Neil"], ["email", "neilhanekom1@gmail.com"], ["encrypted_password", "$2a$10$z/Jpz8shRfXa9E46O70uk.F6NLNVXcqmSKLkFs6i/e1w39soYOwKS"], ["role_id", 1], ["tokens", "{}"], ["uid", "neilhanekom1@gmail.com"], ["created_at", "2016-07-28 15:31:45.666805"], ["updated_at", "2016-07-28 15:31:45.666805"], ["confirmation_token", "JJzkE_2B6yWPrNhg43HC"], ["confirmation_sent_at", "2016-07-28 15:31:45.667027"]]

However the new Parameters never gets saved. Why would this happen??

**Comment by ziazek** [comment]
Having the same issue here

**Comment by ziazek** [comment]
This worked for me:

In base_controller.rb:

```
# ...
include DeviseTokenAuth::Concerns::SetUserByToken
prepend_before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  ## duplicate the line
  # devise_parameter_sanitizer.for(:sign_up) << :nickname
  # devise_parameter_sanitizer.for(:sign_up) << :role
end
# ...
```

**Comment by zachfeldman** [comment]
Workaround posted, closing for now.
