### ISSUE TITLE
using devise_token_auth for API alongside standard devise gem for HTML view

### ISSUE THREAD

**Issue by knagode** [lynndylanhurley/devise_token_auth#689]
I have a project which uses devise for authentication. Now we need an API. I am trying to use devise_token_auth for my API and standard devise for everything else. 

First of all. Is this a good or bad idea?

I see that if I register user on html pages (which use devise) and then try to login with same credential on API (devise_token_auth) I receive:

` {"errors":["Invalid login credentials. Please try again."]}`

routes.rb
```
namespace :api, defaults: {format: :json}  do
  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
  end
end

devise_for :users

```

**Comment by knagode** [comment]
I noticed that the problem was since I was wrapping email & password inside user block (this is how device works).

**Comment by Jefferson210** [comment]
Hi @knagode , could you please help me as you have the configuration of the drivers, routes and models.
I've been trying for days to work together but I have not been able to achieve it
