### ISSUE TITLE
How to properly set headers in order to use current_user, authenticate_user! etc methods?

### ISSUE THREAD

**Issue by knagode** [lynndylanhurley/devise_token_auth#690]
I am trying to write a simple test for a URL which should be visible only to logged in user (I use `before_action :authenticate_user!` to achieve this). 

Even though I (think) that I properly assign all the headers I always get JSON response `{"errors":["Authorized users only."]}`

My test looks like this (Login (to get header info) then visit protected URL with all the headers needed)

```
  post "/api/v1/auth/sign_in", {:email => user.email, password: 'password'}

  header_hash = {
      'access-token'  => response.headers['access-token'],
      'uid'           => response.headers['uid'],
      'client'        => response.headers['client'],
      'expiry'        => response.headers['expiry']
  }

  get "/api/v1/subscription_status", nil , header_hash
```

What am I doing wrong?

**Comment by ShaunSpringer** [comment]
👍  I have the same issue (been battling with it for 2 days now).

I am trying to do two things, one as described above (hit the sign_in route and pull the token from there) and two:


    # Logs a user in and gets the auth tokens
    def auth_request(user)
      sign_in user

      @auth_headers = user.create_new_auth_token
    end

There is literally zero information on how to test this Gem and that's a shame because it's got great documentation otherwise. Any help would be appreciated.

**Comment by Charlie-Hua** [comment]
@knagode did you confirm that ` get "/api/v1/subscription_status", nil , header_hash` is setting the header correctly?
you can print the following in Rails to check:
```
request.headers.env["HTTP_TOKEN_TYPE"]
request.headers.env["HTTP_UID"]
request.headers.env["HTTP_ACCESS_TOKEN"]
request.headers.env["HTTP_CLIENT"]
request.headers.env["HTTP_EXPIRY"]
```

**Comment by zachfeldman** [comment]
Hi there @knagode    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
