### ISSUE TITLE
define_helpers not called at rails launch

### ISSUE THREAD

**Issue by andreassh** [lynndylanhurley/devise_token_auth#708]
Hi there,

I've run into an issue with the gem that effectively means, that authenticated users always gets a 401 when i launch the rails app for the first time.
As soon as i make a change in my code (any change), the authentication works flawlessly. 
More specifically, I noticed that the define_helpers method under DeviseTokenAuth::Controllers::Helpers aren't being called until I make some change in my code.
If i define the helper methods on my ApplicationController, the code runs perfectly when i launch my app, without making any change in the code. Hence it's seem like the helpers aren't being declared at app launch.
Any ideas on why this could be? 

Thanks,
Andreas

**Comment by zachfeldman** [comment]
Hi there @andreassh    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
