### ISSUE TITLE
Unable to reconfirm a users email

### ISSUE THREAD

**Issue by Petecass** [lynndylanhurley/devise_token_auth#716]
Hey I'm using devise_token_auth (0.1.38) along with the Devise confirmable module. 

Everything is working fine but I am unable to reconfirm a users email address if they change it. 

After looking through the source code, this is coming from some Rails method overides in `app/models/devise_token_auth/concerns/user.rb`:

```
def email_changed?
    false
end
```

This means that the before update method `:postpone_email_change_until_confirmation_and_regenerate_confirmation_token` in Devise's confirmable module is never run and the users email address is updated without reconfirmation.

What is this overide for? Any suggestions how to overcome this and reimplement Devise's initial implementation would be great.

Thanks

**Comment by CJBrew** [comment]
@Petecass please see this:
https://github.com/plataformatec/devise/issues/2688

I *may* have worked around the issue by putting the devise_token_auth include directive *above* the devise module directives:

Thus:
``` ruby
class User < ActiveRecord::Base
  include DeviseTokenAuth::Concerns::User

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end
```

**Comment by develop-test1** [comment]
Same here. Additionally even though account_update sanitizer is null, users are able to update their e-mail. How is it even possible by default, and how to disable e-mail updates?

**Comment by matthewnatali** [comment]
I'm also having this issue and unsure how to get passed in.  Any resolution?

**Comment by zachfeldman** [comment]
Hi there @Petecass @matthewnatali    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
