### ISSUE TITLE
401 on sign_in

### ISSUE THREAD

**Issue by tomascharad** [lynndylanhurley/devise_token_auth#717]
Hi,

If i activate the user authentication on the application controller:

``` ruby
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_action :authenticate_api_v1_user!
end
```

Then I cannot log in.

``` bash
Tomass-MBP-2:apple-traceability tomascharad$ curl -XPOST -H 'Content-Type: application/json' http://localhost:3000/api/v1/auth/sign_in -d '{"email": "tomas.charad@gmail.com", "password": "tomascharad87" }'
{"errors":["Authorized users only."]}Tomass-MBP-2:apple-traceability tomascharad$ 
```

 if I take out the autheticate_api_v1_user, then I can.

``` bash
Tomass-MBP-2:apple-traceability tomascharad$ curl -XPOST -H 'Content-Type: application/json' http://localhost:3000/api/v1/auth/sign_in -d '{"email": "tomas.charad@gmail.com", "password": "tomascharad87" }'
{"data":{"id":1,"email":"tomas.charad@gmail.com","provider":"email","company_id":1,"uid":"tomas.charad@gmail.com","name":"Tomás Charad","nickname":null,"image":null}}Tomass-MBP-2:apple-traceability tomascharad$ 
```

**Comment by Sciandra-Leva** [comment]
Well that's expected, right?

I mean, by writing `before_action :authenticate_api_v1_user!` in your ApplicationController you are saying that every method called will require an authenticated user to call it (meaning, you have to provide the auth [headers](https://github.com/lynndylanhurley/devise_token_auth#token-header-format)  for every call).

That said, you should use `before_action :authenticate_api_v1_user!` in all those Controllers which will have authenticated method (ex. a user ability to change its favorite car).

**Comment by tomascharad** [comment]
@Sciandra-Leva ,

I think that the sign_in controller should override that behaviour by default.
I think that devise does the same, so I thought it was kind of standard.

**Comment by Sciandra-Leva** [comment]
I see your point, but I'm not entirely sure about it, given the behaviour you describe in your first post.

That said, you could try to add a filter at that before_action like `, :only => [:destroy]` and see how it goes. I tried glancing over the source code for session and application controller but I can't see evidences of your statement about that overriding.

**Comment by tomascharad** [comment]
I'm not sure that I totally understood your proposal @Sciandra-Leva.

Restrictions of `:only => []` can only be specified at controller level. Here I'm specifying it at application controller, so I don't have the chance of doing that.

I don't know if I explained myself correctly, but the only behaviour that I'm looking for is to be able to sign_in without being authenticated (without cookies/headers) while declaring an overall restriction on my application controller.

I also have `skip_before_actions` at controller level specifying `only`, in those cases I'm able to get a response without being authenticated.

**Comment by tomascharad** [comment]
Oh, and obviously I cannot add a skip_before_actions on the gem. So what I have done so far to override the default behaviour as a patch is by doing this on config/application.rb:

```ruby
# TCT: Skipping devise_auth_token session controller
config.to_prepare do
  DeviseTokenAuth::ApplicationController.skip_before_action :authenticate_api_v1_user!
end
```

**Comment by jarijokinen** [comment]
Devise skips the :authenticate_user! filter by default for sign in actions, and I think this should be default behaviour in devise_token_auth too.  There is no point to try authenticate the user before sign_in action can be used.

**Comment by tomascharad** [comment]
Exactly @jarijokinen.

**Comment by roseliux** [comment]
Agree with @jarijokinen

**Comment by zachfeldman** [comment]
Hi there @tomascharad , @roseliux   ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
