### ISSUE TITLE
Remove dependency on ActiveRecord

### ISSUE THREAD

**Issue by ianks** [lynndylanhurley/devise_token_auth#72]
As of now, there is a baked in depedency on ActiveRecord. Users not wishing to use ActiveRecord and instead wishing to use another db (MongoDB, Neo4j, etc.) are unsupported. There are a few places where this happens, and I would be happy to refactor the code to fix this if it something the community deems useful. I am already doing it for my app, so it would not be too much work.

Here are some places where the dependency exists:

  1. https://github.com/lynndylanhurley/devise_token_auth/blob/master/config/initializers/devise.rb#L22

  2. https://github.com/lynndylanhurley/devise_token_auth/blob/0e39e9ea6b77421b46e4e605488701c2a2c8afa0/app/controllers/devise_token_auth/sessions_controller.rb#L16

  3. https://github.com/lynndylanhurley/devise_token_auth/blob/0e39e9ea6b77421b46e4e605488701c2a2c8afa0/app/controllers/devise_token_auth/passwords_controller.rb#L32

**Comment by tritonresearch** [comment]
+1

**Comment by booleanbetrayal** [comment]
I don't realistically see this happening at this point. Going to close this issue, but feel free to contribute any PRs to the contrary.
