### ISSUE TITLE
Separate Devise Token Auth configuration per model

### ISSUE THREAD

**Issue by navkar** [lynndylanhurley/devise_token_auth#725]
Hello guys,

I have defined devise_token_auth in the following way

```
  mount_devise_token_auth_for 'Expert', at: 'expert', skip: [:invitations], :controllers => {sessions: 'api/v1/experts/sessions', registrations: 'api/v1/experts/registrations'}

 mount_devise_token_auth_for 'Customer', at: 'customer', :controllers => {sessions: 'api/v1/customers/sessions', registrations: 'api/v1/customers/registrations', token_validations: 'api/v1/customers/token_validations'}
```

There are two separate instances of mount_devise_token_auth_for, but they use the same **_config/initializers/devise_token_auth.rb_** file. 

I need to configure 

`config.max_number_of_devices = 1 # for expert
`
and

`config.max_number_of_devices = 10 --- for customer`

Is it possible to do it?

thank you.

**Comment by zachfeldman** [comment]
Hi there @navkar    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
