### ISSUE TITLE
Cannot integrate with omniauth-facebook 

### ISSUE THREAD

**Issue by emman27** [lynndylanhurley/devise_token_auth#729]
Hi, 

I'm having trouble integrating with omniauth-facebook. 

I've managed to set both up correctly - I can create users using omniauth-facebook, I can also create users via POST /auth. Signing in users through POST /auth/sign_in is fine too. However, for Facebook users, I'm unable to retrieve the tokens I need to continue their verification. The headers from the call to /auth/facebook/callback don't contain any token / client info I can use for my next request

**Comment by emman27** [comment]
Solved using manually created headers!

**Comment by waritsan** [comment]
@emman27 Could you please show me an example how you manually created the headers? I have the same issue but can't seem to figure it out.

**Comment by emman27** [comment]
In your controller which catches the request, add this line
`response.headers.merge! @user.create_new_auth_token`
