### ISSUE TITLE
Usage with Grape

### ISSUE THREAD

**Issue by cp** [lynndylanhurley/devise_token_auth#73]
Does anyone have experience using this and ng-token-auth with Grape? I'm looking to access the helpers such as `current_user` in my Grape endpoints.

**Comment by raviada** [comment]
I also have the same setup as you are. I am wondering where in the grape you have ```before``` and ```after``` blocks defined?

I know you mentioned ```/lib/api.rb``` but I don't have that file.

**Comment by rajaaa92** [comment]
My `app/api/api.rb`:

```ruby
class API < Grape::API
  format :json
  formatter :json, Grape::Formatter::ActiveModelSerializers
  logger Rails.logger

  mount ::V1::Base
end
```


My `app/api/v1/base.rb`:

```ruby
require 'authenticated_request'

module V1
  class Base < Grape::API

    version 'v1', using: :path

    before do
      next if @resource
      @req = ::AuthenticatedRequest.new(
        uid:      request.headers['Uid'],
        token:    request.headers['Access-Token'],
        client:   request.headers['Client'],
        resource: @resource
      )
      @resource = @req.begin
      if @resource
        env['warden'].set_user(@resource, scope: :user)
      else
        h = {'Access-Control-Allow-Origin' => "*", 'Access-Control-Request-Method' => %w{GET POST OPTIONS}.join(",")}
        error!('You need to log in to use the app.', 401, h)
      end
    end

    mount V1::Something

    after do
      headers = @req.finish
      next if headers.nil?
      env['warden'].authenticate(scope: :user)

      headers.each{|k,v| header(k,v)}
      header 'Access-Control-Allow-Origin', "*"
      header 'Access-Control-Request-Method', %w{GET POST OPTIONS}.join(",")
    end
  end
end
```

The code from `authenticated_request` is pasted into `app/lib/authenticated_request.rb`

I hope that helps!

**Comment by lynndylanhurley** [comment]
Thanks @rajaaa92!! When I get a chance, I'll add a Grape case to the test suite.

I don't have much Grape experience - let me know if there's anything this gem can do to provide better support for Grape.

**Comment by ColbyAley** [comment]
this is so great, thanks for sharing @rajaaa92!

**Comment by shicholas** [comment]
:+1:, it would be nice to use this w/ grape.

**Comment by mcordell** [comment]
Hi everybody,

I created a gem that allows grape to authenticate using an existing devise_token_auth installation and rails app. Its called [grape_devise_token_auth](https://github.com/mcordell/grape_devise_token_auth) and you can also find an example setup of jToker + devise + devise_token_auth + grape_devise_token_auth [here](https://github.com/mcordell/rails_grape_auth).

**Comment by mcordell** [comment]
Hi again,

So I've created a full port of devise_token_auth for grape. It can be found here at [grape_token_auth](https://github.com/mcordell/grape_token_auth). This is different from the above gem in that it is purely dependent on grape and does not depend on rails, devise, or devise_token_auth.

I'm approaching an initial 0.1.0 release and I'd love it if @lynndylanhurley or @booleanbetrayal could give it a review and tell me what they think.

Cheers!

**Comment by lynndylanhurley** [comment]
Fantastic work @mcordell! I'll make a note in the README that directs grape users to your project.

**Comment by booleanbetrayal** [comment]
:+1:
