### ISSUE TITLE
Error in password reset. Password not changed, even though edit returns 200

### ISSUE THREAD

**Issue by andreassh** [lynndylanhurley/devise_token_auth#732]
Looks to me like there is something wrong with the password reset flow.

In my application, the user is getting an email with the password_reset_token and is able to update password on edit method on the password_controller. The request, returns 200. 
I looked at the lib code and the following:

```
    def edit
      @resource = resource_class.reset_password_by_token({
        reset_password_token: resource_params[:reset_password_token]
      })
      ....
```

Seems to me like it should be:

```
        def edit
          @resource = resource_class.reset_password_by_token(resource_params) #passing both password and password_confirmation
```

Otherwise, the password attribute is never set on the user object as only reset_password_token is passed to reset_password_by_token?

**Comment by zachfeldman** [comment]
Hi there @andreassh    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
