### ISSUE TITLE
E-mail update is enabled by default

### ISSUE THREAD

**Issue by develop-test1** [lynndylanhurley/devise_token_auth#736]
Users are able to update their e-mail even though devise_parameter_sanitizer for account_update is not defined. Is it proper behavior that e-mail update is enabled by default? If so how to disable it?

**Comment by zachfeldman** [comment]
Hi there @develop-test1    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
