### ISSUE TITLE
Best practice for using virtual attributes

### ISSUE THREAD

**Issue by wstrinz** [lynndylanhurley/devise_token_auth#738]
I'm working on adding an api layer an app that implements login via username or email. We're basically following the pattern specified in the [devise docs](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address), but I'm having trouble getting the api auth and regular auth to work side by side.

Using `[:login]` for devise's `authentication_keys` (which is required to sign in with email/username in the main application) causes [session_controller.rb:29](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L29) to generate a `WHERE` query searching based on `login`, which isn't actually present in the database.

We've found a workaround by using `@resource = resource_class.find_for_database_authentication(field => q_value)` instead of `resource_class.where`, which doesn't seem like a very flexible solution 😄 

I'd be happy to put in a PR if there's some some preferred way of handling this that isn't implemented. Maybe branching based on whether or not `field` is a database column or just an attr on the model?

**Comment by danielneis** [comment]
Hello,

it seems that the plugin does not handle multiple authentication_keys correctly.
I need to a second field other than email and had to make some changes.
It may be of your interest:
https://github.com/lynndylanhurley/devise_token_auth/pull/949

**Comment by zachfeldman** [comment]
Workaround posted, closing for now.
