### ISSUE TITLE
Multiple user registration with multiple providers

### ISSUE THREAD

**Issue by wazery** [lynndylanhurley/devise_token_auth#740]
I use Devise Token Auth gem, and ng-token-auth. When signing up a new user with regular signup, then try to login with an OmniAuth provider such as GitHub, I get an exception:

`ActiveRecord::RecordInvalid (Validation failed: Email has already been taken):`

That's because DeviseTokenAuth tries to create a new user instead of updating the current one. I have no idea how to configure DeviseTokenAuth to just update the existing user.

**Comment by mkhatib** [comment]
FWIW I use the following strategy, this might not be totally accurate and not the expected behavior but I find it very useful.

* Catch `RecordNotUnique` in `OmniauthCallbacksController`
* Login the user manually with the authenticated email


```ruby
class Api::V1::OmniauthCallbacksController < DeviseTokenAuth::OmniauthCallbacksController
  rescue_from ActiveRecord::RecordNotUnique, with: :user_exists_with_other_providers

  # RecordNotUnique is thrown when the email has already been used with another
  # provider, sign that user in since we know the user own the email through
  # their provider.
  def user_exists_with_other_providers
    @resource = User.find_by_email(@resource.email)

    create_token_info
    set_token_on_resource
    create_auth_params

    if resource_class.devise_modules.include?(:confirmable)
      @resource.skip_confirmation!
    end

    if @resource.avatar_uid.nil?
      @resource.avatar_url = get_large_image(auth_hash['info']['image'])
    end
    if @resource.nickname.nil?
      @resource.nickname = auth_hash['info']['nickname']
    end

    sign_in(:user, @resource, store: false, bypass: false)
    @resource.save!

    yield @resource if block_given?

    render_data_or_redirect('deliverCredentials', @auth_params.as_json, @resource.as_json)
  end
end
```

**Comment by zachfeldman** [comment]
Workaround posted, so closing for now. I do agree though that a more official way to login through multiple providers would be nice!

**Comment by FlandersBurger** [comment]
Just wanted to mention that for the workaround to work (catching RecordNotUnique), you'll need a unique index on the email column
