### ISSUE TITLE
Rails 5 API deployed as microservices

### ISSUE THREAD

**Issue by raviada** [lynndylanhurley/devise_token_auth#741]
Has anybody done this before with this gem? We are planning to divide our rails API into microservices and deploy them using docker-compose. How does devise_token_auth works in this case? For example I have auth_service, service1, service2 etc.. deployed, clients will get authenticated with auth_service, and calling different services with the same token. Assuming all services are connecting to the same database, can I use devise_auth_token in all other services to authenticate the token?
I want to expose all the methods available with devise_auth_token only in our auth service, and sign_in only in other services. Is it possible?

**Comment by seanmavley** [comment]
Is this an issue or a question? If question, you are better sticking with StackOverflow or somewhere else.

**Comment by raviada** [comment]
It is a question. I am closing this since I haven't heard from anybody.
