### ISSUE TITLE
minor error in README with regard to usage alongside Devise

### ISSUE THREAD

**Issue by edwardmp** [lynndylanhurley/devise_token_auth#745]
Hi,

I noticed the README gives the following snippet of code (https://github.com/lynndylanhurley/devise_token_auth#configinitializersdevise_token_authrb):

```
DeviseTokenAuth.setup do |config|
  # config.enable_standard_devise_support = false
end
```

This does not make sense to me. Shouldn't this be:

```
DeviseTokenAuth.setup do |config|
    config.enable_standard_devise_support = true
end
```

If this is a really a mistake I'll create a pull request but I'm not sure at this point yet.

**Comment by gbrl** [comment]
I was just about to post about this. It seems the instructions imply you should set that value to true, but the example code has that line commented out. I was confused as well.

**Comment by gbrl** [comment]
Also, when I follow the instructions, I get a conflicting routes error:

```
ArgumentError: Invalid route name, already in use: 'new_user_session'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

**Comment by gbrl** [comment]
I don't know if this really solves the issue, but to avoid having duplicated route names, I was able to solve it by configuring my routes.rb like this:

```
  resources :devise do
    devise_for :users
  end
```

This way you get "new_user_devise_session" for devise, and "new_user_session" for devise_token_auth

**Comment by KjellMorgenstern** [comment]
Replace
 `scope '/api' do`
with
 `namespace :api do`
as in the documentation. This also resolves the routing conflict.

**Comment by edwardmp** [comment]
@KjellMorgenstern @gbrl 
Yup, that's what I did eventually

**Comment by KaraAJC** [comment]
So, to clarify, the config file SHOULD or SHOULD NOT be changed to:

```
DeviseTokenAuth.setup do |config|
    config.enable_standard_devise_support = true
end
```

**Comment by zachfeldman** [comment]
@lynndylanhurley this seems like a fairly simple one to close if we have your blessing for the above fix to the README? I can update it if so.
