### ISSUE TITLE
resource name for scoped mounting

### ISSUE THREAD

**Issue by abonec** [lynndylanhurley/devise_token_auth#748]
I have this setup:

```
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Actor', at: 'auth'
    end
  end
```

And devise give me helpers like `current_api_v1_actor` but I want it to be like `current_actor`. It is possible without aliasing in the controller? How I can reach that?

**Comment by andoq** [comment]
this is the same issue as #219

**Comment by zachfeldman** [comment]
Hi there @abonec ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
