### ISSUE TITLE
ArgumentError in Devise::RegistrationsController#new

### ISSUE THREAD

**Issue by KjellMorgenstern** [lynndylanhurley/devise_token_auth#750]
I am trying use standard devise alongside devise_token_auth.
devise 4.2.0
devise_token_auth 0.1.39
ActiveAdmin gem is not installed.

When I open http://localhost:3000/users/sign_up, I get 

```
wrong number of arguments (given 1, expected 0)

Extracted source (around line #284):
            
282 Rails.application.config.to_prepare do
283  Devise::SessionsController.layout "_minimal"
284  Devise::RegistrationsController.layout proc{ |controller| user_signed_in? ? "application" : "_minimal" }
285  Devise::ConfirmationsController.layout "_minimal"
286  Devise::UnlocksController.layout "_minimal"
287  Devise::PasswordsController.layout "_minimal"
```

When I call `user_signed_in?` at the console I get
```
>> user_signed_in?
ArgumentError: wrong number of arguments (given 1, expected 0)
	from /Users/kjell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.2.0/app/controllers/devise_controller.rb:47:in `resource_class'
	from /Users/kjell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise_token_auth-0.1.39/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:21:in `set_user_by_token'
	from /Users/kjell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise_token_auth-0.1.39/lib/devise_token_auth/controllers/helpers.rb:123:in `current_user'
	from /Users/kjell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise_token_auth-0.1.39/lib/devise_token_auth/controllers/helpers.rb:119:in `user_signed_in?'
	from my_project/config/initializers/devise.rb:284:in `block (3 levels) in <top (required)>'
```

The method resource_class from devise_controller.rb:47 does not accept parameters. But resource_class from `0.1.39/app/controllers/devise_token_auth/application_controller.rb` would match the call. 
So, somehow this is mixed up.

**Comment by duard** [comment]
try to remove         <% if user_signed_in? %> in your view

**Comment by duard** [comment]
I'm with this same error in my application view 

`        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>`

**Comment by KjellMorgenstern** [comment]
The code causing the error (line 284) is from config/initializers/devise.rb.
My devise.rb init was modified by a 3rd party gem, so this exact case is not a problem with devise_token_auth or devise.

**Comment by wktq** [comment]
Same here.
Is it an error caused of new version? because it appeared on the agenda recently.
Anyone can help?
