### ISSUE TITLE
undefined method `tokens' upon signing up

### ISSUE THREAD

**Issue by deepushajia** [lynndylanhurley/devise_token_auth#752]
![screenshot from 2016-10-25 15 19 07](https://cloud.githubusercontent.com/assets/12277348/19681363/bebf2540-9ac6-11e6-9a42-ad95a8e1be45.png)
It seems devise and devise_token_auth aren't working alongside. This is an application that has both rails views and json apis . devise_token_auth concern is put under a separate application controller for apis. Help?

**Comment by zachfeldman** [comment]
Hi there @deepushajia    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
