### ISSUE TITLE
API authentication: Use POST /sign_in to sign in. GET is not supported.

### ISSUE THREAD

**Issue by hsadhamh** [lynndylanhurley/devise_token_auth#754]
Hi, 
I tried implementing for API authentication. I am able to sign_in without any hassle, 
When I call custom controller, I see below error.
**{
  "errors": [
    "Use POST /sign_in to sign in. GET is not supported."
  ]
}**

In console, I see 

Started GET "**/v1/names**" for 127.0.0.1 at 2016-10-29 21:46:57 +0530
Processing by Api::V1::NamesController#index as _/_
**Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms)**

Started GET "/auth/sign_in" for 127.0.0.1 at 2016-10-29 21:46:57 +0530
Processing by DeviseTokenAuth::SessionsController#new as _/_
  User Load (1.0ms)  SELECT  `users`.\* FROM `users` WHERE `users`.`uid` = 'admin@factor.in' LIMIT 1
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.0ms)
**Completed 405 Method Not Allowed in 124ms (Views: 122.5ms | ActiveRecord: 1.0ms)**

Can you please help me out here?

**Comment by stephencarr** [comment]
Makes sense that you cannot sign in with a GET request.

The `/auth/sign_in` endpoint should only accept a form POST with the user credentials. Make sure your front end application is POSTing the form data to this endpoint.

**Comment by seza443** [comment]
I'm having the same issue.

Here is the scenario that I'm trying:

1. POST /auth => works fine, I retrieve the headers 
    - access-token
    - uid
    - client
    - expiry
    - token-type
2. GET /symptoms that is protected with ` before_action :authenticate_user!`
    The headers are correctly set with previous values.
    And here is the error in the rails console: 

```
Started GET "/symptoms" for ::1 at 2017-02-08 15:44:04 +0100
Processing by SymptomsController#index as */*
  Parameters: {"symptom"=>{}}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)


Started GET "/auth/sign_in" for ::1 at 2017-02-08 15:44:04 +0100
Processing by DeviseTokenAuth::SessionsController#new as */*
  Parameters: {"session"=>{}}
Completed 405 Method Not Allowed in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

**Comment by seza443** [comment]
Fixed it. I forgot to add `include DeviseTokenAuth::Concerns::SetUserByToken` in my controller

**Comment by zachfeldman** [comment]
What @stephencarr said

**Comment by sparshsamir1993** [comment]
``` Started GET "/omniauth/facebook" for ::1 at 2018-02-16 16:17:42 +0530
I, [2018-02-16T16:17:42.895902 #12664]  INFO -- omniauth: (facebook) Request phase initiated.


Started GET "/omniauth/facebook/callback?code=AQDrfYURb9ZK7f96n0NfW5dxkcNsc9AoDBnKauPGe44c6gNQ3-XeGvJrRl2ASL5X3rtjPYKRSXY0stzFHZOqMm4oLFDMaWRc_1AYLjWaaK3EFPBn8pTpjYpVvkdJViE-Ci5QGYH4pIy1PoRsQ7zDg_225FlHCOq37elc3ybsVwqKbgmEQEBrXpwy59-toFdYyuWDVa0-BXQyMxgSnVrurvJeOw5X5odC867mm8Z8ms1mUCJrwB3msjFHtWcsC9aZr2IWNJ8N0BLDqaXwUZ4uR5eJ6_lcE_Z5cmNei-Wld-NGz8bawLZ_QSQkZ46nXgKYIqk" for ::1 at 2018-02-16 16:17:43+0530
I, [2018-02-16T16:17:43.748936 #12664]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2018-02-16T16:17:44.083502 #12664] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, :
{"access_token":"EAAN5AP9sA8MBAFModa5KNzblkabjP7WbfmX2QPfLZCpAN5WzZA0p76urMGPYvxFCDwyeeX7Yyn2mzCUR9BzdYhNWpWb0SuG1xr85Knhy7KtyZAwd8TsZAXZBeXLZCvRicIs1vFbrVpIH3FboE7czqjLjjtyW8kMR4ZD","token_type":"bearer","expires_in":5183762}
Processing by Devise::OmniauthCallbacksController#failure as HTML
  Parameters: {"code"=>"AQDrfYURb9ZK7f96n0NfW5dxkcNsc9AoDBnKauPGe44c6gNQ3-XeGvJrRl2ASL5X3rtjPYKRSXY0stzFHZOqMm4oLFDMaWRc_1AYLjWaaK3EFPBn8pTpjYpVvkdJViE-Ci5QGYH4pIy1PoRsQ7zDg_225FlHCOq37elc3ybsVwqKbgmEQEBrXpwy59-toFdYyuWDVa0-BXQyMxgSnVrurvJeOw5X5odC867mm8Z8ms1mUCJrwB3msjFHtWcsC9aZr2IWNJ8N0BLDqaXwUZ4uR5eJ6_lcE_Z5cmNei-Wld-NGz8bawLZ_QSQkZ46nXgKYIqk"}
Redirected to http://localhost:3000/api/v1/auth/sign_in
Completed 302 Found in 1ms (ActiveRecord: 0.0ms)


Started GET "/api/v1/auth/sign_in" for ::1 at 2018-02-16 16:17:44 +0530
Processing by DeviseTokenAuth::SessionsController#new as HTML
Completed 405 Method Not Allowed in 8ms (Views: 7.2ms | ActiveRecord: 0.0ms)
````
