### ISSUE TITLE
Use issue for "real" issue with the gem, and stackoverflow for integration problem

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#756]
What do you thing ?

**Comment by zachfeldman** [comment]
@nicolas-besnard I think that's a pretty good idea. @lynndylanhurley what do you think?

**Comment by MaicolBen** [comment]
@zachfeldman With what is explained in https://github.com/lynndylanhurley/devise_token_auth#need-help is enough?
