### ISSUE TITLE
Passing block to for strong parameters breaks code

### ISSUE THREAD

**Issue by erikflood** [lynndylanhurley/devise_token_auth#758]
If I pass anything but scalar values as strong parameters, but instead passes a block, it will break the devise_token_auth gem:

```
devise_parameter_sanitizer.permit(:sign_in) do |user_params|
    user_params.permit(:username, :email)
  end
```

will result in the following error

```
NoMethodError (undefined method 'each' for #<Proc:0x007fd1f03b7f08>):

devise_token_auth (0.1.39) app/controllers/devise_token_auth/application_controller.rb:20:in 'params_for_resource'
devise_token_auth (0.1.39) app/controllers/devise_token_auth/registrations_controller.rb:101:in 'sign_up_params'
devise_token_auth (0.1.39) app/controllers/devise_token_auth/registrations_controller.rb:199:in 'validate_sign_up_params'
```

**Comment by mzane42** [comment]
Hi @erikflood, did you find solution ?

**Comment by dlanileonardo** [comment]
:up:

**Comment by fabianprado** [comment]
Hi, anyone have a workaround to this? I need to receive nested attributes and this should be the way

**Comment by stratigos** [comment]
Yes as @fabianprado was pointing out - the current workaround is to not pass in a block to `devise_parameter_sanitizer`, but declare all white listed params in the `:keys` hash of second argument, i.e.,:

```ruby
def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
```

**Comment by zachfeldman** [comment]
Workaround posted, closing for now
