### ISSUE TITLE
devise_token_auth with LDAP?

### ISSUE THREAD

**Issue by schretzi** [lynndylanhurley/devise_token_auth#759]
I have an existing App with LDAP backend for my users and wanted to integrate devise_token_auth with it for a new Angular2 Frontend. But I'm not sure if that is possbile, you only mention Oauth and Database as backends? Would that mean I get a new Provider LDAP in the model? Any hints for this?

**Comment by mrancys** [comment]
up looking for same feature.

**Comment by ruanpetterson** [comment]
OmniAuth supports LDAP as a provider until I know. You can see it in [list of OAuth2 providers](https://github.com/omniauth/omniauth/wiki/List-of-Strategies).

**Comment by zachfeldman** [comment]
Possible solution posted, closing for now
