### ISSUE TITLE
NoMethodError at /omniauth/facebook/callback - undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by kspe** [lynndylanhurley/devise_token_auth#76]
Hi,

I've updated to:

```
devise_token_auth 0.1.30
ng-token-auth 0.0.24
```

and now after redirect to `/auth/facebook/callback` I get:
`NoMethodError at /omniauth/facebook/callback undefined method`[]' for nil:NilClass`

in 

`omniauth_success devise_token_auth (0.1.30) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:24`

```
def omniauth_success
      # find or create user by provider and provider uid
      @resource = resource_class.where({
        uid:      auth_hash['uid'],
        provider: auth_hash['provider']
      }).first_or_initialize
```

when trying to access auth_hash.

I've tried to clean all browser cache/cookies, removed user from DB in order to have clean installation.

**Comment by stefanahman** [comment]
@ignacykasperowicz how did you solve it? I'm stuck with the same problem.

**Comment by ignacykasperowicz** [comment]
@stefanahman Hmmm, I do not think I was looking at it after in more details, I decided to switch to Ember and used other library for authentication. The issue here was that in `devise_token_auth` the names of methods had changed I think and that is why I was getting `NoMethodError`. Sorry I cannot help you more with this.

**Comment by eugenio1590** [comment]
Hi @kspe , I got the same error using the following request:

````
GET /api/v1/auth/google_oauth2/callback.json?code=4/hNZXTWia27agrvVUGcbS_LwCIFq00BV0jP6GQ1ViQNM&amz;resource_class=User&amp;redirect_uri= HTTP / 1.1
Host: localhost: 8080
X-Requested-With: XMLHttpRequest
Cache-Control: no-cache
Postman-Token: 9b3760ff-996d-4454-8a77-220f98178ed6
````

The gem is mounted on the path /api/ v1/auth. Is there a parameter missing in the request?
