### ISSUE TITLE
Current user from channel.

### ISSUE THREAD

**Issue by mtoribio** [lynndylanhurley/devise_token_auth#760]
Hi,
How I can get current_user from channel?
I am using angularjs with ng-token-auth.

Thanks.

**Comment by merqlove** [comment]
Something like this:

```ruby
def find_verified_user
  ApplicationRecord.connection_pool.with_connection do |conn|
    headers = JSON.parse(cookies['auth_headers'] || '{}')
    uid       = headers['uid']
    token     = headers['access-token']
    client_id = headers['client']

    return nil unless token

    user = uid && User.find_by_uid(uid)

    if user && user.valid_token?(token, client_id)
      user
    end
  end
end
```

**Comment by brunowego** [comment]
Thanks @merqlove. I have similar issue but with multitenancy (apartment gem). Have a experience with this situation?

**Comment by merqlove** [comment]
@brunowego it's different question kind, but I think you can run  dta as shared service, and check tokens/session per tenant.

**Comment by zachfeldman** [comment]
Possible solutions posted (Thanks @merqlove ), closing for now.
