### ISSUE TITLE
QUESTION: `tokens` field in database

### ISSUE THREAD

**Issue by sarbull** [lynndylanhurley/devise_token_auth#763]
What happens with the `token` field in the users table in the database?
- After each login it gets bigger and bigger?
- It's deleted on expiration date?

Can you please explain?

**Comment by lovesmall** [comment]
Yes, seems it will grow up to the max number then delete the oldest. From the config file **devise_token_auth.rb** :

```
  # Sets the max number of concurrent devices per user, which is 10 by default.
  # After this limit is reached, the oldest tokens will be removed.
  # config.max_number_of_devices = 10
```

You can find how it exactly worked at devise_token_auth/app/models/devise_token_auth/concerns/user.rb

**Comment by zachfeldman** [comment]
Possible answer posted by @lovesmall , closing for now
