### ISSUE TITLE
Could not find generator 'devise_token_auth:install'

### ISSUE THREAD

**Issue by lukeipanda** [lynndylanhurley/devise_token_auth#768]
rails g devise_token_auth:install User auth
Running via Spring preloader in process 57673
Could not find generator 'devise_token_auth:install'. Maybe you meant 'rspec:install', 'integration_test' or 'test_unit:model'
Run rails generate --help for more options.

I'm having this problem now. Database pg. Adapter postgis.

Using rails 5.0.0.1
Using devise 4.2.0
Using devise_token_auth 0.1.39
Using omniauth 1.3.1

**Comment by lukeipanda** [comment]
This issue is resolved by restarting the computer. Closing.

**Comment by zachfeldman** [comment]
@lukeipanda the mystery of why this wasn't closed shall haunt me

**Comment by luispcosta** [comment]
This is currently happening with me:

```
Using rails 5.1.4
Using devise 4.3.0
Using devise_token_auth 0.1.42
```

```
rails g devise_token_auth:install User auth
Running via Spring preloader in process 4008
Could not find generator 'devise_token_auth:install'. Maybe you meant 'devise:install', 'responders:install' or 'devise:controllers'
Run `rails generate --help` for more options.
```

Can we re-open this?

**Comment by zachfeldman** [comment]
@luispcosta did you try restarting your computer?

**Comment by nearbycoder** [comment]
@luispcosta I was able to resolve this issue by stopping spring. 😄

**Comment by samnissen** [comment]
I was also able to do this by stopping and removing spring, which is a pretty high barrier to entry. Perhaps the README should include instructions explaining that you will have to remove spring or restart your computer as a prerequisite to proceeding past `bundle install`?

**Comment by zachfeldman** [comment]
@samnissen how about a patch that makes this lib play nice with spring :)? We'd also take a PR to the README if you have limited time!
