### ISSUE TITLE
Prevent user from sharing account

### ISSUE THREAD

**Issue by VladFarion** [lynndylanhurley/devise_token_auth#770]
Hello
Thanks for an awesome library, you have been deving and supporting!
I have a subsribption-based application, which uses devise_token_auth + ng-token-auth for authentication. I want to prevent my users from sharing same account on different computers or browsers (though I would like them to use multiple tabs of same browser). 
Is this possible with current version of library?
Thanks for you patience and work
Best regards,
Vlad

**Comment by zachfeldman** [comment]
Hi there @VladFarion    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
