### ISSUE TITLE
Explicitly do not invalidate token

### ISSUE THREAD

**Issue by tomascharad** [lynndylanhurley/devise_token_auth#772]
Hi,

I have an action that allows to upload files to S3.
When doing this, there are some cases that the user does not wait this query to be done and navigates to another page without receiving the new token. This causes the user to log out.

Is there any way in which I could tell devise_token_auth to not invalidate the token on these 'long' actions?

**Comment by zachfeldman** [comment]
Maybe offload this to a background job, and show the status using subsequent requests? Since ther hasn't been a lot of activity on this, closing for now.
