### ISSUE TITLE
multiple congratulation emails

### ISSUE THREAD

**Issue by arthurbryant** [lynndylanhurley/devise_token_auth#774]
I override ConfirmationsController to add congratulation email after the new user confirmed his/her email like this

```ruby
module Overrides
  class ConfirmationsController < DeviseTokenAuth::ConfirmationsController
    def show
      super do |u|
        if u.errors.empty?
          UserMailer.confirmation(@resource).deliver_now
        end
      end
    end
  end
end
``` 

The problem I found is that the congratulation email will be sent as many times as I click the link in confirm email. It should be only sent once. 

I dug a little bit and found that there is a bug in the source code. The code put the "Email was already confirmed, please try signing in" error in @resource but after that it saves @resource which makes the error message disappear!

The source code which I think has a bug is  as follow

```ruby
 @resource = resource_class.confirm_by_token(params[:confirmation_token])

      Rails.logger.debug "xxxxxxxx after confirm #{@resource.errors.full_messages}"
      if @resource and @resource.id
        # create client id
        client_id  = SecureRandom.urlsafe_base64(nil, false)
        token      = SecureRandom.urlsafe_base64(nil, false)
        token_hash = BCrypt::Password.create(token)
        expiry     = (Time.now + DeviseTokenAuth.token_lifespan).to_i

        @resource.tokens[client_id] = {
          token:  token_hash,
          expiry: expiry
        }

        @resource.save!
```

**Comment by zachfeldman** [comment]
Hi there @arthurbryant    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
