### ISSUE TITLE
LinkedIn SignIn

### ISSUE THREAD

**Issue by Kedarnag13** [lynndylanhurley/devise_token_auth#778]
I am trying to implement Login with LinkedIn. I am writing REST API in rails. And the login happens from the iOS side. I am not sure where to begin for this. I was able to and override sessions controller for  creating session directly. However, I am facing issue with LinkedIn login. I am not sure what should be the route, which controller to inherit. Any information would be helpful.

Thanks in advance.

**Comment by zachfeldman** [comment]
Old issue with no comments, going to close for now. @Kedarnag13 feel free to reopen if it's still a problem.
