### ISSUE TITLE
current_user returns nill

### ISSUE THREAD

**Issue by Valindo** [lynndylanhurley/devise_token_auth#779]
I am using rails 5.0.0.1 in API mode, along with angular 2 as the front end.
Okay, so my issue here is that I cannot authenticate the user in rails or retrieve the current_user using `current_user` and `authenticate_user!` helpers.

You can actually check it out on the examples provided using angular 2 token auth ( which I am using as well in my project).
I've checked this by making a dummy controller in the example and calling current_user which returns nil and `user_signed_in?` returns false( Note: I have signed in via the front end and it says signed in as well )

Am I missing something? Help, please.

**Comment by etagwerker** [comment]
@Valindo This seems like a duplicate of https://github.com/lynndylanhurley/devise_token_auth/issues/74

I used one of the workarounds described in that thread. I hope it works for you.

**Comment by kiritAyya** [comment]
Hi, I'm using the same configuration as @Valindo, and I've implemented the solution from issue #74 as @etagwerker has suggested here, but to no avail.

I have noticed that in the request headers for controllers which use `before_action :authenticate_current_user` (as instructed in #74), the `access-token`, `client` and `uid` headers are missing.

Could someone spread some light on this issue?

Thanks.

**Comment by Valindo** [comment]
Okay, so I found the solution, If you are using angular2token, then just append the headers and pass it with every request you make. Here is an example

> `var req = new Headers();
		req.append('Accept','application/json');
		req.append('access-token', this._tokenService.currentAuthData['accessToken']);
		req.append('client', this._tokenService.currentAuthData['client']);
		req.append('uid', this._tokenService.currentAuthData['uid']);
		req.append('expiry', this._tokenService.currentAuthData['expiry']);
		req.append('token-type', this._tokenService.currentAuthData['tokenType']);`

and then make the request this way,
> `return this._http.get(this.baseUrl,new RequestOptions({
			headers: req
		}))`
