### ISSUE TITLE
Problem with skip_confirmation!

### ISSUE THREAD

**Issue by nicolas-besnard** [lynndylanhurley/devise_token_auth#78]
In my model I add :  `before_create :skip_confirmation!` 

But when I try to register a User, I still have to pass a `confirm_success_url`params to my url. Is that something you want ?

I think it should be an idea to add an option to `DeviseTokenAuth::Engine` such as `is_confirmable`

EDIT : I have down something really quick [here](https://github.com/nicolas-besnard/devise_token_auth/tree/DisableConfirmable) if you wan't to take a look :)

**Comment by achan** [comment]
I'm also having similar issues on 0.1.30.

I'm sure there's something I'm missing.

I've removed `confirmable` from my `User` model like so:

```ruby
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  include DeviseTokenAuth::Concerns::User

  ...
end
```

But when I try to create a registration I get the following response:

```json
{
    "status": "error",
    "data": {
        "id": null,
        "provider": "email",
        "uid": "",
        "name": null,
        "nickname": null,
        "image": null,
        "email": "test@example.com",
        "created_at": null,
        "updated_at": null
    },
    "errors": [
        "Missing `confirm_success_url` param."
    ]
}
```

Am I overriding the devise modules correctly? And if so, is there a reason that I still need to prove a `confirm_success_url`?
