### ISSUE TITLE
Initializer default_password_reset_url not working.

### ISSUE THREAD

**Issue by godinezb** [lynndylanhurley/devise_token_auth#789]
I'm trying to change the redirect url when users reset their passwords like this:

```
DeviseTokenAuth.setup do |config|
  ...
  config.default_password_reset_url = '/password_success'
  ...
end
```
I created a static page with instructions at '/password_success'. I have also tried 'password_success_path', but everytime I reset a password I'm being redirected to the root_path.

Any help will be appreciated.

**Comment by zachfeldman** [comment]
Closed in favor of #324
