### ISSUE TITLE
user_signed_in? doesn't returning access_token  after few  continuous  call to it !!! 

### ISSUE THREAD

**Issue by hiteshsomani** [lynndylanhurley/devise_token_auth#791]
Hey I'm Calling user_signed_in? continuously it is returning true with newly generated access_token but after few continuous it is not returning  access_token ??? why is it so !!!

**Comment by vinsy** [comment]
Facing same issue!! My ghosh, I kept debugging for whole day & found out problem was with this gem.
GET>POST>GET
Immediate 3rd GET request didn't return access-token!

**Comment by zachfeldman** [comment]
Batch request problems are kind of a known issue so I'm going to close this for now.
