### ISSUE TITLE
CORS answers 404 always

### ISSUE THREAD

**Issue by juanpastas** [lynndylanhurley/devise_token_auth#794]
Running this javascript from a plain HTML file:

```javascript
pass = '123123123'; 
$.auth.configure({ apiUrl: 'http://127.0.0.1:3000/api' });
$.auth.emailSignIn({ email: 'fromplain@test.com', password: pass });
$.auth.signOut();
```

Rails answers 404.

What I see in Chrome browser is that an `OPTIONS` request is made before the `DELETE` request, that might be causing this behavior. This is the 404 message:

`User was not found or was not logged in.`

I am using this for rack cors configuration:

```ruby
    config.middleware.use Rack::Cors do
      allow do
        origins '*'
        resource '*',
          :headers => :any,
          :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
          :methods => [:get, :post, :options, :delete, :put]
      end
    end
```

And application routes:

```ruby
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
  end
```

# Update

It seems `OPTIONS` is just sent the first time, but 404 is still being returned.

**Comment by JakeDluhy** [comment]
Are you sending the authentication headers with the request? Devise token auth uses those headers to find the user in order to sign them out.

If you are, is your access-token valid? I ran into a problem where my browser was caching responses, and I was getting stale access tokens to send in the next request.

**Comment by zachfeldman** [comment]
Possible fix posted, closing for now.

**Comment by mateusluizfb** [comment]
Still having the same problem, but with the request being made from Postman.
