### ISSUE TITLE
very unstable gem full of bugs !!

### ISSUE THREAD

**Issue by hiteshsomani** [lynndylanhurley/devise_token_auth#795]
i'm sending any anonymous  access token for authentication still its returning true !!

**Comment by dgleba** [comment]
Do you get the same behavior if you use this example app - https://github.com/lynndylanhurley/devise_token_auth_demo?

**Comment by ashwinimnnit** [comment]
I haven't used this demo I have used this [this](https://github.com/lynndylanhurley/devise_token_auth) version 0.1.39...

**Comment by dgleba** [comment]
Will you try the demo app and let us know if you get the  same behavior?

**Comment by zachfeldman** [comment]
Closing due to no reply in a year or so
