### ISSUE TITLE
Data leak on create password reset

### ISSUE THREAD

**Issue by Mrjaco12** [lynndylanhurley/devise_token_auth#797]
As far as I can tell there isn't a good reason to return the resource data [after a create password reset request](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/passwords_controller.rb#L171). Especially since any user data added to the user object will automatically be included as well even though tokens, etc. are not. I can create a PR for this but wanted to make sure I wasn't missing something obvious first.

**Comment by dkniffin** [comment]
@Mrjaco12 I think this can be closed now

**Comment by Mrjaco12** [comment]
Yes I agree. Closed Via #798.
