### ISSUE TITLE
I18n broken (e.g. :already_in_use)

### ISSUE THREAD

**Issue by morgler** [lynndylanhurley/devise_token_auth#799]
I know this has been reported and fixed twice in the past (https://github.com/lynndylanhurley/devise_token_auth/pull/417 and https://github.com/lynndylanhurley/devise_token_auth/pull/466), but it seems broken again. 

I receive the message "address is already in use" regardless of which locale I use. Since I can't find this phrase in the en.yml file either, I suppose it must have gotten lost in some refactoring. The PRs mentioned above added a key for `errors.messages.already_in_use`, but this key is not present in the current version.

I would love to help here, but I can't find the phrase in the source code either, so I'd need some help.

**Comment by etagwerker** [comment]
@morgler I'm assuming you're using version 0.1.39 - You can find the key here: 

https://github.com/lynndylanhurley/devise_token_auth/blob/v0.1.39/config/locales/en.yml#L28

**Comment by zachfeldman** [comment]
Workaround posted (thank @etagwerker !) closing for now
