### ISSUE TITLE
Generator is not working

### ISSUE THREAD

**Issue by drampelt** [lynndylanhurley/devise_token_auth#8]
I created a new rails project (rails 4.1.4), installed devise, created a user model with the devise generator and then ran `rails g devise_token_auth:install User /auth`. The only output I receive is

```
      create  config/initializers/devise_token_auth.rb
      create  db/migrate/20140720052809_devise_token_auth_create_users.rb
```

Nothing is added to the user model, application controller, or routes file as the generator should. Also, when I tried adding in some of those lines manually, I get `NameError: uninitialized constant DeviseTokenAuth::Concerns::User`

Any help would be greatly appreciated.

**Comment by lukeipanda** [comment]
rails g devise_token_auth:install User auth
Running via Spring preloader in process 57673
Could not find generator 'devise_token_auth:install'. Maybe you meant 'rspec:install', 'integration_test' or 'test_unit:model'
Run `rails generate --help` for more options.

I'm having this problem now.

Using rails 5.0.0.1
Using devise 4.2.0
Using devise_token_auth 0.1.39
Using omniauth 1.3.1
