### ISSUE TITLE
Impersonate user

### ISSUE THREAD

**Issue by brunowego** [lynndylanhurley/devise_token_auth#802]
I'm very frustrated with this, maybe you can help me. I'm trying to do impersonate a user, but whenever I update the page the session is changed.

My controller method bellow:

```rb
def impersonate
  authorize @current_user # pundit ok!

  session[:impersonator_id] = @current_user.id

  warden.set_user @user, scope: :user

  render json: { message: "You are now impersonating #{@user.name}" }
end
```

Any idea how do this or tip? Thanks!

**Comment by rubyconvict** [comment]
I wouldn't play with `warden` or `session`. In this method, try to:
- add a new auth_token to user's tokens
- save the user (with a new token)
- `sign_in` as the user with a new token (devise method)
- return the new auth headers in the action's response headers

**Comment by zachfeldman** [comment]
Possible solution posted (thanks @rubyconvict ), closing for now.

**Comment by thimmaiah** [comment]
So anyone has a code snippet that I can use to do impersonation ?
TIA

**Comment by eterry1388** [comment]
```ruby
user = User.find(1)
user_token = user.create_token
user.save!

{
  "Access-Token" => user_token.token,
  "Client" => user_token.client,
  "Expiry" => user_token.expiry,
  "Uid" => user.uid,
}
```
