### ISSUE TITLE
Securing headers on client side

### ISSUE THREAD

**Issue by omar28** [lynndylanhurley/devise_token_auth#809]
Suppose I build authentication, on server side, using devise_token_auth. How is it possible to protect headers (client_id, token...) saved in client side ? Suppose I encrypt headers generated by server side (so by devise_token_auth) on my client app, does devise_token_auth  provide a feature allowing to decrypt headers received from client side? If yes, how ? 

Thanks for your answer

**Comment by zachfeldman** [comment]
There's no encryption of the client id, token, etc. It is associated with a specific user. If you were concerned about these being intercepted along the way, you could build in an encryption method in your controller overrides.
