### ISSUE TITLE
All the APIs are getting 'Authorized users only'

### ISSUE THREAD

**Issue by nitingrewal** [lynndylanhurley/devise_token_auth#81]
Really good work done here 

I have an issue though. I am following https://www.airpair.com/ruby-on-rails/posts/authentication-with-angularjs-and-ruby-on-rails for my work.

Using ng-token-auth and devise_token_auth

In Controller 
class MyController < ApplicationController
before_filter :authenticate_user!, except: [:new, :create]

but all the API's calls are getting "Filter chain halted as :authenticate_user! rendered or redirected"

Any suggestions would help

**Comment by TGNA** [comment]
@nitingrewal  Hi, I'm having the same problem and I don't know how to solve it. Can you say me what have you done to solve it? Thank you

**Comment by qx** [comment]
did you have something "before_filter :authenticate_user!, only: [:create]" like this in applicationcontroller

**Comment by TGNA** [comment]
I finally solved, the problem was that I don't include the client id properly on the header.
Sorry.
@qx  thanks for your help.

**Comment by qx** [comment]
ok @TGNA

**Comment by prakash-alpine** [comment]
I am having the same problem. In my case I get this error while signing in via REST API. I am not sure what you mean by setting client ID in the header? I am not finding any reference to it in the documentation. Can you explain? Thanks for the help.

**Comment by JamesChevalier** [comment]
I just ran into this issue, where sign in would work properly but subsequent requests would fail with `Filter chain halted as :authenticate_user! rendered or redirected` being logged.

My issue was that my headers were not correct in those subsequent requests. I had `access-token` & `uid`, but I had forgotten to include `client`. That `client` value is passed back on sign in within the headers, just like the `access-token`.

**Comment by tejashande** [comment]
Will any one please suggest from where to set the value of client? I got the response when I signed on first request. But on later request, I keep on getting "Authorized users only." from API. 

I have passed token,expiry & uid from header but I am unable to set the value of client. I read that the value of Client is optional & if it is not passed, new value will be created. 

Any suggestion would be helpful

**Comment by dgliwa** [comment]
@JamesChevalier @tejashande have you found a solution to this?  In the headers I am using the `client`, `uid`, and `access-token` as received from the sign in response. However, i am also getting the "Authorized users only.", with the same `Filter chain halted as :authenticate_user! rendered or redirected`

Thanks

**Comment by paulius005** [comment]
Upgrading from `1.36` to `1.37` resurfaced this issue for me again

**Comment by tejashande** [comment]
There exist comparison between token & ::BCrypt::Password.new(token_hash) in concerns of user. The class of token is string & ::BCrypt::Password.new(token_hash) is Bcrypt. So the comparison will always return false even though values are same. This was the issue in my case.

**Comment by paulius005** [comment]
@tejashande how did you fix that?

**Comment by tejashande** [comment]
@paulius005 You can override tokens_match method in your app

**Comment by paulius005** [comment]
@tejashande do you have to add the new module that overrides the cocerns in `routes.rb` somehow? Not seeing it in the documentation

**Comment by paulius005** [comment]
@tejashande ah never mind just simple method override

**Comment by roanjain** [comment]
@paulius005 I am facing the same issue , can you please mention the file name in which we need to add the above code in config/initializers, since i am unable to find the tokens_match method in my devise gem. I am using devise version 0.1.30
