### ISSUE TITLE
not supporting for angular1.6

### ISSUE THREAD

**Issue by puregold117** [lynndylanhurley/devise_token_auth#810]
I get this error using with angular1.6 

      $http.post(...).success is not a function

still not supporting angular1.6?

**Comment by puregold117** [comment]
Here's dependencies
"dependencies": {
    "angular": ">=1.4 <=1.5.3",
    "angular-cookie": "~4.1.0"
  }

**Comment by deric** [comment]
This repository contains server side code (Ruby gem), for Angular support see [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth).

**Comment by puregold117** [comment]
thank you
