### ISSUE TITLE
Sometimes very frequently, sometimes very randomly - 401 Unauthorized. 

### ISSUE THREAD

**Issue by Kedarnag13** [lynndylanhurley/devise_token_auth#813]
Hi,

I have used devise_token_auth with rails for the Backend to build a iOS application.

1. I am facing an issue, where when I am making requests, I randomly get 401 Unauthorized. There is no proper flow for me to reproduce this in my application.
2. The token just changes for some request on its own, not sure why this is happening.
3. I am sending access-token, client and uid on request in the header.
4. The same issue is not happening when I am trying this in my local machine. What could be the reasons ?

![screen shot 2017-01-19 at 10 04 27](https://cloud.githubusercontent.com/assets/5475397/22093810/b68e2000-de2e-11e6-85ac-22f973dec4a7.png)

**Comment by xpiero** [comment]
I have exactly the same problem #792  and I'm still waiting for an answer

**Comment by Kedarnag13** [comment]
I am using this for building a client application and I am stuck, as I am not able to release a build, as I don't know when the "401 Unauthorized" would occur. Is there any alternatives or patches.

**Comment by dgubitsky** [comment]
Confirming the same issue

**Comment by bartes** [comment]
try code from this PR: https://github.com/lynndylanhurley/devise_token_auth/pull/703

**Comment by onlyyouandty** [comment]
Maybe you need to implement the CORS has stated in the docs https://github.com/lynndylanhurley/devise_token_auth#cors
https://gyazo.com/ee77c6233aad7334b8a945f61dc0576c

**Comment by bartes** [comment]
@onlyyouandty - there are no problems with sending request to the API but with authenticating the request (at least on my end)

**Comment by zachfeldman** [comment]
@lynndylanhurley seems that merging #703 would allow us to close several issues :)

**Comment by zachfeldman** [comment]
#703 has been merged! Try pointing to master to try it out. Closing this for now but feel free to reopen if this didn't fix it.
