### ISSUE TITLE
NoMethodError in DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks

### ISSUE THREAD

**Issue by narapon** [lynndylanhurley/devise_token_auth#82]
I'm trying to get this working on Steam but it was returning even less parameters than facebook so I tried the facebook oauth stratrgy. Got a similar error here:

omniauth-facebook:

undefined method `underscore' for nil:NilClass
Rails.root: /home/rails/tapp

Request
Parameters:

{"code"=>"AQAgnaKoVBwBdPekK_ILh56a0EJi_d-bdrZV-BxqZcj1zXZrFV071dYosQvWYziJ6shjrVTmKjW-SVInr0YrkXJ20J7IwYxaC6ipfVtHxRPL8fUmFB2r2NUH3KyZb8d4AEuGxZtpYbhQ689o2Jq-Jy1pvBO1CrEExSSF3hWODnq1JSo_Kds0VU2_ekXeuP-sU4_Ndp5ORwvSRlVCpunuXQA0GSXdl9uKNndqNZG_E9LfI6lmb-m6vDu7tHS5GpDzaeDVQKYF9PrV24IA50Pd0WOVsi9HTOuw5luK8yQVJb9487TYFWS7kYMyF6z8vFJhK7Y",
 "state"=>"c86ca9b20ebd9205904d4e291a9e6eec19e8074ceafe246f",
 "provider"=>"facebook"}

framework trace:

devise_token_auth (0.1.30) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:11:in `redirect_callbacks'
actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in`call'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in`run_callbacks'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in`block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in`instrument'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:136:in`process'
actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.8) lib/action_controller/metal.rb:196:in`dispatch'
actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal.rb:232:in`block in action'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in`dispatch'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in`block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:404:in`call_app!'
omniauth (1.2.2) lib/omniauth/strategy.rb:362:in `callback_phase'
omniauth-oauth2 (1.2.0) lib/omniauth/strategies/oauth2.rb:77:in`callback_phase'
omniauth-facebook (2.0.0) lib/omniauth/strategies/facebook.rb:72:in `block in callback_phase'
omniauth-facebook (2.0.0) lib/omniauth/strategies/facebook.rb:135:in`with_authorization_code!'
omniauth-facebook (2.0.0) lib/omniauth/strategies/facebook.rb:71:in `callback_phase'
omniauth (1.2.2) lib/omniauth/strategy.rb:227:in`callback_call'
omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in`call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in`call'
omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in`block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in`call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in`call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in`context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in`call'
activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in`call'
activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in`call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in`block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in`call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in`call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in`call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in`call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in`call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in`service'
/home/rails/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/rails/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in`run'
/home/rails/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

omniauth-steam: 

undefined method `underscore' for nil:NilClass
Rails.root: /home/rails/af

Request

Parameters:

{"provider"=>"steam"}

framework trace:

devise_token_auth (0.1.30) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:11:in `redirect_callbacks'
actionpack (4.1.6) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (4.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.6) lib/active_support/callbacks.rb:113:in`call'
activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:229:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:166:in`block in halting'
activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.6) lib/active_support/callbacks.rb:86:in`run_callbacks'
actionpack (4.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.6) lib/active_support/notifications.rb:159:in`block in instrument'
activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.6) lib/active_support/notifications.rb:159:in`instrument'
actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
activerecord (4.1.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.6) lib/abstract_controller/base.rb:136:in`process'
actionview (4.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.6) lib/action_controller/metal.rb:196:in`dispatch'
actionpack (4.1.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.6) lib/action_controller/metal.rb:232:in`block in action'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in`dispatch'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in`block in call'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:404:in`call_app!'
omniauth (1.2.2) lib/omniauth/strategy.rb:362:in `callback_phase'
omniauth-openid (1.0.1) lib/omniauth/strategies/open_id.rb:81:in`callback_phase'
omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
omniauth (1.2.2) lib/omniauth/strategy.rb:184:in`call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/builder.rb:59:in`call'
rack-cors (0.2.9) lib/rack/cors.rb:54:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in`block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in`call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in`call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in`context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in`call'
activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in`call'
activerecord (4.1.6) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in`call'
actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.6) lib/rails/rack/logger.rb:20:in`block in call'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.6) lib/rails/rack/logger.rb:20:in`call'
actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in`call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in`call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.6) lib/rails/engine.rb:514:in`call'
railties (4.1.6) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in`call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in`catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in`process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.3) lib/eventmachine.rb:187:in`run_machine'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in`start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in`run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.1.6) lib/rails/commands/server.rb:69:in`start'
railties (4.1.6) lib/rails/commands/commands_tasks.rb:81:in `block in server'
railties (4.1.6) lib/rails/commands/commands_tasks.rb:76:in`tap'
railties (4.1.6) lib/rails/commands/commands_tasks.rb:76:in `server'
railties (4.1.6) lib/rails/commands/commands_tasks.rb:40:in`run_command!'
railties (4.1.6) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:8:in`require'
bin/rails:8:in `<top (required)>'
spring (1.2.0) lib/spring/client/rails.rb:27:in`load'
spring (1.2.0) lib/spring/client/rails.rb:27:in `call'
spring (1.2.0) lib/spring/client/command.rb:7:in`call'
spring (1.2.0) lib/spring/client.rb:26:in `run'
spring (1.2.0) bin/spring:48:in`<top (required)>'
spring (1.2.0) lib/spring/binstub.rb:11:in `load'
spring (1.2.0) lib/spring/binstub.rb:11:in`<top (required)>'
bin/spring:16:in `require'
bin/spring:16:in`<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in`<main>'

**Comment by galharth** [comment]
@narapon Hey can you describe please how you override the omniauth_callbacks_controller to fix this problem?

**Comment by sarink** [comment]
I'm still getting this same error _today_ with rails 5 and omniauth-google-oauth2

**Comment by lynndylanhurley** [comment]
@sarink we just pushed a beta yesterday. Can you please try with version `0.1.43.beta1`?

**Comment by sarink** [comment]
Just tried the beta, same error. Can you elaborate on what you mean by ["disable the Rails session system"](https://github.com/lynndylanhurley/devise_token_auth/issues/82#issuecomment-65323741)? I haven't seen any instructions for that in the readme, so I'm not sure if I've done it

**Comment by lynndylanhurley** [comment]
When I wrote that comment OmniAuth relied on sessions to function. I'm not sure if that's still the case, but if you've disabled sessions you may want to try re-enabling them to see if that resolves the issue.

**Comment by sarink** [comment]
I haven't disabled it, I'm on a vanilla Rails 5 API Only project, I've encountered/fixed quite a few other errors, but I'm pretty stuck on this one. Any suggestions?

**Comment by lynndylanhurley** [comment]
We'll need more info about your environment. Please open a new issue that follows the [issue template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by sarink** [comment]
`rails new . --api` is my environment.

I've seen this same issue actually opened and closed, without resolution, three times now... do you really want a fourth? I can document all the other issues and solutions I've encountered too, but my first priority has to be fixing this error

**Comment by lynndylanhurley** [comment]
When using the `--api` flag, the [session middleware is not included](http://edgeguides.rubyonrails.org/api_app.html#choosing-middleware). Please try [adding the session middleware](http://edgeguides.rubyonrails.org/api_app.html#other-middleware) and let me know if that resolves the issue.

**Comment by sarink** [comment]
This issue still occurs with (this is how my configuration already was)
```
config.middleware.use ActionDispatch::Session::CookieStore
```

I've tried switching it to:
```
 config.middleware.insert_after ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies
 config.middleware.insert_after ActionDispatch::Cookies, ActionDispatch::Session::CookieStore
``` 

Which yields a new error:
```
ActiveModel::ForbiddenAttributesError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success
```

Relevant stack trace:
```
activemodel (5.1.4) lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
activemodel (5.1.4) lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
devise_token_auth (0.1.43.beta1) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:83:in `assign_provider_attrs'
devise_token_auth (0.1.43.beta1) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:244:in `get_resource_from_auth_hash'
devise_token_auth (0.1.43.beta1) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:29:in `omniauth_success'
actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
```

**Comment by lynndylanhurley** [comment]
Have you tried following [these instructions](https://github.com/omniauth/omniauth#integrating-omniauth-into-your-rails-api)?

**Comment by sarink** [comment]
I updated my `application.rb` config according to those instructions^, that didn't fix the problem though.

I had to override the `omniauth_callbacks_controller`s `assign_provider_attrs` method

I monkey patched it to look like this:
```
    def assign_provider_attrs(user, auth_hash)
      all_attrs = auth_hash['info'].slice(*user.attributes.keys)
      orig_val = ActionController::Parameters.permit_all_parameters
      ActionController::Parameters.permit_all_parameters = true
      permitted_attrs = ActionController::Parameters.new(all_attrs)
      permitted_attrs.permit({})
      return_val = user.assign_attributes(permitted_attrs)
      ActionController::Parameters.permit_all_parameters = orig_val
      return return_val
    end
```

**Comment by sarink** [comment]
Writeup of everything is here: https://github.com/lynndylanhurley/devise_token_auth/issues/1020

**Comment by zachfeldman** [comment]
Thanks @sarink ! Appreciate your contribution

**Comment by tootis** [comment]
Hi @lynndylanhurley and all, 
I followed instructions in @sarink 's comment but I still get:
```
NoMethodError (undefined method `[]' for nil:NilClass)
bundler/gems/devise_token_auth-49911e7522ba/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:14:in `redirect_callbacks
```
I am using `omniauth-facebook` only, and using the latest version of `devise_token_auth`

Can anyone help?

**Comment by sarink** [comment]
@tootis i only used google-oauth2, maybe you could try setting that up to see if the problem is related to facebook or something else?
