### ISSUE TITLE
Devise redirecting Web request to the Token JSON API

### ISSUE THREAD

**Issue by JohnMerlino2** [lynndylanhurley/devise_token_auth#821]
I am using devise, both for web and mobile. The web authentication was working fine until I added the devise_token_auth gem. Once I added that gem, I changed the routes file to add a namespace:

```
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end
```

Now when I visit localhost:3000 on the web google chrome browser, I get a json text on the page:

{"errors":["Authorized users only."]}

Since I accessed the page on the web, I should not be getting json response, I should see the web page. What am I doing wrong?

**Comment by muratbsts** [comment]
+1 this issue

**Comment by roshangm1** [comment]
same issue here.

**Comment by zachfeldman** [comment]
Hi there @JohnMerlino2    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
