### ISSUE TITLE
uid is similar to email

### ISSUE THREAD

**Issue by nandhini-ramanujam** [lynndylanhurley/devise_token_auth#825]
Hi,

On signup, the uid of the user is creating as same as the email. Is this the existing behaviour?

**Comment by ratschance** [comment]
The "uid" attribute is just a unique ID for a user. It is often convenient to use the user's email in the "uid" attribute since you can then limit one account to one email. However, it is not required to fill the "uid" attribute with an email, it just needs to be unique.

**Comment by marothstein** [comment]
Where is the appropriate place to adjust the default value for this field in the User?

**Comment by zachfeldman** [comment]
Closing this out due to lack of activity.

@marothstein you could super into any of the overridden controllers to adjust the default value!
