### ISSUE TITLE
omniauth-facebook authentication with an Angular 2 front end application.

### ISSUE THREAD

**Issue by 91sticker** [lynndylanhurley/devise_token_auth#827]
This might not be an issue its more of a guidance I need regarding the apporoach I am using.
I have a scenario consisting of an angular 2 application with a rails api where I have been able to implement token based authentication using **angular2-token** package with **devise_token_auth** gem. The part m confused about is how do I use **devise_token_auth** to correctly implement omniauth-facebook's authentication through my angular 2 application having a rails API. I have seen the angular code snippet about it provided in the gem's documentation. 
Using ng2-facebook-sdk I have been able to login via facebook and get a cookie as a response on the front end. However the part that confuses me is how to send that information I received in the cookie on my front end to the rails api's ''/auth/facebook/callback" endpoint.

Please let me know if this is the correct approach or if I am missing something. If this has been answered I apologize I didnt come across any material that addresses this issue.
Thanks in advance.

I have also posted a question on stackoverflow:
http://stackoverflow.com/questions/41979919/unable-to-authenticate-my-angular-2-app-having-a-rails-api-as-backend-with-faceb

**Comment by zachfeldman** [comment]
@91sticker try super-ing into the methods in the overrides controllers to see why the resource_class isn't being found. Please reopen if you're still having an issue.
