### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by osazemeu** [lynndylanhurley/devise_token_auth#828]
I get the following warning when I install the following gems:

```
gem 'devise_token_auth', '~> 0.1.40'
gem 'omniauth', '~> 1.3'
```

rails v5.0.1
ruby 2.3.1p112

You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.

Similar issue was raised [here](https://github.com/omniauth/omniauth/issues/872)

I had to load omniauth gem manually because I kept getting the following error:

Could not load 'omniauth'. Please ensure you have the omniauth gem >= 1.0.0 installed and listed in your Gemfile.

**Comment by amingilani** [comment]
Can here to report this. Here's a sample app that produces this warning: https://github.com/amingilani/token-app-warning

Is this just a warning or does this break stuff?

**Comment by shannonio** [comment]
Getting the same error, any ideas?

**Comment by dominicsayers** [comment]
See here https://github.com/intridea/hashie/issues/394

**Comment by michaelherold** [comment]
I just released Hashie v3.5.2 which has the `disable_warnings` feature for the Mash logger and sets the Hashie logger to the Rails logger when we detect that we're running in Rails. Hopefully, this helps!

**Comment by kkoci** [comment]
Awesome! Issue fixed

**Comment by alibowling** [comment]
same error i do not understand how can i fix it
