### ISSUE TITLE
DeviseTokenAuth::TokenValidationsController#validate_token returns 401 unauthorized.

### ISSUE THREAD

**Issue by 91sticker** [lynndylanhurley/devise_token_auth#829]
Its been almost 3 days and I haven't actually pin pointed the cause of the issue.
I have a set up consisting of a rails 4 API created using **rails-api** gem and a front end angular2 application created using **angular cli**. 
I have been successfully able to create users, log them in and log them out of my angular 2 app using angular2-token package and devise_token_auth gem on backend.
The issue I face occurs when I have logged in as a user and upon every page reload I get 401 unauthorized in my browser's console.

And on the rails end I get the following output.

```
Started GET "/api/v1/auth/validate_token" for 127.0.0.1 at 2017-02-06 17:42:49 +0500
Processing by DeviseTokenAuth::TokenValidationsController#validate_token as JSON
SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT 1  [["uid", "abc@xyz.com"]]
Completed 401 Unauthorized in 76ms (Views: 0.2ms | ActiveRecord: 0.3ms)
```

If I run **request.headers.inspect** I get the following response on the server side
`
"HTTP_ACCESS_TOKEN_NAME"=>"xxxxxxxxxxxxxxxxxx", "HTTP_EXPIRY"=>"xxxxxxxxxxxxxxxxxx", "HTTP_UID"=>"abc@xyz.com", "HTTP_CLIENT_NAME"=>"xxxxxxxxxxxxxxxxxx", "HTTP_TOKEN_TYPE"=>"Bearer"`

Which gives the idea that the authentication headers are being actually sent to the rails API.

Further more I have also sent curl requests to the validate_token method using the credentials I have in my localstorage as I login and I get similar 401 response which narrows down the problem to the API (I may be wrong in that regard).
[Here](http://storage5.static.itmages.com/i/17/0208/h_1486544830_6813876_6eee490dcc.png) is the response I get upon running a curl request.

Further more I get nil when I inspect current_user on the server side.

I also have rack-cors configured on my API with the following configurations:
```

config.middleware.use Rack::Cors do
      allow do
        origins '*'
        resource '/cors',
          :headers => :any,
          :methods => [:post],
          :credentials => true,
          :max_age => 0
        resource '*',
          :headers => :any,
          :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
          :methods => [:get, :post, :options, :delete, :put]
      end
    end
```

If there is anything I am missing or any more information that I should be providing please let me know I have been stuck on this issue for a long time now.

Thank u so much.

**Comment by YUzhva** [comment]
Could you write content of your **app/models/user.rb** file?

And did you check server responce?

P.S: issue could be related to :confirmable user email. If you setup Devise on that way (user need to verify email after registration) he would not be able to login until he would confirm email.

**Comment by 91sticker** [comment]
Sorry for delayed response i fixed the by using Rails 5 for my API. Previously I used rails-api gem with rails 4 in which scenario I was getting the 401.

It seems to work perfectly fine on development but in production upon refreshing repeatedly I get 401 from the server. Is it a normal behavior ?

**Comment by rmagnum2002** [comment]
Have the same issue, update to latest rails
Rails 5.0.2
devise_token_auth (0.1.40)

https://vimeo.com/212141533

**Comment by MatthewMarkgraaff** [comment]
Also experiencing this issue, haven't looked into this in too much detail yet but will post here if I find a solution @91sticker.

**Comment by zachfeldman** [comment]
Seems like this was resolved according to @91sticker ...

might be a problem with tokens being generated or not being generated. Feel free to reopen if it's still an issue.
