### ISSUE TITLE
No HTML for omniauth_external_window view in Rails 5 API

### ISSUE THREAD

**Issue by thorsteneckel** [lynndylanhurley/devise_token_auth#830]
Version: 0.1.39
Devise 4.2.0
Rails 5.0.0.1 API

I had the issue that no HTML (of the omniauth_external_window view) was rendered after a successful OmniAuth redirect.

This is because all Devise controllers inherit by default from ApplicationController which inherits from ActionController::API by default/in my setting. But ActionController::API can't render HTML. So the trick is to add the following lines to `config/initializers/devise.rb`:

```ruby
Devise.setup do |config|
  config.parent_controller = 'ActionController::Base'
end
```

This worked for me. There were some other obstacles I had to take but those could be found via googleing the error messages.

**Comment by louism517** [comment]
Thanks for this, this was the final piece of a 2-day puzzle for me!

**Comment by skoropadas** [comment]
Omg, thanks! You save my day!

**Comment by skoropadas** [comment]
Guys, I found a new problem. If you use a Rails 5 API, then the `before_action :configure_permitted_parameters, if: :devise_controller?` will not work. Because the Rails 5 API inherits the `ActionController::API` and not the `ActionController::Base.`

**Comment by zachfeldman** [comment]
Seems like this has been solved/worked around, closing for now.

**Comment by ljesus** [comment]
This should be added to the FAQ or docs. I spent a couple of hours wondering why it wasn't working and debugging the code, until I came to the conclusion that the HTML template wasn't being properly rendered. Thank you for the fix.
