### ISSUE TITLE
no registration routes when used with devise 

### ISSUE THREAD

**Issue by ChrisCPO** [lynndylanhurley/devise_token_auth#834]
I have added devise and devise auth_token in the same rails app as suggested:
https://github.com/lynndylanhurley/devise_token_auth#can-i-use-this-gem-alongside-standard-devise

However I have no devise_token_auth/registrations routes in. All of the registration endpoints disappear.

I tried adding the routes back in but this needs to be done in a namespace which then changes the Constant that it is looking for.
 ```ruby
 namespace :api do
    scope :v1 do
      post "auth", to: "devise_token_auth/registrations#create" => api/devise_token_auth/registrations#create
    end
  end
```

Either the registration endpoints disappear or Rails throws a duplicate route path error. This is a serious issue.

**Comment by zachfeldman** [comment]
Hi there @ChrisCPO    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
