### ISSUE TITLE
CookieOverflow on namespaced controllers

### ISSUE THREAD

**Issue by hudadiaz** [lynndylanhurley/devise_token_auth#835]
I'm on Rails 5 Api mode. Referencing to `current_api_v1_user` in `Api::V1::SomeControllers` gives me `ActionDispatch::Cookies::CookieOverflow`.

This does not happen if I `mount_devise_token_auth_for` outside my namespaced routes. I can use `current_user` inside the namespaced controllers this way but I prefer not to.

**Comment by zachfeldman** [comment]
Hi there @hudadiaz  ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by maysam** [comment]
@hudadiaz I think this happens when you override the user as_json method
