### ISSUE TITLE
No resource_class found

### ISSUE THREAD

**Issue by frodrigueza** [lynndylanhurley/devise_token_auth#838]
Hi, Im trying to access a route in one of my controllers. I looks like this:

```
class ExternalAuthsController < DeviseTokenAuth::OmniauthCallbacksController
  include DeviseTokenAuth::Concerns::SetUserByToken
  skip_before_filter :authenticate_user!, :only => [:clave_unica_callback, :redirect]

  def client_certificate_callback
    if valid_authenticity_token?(session, state)
      if current_entity_user
        render json: {message: 'ok'}
      end
    end
  end
end
```

entity_user is another model class I use to authenticate
But it raises `No resource_class found` when it tries current_entity_user. Help?

Thanks

**Comment by zachfeldman** [comment]
@frodrigueza have you tried supering into the parent method and looking into if the resource_class is being found or not?

Closing for now, feel free to reopen if still an issue.
