### ISSUE TITLE
jsonb token

### ISSUE THREAD

**Issue by dijonkitchen** [lynndylanhurley/devise_token_auth#841]
Should `jsonb` be used here instead of `json`? 

https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/templates/devise_token_auth_create_users.rb.erb#L43

References:
https://www.postgresql.org/docs/9.4/static/datatype-json.html
https://github.com/rails/rails/issues/17706#issuecomment-181205924
http://stackoverflow.com/questions/23509740/distinct-on-postgresql-json-data-column

**Comment by zachfeldman** [comment]
Hi there @dijonkitchen    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by dijonkitchen** [comment]
@zachfeldman it's still relevant since unless the project plans to support Postgres <9.4.

**Comment by zachfeldman** [comment]
@dijonkitchen interesting. Do you want to submit a pull request perhaps to rectify it?

**Comment by dijonkitchen** [comment]
I proposed this as a question, but it's an easy change. So should `jsonb` be used instead of `json`?

**Comment by zachfeldman** [comment]
Good point. I just read the accompanying links you posted (sorry for not doing that earlier) and it does seem that jsonb has some clear advantages.

Let's see what @lynndylanhurley thinks?

**Comment by lynndylanhurley** [comment]
@dijonkitchen what would the advantage be for this gem specifically? Some things to keep in mind:

* The token column does not need to be indexed because we query by the `uid` value.
* The equality stuff isn't relevant because we're doing the comparison using bcrypt.

**Comment by kongo** [comment]
@lynndylanhurley I encountered a situation when I needed to select *distinct* values of `clients` joined with `users`. The query failed with error "could not identify an equality operator for type json". Converting `tokens` to `jsonb` solved the issue.

**Comment by javierm** [comment]
Sorry, I know this issue is an old one, but since it's still open, here's my feedback regarding the possible advantages of using jsonb.

We've got code in our application which generates the following query to get all user who have commented on proposals:

```
"SELECT DISTINCT \"users\".* FROM \"users\"
INNER JOIN \"comments\" ON \"comments\".\"user_id\" = \"users\".\"id\"
WHERE \"comments\".\"commentable_type\" = 'Proposal' AND \"comments\".\"commentable_id\" IN (
  SELECT \"proposals\".\"id\" FROM \"proposals\" WHERE \"proposals\".\"hidden_at\" IS NULL
)"
```

We're now integrating `devise_token_auth` in our application (thanks for the gem, by the way!) and we're getting an `ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  could not identify an equality operator for type json` exception. Using jsonb seems to solve the issue.

**Comment by dijonkitchen** [comment]
> @dijonkitchen what would the advantage be for this gem specifically? Some things to keep in mind:
> 
> * The token column does not need to be indexed because we query by the `uid` value.
> * The equality stuff isn't relevant because we're doing the comparison using bcrypt.
> 
> Is there another advantage that I'm missing?

I think that's right. 

Either way, I think it's been a while for this to marinate and it doesn't seem to be a problem besides some `DISTINCT` problems that people have found a workaround for. 

I'll close this now, but feel free to reopen if it's relevant.
