### ISSUE TITLE
uninitialized constant SECRET_KEY_BASE

### ISSUE THREAD

**Issue by gamesover** [lynndylanhurley/devise_token_auth#845]
I have an old project want to add `devise_token_auth`. I've included gem and then run `rails g devise_token_auth:install`. But it display
`(erb):8:in <main>: uninitialized constant SECRET_KEY_BASE (NameError)
`
## update
my `secrets.yml` format is not correct. Please close this issue. Thanks

**Comment by olleolleolle** [comment]
(Hi @gamesover, thanks for the update - _you_ can close this issue, I reckon.)
