### ISSUE TITLE
Swagger / Yard Docs

### ISSUE THREAD

**Issue by jancel** [lynndylanhurley/devise_token_auth#846]
Has anyone been able to integrate/document the paths here with Swagger or is there a reason not to? (Security/Best Practice/etc)

**Comment by MaicolBen** [comment]
Could be [api blueprint](https://apiblueprint.org/) ? Because I can do that

**Comment by zachfeldman** [comment]
No discussion since March, closing for now. Feel free to reopen if this interests you!

**Comment by vanessasoutoc** [comment]
How use grape-swagger-rails gem to document authentication with devise auth token?????

**Comment by DeepakGT** [comment]
https://www.javavines.com/2021/12/swagger-file-devise-token-auth.html
