### ISSUE TITLE
Insecure session created with reset password link

### ISSUE THREAD

**Issue by serene** [lynndylanhurley/devise_token_auth#848]
With the current implementation, the reset password token provided in the reset password email provides the user with a complete valid session.

This was noted in this thread https://github.com/lynndylanhurley/devise_token_auth/issues/604 by @piotr-galas.

Was it done this way for a reason? Regular devise just has a reset password token that is passed to the back-end and can only be used for resetting the user's password.

I can provide a fix for this, but it would obviously not be backward compatible, which would require a major version bump.

**Comment by hughkolias** [comment]
I guess theoretically if they can get to the reset password with token page it's the same as gaining access to the account? Just trying to figure out why they took this approach?

I agree with you and @piotr-galas though, sending the token as param just seems safer/better. Wonder what the rest of the community's thoughts are?

**Comment by rachuxx** [comment]
This behaviour is nonsense. Why not operating on tokens? Now, we are completely logged in after clicking the link which is really bad. Please try to fix it. Manual sign-in after password reset would be great and more secure.

**Comment by lynndylanhurley** [comment]
> I guess theoretically if they can get to the reset password with token page it's the same as gaining access to the account?

Those were my thoughts.
