### ISSUE TITLE
NoMethodError (undefined method `new_session_path' for #<Devise::OmniauthCallbacksController:0x0000000630f628>)

### ISSUE THREAD

**Issue by ckho** [lynndylanhurley/devise_token_auth#853]
I am using omniauthable only

**Comment by zachfeldman** [comment]
Not nearly enough information to solve this one. Feel free to reopen using our issue template if you're still having a problem.

**Comment by zachfeldman** [comment]
Closing due to lack of information, feel free to reopen if it's still a problem following our [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md)
