### ISSUE TITLE
How to Restrict Access to a Single Client?

### ISSUE THREAD

**Issue by stratigos** [lynndylanhurley/devise_token_auth#854]
I can't seem to find this in the documentation, and diddn't notice anything in the configuration regarding this: how can I restrict access to a single client? I am wondering if there is a way I can actually eliminate multi device support for my API, and if it is possible to limit an end user to the device that she/he registered with, allowing no other devices. If this can be achieved through the `devise_token_auth` (or `devise`) configuration, that would be helpful to know about. TIA :)

**Comment by andoq** [comment]
There is a max_number_of_devices config setting for devise token auth.  I haven't tried to set it to 1, but you could try.  This is present and commented out in the config file that is generated by rails g devise_token_auth:install

**Comment by stratigos** [comment]
Thanks @andoq, Ill try that out if I need to implement this feature. I dont think this fully accomplishes what I want, which is to prevent an additional device to connect to an API. 

The `max_number_of_devices` setting looks like it just invalidates the session on "older" devices once the max has been reached. 

I suspect Ill need to roll my own, in terms of identifying a specific user device and disallowing any others. I was just hoping I missed something already baked in to either this or the `devise` source.

**Comment by zachfeldman** [comment]
Probably @stratigos . Let us know how that went! Closing this for now though.
