### ISSUE TITLE
No access-token in the header

### ISSUE THREAD

**Issue by suthaRavi** [lynndylanhurley/devise_token_auth#855]
I am using 

devise 4.2.0
devise_token_auth 0.1.40
rails 5.02, 5.0.1

I am not getting access token in the header after successful signin.

**Comment by MaicolBen** [comment]
@suthaRavi Can you give more details? Like the curl command that you used to sign in and/or the server response headers

**Comment by suthaRavi** [comment]
I had found the problem.

I did not properly edit cors.rb.

problem solved.

Thanks
