### ISSUE TITLE
Segmentation Fault is raising while trying to send emails.

### ISSUE THREAD

**Issue by mahi-wal** [lynndylanhurley/devise_token_auth#857]
Hi, I'm facing problem in sending user authentication emails when I use devise_token_auth with **ruby version 2.4.0 and 2.4.1**.

**ApplicationMailer.send_test_mail.deliver!** segmentation fault error is raising.
However same thing is working with **ruby-version 2.2.5**.
Please find the log file.

[logs.txt](https://github.com/lynndylanhurley/devise_token_auth/files/884685/logs.txt)

I would appreciate if you can look into it.

**Comment by zachfeldman** [comment]
Hi there @mahi-wal    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
