### ISSUE TITLE
Sample Sessions Controller for logging in via Rails View.

### ISSUE THREAD

**Issue by npham1** [lynndylanhurley/devise_token_auth#86]

**Comment by lynndylanhurley** [comment]
@ACPK - I vaguely remember working through this issue with you, but I forget the details. Do you remember how it was resolved?

**Comment by ACPK** [comment]
@lynndylanhurley  - I needed to namespace as API.

**Comment by lynndylanhurley** [comment]
Ahh ok. I'm closing this one out.

Also, I just fixed a bunch of `namespace` / `scope` issues in version `0.1.31.beta8`. Not sure if you were having trouble before, but everything should work as expected now.
