### ISSUE TITLE
Caching causing an issue

### ISSUE THREAD

**Issue by jgoodall628** [lynndylanhurley/devise_token_auth#861]
I am currently running in to an issue with caching. After I have completely cleared the cache and memory, I can login and navigate fine. Once I logout and relogin, one of the requests I make has been cached so it returns the wrong token credentials resulting in a 401 error on the next request. 
Note: if I disable caching in the Chrome inspector this issue does not occur.

**Comment by andoq** [comment]
this is likely the same issue as #702

**Comment by zachfeldman** [comment]
closing in favor of #702
