### ISSUE TITLE
validate_token works on local web server, but not remote?

### ISSUE THREAD

**Issue by hoggworks** [lynndylanhurley/devise_token_auth#873]
Hey all,

I've got this gem enabled on a project and it's working fine locally. BUT when I'm deployed, while I can register/login and my calls (using a custom authentication helper) work just fine, the actual validate_token doesn't do anything. It looks like maybe on the server the tokens aren't being set correctly, as when I look at my actual User data, I can find the client, but not the token itself. Is there an easy, obvious gotcha for this? I imagine it's something very simple.

**Comment by zachfeldman** [comment]
Hi there @hoggworks    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
