### ISSUE TITLE
json-hyper-schema for devise_token_auth

### ISSUE THREAD

**Issue by tooppoo** [lynndylanhurley/devise_token_auth#879]
When I develop client side which communicate with api server, sometime create mock server from json-schema.
I want to include json-hyper-schema of devise_token_auth's api, to create mock devise server from schema.

**Comment by zachfeldman** [comment]
Hi there @tooppoo    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
