### ISSUE TITLE
Return parent with sign in data?

### ISSUE THREAD

**Issue by jgoodall628** [lynndylanhurley/devise_token_auth#880]
Is there a way to have the parent be returned along with the user data when logging in or validating the user?

For instance,
`class User
belongs_to :business
end
`
`class Business
has_many :employees
end`

I want to return the business model along with my user.
Thanks in advance

**Comment by zachfeldman** [comment]
Yup, you could super into the endpoint that returns user data and override what is returned normally. Feel free to reopen if that is unclear.
