### ISSUE TITLE
undefined method `[]=' for nil:NilClass due to missing client_id

### ISSUE THREAD

**Issue by muhammadn** [lynndylanhurley/devise_token_auth#881]
I have this error when i am doing batch request:
```
undefined method `[]=' for nil:NilClass
```

```
…h-0.1.40/app/models/devise_token_auth/concerns/
user.rb: 218:in `extend_batch_buffer'
```

The offending code is in user.rb line 218

```
  def extend_batch_buffer(token, client_id)
    if self.tokens[client_id] != nil
      self.tokens[client_id]['updated_at'] = Time.now
    end

    return build_auth_header(token, client_id)
  end
```

Problem is, sometimes the tokens do not have the matching client_id which is from the request, and fails with `undefined method `[]=' for nil:NilClass`

I will submit a PR which is a simple fix. See resolve #882

**Comment by MaicolBen** [comment]
@muhammadn Why did you close the PR?

**Comment by zachfeldman** [comment]
We have a PR open to fix batching issues...hopefully it will be merged soon. Closing this for now.
