### ISSUE TITLE
Email Regex causing Issue - not synced with Devise email RegEx

### ISSUE THREAD

**Issue by kameshprasad** [lynndylanhurley/devise_token_auth#885]
Hi Devs,

Email validator regex is not as similar to Devise, which in turn failing user save for email even for few valid emails.
`*** ActiveRecord::RecordInvalid Exception: Validation failed: Email is not an email`

I'm using this Gem with Devise for API. For now have updated email validator to use default email regular expression.

**Comment by zachfeldman** [comment]
Valid point. I agree that this should probably be done....there may even be an open PR for it. I will check.
