### ISSUE TITLE
unknown attribute 'expiry' for User.

### ISSUE THREAD

**Issue by stansongman** [lynndylanhurley/devise_token_auth#886]
I have an ionic 1-based app talking to Rails 5 backend, using ng-token-auth and devise_token_auth.  I just added an error handler, and now when I try to register a new user, $auth.signup fails and returns this StandardError message:  "unknown attribute 'expiry' for User."

**Comment by 13LD** [comment]
had the same problem, try to not include this header and it works for me

**Comment by stansongman** [comment]
I'm not sure what your answer means.

**Comment by 13LD** [comment]
![2017-05-24 10 58 18](https://cloud.githubusercontent.com/assets/9123189/26392668/117e67a6-4070-11e7-8915-a553d71aff51.png)
example request with auth headers

**Comment by stansongman** [comment]
Thanks for clarifying.  the problem seems to have disappeared at this moment, I have no idea why.  I will look into the headers, though.

**Comment by stansongman** [comment]
It cropped up again when implementing password reset.  I solved it by adding an expiry field to the users table.
