### ISSUE TITLE
API Does Not Use Api_Controller 

### ISSUE THREAD

**Issue by iamameme** [lynndylanhurley/devise_token_auth#887]
Sorry, but I couldn't find a solution to this anywhere. In the documentation, it says that if you are using both devise and devise_token_auth, you need two different controllers.

```
# app/controllers/api_controller.rb
# API routes extend from this controller
class ApiController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
end

# app/controllers/application_controller.rb
# leave this for ActiveAdmin, and any other non-api routes
class ApplicationController < ActionController::Base
end
```

I did this, but the API calls still go to the normal application controller and don't ever reach the API controller. How do you connect them?

**Comment by zachfeldman** [comment]
Hi there @iamameme    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by RigoTheCEO** [comment]
+ 1

**Comment by RigoTheCEO** [comment]
+1

**Comment by zachfeldman** [comment]
@RigoTheCEO would you prefer we keep this issue open?

**Comment by RigoTheCEO** [comment]
Yes. We should be able to decide which application class this gem descends from. This could be helpful in many ways, especially when using the standard Devise gem with this one.

**Comment by zachfeldman** [comment]
Awesome! @RigoTheCEO can you submit a pull request to that effect if you feel this way? I'd be glad to review.

**Comment by karlingen** [comment]
@zachfeldman PR up for grabs!

**Comment by karlingen** [comment]
@iamameme see if the latest master fixes your issue
