### ISSUE TITLE
allow_unconfirmed_access_for

### ISSUE THREAD

**Issue by samstickland** [lynndylanhurley/devise_token_auth#89]
Hi,

How do you configure allow_unconfirmed_access_for. I've added 

``` ruby
Devise.setup do |config|   
  config.allow_unconfirmed_access_for = 7.days
end
```

to config/initializers/devise.rb and confirmed with byebug that the configuration is hit, but the users still aren't allowed unconfirmed access.

**Comment by lynndylanhurley** [comment]
@samstickland - sorry for the late reply. This feature hasn't been implemented yet. 

I'm just about to roll out version `0.1.31` and I don't want to introduce any more changes. Hopefully I'll be able to include this feature in version `0.1.32`.

**Comment by klautcomputing** [comment]
@lynndylanhurley if you give me some pointers on how to do it, I'd go ahead and give it a try.

**Comment by sdornan** [comment]
Would love to see this implemented. I'd also be up for trying to do it myself if I had some pointers.

**Comment by mkhatib** [comment]
Would love to see this as well.

**Comment by ACPK** [comment]
+1  Any progress on this?

**Comment by masanorinyo** [comment]
Would love to see this as well.  Do we have any other ways to allowed unconfirmed access?

**Comment by serhiym** [comment]
+1 maybe there is another way how we can achieve this without allow_unconfirmed_access_for option?

**Comment by serhiym** [comment]
for those who may be interested - I implemented "allow_unconfirmed_access_for" in next way
add devise.rb file with
```
Devise.setup do |config|
  config.allow_unconfirmed_access_for = 365.days
end
```
+ code from this issue (adds access token after sign up)
https://github.com/lynndylanhurley/devise_token_auth/issues/361

**Comment by zachfeldman** [comment]
I was able to use:

`config.allow_unconfirmed_access_for = nil`

with the current version of devise_token_auth, and it allowed a user to login without being confirmed.

Closing this issue for now!
