### ISSUE TITLE
The action 'edit' could not be found for DeviseTokenAuth::RegistrationsController

### ISSUE THREAD

**Issue by trepidity** [lynndylanhurley/devise_token_auth#896]
Rails 5.1.1 fresh app.
Installed devise_token_auth with the following command
`rails g devise_token_auth:install User auth`

I have a route for this even
`  edit_user_registration GET      /auth/edit(.:format)                   devise_token_auth/registrations#edit`

Yet, when I try calling the route, the controller throws an error.

```
devise (4.3.0)
devise_token_auth (0.1.42)
```

```
INFO -- :  Started GET "/auth/edit" for 162.158.69.84 at 2017-05-29 03:12:01 +0000
FATAL -- : AbstractController::ActionNotFound (The action 'edit' could not be found for DeviseTokenAuth::RegistrationsController):
```

**Comment by nicholasshirley** [comment]
There's no edit action on the [registrations controller](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/registrations_controller.rb). I don't know enough about the gem to say why, but there are other routes that aren't defined in controllers.

**Comment by zachfeldman** [comment]
I suppose we could add an edit action, I don't see why not. @trepidity or @nicholasshirley feel free to reopen this if you'd like to work on it!
