### ISSUE TITLE
change_headers_on_each_request not working expiry header empty

### ISSUE THREAD

**Issue by twelve34** [lynndylanhurley/devise_token_auth#90]
The expiry header is empty when enabling change_headers.
I used the environment: ruby 2.1.5p273 and found that the expiry header is not correct build based on the auth_header tokens var

user.rb:  
def build_auth_header(token, client_id='default')
....
    expiry = self.tokens[client_id]['expiry'].to_s

To solve the problem i change 

 expiry = self.tokens[client_id][:expiry].to_s

**Comment by lynndylanhurley** [comment]
@twelve34 - can you please check out version `0.1.31.beta7` and let me know if this is still an issue?

**Comment by twelve34** [comment]
@lynndylanhurley thanks works fine now.
