### ISSUE TITLE
API authentication. Method not allowed 405. Use POST /sign_in to sign in. GET is not supported.

### ISSUE THREAD

**Issue by jvalenciag** [lynndylanhurley/devise_token_auth#900]
Hi,
I am using devise_token_auth to authenticate an API of my web app, everything works fine on staging environment, but when I try to sign in to my API in production I got this error:
```
405 method not allowed
"errors": [
    "Use POST /sign_in to sign in. GET is not supported."
  ]
```
I am not using any omniauth service, I read other people with a similar issue but they were trying to integrate to other service. Any clue of what is going wrong in the production environment?

**Comment by jackpope** [comment]
@jvalenciag Why did you close this? Did you find a solution? I'm running into the same problem in my local environment.
