### ISSUE TITLE
Completed 422 Unprocessable Entity [Rails 5 API only, React with J-Toker]

### ISSUE THREAD

**Issue by nthock** [lynndylanhurley/devise_token_auth#904]
Sorry that I have to post this issue as I am stuck for a few days. I am using Rails 5 API-only app hosted with Heroku. I try to use React as the front end to do user authentication with J-Toker.

However, I keep getting the error "Completed 422 Unprocessable Entity". I have set the settings using Rack Cors gem to allow origin from any domains. So I really don't know what is wrong. Is there anyone who experience this can share how do you deal with this issue:

Here's my code:

application_controller.rb
```ruby
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  respond_to :json

end
```
In my React:

Registration_form.js
```javascript
Auth.configure({
  apiUrl: <Heroku URL>
});

handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        this.setState({ email: values.email });
        this.setState({ password: values.password });
        this.setState({ password_confirmation: values.password_confirmation });

        Auth.emailSignUp({
          email: this.state.email,
          password: this.state.password,
          password_confirmation: this.state.password_confirmation
        });

      }
    });
  }
```

I do not think the issue lies with J-Toker. Really thank you so much for your help on this.

**Comment by pnewsam** [comment]
Was having the same issue myself, but I think I found the problem. In the DeviseTokenAuth Registrations Controller it is expecting a "confirm_success_url" param to be included along with the email, password, and password_confirmation. Try adding that and seeing how it goes.

**Comment by zachfeldman** [comment]
Workaround posted, so closing this one for now.

**Comment by moyuanhuang** [comment]
In the request response, you can inspect the error message to see why your request got denied. Mine was
```
"errors":{"password":["is too short (minimum is 8 characters)"],"full_messages":["Password is too short (minimum is 8 characters)"]}
```

**Comment by treva556** [comment]
@moyuanhuang how did you solve it, i have same issue
