### ISSUE TITLE
JSON API status?

### ISSUE THREAD

**Issue by stephanebruckert** [lynndylanhurley/devise_token_auth#906]
Has anyone succeeded at making this gem compatible with [JSON API](http://jsonapi.org/)?

@lynndylanhurley are you still maintaining this project? and is JSON API something you would consider supporting?

I can see the following inactive issues:
https://github.com/lynndylanhurley/devise_token_auth/pull/566
https://github.com/lynndylanhurley/devise_token_auth/pull/596

**Comment by zachfeldman** [comment]
Hi @stephanebruckert , we're now more actively maintaining this! Someone else posted an interesting idea for how to get this done without it being super disturbing that was interesting:
https://github.com/lynndylanhurley/devise_token_auth/issues/818

Maybe you want to work with them on this a bit?

**Comment by stephanebruckert** [comment]
I think this would be great to have, unfortunately my implementation had to be made without JSONAPI and I won't have time come back on it. You can close it for now but hopefully someone will want to re-open it!

**Comment by zachfeldman** [comment]
We can only hope!

**Comment by zachfeldman** [comment]
...and you're welcome. We need a standard and this gem has a lot of what Ruby devs need, I want to make it awesome!

**Comment by andresgutgon** [comment]
Hi! Maybe I'm late to the party but I wanted to know what's the status of this? I added devise token to my API and is working great but now i want to implemenent the rest of the endpoints of the API using this https://github.com/stas/jsonapi.rb 

Should I do someting to make devise token auth compatible with [JSON::API](https://jsonapi.org/)?
