### ISSUE TITLE
RuntimeError in DeviseTokenAuth::OmniauthCallbacksController#omniauth_success on google_oauth2 login

### ISSUE THREAD

**Issue by jvkiran** [lynndylanhurley/devise_token_auth#907]
.rvm/gems/ruby-2.2.2/gems/**devise_token_auth-0.1.42**
.rvm/gems/ruby-2.2.2/gems/**omniauth-google-oauth2-0.5.0**

i'm using angular2-token 

> Following is the error facing while login with google

 
`Processing by DeviseTokenAuth::OmniauthCallbacksController#omniauth_success as HTML
  Parameters: {"state"=>"976a7db99948496ccb2d5b309233a07eaaf01d5e8f146eed", "code"=>"4/5eV4wYYnqfRlbBpFrlvHVBkuTTQvnvEyk2WPf95MCD4", "provider"=>"google_oauth2"}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

  
RuntimeError (No resource_class found):
  
devise_token_auth (0.1.42) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:109:in `resource_class'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:237:in `get_resource_from_auth_hash'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:29:in `omniauth_success'
actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `call'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/strategy.rb:407:in `call_app!'
omniauth (1.6.1) lib/omniauth/strategy.rb:361:in `callback_phase'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `call'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by WMahoney09** [comment]
I have the same issue, using Angular 1 front end and [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth)

```
", "provider"=>"google_oauth2"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
RuntimeError (No resource_class found):
  
devise_token_auth (0.1.42) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:109:in `resource_class'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:21:in `set_user_by_token'
devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:123:in `current_user'
devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:111:in `authenticate_user!'
```

**Comment by ohayou-ikechan** [comment]
maybe related issue I've just posted #910

**Comment by nghiemdao** [comment]
I got the same issue on my current project. 
After searching around without any solutions, I decided to use omniauth strategies with devise  only, by following [this wiki](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview). Then, generate tokens and add them to response headers.

**Comment by ohayou-ikechan** [comment]
Thanks!
there are lots of issues in this,so I'm thinking of using only devise without devise_token_auth.

**Comment by zachfeldman** [comment]
Sadly going to close this for now. Hopefully we can meet your needs better in the future!

**Comment by Olek-sii** [comment]
Same issue and i can not find solution. Is there any solution for this?

**Comment by jameseggers** [comment]
@zachfeldman have you any idea what might be causing the issue?

**Comment by zachfeldman** [comment]
Nope, just closed it due to lack of activity. Sorry

**Comment by jameseggers** [comment]
@zachfeldman no worries, figured it out. had to add `except: :callback` to `protect_from_forgery` and that fixed it

**Comment by zachfeldman** [comment]
Nice! Thanks for posting the solution for future generations :D

**Comment by Thananjaya** [comment]
@jameseggers it is not working. I am sadly seeking solutions for this issue.

**Comment by jameseggers** [comment]
To what controller did you add it, @Thananjaya ?

**Comment by Thananjaya** [comment]
@jameseggers ApplicationController Sir

**Comment by yanivps** [comment]
@Thananjaya  protect_from_forgery does not exist when you intherits from `ActionController::API`. Only from `ActionController::Base`
If you are building an Rails API app it is probably not the way to implement it

**Comment by NOOBFREEAKER** [comment]
```
Started POST "/omniauth/facebook/callback" for 127.0.0.1 at 2019-03-12 13:26:08 +0530
Processing by DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks as */*
  Parameters: {"provider"=>"facebook"}
Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)


  
RuntimeError (No resource_class found):
  
app/controllers/application_controller.rb:6:in `configure_permitted_parameters'
```

Now my configure_permitted_parameters are defined and needed during `/auth/` .
How do i overcome this? Is their a workaround for this?
Is it still an issue which has not been resolved?

**Comment by Tosh39** [comment]
This doesn't become a solution to the root of the problem, but as a quick-fix I override `DeviseTokenAuth::OmniauthCallbacksController` like this:

```rb
# Based on: https://github.com/lynndylanhurley/devise_token_auth/blob/v1.1.2/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb

class Api::V1::OmniauthCallbacksController < DeviseTokenAuth::OmniauthCallbacksController
  include Devise::Controllers::Rememberable

  def omniauth_success
    get_resource_from_auth_hash
    set_token_on_resource
    create_auth_params

    if resource_class.devise_modules.include?(:confirmable)
      # don't send confirmation email!!!
      @resource.skip_confirmation!
    end

    # ================================================
    # Update here to Model Class
    # from :
    #      sign_in(:user, @resource, store: false, bypass: false)
    # to: 
    sign_in(:traveler, @resource, store: false, bypass: false)

    @resource.save!

    yield @resource if block_given?

    render_data_or_redirect('deliverCredentials', @auth_params.as_json, @resource.as_json)

  end

  protected
  def get_resource_from_auth_hash
    # find or create user by provider and provider uid

    # ================================================
    # Update here to Model Class
    # from :
    #    @resource = resource_class.where(
    # to: 
    @resource = Traveler.where({
      uid:      auth_hash['uid'],
      provider: auth_hash['provider']
    }).first_or_initialize

    if @resource.new_record?
      handle_new_resource
    end

    # sync user info with provider, update/generate auth token
    assign_provider_attrs(@resource, auth_hash)

    # assign any additional (whitelisted) attributes
    if assign_whitelisted_params?
      extra_params = whitelisted_params
      @resource.assign_attributes(extra_params) if extra_params
    end

    @resource
  end

end
```

Also needed to update `config/routes.rb` like this:
```rb
Rails.application.routes.draw do
   # ================================================
   # Enable custom controller
   # from :
   #   mount_devise_token_auth_for 'Traveler', at: 'traveler'
   # to: 
   mount_devise_token_auth_for 'Traveler', at: 'traveler', controllers: { omniauth_callbacks: "api/v1/omniauth_callbacks" }
end
```

**Comment by arifikhsan** [comment]
why is this closed? any solution?
