### ISSUE TITLE
Using the Generator Without Capitalizing Model Name

### ISSUE THREAD

**Issue by moeabdol** [lynndylanhurley/devise_token_auth#912]
When using the generator to generate a user model such as:

`rails generate devise_token_auth:install user auth`

The user model calss in app/models/user.rb is created such as:

`class user < ActiveRecord::Base`

Also when modifying this manually I get other weird behavior when trying to `rails db:migrate`
I think it's better to make devise_auth_token handle this automatically just like other generators in rails. This would result in a seamless experience. Thanks.

**Comment by zachfeldman** [comment]
@moeabdol I agree. How would you feel about submitting a pull request to take care of this? Going to tag this close-in-7-days in case you've moved on but we'd be game!

**Comment by MaicolBen** [comment]
Removing label, this seems a probable issue.
