### ISSUE TITLE
Devise Set User By Token Is Clashing with Normal Devise Helpers

### ISSUE THREAD

**Issue by RailsCod3rFuture** [lynndylanhurley/devise_token_auth#917]
I'm unable to use devise helpers like user_signed_in? or any of the others with this gem. My stack trace and errors are below. Does anyone have a working solution?

wrong number of arguments (given 1, expected 0)
<% if user_signed_in? %>

devise (4.3.0) app/controllers/devise_controller.rb:47:in `resource_class'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:21:in `set_user_by_token'
devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:123:in `current_user'
devise_token_auth (0.1.42) lib/devise_token_auth/controllers/helpers.rb:119:in `user_signed_in?'
actionpack (5.1.1) lib/abstract_controller/helpers.rb:68:in `user_signed_in?'
app/views/layouts/application.html.erb:16:in `_app_views_layouts_application_html_erb___51327025_116383452'
actionview (5.1.1) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.1) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.1) lib/action_view/template.rb:155:in `render'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.1) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.1) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
C:/Ruby233/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.1.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
devise (4.3.0) app/controllers/devise/sessions_controller.rb:12:in `new'
actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by RailsCod3rFuture** [comment]
I'm closing this issue. But, I hope that the makers of the gem will come up with a concrete solution for avoiding collisions between devise base and devise_token_auth

**Comment by acovrig** [comment]
I have this exact same issue, has anyone figured out how to use devise and devise_token_auth together?

I noticed `user_signed_in?` does work unless I'm on a devise route (such as /users/sign_in). 

/app/controllers/application_controller.rb:
```ruby
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  protect_from_forgery with: :null_session
  include ApplicationHelper
end
```
Note, if I take out the `include DeviseTokenAuth::Concerns::SetUserByToken` line, then the login page displays.

/config/routes.rb:
```ruby
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
  end
  resources :contacts
end
```
/app/models/user.rb:
```ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :omniauthable, :two_factor_authenticatable
  include DeviseTokenAuth::Concerns::User
  
  has_many :user_contacts
  has_many :contacts, through: :user_contacts
end
```

I know this issue is marked as closed, but I still have the issue, should I let this be here, or make a new issue?

**Comment by wktq** [comment]
Same here.
Is it an error caused of new version? because it appeared on the agenda recently.
Anyone can help?

**Comment by wktq** [comment]
I solved this. It was mentioned in other issues already.

remove ' include DeviseTokenAuth::Concerns::SetUserByToken ' in general application_controller.rb
```ruby
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken # remove this line
  protect_from_forgery with: :exception
end
```

And then, create application_controller.rb for Devise Token Auth in api/auth/v1 (mounted path)

```ruby
module Api
  module V1
    class ApplicationController < ActionController::API # Note: here is not ::BASE
      include DeviseTokenAuth::Concerns::SetUserByToken
    end
  end
end
```

It worked for me.

**Comment by acovrig** [comment]
Thanks, that seems to fix the wrong # of args error, but now `authenticate_user!` always returns a 401.

A `GET /contacts.json` always returns a 401 (even with the headers included from the `POST /api/auth/sign_in`.

/config/routes.rb:
```ruby
Rails.application.routes.draw do
  resources :contacts
  devise_for :users
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :contacts
  end
end
```

my updated /app/controllers/application_controller.rb:
```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  include ApplicationHelper
end
```

I created app/controllers/api/application_controller.rb:
```ruby
module Api
  class ApplicationController << ApplicationController::API
    include DeviseTokenAuth::Concerns::SetUserByToken
  end
end
```

If I try a `GET /api/contacts` I get a `uninitialized constant Api::ContactsController` error, which I understand and am guessing would be fixed by duplicating `/app/controllers/contacts_controller.rb` to `/app/controllers/api/contacts_controller.rb`? I would rather not duplicate all my controllers though.
