### ISSUE TITLE
Change Authentication Keys

### ISSUE THREAD

**Issue by rddm2bb** [lynndylanhurley/devise_token_auth#919]
Hello,
I'm build an api for a SaaS application and I'm trying to use 'devise_token_auth' for authentication in the api. The problem is my authentication keys are [:email, :tenant_id], tenant_id (is a model with a subdomain, I use a middleware to get it). Right know authentication is working using only the email, so it isn't scopping by tenant_id.
How can I implement it?
My confirmation and reset_password keys are the same.

Best regards

**Comment by zachfeldman** [comment]
Hi there @rddm2bb    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
