### ISSUE TITLE
Resend confirmation email

### ISSUE THREAD

**Issue by nicholasshirley** [lynndylanhurley/devise_token_auth#920]
Ok, so I'm going to feel dumb is this functionality is right under my nose, but here goes. I wanted to be able to resend confirmation emails if a user requested it. I didn't see any reference for how to do that with the gem and couldn't find a way in the code so I wrote my own way. This is for a Rails API server with a React front end. I have also removed all the redirect logic and variables from the controllers as we're handling that with the client.

I would be very happy to get some feedback on how this is structured (or just to be told it already exists). Also, I hijacked `confirmations#create` as I didn't think it was doing anything. Will my app blow up in the future?
```
module Overrides
  class ConfirmationsController < DeviseTokenAuth::ApplicationController
    
    ....

    def create
      @email = params[:email]
      @user = User.find_by(email: @email)

      if @user && @user.confirmed_at.nil?
        @user.send_confirmation_instructions({
          client_config: params[:config_name]
        })
        render status: 200, json: {
          email: @email,
          message: 'Your request has been received. A new confirmation email has been sent.'
          }.to_json
      elsif @user && @user.confirmed_at.present?
        render status: 200, json: {
          email: @email,
          message: 'This account has already been confirmed.'
        }.to_json
      else
        render status: 404, json: {
          email: @email,
          message: 'No user account exists for this email.'
        }.to_json
      end
    end
  end
end

**Comment by nicholasshirley** [comment]
Do I understand correctly that confirmation tokens do not expire?

**Comment by zachfeldman** [comment]
@nicholasshirley confirmation tokens do typically expire at some point. Take a look at this:
https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb

You're going to probably need to regenerate the confirmation token to be truly sure that the user will be able to re-confirm. I would do this with a new endpoint rather than hijacking create too, I don't see why it shouldn't be in an action called something like `resend_confirmation`.

Good luck and feel free to reopen if this is still an issue!

**Comment by mattsketchy** [comment]
@nicholasshirley did you ever find/create a good solution for this? Resending the confirmation email with devise_token_auth?

**Comment by nicholasshirley** [comment]
@mattsketchy I used the above for a while, but I ended up re-writing using JWT so I never re-factored that into something better

**Comment by mattsketchy** [comment]
@nicholasshirley awesome - thanks for the reply, was just curious - working with this gem where I work. Thanks again, take care.

**Comment by numice** [comment]
@nicholasshirley Did you rewrite only the resending confirmation email part or the whole authentication in JWT? I'm curious since I'm deciding between using the gem or use JWT instead. JWT seems to come with complexity in revoking tokens or keeping a blacklist.

**Comment by nicholasshirley** [comment]
Hey @numice, try this lib https://github.com/adamniedzielski/tiddle It makes working with Devise + tokens really smooth (and no need to re-write a bunch of stuff under the hood for Devise). That's what I use now for all projects that need token authentication with Devise
