### ISSUE TITLE
In batch mode tokens are unnecessarily stored for every request although unchanged

### ISSUE THREAD

**Issue by tmfrnz** [lynndylanhurley/devise_token_auth#922]
When in batch mode, it appears that tokens are written to user table in database for every request, even when the tokens only changes for the first request. 

These unnecessary operations can lead to poor performance, especially when combined with model versioning (eg using paper_trail). 

Our test (paper_trail enabled) with 100 requests, resulted in a total processing time of 25s with `change_headers_on_each_request` enabled and only 6s with `change_headers_on_each_request` disabled.

**Comment by lynndylanhurley** [comment]
The DB write is necessary to extend the duration of the batch buffer to account for the time taken for each request.

https://github.com/lynndylanhurley/devise_token_auth/blob/c158898b81e03478ee47dba066556ed49a841bf9/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L111

Can you think of another way to accomplish this without DB writes?

**Comment by lynndylanhurley** [comment]
Alternatively, can't you just have papertrail ignore the `tokens` column?

https://github.com/airblade/paper_trail#2c-choosing-attributes-to-monitor

**Comment by tmfrnz** [comment]
Thank you so much @lynndylanhurley for providing insight and also for pointing us to the relevant papertrail docs - we will give that a go

**Comment by tmfrnz** [comment]
@lynndylanhurley just to report back on this: having papertrail ignoring the token column did make it significantly faster (100 requests ~ 18s (instead of 25s)) but still it appears that the write operation to the user table is quite expensive... for now we will be turning off `change_headers_on_each_request` reducing it to ~6s. thanks again for your help regardless
