### ISSUE TITLE
Reset password url no host

### ISSUE THREAD

**Issue by ZhanZero** [lynndylanhurley/devise_token_auth#923]
Hi, I'm facing problem in sending reset password emails.
My client site use Angular. receive url in email:
**http://:/auth/password/edit?config=default&redirect_url=http%3A%2F%2Flocalhost%3A4200%2F&reset_password_token=srdQMPRCunjsvHmLsKCJ**

devise_token_auth 0.1.42
ruby 2.4.0p0
Rails 5.1.2

**Comment by nicholasshirley** [comment]
How is host defined in your `config/environments/development.rb` & `../production.rb` file?

This is my `development.rb` file which renders the correct host in reset links if it helps:

```
config.action_mailer.raise_delivery_errors = true
  config.action_mailer.delivery_method = :test
  host = 'localhost:3333'
  config.action_mailer.default_url_options = { host: host, protocol: 'http' }

  config.action_mailer.perform_caching = false
```

**Comment by ZhanZero** [comment]
@nicholasshirley Thank you!! This work for me.

I want to dynamic generate my host and port.
So this is my original code.
`host = "#{Rails::Server.new.options[:Host]}:#{Rails::Server.new.options[:Port]}`

But it doesn't work.

**Comment by Jaissel** [comment]
and now how its the best way to configure the "production.rb" file???

**Comment by zachfeldman** [comment]
@ZhanZero glad you were able to get to the bottom of this! Closing for now.
