### ISSUE TITLE
How do I include User relationships to response after authenticate

### ISSUE THREAD

**Issue by ricardohonorio** [lynndylanhurley/devise_token_auth#928]
Hi, 
My User has_and_belongs_to_many Profiles;
my question is: how do I include User.profiles to sign in callback.

thanks in advanced.

**Comment by zachfeldman** [comment]
@ricardohonorio have you tried overriding the normal routes in the correct overridescontroller in order to send back a custom response?

Closing this in 7 days if we don't hear back from ya.
