### ISSUE TITLE
render_create_error not called when no json is provided

### ISSUE THREAD

**Issue by mithom** [lynndylanhurley/devise_token_auth#929]
when sending an empty POST request, there does not seem to be a function to override the returned error.
The function render_create_error is not called and render_create_error_bad_credentials is never called as far as I can detect. Is there a way to solve the first part of this problem (the not being able to customize the render)?

**Comment by zachfeldman** [comment]
@mithom have you tried just overriding the entire action on the controller action in question?

**Comment by mithom** [comment]
I think i did this to solve the problem (will have to check to be sure), but the fact you cannot customize this error seems a big shortcoming/bug to me, as it is nowhere documented that the missing of post data excludes the render_create_error method.

**Comment by zachfeldman** [comment]
@mithom sure, if you have time we'd enjoy a pull request to fix this, possibly an addition to the README or a code fix.

**Comment by mithom** [comment]
I am not working on this project anymore and likely will not have time or think about checking the codebase again. So this can be closed as it is 2y oldwithout action
