### ISSUE TITLE
token authentication not working on production

### ISSUE THREAD

**Issue by abeltje1** [lynndylanhurley/devise_token_auth#931]
Dear people,

I'm trying to implement devise_token_auth for my API and most of it is working perfectly. On development actually everything works great, but all token-related requests which do need headers on my amazon production server (update account, delete account) return a 404, stating that the user could not be found. Only email registration and sign up are working as expected. For now I have set change_headers_on_each_request to false, but still it can't find the user. To me it looks like there is some configuration present in devise_token_auth which is production-only, otherwise it's very hard for me to understand this difference between the two environments.

FYI: I'm using devise_token_auth together with devise (API and web-app) and my devise version is 4.3.0, token_auth is 0.1.42 and rails is 5.0.3. 

I don't know how to proceed or debug this issue, so it would be greatly appreciated if someone could help me a little. Thank you! If I need to share more code or something, do tell!

PS: request/response info (for a test I ran it in my terminal with httpie. Exact same steps do work when pointing to my dev environment (localhost) but fail as seen below on my amazon ec2 instance):

**REQUEST**
http DELETE http://serverurl/api/auth  uid:master@g.com access_token:3g-JTuSNDHezo2PksegR-A client:ltF-ZdV6ZfN5M4kIV8LmQw token-type:bearer

**RESPONSE**
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 25 Jul 2017 14:22:10 GMT
Server: nginx/1.10.3 (Ubuntu)
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 372908ff-f00d-49be-ac47-07f93f62371c
X-Runtime: 0.001446
X-XSS-Protection: 1; mode=block

{
    "errors": [
        "Unable to locate account for destruction."
    ],
    "status": "error"
}

**Comment by abeltje1** [comment]
Still no luck with this...does anyone have an idea?

**Comment by lynndylanhurley** [comment]
Is your CORS setup different for production?

**Comment by abeltje1** [comment]
I have actually not set up anything for CORS yet, but will try to open up all CORS as a test. thanks for the lead!

**Comment by abeltje1** [comment]
Too bad... I tried opening up all CORS (with https://github.com/cyu/rack-cors) but it still gives me a 404: undefined. It seems like the tokens do keep changing, even though my config specifies they shouldn't. Still in dev everything working perfectly xD any other idea/lead which I could follow? I'm completely out of ideas :(

**Comment by abeltje1** [comment]
Maybe an extra piece of info: I'm using devise_token_auth in combination with standalone devise. Maybe that helps in a way. I'd be happy to look into this, but I have no idea where to look :(

**Comment by lynndylanhurley** [comment]
Can you post your prod config for devise + devise_token_auth?

**Comment by abeltje1** [comment]
Sure!

devise_token_auth config:

```
DeviseTokenAuth.setup do |config|

  # By default the authorization headers will change after each request. The
  # client is responsible for keeping track of the changing tokens. Change
  # this to false to prevent the Authorization header from changing after
  # each request.
   config.enable_standard_devise_support = true

  config.change_headers_on_each_request = false


  config.token_lifespan = 2.weeks # also tried three years

  config.max_number_of_devices = 10 # Also tried ridiculous values like 1000

end
```

Devise config:

```
Devise.setup do |config|

  config.mailer_sender = 'wachtwoorden@eitje-app.nl'

  
  require 'devise/orm/active_record'


  config.case_insensitive_keys = [:email]


  config.strip_whitespace_keys = [:email]


  config.skip_session_storage = [:http_auth]


  config.stretches = Rails.env.test? ? 1 : 11


  config.reconfirmable = true

  config.expire_all_remember_me_on_sign_out = true


  config.password_length = 6..128


  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/


  config.reset_password_within = 6.hours

  config.sign_out_via = :delete


end

```
CORS config:

```
module EitjeApi
  class Application < Rails::Application
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
```

One more thing which might be helpful: all non devise-token-auth API requests from my mobile apps to the back-end do work w/o problems. 

Thanks so much for looking into this, and do let me know if you spot something! 

Cheers

**Comment by abeltje1** [comment]
Do you see anything weird here? To me it looks like quite standard config for devise/devise_token_auth. I'm testing some more things today, will let you know if I solve the problem.

**Comment by abeltje1** [comment]
Okay, small update: I've tried running a production server locally (should've done this earlier lol) and it works flawlessly there. The server itself is the problem and not the rails env. Your idea that it could be a CORS-issue seems very plausible now, but how can it still be an issue when I opened up all CORS as you can see above? That's the part where I'm stuck now. For extra info: I'm running an Ubuntu 16.04 image at Amazon EC2. 

Cheers!

**Comment by abeltje1** [comment]
Hmm I saw another error in my CORS config: I didn't specify put/patch/delete as methods. When I saw this, I was very hopeful it'd be solved..but sadly the error's still there :(

**Comment by lynndylanhurley** [comment]
If it's running locally with your production setup, then the problem must be somewhere in your EC2 server config. Is there any additional configuration that could be interfering there (nginx config, AWS policies, etc.)?

**Comment by abeltje1** [comment]
That seems logical indeed, my nginx conf and AWS policies are fairly straightforward, but I'm looking into it.

**Comment by zachfeldman** [comment]
Hi there @abeltje1    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
