### ISSUE TITLE
Is there a way to prevent persisting the same token to user table when in batch mode?

### ISSUE THREAD

**Issue by tmfrnz** [lynndylanhurley/devise_token_auth#934]
Following-up on #922 

> When in batch mode, it appears that tokens are written to user table in database for every request, even when the tokens only changes for the first request.

> These unnecessary operations can lead to poor performance, especially when combined with model versioning (eg using paper_trail).

> Our test (paper_trail enabled) with 100 requests, resulted in a total processing time of 25s with change_headers_on_each_request enabled and only 6s with change_headers_on_each_request disabled.

**Comment by lynndylanhurley** [comment]
Just commented on #922. Let's continue the discussion there.
