### ISSUE TITLE
Working example with omniauth?

### ISSUE THREAD

**Issue by Eduardoveras** [lynndylanhurley/devise_token_auth#937]
Does anyone have a working example with omniauth?

im triying to login with google_oauth2 omniauth provider and everything seems to work, but i get to a white page after the login and dont know how to change that

**Comment by Eduardoveras** [comment]
Im using JToker, i configure it with my backend as it says in the example, but after a successfull login im unable to return to the front-end, it just leaves me at a blank page

**Comment by Eduardoveras** [comment]
Started GET "/auth/google_oauth2?auth_origin_url=http%3A%2F%2Flocalhost%3A8080%2F%23%2Fdashboard&config_name=default&omniauth_window_type=newWindow" for ..........
Started GET "/omniauth/google_oauth2?auth_origin_url=http%3A%2F%2Flocalhost%3A8080%2F%23%2Fdashboard&config_name=default&omniauth_window_type=newWindow&resource_class=User" for ....... at 2017-08-08 10:12:43 -0400
I, [2017-08-08T10:12:43.665188 #674]  INFO -- omniauth: (google_oauth2) Request phase initiated.
Started GET "/omniauth/google_oauth2/callback?state=----------&code=-----" for ------ at 2017-08-08 10:12:53 -0400
I, [2017-08-08T10:12:53.462935 #674]  INFO -- omniauth: (google_oauth2) Callback phase initiated.
Processing by DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks as HTML
  Parameters: {"state"=>"-------", "code"=>"---------------", "provider"=>"google_oauth2"}
Redirected to http://42e479e2.ngrok.io/auth/google_oauth2/callback
Completed 302 Found in 2ms (ActiveRecord: 0.0ms)

**Comment by Eduardoveras** [comment]
Issue fixed with this, https://github.com/lynndylanhurley/devise_token_auth/issues/830

**Comment by sarink** [comment]
https://github.com/lynndylanhurley/devise_token_auth/issues/1020
