### ISSUE TITLE
Not send email notification when email changed ?

### ISSUE THREAD

**Issue by danglv** [lynndylanhurley/devise_token_auth#940]
- Because you override method email_changed? in https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L55.  So the features send_email_changed_notification is disabled. you can find it in https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb#L174

**Comment by zachfeldman** [comment]
Hi there @danglv    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by MaicolBen** [comment]
@danglv You can override `email_changed?`. Do you want to change the default behavior? I am not sure if not sending an email is the common behavior
