### ISSUE TITLE
tokens_match? issue

### ISSUE THREAD

**Issue by mackmm145** [lynndylanhurley/devise_token_auth#942]
on line 10 of `DeviseTokenAuth::Concerns::User`
i think that 
`result = @token_equality_cache[key] ||= (::BCrypt::Password.new(token_hash) == token)`

should be 
`result = @token_equality_cache[key] ||= (::BCrypt::Password.new(token_hash).to_str == token)`

`BCrypt::Password` inherits from `String`, but it doesn't evaluate to `true` unless i cast it. obviously it's working for others, but i don't think that there's a downside to making the change.

**Comment by codebreach** [comment]
I have been facing the same issue...but only sometimes.
It happens on dev wayyy more than prod

**Comment by lynndylanhurley** [comment]
@mackmm145 - I think there may be an issue with what you're trying to do. `==` means something different in BCrypt:
https://github.com/codahale/bcrypt-ruby#how-to-use-bcrypt-ruby-in-general

**Comment by zachfeldman** [comment]
Closing for now due to a decent suggested answer.
