### ISSUE TITLE
Make DeviseAuthToken inherits my API base Controller?

### ISSUE THREAD

**Issue by newfylox** [lynndylanhurley/devise_token_auth#945]
* Version: v0.1.42

Hi, I was wondering if there is way to make this Gem inherits from my API base controller instead of Application::Base?

My API base controller shares common methods (JSON errors handling, validations, concerns, includes, etc.) and I want DeviseAuthToken to follow the same rules **BEFORE** everything else, before running code of Application::Base or same.

I want to apply DRY principle.

Thanks :)

**Comment by Uysim** [comment]
Any good new?

**Comment by zachfeldman** [comment]
Hi there @newfylox    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by MaicolBen** [comment]
But how do we know your api base controller? Maybe we can generate one. But I think is better to use concerns and add the concern to the devise toke auth controllers that you use.

What do you think @lynndylanhurley ?

**Comment by lynndylanhurley** [comment]
We can't inherit from `ApplicationController` - it will cause a ton of problems. For example, some projects define multiple `ApplicationControllers` and some don't use any at all. And I don't think there's a way to inherit from a dynamic class in ruby, so we can't make the base class an initializer setting.

@newfylox - this is a pain but I think your best bet is to:
1. Factor your shared methods into their own concerns
2. Override the controllers in this project as described [here](https://github.com/lynndylanhurley/devise_token_auth#custom-controller-overrides)
3. Include the concerns from step 1 in the controller overrides from step 2

**Comment by newfylox** [comment]
Thank you guys, I understand the problems it may caused and I will deal with that following your advises.
