### ISSUE TITLE
Can not have multiple model

### ISSUE THREAD

**Issue by Uysim** [lynndylanhurley/devise_token_auth#950]
When I have two Model User And Customer it will raise errors

 ActiveRecord::StatementInvalid:
       PG::UndefinedColumn: ERROR:  column users.uid does not exist
       LINE 1: SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMI...
                                                    ^
       HINT:  Perhaps you meant to reference the column "users.id".
       : SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2

**Comment by Uysim** [comment]
Also get this errors

/Users/macbook/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:712:in `block (2 levels) in skip_callback': Before process_action callback :authenticate_user! has not been defined (ArgumentError)

**Comment by zachfeldman** [comment]
Hi there @Uysim    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.
