### ISSUE TITLE
Model for nested attributes not being saved

### ISSUE THREAD

**Issue by swigrid** [lynndylanhurley/devise_token_auth#952]
Hi

I have Customer model which has_many Addresses. I'm trying to send params from API client like this:

`{"confirm_success_url"=>"", "commit"=>"Register", "email"=>"email@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Matt", "last_name"=>"Dee", "addresses"=>[{"addr_type"=>"home", "line1"=>"47 Westhill rd."}]}`.

I have tried it also like this

`"addresses_attributes"=>{"0"=>{"addr_type"=>"home", "line1"=>"asdf", "line2"=>"asdf", "city"=>"asdf", "post_code"=>"asdf"}}}`

`"addresses"=>{"addr_type"=>"home", "line1"=>"asdf", "line2"=>"asdf", "city"=>"asdf", "post_code"=>"asdf"}}`

I'm not sure if this is an issue or I'm doing it wrong.

**Comment by swigrid** [comment]
I'm sorry, I didn't release that this is Devise responsibility.

https://github.com/plataformatec/devise#strong-parameters

**Comment by newfylox** [comment]
@swigrid Did you manage to do this? I'm stuck to the same issue.
