### ISSUE TITLE
how to get first name and last name of user

### ISSUE THREAD

**Issue by anklos** [lynndylanhurley/devise_token_auth#953]
Hi there,

this gem seems only retrieves `name` field from auth provider, rather than `first_name` and `last_name`: https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb#L84

Is there a way to get `first_name` and `last_name` by using this gem?

Thanks!

**Comment by dhurba87** [comment]
Auth provider provides `name` instead of `first_name` and `last_name`. You can split it to get `first_name` and `last_name`.
```
first_name = auth_hash['info']['name'].split(' ').first
last_name = auth_hash['info']['name'].split(' ').last
```

**Comment by lynndylanhurley** [comment]
You can also just remove the `name` column add those columns to the `User` migration.

**Comment by anklos** [comment]
@lynndylanhurley that will automatically work? that would be really nice.

if i keep the `name` and add `first_name` and `last_name` into the `User` migration, does all three columns get value stored?

Thanks!

**Comment by zachfeldman** [comment]
I don't think it will automatically work @anklos , I think you have to override some of the create user methods. Feel free to reopen if you need help with that.
