### ISSUE TITLE
Readme "Usage TL;DR" section - add confirm_success_url to required params?

### ISSUE THREAD

**Issue by pnewsam** [lynndylanhurley/devise_token_auth#955]
> / | POST | Email registration. Requires email, password, and password_confirmation params. A verification email will be sent to the email address provided. Accepted params can be customized using the devise_parameter_sanitizer system.

It took me a little while to figure out that RegistrationsController expected a confirm_success_url param in addition to email, password, and password_confirmation. (I'm using Rails in API mode with a React front-end sending the form post, and only received a 422 response). Could be helpful to others to add that to the Readme?

**Comment by lynndylanhurley** [comment]
Sure - can you send a PR?

**Comment by pnewsam** [comment]
Submitted, thanks!
