### ISSUE TITLE
devise_token_auth initializer breaks omniauth paths

### ISSUE THREAD

**Issue by alexandrapersea** [lynndylanhurley/devise_token_auth#966]
I am using the gem for a bare api token authentication and I have noticed that the initializer breaks my omniauth paths.

**routes.rb**

```
mount_devise_token_auth_for 'User',
  controllers: {
    sessions: 'api/sessions',
    registrations: 'api/registration',
  }
```

**devise_token_auth.rb**

```
DeviseTokenAuth.setup do |config|
  config.change_headers_on_each_request = false
  config.token_lifespan = 3.months
end
```

Without the initializer `auth/google_oauth2` redirect to the google authetication page, but when i add the initializer `auth/google_oauth2` raises `No route matches [GET] /auth/google_oauth2`

Is there something i can do? Could the initializer override the previous declared omniauth paths?

**Comment by Blitzkev** [comment]
Have you checked what the routes are with rake after the change? I have oauth/devise_token_auth installed and the routes are the following:

```
     auth_validate_token GET      /auth/validate_token(.:format)         devise_token_auth/token_validations#validate_token
            auth_failure GET      /auth/failure(.:format)                devise_token_auth/omniauth_callbacks#omniauth_failure
                         GET      /auth/:provider/callback(.:format)     devise_token_auth/omniauth_callbacks#omniauth_success
                         GET|POST /omniauth/:provider/callback(.:format) devise_token_auth/omniauth_callbacks#redirect_callbacks
        omniauth_failure GET|POST /omniauth/failure(.:format)            devise_token_auth/omniauth_callbacks#omniauth_failure
                         GET      /auth/:provider(.:format)              redirect(301)
                         GET      /500(.:format)                         errors#internal_error
```

And doing a GET on '/auth/facebook' works fine (don't have google oauth configured)

What does your omniauth.rb initializer look like?

**Comment by alexandrapersea** [comment]
These are my `devise_token_auth` routes
```
               api_validate_token GET      /api/validate_token(.:format)                    devise_token_auth/token_validations#validate_token
                      api_failure GET      /api/failure(.:format)                           devise_token_auth/omniauth_callbacks#omniauth_failure
                                  GET      /api/:provider/callback(.:format)                devise_token_auth/omniauth_callbacks#omniauth_success
                                  GET|POST /omniauth/:provider/callback(.:format)           devise_token_auth/omniauth_callbacks#redirect_callbacks
                 omniauth_failure GET|POST /omniauth/failure(.:format)                      devise_token_auth/omniauth_callbacks#omniauth_failure
                                  GET      /api/:provider(.:format)                         redirect(301)
```

**omniauth.rb**
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_KEY'],   ENV['GOOGLE_SECRET'], :client_options => { :ssl 
     => { :verify => !Rails.env.development? } }
end
```
What's interesting is that without the `devise_token_auth initializer` both `auth/google` and `api/google` path work. With the initializer `auth/google` is undefined while `api/google` still works.

**Comment by Blitzkev** [comment]
Seems like it's working as expected then, devise_token_auth moves the oauth paths to /api (Thats where you mounted it in routes.rb) - it might not fully take effect until the gem is initialized.

**Comment by alexandrapersea** [comment]
But i do not want to use `omniauth` with `devise_token_auth` and even so, I should be able to declare multiple oauth paths without the gem moving them to a different path.

**Comment by Blitzkev** [comment]
How are you mounting the omniauth routes themselves? Try mounting devise_token_auth somewhere other than api/auth, or having the base omniauth routes mounted elsewhere so there isn't conflict and see if that helps.

**Comment by MaicolBen** [comment]
Seems it's working as expected, @alexandrapersea feel free to reopen if you think isn't working.
