### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by zachfeldman** [lynndylanhurley/devise_token_auth#972]
We've merged a bunch of changes so sometime soon we should cut a new release.

**Comment by lynndylanhurley** [comment]
I'll pull down the latest and test with an actual client, then push out a beta release by the end of this week.

**Comment by zachfeldman** [comment]
Good plan!

**Comment by MaicolBen** [comment]
I'm testing master as well with several projects that uses it (except Omniauth that we don't use it), for now I only found an issue #975

**Comment by MaicolBen** [comment]
Testing master I found failing some tests in a project because I don't have the new field `allow_password_change`, it was [introduced here](https://github.com/lynndylanhurley/devise_token_auth/pull/981/files#diff-a8896c96c8847a9cc2fe37d3c448849cR14). What do I have to do? Shouldn't it check if recoverable is enabled?

**Comment by zachfeldman** [comment]
@MaicolBen it probably should check if recoverable is enabled, that's a good point. Can you find a precedent in Devise or our codebase for how to check for a module being enabled?

**Comment by MaicolBen** [comment]
Yeah, it's possible, I made a PR #995

**Comment by Blitzkev** [comment]
While we're waiting for a release to be cut (which would be really great), is there any way to use what's in master on github in a project? Pointing to here in the gemfile still makes it use 0.1.42 code

**Comment by MaicolBen** [comment]
@Blitzkev You can doing `gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth'`

@lynndylanhurley Any ETA in testing and publishing the release? If we are following semver, this should be 0.2.0 because we have some new features merged in master

**Comment by ethagnawl** [comment]
@Blitzkev The following is working for me: 

```
gem "devise_token_auth", git: "https://github.com/lynndylanhurley/devise_token_auth", ref: "dc9456d99c2ea6f96323a95c87c1fee8f6cc857b"
```

**Comment by zachfeldman** [comment]
Thanks for your patience all and @ethagnawl thanks for the workaround!

**Comment by lynndylanhurley** [comment]
Just pushed `v0.1.43.beta1`. I'll do extensive testing over the next couple of days and push `v0.1.43` later this week.

In the meantime please pull down the beta and test.

Thanks!!

**Comment by MaicolBen** [comment]
Thanks @lynndylanhurley! can you take a look at #995, because it will break for the projects that update the gem. I would like #989 merged, but that's only for our projects.

**Comment by Blitzkev** [comment]
Would appreciate this merged also:

https://github.com/lynndylanhurley/devise_token_auth/pull/1021

**Comment by h4b00** [comment]
@lynndylanhurley 
when can we expect the next release?

**Comment by zachfeldman** [comment]
@h4b00 have you tested  v0.1.43.beta1 and has it been working well for you?

The more people test the beta branch, the faster we cut a release :).

**Comment by MaicolBen** [comment]
It was done, it's v0.1.43
