### ISSUE TITLE
How to customize Omniauth payload

### ISSUE THREAD

**Issue by mattfordham** [lynndylanhurley/devise_token_auth#974]
Using "overrides" I am successfully customizing the data passed back to the front-end overriding methods such as `render_validate_token_success` and `render_create_success`, as described in the docs. That said, I have not been able to find any information on doing the same in OmniauthCallbacksController. 

I do not need a simple `.to_json` representation of User model, and need to add additional data... how can I achieve this?

**Comment by zachfeldman** [comment]
Hi @mattfordham !

Have you tried just overriding the methods in the omniauthcallbackscontroller, and calling code before or after `super` to achieve what you're trying to do?

**Comment by mattfordham** [comment]
Yes, and I got that working. Just wanted to make sure there wasn't a "hook" like `render_create_success`. It seems not. Thanks!

**Comment by zachfeldman** [comment]
Glad to hear it's working
