### ISSUE TITLE
responders - rails 4.2

### ISSUE THREAD

**Issue by matteolc** [lynndylanhurley/devise_token_auth#98]
hi
is token auth ready for rails 4.2 (with responders gem moved out?)
i can't seem to get it to respond to :json ..
thanks

**Comment by lynndylanhurley** [comment]
@matteolc - I haven't tested against rails 4.2 yet. I'll take a look ASAP.

**Comment by matteolc** [comment]
Thanks much appreciated ;)

**Comment by matteolc** [comment]
FYI

Here's my application controller:

class ApplicationController < ActionController::API
	
  include ActionController::Caching  
  include ActionController::MimeResponds
   
  def self.respond_to(*mimes)
    include ActionController::RespondWith::ClassMethods
  end  
  
  respond_to :json
  
  include DeviseTokenAuth::Concerns::SetUserByToken
  before_filter :authenticate_account!

end

I had to add

  def self.respond_to(*mimes)
    include ActionController::RespondWith::ClassMethods
  end  

to avoid the error: ActionController::RoutingError (The controller-level `respond_to' feature has been extracted to the `responders` gem.

I think it's related to warden.

Thanks

**Comment by matteolc** [comment]
Update.
If i make an explicit json request, session controller responds with json:
curl http:/..../api/auth/sign_in.json --data "email=...&password=..."
Processing by DeviseTokenAuth::SessionsController#create as JSON
however, i must be missing something as i get straight 401 with no active record call:
Filter chain halted as :authenticate_account! rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)

**Comment by matteolc** [comment]
Update
It must be related to request.headers / permitted parameters ..
Filter chain is halted in set_user_by_token at return false unless @token because request.headers['..'] is apparently empty / gets filtered

Started POST "/api/v1/auth/sign_in"
  Parameters: {"email"=>"1@matteo.lc", "password"=>"12345678", "uid"=>"1@matteo.lc", "access-token"=>"12345678"}
UID:
token:
client_id: default
Filter chain halted as :authenticate_account! rendered or redirected

**Comment by matteolc** [comment]
So actually all that should be required to make it work when inheriting from ActionController::API is

class ApplicationController < ActionController::API                             
	                                                                       
  include ActionController::MimeResponds       

  def self.respond_to(*mimes)
    include ActionController::RespondWith::ClassMethods
  end

  respond_to :json

end

(Not sure what wasn't working before :O)

**Comment by matteolc** [comment]
weird..i got it to work, restarted the server, and got again halted before finding the user..

Filter chain halted as :authenticate_account! rendered or redirected

:O

**Comment by lynndylanhurley** [comment]
@matteolc - I just updated to rails 4.2.

Can you please check out version `0.1.31.beta3` and let me know if it works for you?

**Comment by lynndylanhurley** [comment]
@matteolc  - I just pushed version `0.1.31.beta6` and everything seems to be ok. Please re-open if you run into any issues.

**Comment by matteolc** [comment]
Ok thanks!

**Comment by lynndylanhurley** [comment]
@matteolc - make that `0.1.31.beta8` :smiley:
