### ISSUE TITLE
access token always expires in one minute

### ISSUE THREAD

**Issue by anklos** [lynndylanhurley/devise_token_auth#980]
**Gem Version**: 0.1.42
**Rails Version**: 5.1.3

**Request**:
`curl -X POST localhost:3000/auth/sign_in -d '{ "email": "xxxx@mailinator.com", "password": "12345678" }' -H 'Content-Type: application/json' -v`

**Response**:
```
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Access-Token: j0BqW7HE0UV2dKrHcsyk4A
< Token-Type: Bearer
< Client: vq4nl95EKwvtjrX7TqRxYA
< Expiry: 1509150892
< Uid: xxxx@mailinator.com
< Etag: W/"49908d9c5f5c79b340df5f4b3b97183c"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: ce01c140-fc65-470f-84ee-01d218da15bb
< X-Runtime: 0.255476
< Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
< Date: Sat, 14 Oct 2017 00:34:52 GMT
< Content-Length: 172
< Connection: Keep-Alive
<
* Connection #0 to host localhost left intact
{"data":{"id":5,"email":"xxxx@mailinator.com","provider":"email","uid":"xxxx@mailinator.com","nickname":null,"image":null,"first_name":null,"last_name":null,"name":null}}
```

I use the access-token, client and expiry time in following requests for authentication purpose. However the lifetime of the token can only exist for about one minute, after that server will return 401 with error `{"errors":["You need to sign in or sign up before continuing."]}`

I didn't customize anything in the config, all are default. It is supposed to be valid for two weeks according to documentation. 

I don't call `create_new_token` explicitly which expires the old token. I don't have more than 10 devices, I only test on my laptop. Just to confirm, `devices` in the config means hardware like laptop or mobile right?

Can anyone please advise how i can make the token last two weeks long?

Thanks!

**Comment by anklos** [comment]
find that change `change_headers_on_each_request` config to false will stop refreshing token every time.

what confused me was that why i could get valid response by sending several requests with the same token in a short period. If header change on each request, it should return error on the second request.

**Comment by zachfeldman** [comment]
Yeah @anklos I also found this confusing when I first used this gem. Ended up turning off that option as well. I think we probably need to update the clients, is my suspicion. Are you using jtoker or similar?

**Comment by anklos** [comment]
@zachfeldman nope, i only write API. issue reported by frontend dev, they use react/react-native.

**Comment by zachfeldman** [comment]
Ok, @anklos could you ask them which approach they're using to send/receive this information - are they using an abstraction, or are they just writing their own approach from scratch? That would be helpful, to know if there's an issue with one of our client libraries.

**Comment by anklos** [comment]
@zachfeldman they just write their own approach from scratch.

also as described in the ticket, I was just using `curl` to reproduce the issue.

**Comment by lynndylanhurley** [comment]
@anklos the default behavior is to use a different token for each request. By default there is a buffer of about 1 minute in which the same token can be used to account for concurrent / parallel requests. The client is expected to keep track of the most recent token.

See [this section](https://github.com/lynndylanhurley/devise_token_auth#about-token-management) of the readme for more info.

**Comment by developius** [comment]
@lynndylanhurley that link is now dead and I can't find the info you mentioned about the 1-min buffer anywhere else? I ran into this and became very confused. Can we add that to the documentation somewhere?
