### ISSUE TITLE
Password Reset: Is it possible to disable returning 404 when user is not found?

### ISSUE THREAD

**Issue by misham** [lynndylanhurley/devise_token_auth#987]
I'm trying not having to re-implement the entire controller functionality and just want to change the behavior a bit.

I don't care if the user is found or not, the response should always be 200.

Is the only solution to just re-implement `POST create` for the passwords controller?

Thank you

**Comment by MaicolBen** [comment]
Seems that 404 is the only way to reach `render_create_error`, so maybe you want to override it. In the future, we'll refactor the controller.

**Comment by misham** [comment]
I'd be interested in submitting a PR around this.  Would it be sufficient to pass another variable to skip the 404 error?  E.g. `POST {pasword: 'somepass', ..., skip_404: true}`

That feels a bit hacky, but not sure what would make more sense here?  Maybe a global config that can be set in the initializer?

**Comment by MaicolBen** [comment]
That's ugly, I made a PR where you can override `render_not_found_error` in the passwords controller

**Comment by misham** [comment]
That's great!  Do you know when the next release will land?
