### ISSUE TITLE
Improve after action update headers in case change headers is disabled

### ISSUE THREAD

**Issue by MaicolBen** [lynndylanhurley/devise_token_auth#992]
In the [after action](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L92) when the headers update is disabled, it stores the token that is retrieved by the frontend which must be the same since is checked in the before action, why is that?

The code that I'm talking about is: 
```ruby
    if @used_auth_by_token && !DeviseTokenAuth.change_headers_on_each_request
      # should not append auth header if @resource related token was
      # cleared by sign out in the meantime
      return if @resource.reload.tokens[@client_id].nil?

      auth_header = @resource.build_auth_header(@token, @client_id)

      # update the response header
      response.headers.merge!(auth_header)
```

I think we can get rid of that code and improve the performance (and thus removing 3 db requests each time an api request is made)

**Comment by lynndylanhurley** [comment]
@MaicolBen do you mean this line?

```ruby
return if @resource.reload.tokens[@client_id].nil?
```
That line is checking to see if the user initiated a logout while the current request was processing. That's where the db request is coming from.

Can you think of another way to go about that?

**Comment by MaicolBen** [comment]
I mean the 2 below (if you get rid of them, the one mentioned is useless):
```ruby

      auth_header = @resource.build_auth_header(@token, @client_id)

      # update the response header
      response.headers.merge!(auth_header)
```

You can build the headers without going to the db (that's what `build_auth_header` does)

**Comment by lynndylanhurley** [comment]
Oh good catch. I forgot that `build_auth_header` writes to the db. We should probably break out the building and saving of the auth header into two separate methods. All we really need here is this part:

```ruby
def build_auth_header(token, client_id='default')
    client_id ||= 'default'

    # client may use expiry to prevent validation request if expired
    # must be cast as string or headers will break
    expiry = self.tokens[client_id]['expiry'] || self.tokens[client_id][:expiry]
   
    # ...

    return {
      DeviseTokenAuth.headers_names[:"access-token"] => token,
      DeviseTokenAuth.headers_names[:"token-type"]   => "Bearer",
      DeviseTokenAuth.headers_names[:"client"]       => client_id,
      DeviseTokenAuth.headers_names[:"expiry"]       => expiry.to_s,
      DeviseTokenAuth.headers_names[:"uid"]          => self.uid
    }
end
```

This should just be its own method, and then the saving should happen in its own method that gets called when using the `change_headers_on_each_request` feature. Would that solve this issue?

**Comment by MaicolBen** [comment]
Yeah! I'll make a PR if I have time, thanks
