### ISSUE TITLE
Confirmation URL query parameters don't match header counterparts

### ISSUE THREAD

**Issue by ethagnawl** [lynndylanhurley/devise_token_auth#993]
I've noticed that the keys used in the query parameters added to my email confirmation mailer's `redirect_url` don't match their header counterparts. (I'm currently using v0.1.42.)

Here's an example:

`http://www.somewhere.com/?account_confirmation_success=true&client_id=xxx&config=default&expiry=yyy&token=zzz&uid=someone@somewhere.com`

I'm writing documentation which will instruct FE devs on how to submit a PATCH request to update the confirmed user's account (user is invited to application and then uses this confirmation page to enter additional account info - I'd like to have this be a single step instead of them setting a password, logging in and then entering info). It seems counter-intuitive to say, "extract `client_id|token` from the query string and use its value to populate the `client|access-token` header".

I'd be happy to provide any additional information and will look into submitting a backwards compatible PR if I can find some time.

**Comment by zachfeldman** [comment]
@ethagnawl that's a good point. I agree that the keys should match everywhere.

I'd be very open to a PR fixing this! Thanks for reporting.

**Comment by ethagnawl** [comment]
@zachfeldman I've made a first pass at this. Please have a look when you get a chance and let me know if you have any feedback.

**Comment by ethagnawl** [comment]
Closed via #996.
