### ISSUE TITLE
Hardcoded resource.provider in RegistrationsController?

### ISSUE THREAD

**Issue by m4-miranda** [lynndylanhurley/devise_token_auth#997]
The resource.provider field in Registrations#create is hardcoded to 'email'. Shouldn't this be obtained from Devise?

I'm trying to get rid of email dependency altogether

**Comment by zachfeldman** [comment]
Hey @m4-miranda sure, I agree with your logic here. Mind opening a pull request to illustrate your exact changes in mind?

**Comment by MaicolBen** [comment]
If you make a PR, you can reuse the `provider` method defined in #975

**Comment by m4-miranda** [comment]
@MaicolBen It isn't possible to override the concern, is it? I could modify the get_resource method to accept a provider parameter, but the method would have to be declared in each controller

**Comment by MaicolBen** [comment]
You can override it in your code, and yes, you have to do it in every controller (you can make a concern in your code to avoid repeating)

**Comment by MaicolBen** [comment]
Closed via #998

**Comment by KelseyDH** [comment]
This gotcha really screwed me up.  It would be really nice for `provider` not to be hardcoded from params.  e.g. by checking if its defined *before* hardcoding it to `email`

I lost many hours trying to figure out why my user model kept hardcoding provider to 'email'.

**Comment by MaicolBen** [comment]
Sorry to hear that, as we don't have a lot of code documentation, you need to read the source code, in case of the provider, you can override with what was defined in #975

**Comment by KelseyDH** [comment]
@MaicolBen  Thanks for getting back.  My intention is to have `provider` [switch between `username` and `email` based on the params received](https://github.com/lynndylanhurley/devise_token_auth/issues/1066) within the same controller.  Any idea on how I could go about implementing that kind of dynamic override for the registrations controller -- and not have this hardcoded override break my User model elsewhere on subsequent updates?

**Comment by KelseyDH** [comment]
I tried modifying the gem to override the registrations controller code from something like this:

```
module DeviseTokenAuth
  class RegistrationsController < DeviseTokenAuth::ApplicationController
 ...
    def create
      @resource            = resource_class.new(sign_up_params.except(:confirm_success_url))
      @resource.provider   = provider
```

over to this:

```
if sign_up_params[:provider].present?
  @resource.provider = sign_up_params[:provider]
else
  @resource.provider = provider
end
```

 but it didn't work and I still get back an 'email' provider despite sending in params for `provider` and whitlisting this for `sign_up`. :(

**Comment by MaicolBen** [comment]
That's happening because you aren't saving the provider in the resource, which it isn't a good solution. I believe this has been worked on #990, but we need it finished in order to use it. In fact, we put a bounty on it in order to get it ASAP
